### ISSUE TITLE
ipv6 smtp发信问题

### ISSUE THREAD

**Issue by jianfei96** [halo-dev/halo#1096]
## 我的环境
版本：1.4.1
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

---

## 错误日志

465端口发信测试
```
Oct 06 08:12:05 vm227140 java[405]: Exception in thread "pool-4-thread-1" run.halo.app.exception.EmailException: 邮件发送失败，请检查 SMTP 服务配置是否正确
Oct 06 08:12:05 vm227140 java[405]:         at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:114)
Oct 06 08:12:05 vm227140 java[405]:         at run.halo.app.mail.AbstractMailService.lambda$sendMailTemplate$0(AbstractMailService.java:128)
Oct 06 08:12:05 vm227140 java[405]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Oct 06 08:12:05 vm227140 java[405]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Oct 06 08:12:05 vm227140 java[405]:         at java.lang.Thread.run(Thread.java:748)
Oct 06 08:12:05 vm227140 java[405]: Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
Oct 06 08:12:05 vm227140 java[405]:   nested exception is:
Oct 06 08:12:05 vm227140 java[405]:         java.net.SocketException: Network is unreachable (connect failed). Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
Oct 06 08:12:05 vm227140 java[405]:   nested exception is:
Oct 06 08:12:05 vm227140 java[405]:         java.net.SocketException: Network is unreachable (connect failed); message exceptions (1) are:
Oct 06 08:12:05 vm227140 java[405]: Failed message 1: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
Oct 06 08:12:05 vm227140 java[405]:   nested exception is:
Oct 06 08:12:05 vm227140 java[405]:         java.net.SocketException: Network is unreachable (connect failed)
Oct 06 08:12:05 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448)
Oct 06 08:12:05 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
Oct 06 08:12:05 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
Oct 06 08:12:05 vm227140 java[405]:         at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:107)
Oct 06 08:12:05 vm227140 java[405]:         ... 4 more
Oct 06 08:12:05 vm227140 java[405]: Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
Oct 06 08:12:05 vm227140 java[405]:   nested exception is:
Oct 06 08:12:05 vm227140 java[405]:         java.net.SocketException: Network is unreachable (connect failed)
Oct 06 08:12:05 vm227140 java[405]:         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2210)
Oct 06 08:12:05 vm227140 java[405]:         at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
Oct 06 08:12:05 vm227140 java[405]:         at javax.mail.Service.connect(Service.java:342)
Oct 06 08:12:05 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
Oct 06 08:12:05 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
Oct 06 08:12:05 vm227140 java[405]:         ... 7 more
Oct 06 08:12:05 vm227140 java[405]: Caused by: java.net.SocketException: Network is unreachable (connect failed)
Oct 06 08:12:05 vm227140 java[405]:         at java.net.PlainSocketImpl.socketConnect(Native Method)
Oct 06 08:12:05 vm227140 java[405]:         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
Oct 06 08:12:05 vm227140 java[405]:         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Oct 06 08:12:05 vm227140 java[405]:         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Oct 06 08:12:05 vm227140 java[405]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Oct 06 08:12:05 vm227140 java[405]:         at java.net.Socket.connect(Socket.java:607)
Oct 06 08:12:05 vm227140 java[405]:         at java.net.Socket.connect(Socket.java:556)
Oct 06 08:12:05 vm227140 java[405]:         at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:335)
Oct 06 08:12:05 vm227140 java[405]:         at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
Oct 06 08:12:05 vm227140 java[405]:         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
Oct 06 08:12:05 vm227140 java[405]:         ... 11 more

```
587端口发信测试
```
Oct 06 08:13:51 vm227140 java[405]: Exception in thread "pool-4-thread-3" run.halo.app.exception.EmailException: 邮件发送失败，请检查 SMTP 服务配置是否正确
Oct 06 08:13:51 vm227140 java[405]:         at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:114)
Oct 06 08:13:51 vm227140 java[405]:         at run.halo.app.mail.AbstractMailService.lambda$sendMailTemplate$0(AbstractMailService.java:128)
Oct 06 08:13:51 vm227140 java[405]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Oct 06 08:13:51 vm227140 java[405]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Oct 06 08:13:51 vm227140 java[405]:         at java.lang.Thread.run(Thread.java:748)
Oct 06 08:13:51 vm227140 java[405]: Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
Oct 06 08:13:51 vm227140 java[405]:   nested exception is:
Oct 06 08:13:51 vm227140 java[405]:         java.net.SocketException: Network is unreachable (connect failed). Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
Oct 06 08:13:51 vm227140 java[405]:   nested exception is:
Oct 06 08:13:51 vm227140 java[405]:         java.net.SocketException: Network is unreachable (connect failed); message exceptions (1) are:
Oct 06 08:13:51 vm227140 java[405]: Failed message 1: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
Oct 06 08:13:51 vm227140 java[405]:   nested exception is:
Oct 06 08:13:51 vm227140 java[405]:         java.net.SocketException: Network is unreachable (connect failed)
Oct 06 08:13:51 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448)
Oct 06 08:13:51 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
Oct 06 08:13:51 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
Oct 06 08:13:51 vm227140 java[405]:         at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:107)
Oct 06 08:13:51 vm227140 java[405]:         ... 4 more
Oct 06 08:13:51 vm227140 java[405]: Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout -1;
Oct 06 08:13:51 vm227140 java[405]:   nested exception is:
Oct 06 08:13:51 vm227140 java[405]:         java.net.SocketException: Network is unreachable (connect failed)
Oct 06 08:13:51 vm227140 java[405]:         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2210)
Oct 06 08:13:51 vm227140 java[405]:         at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
Oct 06 08:13:51 vm227140 java[405]:         at javax.mail.Service.connect(Service.java:342)
Oct 06 08:13:51 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
Oct 06 08:13:51 vm227140 java[405]:         at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
Oct 06 08:13:51 vm227140 java[405]:         ... 7 more
Oct 06 08:13:51 vm227140 java[405]: Caused by: java.net.SocketException: Network is unreachable (connect failed)
Oct 06 08:13:51 vm227140 java[405]:         at java.net.PlainSocketImpl.socketConnect(Native Method)
Oct 06 08:13:51 vm227140 java[405]:         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
Oct 06 08:13:51 vm227140 java[405]:         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Oct 06 08:13:51 vm227140 java[405]:         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Oct 06 08:13:51 vm227140 java[405]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Oct 06 08:13:51 vm227140 java[405]:         at java.net.Socket.connect(Socket.java:607)
Oct 06 08:13:51 vm227140 java[405]:         at java.net.Socket.connect(Socket.java:556)
Oct 06 08:13:51 vm227140 java[405]:         at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:335)
Oct 06 08:13:51 vm227140 java[405]:         at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
Oct 06 08:13:51 vm227140 java[405]:         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
Oct 06 08:13:51 vm227140 java[405]:         ... 11 more
```
---

## 期望行为

纯ipv6环境下，smpt发信成功（smtp.gmail.com应该是支持ipv6的）
```
host -6 smtp.gmail.com
smtp.gmail.com has address 108.177.14.109
smtp.gmail.com has IPv6 address 2a00:1450:4010:c08::6d

nmap -6 -Pn 2a00:1450:4010:c0f::6d
Starting Nmap 7.80 ( https://nmap.org ) at 2020-10-06 08:15 MSK
Nmap scan report for lt-in-x6d.1e100.net (2a00:1450:4010:c0f::6d)
Host is up (0.062s latency).
Not shown: 995 filtered ports
PORT    STATE SERVICE
25/tcp  open  smtp
465/tcp open  smtps
587/tcp open  submission
993/tcp open  imaps
995/tcp open  pop3s
```
## 当前行为
连接smtp服务器失败
`Network is unreachable (connect failed)`

**Comment by aumk** [comment]
补充：
用以下python3代码成功测试了ipv6下google smtp服务器的可用性
```
import smtplib
from email.mime.text import MIMEText
from email.header import Header

from_addr = 'xxx@gmail.com'
password = 'xxx' 
to_addr = 'xxx@qq.com'
smtp_server = 'smtp.gmail.com'

msg = MIMEText('hello,python', 'plain', 'utf-8')

msg['From'] = 'Python Dev'
msg['To'] = 'Admin'
msg['Subject'] = Header('来自SMTP的问候...', 'utf-8').encode()

server = smtplib.SMTP(smtp_server, 587)  
server.starttls()
server.set_debuglevel(1)
server.login(from_addr, password)
server.sendmail(from_addr, [to_addr], msg.as_string())
server.quit()
```
排除了网络造成问题的可能性

**Comment by JohnNiang** [comment]
你可能需要加上 `-Djava.net.preferIPv4Stack=true` 参数启动 halo 来临时解决这个问题。

**Comment by JohnNiang** [comment]
如果你是用 `Docker` 启动的 `halo`，可能无法正常使用宿主机的 `ipv6`，建议你通过  jar 包在宿主机上启动并测试一下（同 python）。

**Comment by jianfei96** [comment]
> 你可能需要加上 `-Djava.net.preferIPv4Stack=true` 参数启动 halo 来临时解决这个问题。

这个命令是优先使用ipv4吗？我那个机器是纯ipv6的。

> 如果你是用 `Docker` 启动的 `halo`，可能无法正常使用宿主机的 `ipv6`，建议你通过 jar 包在宿主机上启动并测试一下（同 python）。

倒是没有在用docker。
log也只有这些。只能期待大佬用ipv6环境去测试一下了。
