### ISSUE TITLE
admin页面502

### ISSUE THREAD

**Issue by zeno-sh** [halo-dev/halo#1117]
1.4.1版本

后台登录页面报502

![image](https://user-images.githubusercontent.com/19320698/96832296-1d473d00-1471-11eb-9609-2a9702c03e64.png)

![image](https://user-images.githubusercontent.com/19320698/96832358-34862a80-1471-11eb-9a7a-5f7da6e75ec6.png)
![image](https://user-images.githubusercontent.com/19320698/96832378-3d76fc00-1471-11eb-93b5-1c035ef8651a.png)

`2020-10-22 14:07:52.099 ERROR 3471 --- [qtp872826668-12] r.h.a.controller.core.CommonController   :  URI: [/error], Request Method: [GET], IP: [103.202.147.77]
2020-10-22 14:08:05.847  WARN 3471 --- [qtp872826668-11] org.eclipse.jetty.server.HttpChannel     : /502.html

javax.servlet.ServletException: Could not resolve view with name '502' in servlet with name 'dispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1353) ~[spring-webmvc-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118) ~[spring-webmvc-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057) ~[spring-webmvc-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226) ~[websocket-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at run.halo.app.security.filter.ContentFilter.doAuthenticate(ContentFilter.java:57) ~[classes!/:1.4.1]
        at run.halo.app.security.filter.AbstractAuthenticationFilter.doFilterInternal(AbstractAuthenticationFilter.java:190) ~[classes!/:1.4.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at run.halo.app.filter.CorsFilter.doFilter(CorsFilter.java:49) ~[classes!/:1.4.1]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at run.halo.app.filter.LogFilter.doFilterInternal(LogFilter.java:38) ~[classes!/:1.4.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[jetty-security-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) ~[jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar!/:9.4.31.v20200723]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar!/:9.4.31.v20200723]`

**Comment by ruibaby** [comment]
看起来是反向代理配置导致的问题。能否提供你 nginx 的配置。

**Comment by zeno-sh** [comment]
> 看起来是反向代理配置导致的问题。能否提供给您nginx的配置。

用的宝塔，配置如下

server
{
    listen 80 default_server;
	listen 443 ssl http2 default_server;
    server_name www.zamblog.cn zamblog.cn;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/www.zamblog.cn;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    ssl_certificate    ***隐藏
    ssl_certificate_key    ***隐藏
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers  ***隐藏
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;



    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    error_page 404 /404.html;
    error_page 502 /502.html;
    #ERROR-PAGE-END
    
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/www.zamblog.cn.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }

    location / {
		proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_pass http://127.0.0.1:8081;
    }
    
    
    location /api {
		proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_pass http://127.0.0.1:8088;
    }
    
    access_log  /www/wwwlogs/www.zamblog.cn.log;
    error_log  /www/wwwlogs/www.zamblog.cn.error.log;
}

**Comment by zeno-sh** [comment]
> > 看起来是反向代理配置导致的问题。能否提供给您nginx的配置。
> 
> 用的宝塔，配置如下
> 
> server
> {
> listen 80 default_server;
> listen 443 ssl http2 default_server;
> server_name [www.zamblog.cn](http://www.zamblog.cn) zamblog.cn;
> index index.php index.html index.htm default.php default.htm default.html;
> root /www/wwwroot/www.zamblog.cn;
> 
> ```
> #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
> #error_page 404/404.html;
> ssl_certificate    ***隐藏
> ssl_certificate_key    ***隐藏
> ssl_protocols TLSv1.1 TLSv1.2;
> ssl_ciphers  ***隐藏
> ssl_prefer_server_ciphers on;
> ssl_session_cache shared:SSL:10m;
> ssl_session_timeout 10m;
> error_page 497  https://$host$request_uri;
> 
> 
> 
> #SSL-END
> 
> #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
> error_page 404 /404.html;
> error_page 502 /502.html;
> #ERROR-PAGE-END
> 
> 
> #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
> include /www/server/panel/vhost/rewrite/www.zamblog.cn.conf;
> #REWRITE-END
> 
> #禁止访问的文件或目录
> location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
> {
>     return 404;
> }
> 
> #一键申请SSL证书验证目录相关设置
> location ~ \.well-known{
>     allow all;
> }
> 
> location / {
> 	proxy_set_header HOST $host;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     
>     proxy_pass http://127.0.0.1:8081;
> }
> 
> 
> location /api {
> 	proxy_set_header HOST $host;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     
>     proxy_pass http://127.0.0.1:8088;
> }
> 
> access_log  /www/wwwlogs/www.zamblog.cn.log;
> error_log  /www/wwwlogs/www.zamblog.cn.error.log;
> ```
> 
> }

大概知道问题了，因为8088端口的服务是我自己的另外一个项目，/api这个路径冲突了。我修改一下

**Comment by ruibaby** [comment]
嗯，是这样的。
