### ISSUE TITLE
博客没有内容保存时发生npe异常

### ISSUE THREAD

**Issue by MrLawrenc** [halo-dev/halo#1179]
## 我的环境

版本：本地最新代码测试
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

---

## 错误日志

```java
java.lang.NullPointerException: null
	at run.halo.app.utils.HaloUtils.cleanHtmlTag(HaloUtils.java:277) ~[main/:na]
	at run.halo.app.service.impl.BasePostServiceImpl.createOrUpdateBy(BasePostServiceImpl.java:265) ~[main/:na]
	at run.halo.app.service.impl.PostServiceImpl.createOrUpdate(PostServiceImpl.java:765) ~[main/:na]
	at run.halo.app.service.impl.PostServiceImpl.createBy(PostServiceImpl.java:132) ~[main/:na]
```

---

## 期望行为

修复空指针，运行临时保存未开始书写的文章
run.halo.app.service.impl.BasePostServiceImpl#createOrUpdateBy
```java
    @Override
    @Transactional
    public POST createOrUpdateBy(POST post) {
        Assert.notNull(post, "Post must not be null");
        //内容为空
        String originalContent = post.getOriginalContent();
        originalContent = HaloUtils.cleanHtmlTag(originalContent);
       ..........
}
```
## 当前行为
准备写博客，想了个标题没有写任何内容临时有事出门，就想先保存，就报错了
![image](https://user-images.githubusercontent.com/35510822/101235915-8fb16b00-3707-11eb-94b3-a11d0682343c.png)

**Comment by ruibaby** [comment]
确定是最新代码的问题？

https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/utils/HaloUtils.java#L277

在 https://github.com/halo-dev/halo/pull/1099 已经被修复。
