### ISSUE TITLE
启动报错2021-02-10 15:08:39.254 ERROR 5058 --- [           main] o.s.boot.SpringApplication               : Application run failed

### ISSUE THREAD

**Issue by ZONGQUAN-HU** [halo-dev/halo#1268]
- java -version
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
- system
Linux VM-0-3-centos 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- 运行报错结果：

    __  __      __
   / / / /___ _/ /___
  / /_/ / __ `/ / __ \
 / __  / /_/ / / /_/ /
/_/ /_/\__,_/_/\____/

Version: 1.4.5
2021-02-10 15:08:14.044  INFO 5058 --- [           main] run.halo.app.Application                 : Starting Application v1.4.5 using Java 15.0.2 on VM-0-3-centos with PID 5058 (/home/halo/app/halo.jar started by halo in /home/halo/app)
2021-02-10 15:08:14.053  INFO 5058 --- [           main] run.halo.app.Application                 : No active profile set, falling back to default profiles: default
2021-02-10 15:08:17.047  INFO 5058 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2021-02-10 15:08:17.527  INFO 5058 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 455 ms. Found 22 JPA repository interfaces.
2021-02-10 15:08:20.070  INFO 5058 --- [           main] org.eclipse.jetty.util.log               : Logging initialized @8937ms to org.eclipse.jetty.util.log.Slf4jLog
2021-02-10 15:08:20.625  INFO 5058 --- [           main] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 80
2021-02-10 15:08:20.654  INFO 5058 --- [           main] org.eclipse.jetty.server.Server          : jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 15.0.2+7-27
2021-02-10 15:08:20.858  INFO 5058 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2021-02-10 15:08:20.858  INFO 5058 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6620 ms
2021-02-10 15:08:22.142  INFO 5058 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2021-02-10 15:08:22.413  INFO 5058 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.27.Final
2021-02-10 15:08:22.883  INFO 5058 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2021-02-10 15:08:23.236  INFO 5058 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-02-10 15:08:23.767  INFO 5058 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-02-10 15:08:23.846  INFO 5058 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2021-02-10 15:08:27.155  INFO 5058 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2021-02-10 15:08:27.181  INFO 5058 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-02-10 15:08:28.420  INFO 5058 --- [           main] run.halo.app.config.HaloConfiguration    : Halo cache store load impl : [class run.halo.app.cache.InMemoryCacheStore]
2021-02-10 15:08:29.887  INFO 5058 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2021-02-10 15:08:29.887  INFO 5058 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2021-02-10 15:08:29.889  INFO 5058 --- [           main] org.eclipse.jetty.server.session         : node0 Scavenging every 660000ms
2021-02-10 15:08:29.909  INFO 5058 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@b428830{application,/,[file:///tmp/jetty-docbase.80.12616557699118827259/, jar:file:/home/halo/app/halo.jar!/BOOT-INF/lib/springfox-swagger-ui-3.0.0.jar!/META-INF/resources],AVAILABLE}
2021-02-10 15:08:29.910  INFO 5058 --- [           main] org.eclipse.jetty.server.Server          : Started @18778ms
2021-02-10 15:08:34.351  INFO 5058 --- [           main] run.halo.app.handler.file.FileHandlers   : Registered 9 file handler(s)
2021-02-10 15:08:37.444  INFO 5058 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-02-10 15:08:38.903  INFO 5058 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2021-02-10 15:08:38.971  INFO 5058 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/api/admin/actuator'
2021-02-10 15:08:39.105  INFO 5058 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-02-10 15:08:39.105  INFO 5058 --- [           main] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-02-10 15:08:39.107  INFO 5058 --- [           main] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2021-02-10 15:08:39.115  INFO 5058 --- [           main] o.e.jetty.server.AbstractConnector       : Stopped ServerConnector@3fcdcf{HTTP/1.1, (http/1.1)}{0.0.0.0:80}
2021-02-10 15:08:39.127  INFO 5058 --- [           main] org.eclipse.jetty.server.session         : node0 Stopped scavenging
2021-02-10 15:08:39.128  INFO 5058 --- [           main] o.e.j.s.h.ContextHandler.application     : Destroying Spring FrameworkServlet 'dispatcherServlet'
2021-02-10 15:08:39.129  INFO 5058 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@b428830{application,/,[file:///tmp/jetty-docbase.80.12616557699118827259/, jar:file:/home/halo/app/halo.jar!/BOOT-INF/lib/springfox-swagger-ui-3.0.0.jar!/META-INF/resources],STOPPED}
2021-02-10 15:08:39.146  WARN 5058 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
2021-02-10 15:08:39.147  INFO 5058 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2021-02-10 15:08:39.148  INFO 5058 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2021-02-10 15:08:39.171  INFO 5058 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2021-02-10 15:08:39.172  INFO 5058 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-02-10 15:08:39.177  INFO 5058 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2021-02-10 15:08:39.208  INFO 5058 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-02-10 15:08:39.254 ERROR 5058 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.3.jar!/:5.3.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.3.jar!/:5.3.3]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.3.jar!/:5.3.3]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.3.jar!/:5.3.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.3.jar!/:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:940) ~[spring-context-5.3.3.jar!/:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591) ~[spring-context-5.3.3.jar!/:5.3.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at run.halo.app.Application.main(Application.java:21) ~[classes!/:1.4.5]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[halo.jar:1.4.5]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[halo.jar:1.4.5]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[halo.jar:1.4.5]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[halo.jar:1.4.5]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:194) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.4.2.jar!/:2.4.2]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.3.jar!/:5.3.3]
	... 23 common frames omitted
Caused by: java.io.IOException: Failed to bind to /0.0.0.0:80
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:174) ~[spring-boot-2.4.2.jar!/:2.4.2]
	... 25 common frames omitted
Caused by: java.net.BindException: Permission denied
	at java.base/sun.nio.ch.Net.bind0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.bind(Net.java:550) ~[na:na]
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:249) ~[na:na]
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88) ~[na:na]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345) ~[jetty-server-9.4.35.v20201120.jar!/:9.4.35.v20201120]
	... 30 common frames omitted

**Comment by ruibaby** [comment]
是不是80端口被占用了？

**Comment by Lewhan** [comment]
看你用户名是halo，应该是没有root权限不能绑定80端口

**Comment by ZONGQUAN-HU** [comment]
> 看你用户名是halo，应该是没有root权限不能绑定80端口

确实，我才发现，没有root权限就不能用80端口，确定是端口和权限的问题吧，不是其他问题就好。

**Comment by ruibaby** [comment]
> 看你用户名是halo，应该是没有root权限不能绑定80端口

正解。
