### ISSUE TITLE
Steps to initialize internal themes

### ISSUE THREAD

**Issue by salahatwa** [halo-dev/halo#1269]
Please for yours support , to explaining steps of initializing internal theme , 
as we put  theme under **resources/templates/themes** , and build jar file , and run following **java -jar halo-1.4.2.jar**
we received below error 

following path `try copy theme folder from [/BOOT-INF/classes/templates/themes] to [/app/.halo/templates/themes]

2021-02-10T07:59:58.701087+00:00 app[web.1]:run.halo.app.listener.StartedListener  ,  Initialize internal theme to user path error!
2021-02-10T07:59:58.701090+00:00 app[web.1]: 
2021-02-10T07:59:58.701091+00:00 app[web.1]: java.util.zip.ZipException: **invalid code lengths set**
2021-02-10T07:59:58.701091+00:00 app[web.1]: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[na:1.8.0_282-heroku]
2021-02-10T07:59:58.701092+00:00 app[web.1]: 	at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[na:1.8.0_282-heroku]
2021-02-10T07:59:58.701093+00:00 app[web.1]: 	at java.nio.file.Files.copy(Files.java:2908) ~[na:1.8.0_282-heroku]
2021-02-10T07:59:58.701093+00:00 app[web.1]: 	at java.nio.file.Files.copy(Files.java:3027) ~[na:1.8.0_282-heroku]
2021-02-10T07:59:58.701094+00:00 app[web.1]: 	at java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:126) ~[na:1.8.0_282-heroku]
2021-02-10T07:59:58.701094+00:00 app[web.1]: 	at java.nio.file.Files.copy(Files.java:1277) ~[na:1.8.0_282-heroku]
2021-02-10T07:59:58.701095+00:00 app[web.1]: 	at run.halo.app.utils.FileUtils$1.visitFile(FileUtils.java:62) ~[classes!/:1.4.2]`

**Comment by ruibaby** [comment]
It is not recommended to install the theme this way, you can upload it in admin. In the development environment, the default theme is a git submodule, so you may need `git submodule init` then `git submodule update`.

**Comment by salahatwa** [comment]
we can install theme , but in our case we need to initialize default theme , cause we have issue in our cloud deployment when we install theme after restart application we need to install theme every time , so if you can help us to solve above issue

**Comment by ruibaby** [comment]
> we can install theme , but in our case we need to initialize default theme , cause we have issue in our cloud deployment when we install theme after restart application we need to install theme every time , so if you can help us to solve above issue 

It seems to be a problem with heroku, I also tried deploying on heroku, but it seems that the working directory cannot be kept（~/.halo）

**Comment by ruibaby** [comment]
Any follow-up feedback?

**Comment by JohnNiang** [comment]
You have to persist ~/.halo folder in your cloud deployment now.

**Comment by salahatwa** [comment]
We done from intialize theme on heroku cloud , but there is some issue when application dyno sleep the theme deleted , 
We still trying to solve this issue

**Comment by JohnNiang** [comment]
Hello, @salahatwa , how is the progress recently?

**Comment by salahatwa** [comment]
we finished intialized default theme , we working now to upgrade vue to angular ,   really great works from yours , thanks alot
