### ISSUE TITLE
从v1.4.3升级到v1.4.4和v1.4.5版本，清缓存后，第一次访问首页，页面加载不完全。

### ISSUE THREAD

**Issue by Lilac-Dream** [halo-dev/halo#1270]
## 我的环境
版本：1.4.5
数据库：MySQL 8.0.22
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

## 错误日志
没有错误日志

## 期望行为
页面显示正常
![image](https://user-images.githubusercontent.com/49761134/107750946-a9021380-6d57-11eb-9584-1276b13a3d4b.png)

## 当前行为
（LIlGG/halo-theme-sakura主题的首屏图片无法加载，文章内容图片一直模糊状态，不会继续加载，尝试更换主题也会出现类似的问题。）
![image](https://user-images.githubusercontent.com/49761134/107750952-ab646d80-6d57-11eb-92a2-e990c0539895.png)

## 补充：
1、尝试更新v1.4.4和v1.4.5版本，都出现问题，回退到v1.4.3版本，一切正常。
（所以，不存在http和https以及nginx配置的问题，而且是内网，网速也没问题）
2、尝试删除主题（包括主题配置），重新下载安装主题后也无法解决问题。
3、尝试直接搭建v1.4.5版本的halo微博，下载安装主题，不出问题。
4、从v1.4.3之前的微博搭建的新的空的微博，更新后也不出现这个问题。
5、删掉数据库，v1.4.5版本重建立数据库，也正常了。
6、尝试切换到别的页面，再切回到首页，首页显示也正常了，但是清理浏览器缓存后直接尝试打开主页，问题又出现了。
7、并不是只有LIlGG/halo-theme-sakura的主题出问题，换主题也出现类似的问题。

我猜测，在v1.4.4版本时的改动影响到初次登录首页时部分文件的加载，而且是旧版本的注册表项目在更新后影响到的。
所以，我想知道，我的数据库哪里有bug造成的吗？怎么修复？虽然我更怀疑是v1.4.4的改动造成的。

很抱歉，由于是我内网ip，无法给出复现链接。
搭建方式：CentOS直接安装，没有使用Docker。

**Comment by ruibaby** [comment]
先看看浏览器控制台有没有什么异常。

**Comment by Lilac-Dream** [comment]
![image](https://user-images.githubusercontent.com/49761134/107754672-c685ac00-6d5c-11eb-9e42-1944ab44d2b5.png)
![image](https://user-images.githubusercontent.com/49761134/107754692-ce455080-6d5c-11eb-8f01-9f5c7fa3a411.png)
空白的，没有异常。

**Comment by ruibaby** [comment]
> ![image](https://user-images.githubusercontent.com/49761134/107754672-c685ac00-6d5c-11eb-9e42-1944ab44d2b5.png)
> 
> ![image](https://user-images.githubusercontent.com/49761134/107754692-ce455080-6d5c-11eb-8f01-9f5c7fa3a411.png)
> 
> 空白的，没有异常。

我们晚些时候会根据你的步骤尝试复现。

**Comment by Lilac-Dream** [comment]
谢谢！

**Comment by Lilac-Dream** [comment]
我发现，原来我有文章影响到首页显示的情况了。。。。从数据库删掉一些文章，竟然好用了。晚些我会上传更多的内容方便复现。

**Comment by Lilac-Dream** [comment]
（实在不知道怎么发文件了，只好传到github上面了）

https://github.com/Lilac-Dream/halo_bug/
这里是我出现问题的数据库和服务器的文件夹，我把多余的内容删掉了，容易复现。

作者大大只需要把halodb.sql数据库内容导入到halodb里面。然后把.halo文件解压到Centos上面。

我设置的服务器ip：http://192.168.200.6:10000
当前用户名：admin
密码：12345678

当前发现的解决方式：
1、mysql数据库：删除tags、删除categories、删除posts的内容都可以解决。

**Comment by ruibaby** [comment]
有成功复现，但是没有在其他主题上成功复现。

具体原因是请求发生了中断：

```
GET http://localhost:10000/ net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
```

但是很遗憾，并没有排查出来请求中断的原因。

这个可能得我们年后再看看了。

**Comment by Lilac-Dream** [comment]
嗯嗯，好的，谢谢～

**Comment by ruibaby** [comment]
@LIlGG 我们需要先排查是否是Sakura主题的问题。

**Comment by LIlGG** [comment]
> @LIlGG 我们需要先排查是否是Sakura主题的问题。

了解～明天我将系统的排查一遍主题，看看是不是主题的问题

**Comment by Lilac-Dream** [comment]
又要麻烦大佬们解决一下~~~我是通过删除我的数据库，把问题复现出来的。

#### 新的问题的复现文件下载：
https://github.com/Lilac-Dream/halo_bug/tree/master/%E6%96%B0%E7%9A%84%E9%97%AE%E9%A2%98%E5%A4%8D%E7%8E%B0

#### 当前halo微博的用户名：admin 密码：12345678

## 说明：
- 我只发现Sagiri和Sakura主题更新halo版本后才出现问题，默认主题是没有问题的。
- halo使用v1.4.4和v1.4.5版本运行会出现问题。
- halo使用v1.4.3版本运行，没有问题。
- 如果先进入归档页或者其他页面，比如先进入：`http://192.168.200.6:10000/archives`，然后再进行访问主页，就一切正常了，但是清理缓存后直接访问主页，就又出问题了。

## 复现的方式：
+ 完全清除浏览器缓存，直接访问首页。

## 当前出现的情况：

1. 清除缓存，直接访问主页，无法访问，并且控制台会报错。
![image](https://user-images.githubusercontent.com/49761134/107848185-63634a80-6e2c-11eb-8ce8-d79b8e4ad691.png)

2. 不打开F12控制台(不要一直清除缓存的)情况下，尝试F5多次刷新页面进行访问，两个主题都会进入主页加载不完全的情况。
#### 如图所示：
Sagiri的右侧用户信息的地方不显示，以及最底部的文章和翻页也加载不出来。
![image](https://user-images.githubusercontent.com/49761134/107848208-7c6bfb80-6e2c-11eb-8f83-cedad1ed8217.png)
![image](https://user-images.githubusercontent.com/49761134/107848211-82fa7300-6e2c-11eb-8a89-5a9d9f1e403a.png)

**Comment by JohnNiang** [comment]
我怀疑是你的文章内容中包含特殊字符，导致最后渲染结果出问题了。

**Comment by ruibaby** [comment]
> 我怀疑是你的文章内容中包含特殊字符，导致最后渲染结果出问题了。

没有，内容都是 11 12 这种。

**Comment by JohnNiang** [comment]
我尝试用 docker 复现一下。

**Comment by JohnNiang** [comment]
使用 docker 从 1.4.3 升级至 1.4.4，再升级至 1.4.5，没有发现任何问题。

**Comment by kk140906** [comment]
我更新到1.45也发现这个问题了

**Comment by ruibaby** [comment]
捕获到异常：

```
2021-02-21 15:01:30.992  WARN 33944 --- [ qtp78797488-22] org.eclipse.jetty.server.HttpChannel     : /

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: Response is committed
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar:4.0.4]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228) ~[websocket-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.3.jar:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.3.jar:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at run.halo.app.security.filter.ContentFilter.doAuthenticate(ContentFilter.java:57) ~[classes/:na]
	at run.halo.app.security.filter.AbstractAuthenticationFilter.doFilterInternal(AbstractAuthenticationFilter.java:229) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at run.halo.app.filter.CorsFilter.doFilter(CorsFilter.java:53) ~[classes/:na]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.4.2.jar:2.4.2]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.3.jar:5.3.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at run.halo.app.filter.LogFilter.doFilterInternal(LogFilter.java:40) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[jetty-security-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) ~[jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: java.lang.IllegalStateException: Response is committed
	at org.eclipse.jetty.server.Request.getSession(Request.java:1620) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at org.eclipse.jetty.server.Request.getSession(Request.java:1599) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
	at run.halo.app.service.impl.AuthorizationServiceImpl.buildAccessPermissionKey(AuthorizationServiceImpl.java:73) ~[classes/:na]
	at run.halo.app.service.impl.AuthorizationServiceImpl.getAccessPermissionStore(AuthorizationServiceImpl.java:38) ~[classes/:na]
	at run.halo.app.service.impl.AuthenticationServiceImpl.categoryAuthentication(AuthenticationServiceImpl.java:77) ~[classes/:na]
	at run.halo.app.service.impl.CategoryServiceImpl.doFilterEncryptCategory(CategoryServiceImpl.java:407) ~[classes/:na]
	at run.halo.app.service.impl.CategoryServiceImpl.filterEncryptCategory(CategoryServiceImpl.java:383) ~[classes/:na]
	at run.halo.app.service.impl.CategoryServiceImpl.listAll(CategoryServiceImpl.java:491) ~[classes/:na]
	at run.halo.app.service.impl.CategoryServiceImpl.listAll(CategoryServiceImpl.java:480) ~[classes/:na]
	at run.halo.app.service.impl.CategoryServiceImpl$$FastClassBySpringCGLIB$$816363be.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.3.jar:5.3.3]
	at run.halo.app.service.impl.CategoryServiceImpl$$EnhancerBySpringCGLIB$$93e167b6.listAll(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-5.3.3.jar:5.3.3]
	at com.sun.proxy.$Proxy166.listAll(Unknown Source) ~[na:na]
	at run.halo.app.service.impl.PostCategoryServiceImpl.listCategoryWithPostCountDto(PostCategoryServiceImpl.java:310) ~[classes/:na]
	at run.halo.app.service.impl.PostCategoryServiceImpl$$FastClassBySpringCGLIB$$7cfaa37e.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.3.jar:5.3.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.3.3.jar:5.3.3]
	at run.halo.app.service.impl.PostCategoryServiceImpl$$EnhancerBySpringCGLIB$$f84cfef6.listCategoryWithPostCountDto(<generated>) ~[classes/:na]
	at run.halo.app.core.freemarker.tag.CategoryTagDirective.execute(CategoryTagDirective.java:54) ~[classes/:na]
	at freemarker.core.Environment.visit(Environment.java:451) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:102) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:334) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:376) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:876) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.invokeMacro(Environment.java:812) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:334) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.visit(Environment.java:340) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.core.Environment.process(Environment.java:313) ~[freemarker-2.3.30.jar:2.3.30]
	at freemarker.template.Template.process(Template.java:383) ~[freemarker-2.3.30.jar:2.3.30]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:391) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:304) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:255) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:179) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1393) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1138) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1077) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.3.jar:5.3.3]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.3.jar:5.3.3]
	... 73 common frames omitted
```

@zhixiangyuan 和你提交的 java/run/halo/app/service/AuthenticationService#buildAccessPermissionKey 有关，希望可以排查一下。

**Comment by ruibaby** [comment]
@zhixiangyuan 可复现的工作目录：https://ryanc.cc/upload/2021/02/halo-backup-2021-02-20-00-18-56--1657152137-c5ee37cd2b224f939c1cfc8cc94e87af.zip
