### ISSUE TITLE
初始化脚本在哪个目录么？

### ISSUE THREAD

**Issue by 13077598960** [halo-dev/halo#1368]
我需要冲很老的1.1.1升级到最新版本，想要进行数据迁移，所以想找一下初始化脚本在哪目录。
运行报错如下：
021-05-07 23:22:09.870 ERROR 8 --- [main] o.s.boot.SpringApplication               : Application run failed

org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql failed
-------------------------------------------------------------
SQL State  : 42S22
Error Code : 42122
Message    : Column "SOURCE_CONTENT" not found; SQL statement:
update journals set `source_content`=`content` [42122-197]
Location   : migration/V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql (/application/BOOT-INF/classes/migration/V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql)
Line       : 5
Statement  : update journals set `source_content`=`content`

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:424) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:328) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:325) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:290) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:194) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:191) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:216) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:570) ~[flyway-core-7.5.1.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165) ~[flyway-core-7.5.1.jar:na]
	at run.halo.app.listener.StartedListener.migrate(StartedListener.java:123) ~[classes/:1.4.8]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:76) ~[classes/:1.4.8]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:47) ~[classes/:1.4.8]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.5.jar:5.3.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.5.jar:5.3.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.5.jar:5.3.5]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.5.jar:5.3.5]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.5.jar:5.3.5]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:105) ~[spring-boot-2.5.0-M3.jar:2.5.0-M3]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.0-M3.jar:2.5.0-M3]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.0-M3.jar:2.5.0-M3]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.0-M3.jar:2.5.0-M3]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.0-M3.jar:2.5.0-M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-2.5.0-M3.jar:2.5.0-M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) ~[spring-boot-2.5.0-M3.jar:2.5.0-M3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1314) ~[spring-boot-2.5.0-M3.jar:2.5.0-M3]
	at run.halo.app.Application.main(Application.java:21) ~[classes/:1.4.8]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[application/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application/:na]

**Comment by ruibaby** [comment]
@13077598960 建议再将 flyway_history 这个表删除时候重新启动。

**Comment by 13077598960** [comment]
已清空
