### ISSUE TITLE
生产环境邮件推送无法成功

### ISSUE THREAD

**Issue by li-guohao** [halo-dev/halo#1441]
### What is version of Halo has the issue?

1.4.11

### What database are you using?

Other

### Your site address.

https://blog.liguohao.cn

### What happened?

生产环境下，邮件推送无法成功，相同的配置本地开发木的问题
生产环境状况：
数据库用的是`MariaDB10`
涉及halo服务的有两台机器，分别是部署`halo`的`blog-halo`，和进行反向代理的`home-nginx`
`halo`部署在服务器`blog-halo`上，端口占用默认的`8090`，防火墙已关闭，IP地址是局域网的`192.168.0.122`
`nginx`部署在服务器`home-nginx`上，防火墙已关闭，反向代理`halo`的配置文件`blog.conf`如下
``` conf
server {
    listen 80;
    server_name blog.liguohao.cn;
    #将请求转成https
    return 301 https://$server_name$request_uri;
}

server {
listen       443 ssl;
server_name  blog.liguohao.cn;

    # ssl证书地址
    ssl_certificate /ssl/liguohao.cn/fullchain.crt;
    ssl_certificate_key /ssl/liguohao.cn/private.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

location / {
    
    proxy_pass http://192.168.0.122:8090/;
}
}
```

### Relevant log output

```shell
Jul 26 21:21:24 blog-halo java[5288]: 2021-07-26 21:21:24.694 DEBUG 5288 --- [tp1164241227-19] run.halo.app.core.ControllerLogAop       : Usage:
Jul 26 21:21:24 blog-halo java[5288]: StopWatch '/api/admin/mails/test': running time = 11943024 ns
Jul 26 21:21:24 blog-halo java[5288]: ---------------------------------------------
Jul 26 21:21:24 blog-halo java[5288]: ns         %     Task name
Jul 26 21:21:24 blog-halo java[5288]: ---------------------------------------------
Jul 26 21:21:24 blog-halo java[5288]: 000698459  006%  PrintRequest
Jul 26 21:21:24 blog-halo java[5288]: 010942497  092%  MailController#testMail
Jul 26 21:21:24 blog-halo java[5288]: 000302068  003%  PrintResponse
Jul 26 21:21:24 blog-halo java[5288]: 2021-07-26 21:21:24.702 DEBUG 5288 --- [tp1164241227-19] run.halo.app.filter.LogFilter            : Ending   url: [http://192.168.0.122:8090/api/admin/mails/test], method: [POST], ip: [192.168.0.118], status: [200], usage: [56] ms
Jul 26 21:21:24 blog-halo java[5288]: 2021-07-26 21:21:24.706 DEBUG 5288 --- [pool-4-thread-3] run.halo.app.mail.AbstractMailService    : MailProperties{,
Jul 26 21:21:24 blog-halo java[5288]: host=smtpdm.aliyun.com,
Jul 26 21:21:24 blog-halo java[5288]: username=mail@liguohao.cn,
Jul 26 21:21:24 blog-halo java[5288]: password=<non-null>port=465,
Jul 26 21:21:24 blog-halo java[5288]: protocol=smtp,
Jul 26 21:21:24 blog-halo java[5288]: defaultEncoding=UTF-8,
Jul 26 21:21:24 blog-halo java[5288]: properties={mail.debug=true, mail.smtp.auth=true, mail.smtp.timeout=10000, mail.smtp.ssl.enable=true},
Jul 26 21:21:24 blog-halo java[5288]: }
Jul 26 21:21:24 blog-halo java[5288]: DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
Jul 26 21:21:24 blog-halo java[5288]: DEBUG SMTP: useEhlo true, useAuth true
Jul 26 21:21:24 blog-halo java[5288]: DEBUG SMTP: trying to connect to host "smtpdm.aliyun.com", port 465, isSSL true
Jul 26 21:21:24 blog-halo java[5288]: 220 smtp.aliyun-inc.com MX AliMail Server(127.0.0.1)
Jul 26 21:21:24 blog-halo java[5288]: DEBUG SMTP: connected to host "smtpdm.aliyun.com", port: 465
Jul 26 21:21:45 blog-halo java[5288]: EHLO blog-halo
Jul 26 21:21:45 blog-halo java[5288]: DEBUG SMTP: EOF: [EOF]
Jul 26 21:21:45 blog-halo java[5288]: HELO blog-halo
Jul 26 21:21:45 blog-halo java[5288]: Exception in thread "pool-4-thread-3" run.halo.app.exception.EmailException: 邮件发送失败，请检查 SMTP 服务配置是否正确
Jul 26 21:21:45 blog-halo java[5288]: at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:122)
Jul 26 21:21:45 blog-halo java[5288]: at run.halo.app.mail.AbstractMailService.lambda$sendMailTemplate$0(AbstractMailService.java:137)
Jul 26 21:21:45 blog-halo java[5288]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jul 26 21:21:45 blog-halo java[5288]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jul 26 21:21:45 blog-halo java[5288]: at java.base/java.lang.Thread.run(Thread.java:829)
Jul 26 21:21:45 blog-halo java[5288]: Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Can't send command to SMTP host;
Jul 26 21:21:45 blog-halo java[5288]: nested exception is:
Jul 26 21:21:45 blog-halo java[5288]: java.net.SocketException: Connection or outbound has closed. Failed messages: javax.mail.MessagingException: Can't send command to SMTP host;
Jul 26 21:21:45 blog-halo java[5288]: nested exception is:
Jul 26 21:21:45 blog-halo java[5288]: java.net.SocketException: Connection or outbound has closed; message exceptions (1) are:
Jul 26 21:21:45 blog-halo java[5288]: Failed message 1: javax.mail.MessagingException: Can't send command to SMTP host;
Jul 26 21:21:45 blog-halo java[5288]: nested exception is:
Jul 26 21:21:45 blog-halo java[5288]: java.net.SocketException: Connection or outbound has closed
Jul 26 21:21:45 blog-halo java[5288]: at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448)
Jul 26 21:21:45 blog-halo java[5288]: at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
Jul 26 21:21:45 blog-halo java[5288]: at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
Jul 26 21:21:45 blog-halo java[5288]: at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:115)
Jul 26 21:21:45 blog-halo java[5288]: ... 4 more
Jul 26 21:21:45 blog-halo java[5288]: Caused by: javax.mail.MessagingException: Can't send command to SMTP host;
Jul 26 21:21:45 blog-halo java[5288]: nested exception is:
Jul 26 21:21:45 blog-halo java[5288]: java.net.SocketException: Connection or outbound has closed
Jul 26 21:21:45 blog-halo java[5288]: at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2431)
Jul 26 21:21:45 blog-halo java[5288]: at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2418)
Jul 26 21:21:45 blog-halo java[5288]: at com.sun.mail.smtp.SMTPTransport.issueCommand(SMTPTransport.java:2334)
Jul 26 21:21:45 blog-halo java[5288]: at com.sun.mail.smtp.SMTPTransport.helo(SMTPTransport.java:1663)
Jul 26 21:21:45 blog-halo java[5288]: at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:728)
Jul 26 21:21:45 blog-halo java[5288]: at javax.mail.Service.connect(Service.java:342)
Jul 26 21:21:45 blog-halo java[5288]: at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
Jul 26 21:21:45 blog-halo java[5288]: at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
Jul 26 21:21:45 blog-halo java[5288]: ... 7 more
Jul 26 21:21:45 blog-halo java[5288]: Caused by: java.net.SocketException: Connection or outbound has closed
Jul 26 21:21:45 blog-halo java[5288]: at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1217)
Jul 26 21:21:45 blog-halo java[5288]: at com.sun.mail.util.TraceOutputStream.write(TraceOutputStream.java:116)
Jul 26 21:21:45 blog-halo java[5288]: at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
Jul 26 21:21:45 blog-halo java[5288]: at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
Jul 26 21:21:45 blog-halo java[5288]: at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:2429)
Jul 26 21:21:45 blog-halo java[5288]: ... 14 more
```

### Additional information

halo生产环境邮件发送错误DEBUG日志如上方，在第24行连接SMTP服务器时出现的EOF错误，我没啥头绪额

本地开发环境邮件发送DEBUG日志如下：
```
2021-07-26 21:28:03.530 DEBUG 7884 --- [ qtp79197999-52] run.halo.app.core.ControllerLogAop       : Usage:
StopWatch '/api/admin/mails/test': running time = 5767200 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
001372000  024%  PrintRequest
003146400  055%  MailController#testMail
001248800  022%  PrintResponse

2021-07-26 21:28:03.533 DEBUG 7884 --- [ qtp79197999-52] run.halo.app.filter.LogFilter            : Ending   url: [http://127.0.0.1:8090/api/admin/mails/test], method: [POST], ip: [127.0.0.1], status: [200], usage: [73] ms
2021-07-26 21:28:03.564 DEBUG 7884 --- [pool-5-thread-1] run.halo.app.mail.AbstractMailService    : MailProperties{,
host=smtpdm.aliyun.com,
username=mail@liguohao.cn,
password=<non-null>port=465,
protocol=smtp,
defaultEncoding=UTF-8,
properties={mail.debug=true, mail.smtp.auth=true, mail.smtp.timeout=10000, mail.smtp.ssl.enable=true},
}
DEBUG: Jakarta Mail version 1.6.7
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: Providers Listed By Protocol: {imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth true
DEBUG SMTP: trying to connect to host "smtpdm.aliyun.com", port 465, isSSL true
220 smtp.aliyun-inc.com MX AliMail Server(127.0.0.1)
DEBUG SMTP: connected to host "smtpdm.aliyun.com", port: 465
EHLO liguohao-pc
250-smtp.aliyun-inc.com
250-8BITMIME
250-AUTH=PLAIN LOGIN XALIOAUTH
250-AUTH PLAIN LOGIN XALIOAUTH
250-PIPELINING
250 DSN
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "AUTH=PLAIN", arg "LOGIN XALIOAUTH"
DEBUG SMTP: Found extension "AUTH", arg "PLAIN LOGIN XALIOAUTH"
DEBUG SMTP: Found extension "PIPELINING", arg ""
DEBUG SMTP: Found extension "DSN", arg ""
DEBUG SMTP: protocolConnect login, host=smtpdm.aliyun.com, user=mail@liguohao.cn, password=<non-null>
DEBUG SMTP: Attempt to authenticate using mechanisms: LOGIN PLAIN DIGEST-MD5 NTLM XOAUTH2 
DEBUG SMTP: Using mechanism LOGIN
DEBUG SMTP: AUTH LOGIN command trace suppressed
DEBUG SMTP: AUTH LOGIN succeeded
DEBUG SMTP: use8bit false
MAIL FROM:<mail@liguohao.cn>
250 Mail Ok
RCPT TO:<liguohao_cn@qq.com>
250 Rcpt Ok
DEBUG SMTP: Verified Addresses
DEBUG SMTP:   liguohao_cn@qq.com
DATA
354 End data with <CR><LF>.<CR><LF>
Date: Mon, 26 Jul 2021 21:28:04 +0800 (CST)
From: "mail@liguohao.cn" <mail@liguohao.cn>
To: liguohao_cn@qq.com
Message-ID: <1510015138.0.1627306084520@liguohao-pc>
Subject: =?UTF-8?B?5rWL6K+V6YKu5Lu2?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

6L+Z5piv5LiA5bCB5Y+R5L+h5rWL6K+V6YKu5Lu277yM5pys5Zyw5byA5Y+R546v5aKD
.
250 Data Ok: queued as freedom ###envid=17870283497611498281
DEBUG SMTP: message successfully delivered to mail server
QUIT
221 Bye
2021-07-26 21:28:04.725  INFO 7884 --- [pool-5-thread-1] run.halo.app.mail.AbstractMailService    : Sent an email to [[liguohao_cn@qq.com]] successfully, subject: [�����ʼ�], sent date: [Mon Jul 26 21:28:04 CST 2021]

```

**Comment by JohnNiang** [comment]
生产环境下能够和邮件服务器正常沟通么？

**Comment by li-guohao** [comment]
> 生产环境下能够和邮件服务器正常沟通么？

我试过了部署 halo的机器对阿里云的那个smtp域名是可以ping通，然而程序如日志里那样，在连接域名服务器时出现EOF错误。

我这边目前打算去了解下SMTP协议的相关定义信息，了解下EOF错误

**Comment by ruibaby** [comment]
是否有解决此问题呢？

**Comment by li-guohao** [comment]
> 是否有解决此问题呢？

最近在忙工作，这个问题目前还没解决，这段时间没有空了，建议可以先暂时关闭，毕竟这个问题可能的原因有多个方面，或许并不是halo本身造成的问题。

**Comment by dejavuwl** [comment]
1.4.8 生产环境没有问题，用的是163的SMTP服务，过两天升级到最新版试一下

**Comment by mimajiushi** [comment]
我以前遇到过这个错误，不过原因似乎是自己改了springboot版本导致的

我现在用的1.4.11版本+MySQL，从阿里云切到腾讯云都木有问题，或者可以换台服务器试试？

**Comment by li-guohao** [comment]
我迁移博客到阿里云的服务器上了，一样的jar包，阿里云的服务器没问题，不知道什么原因，这个issue我关掉了
