### ISSUE TITLE
无法访问halo

### ISSUE THREAD

**Issue by xiaofengjue** [halo-dev/halo#1467]
### What is version of Halo has the issue?

1.4.8

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

https://sillage.wang

### What happened?

早上醒来看到阿里云给我发的信息，halo博客所在的阿里云宕机了，然后重启实例
然后重启halo，halo显示运行着，但是无法访问，排除了防火墙以及阿里云安全组的端口问题
halo的安装是根据官方文档来的，新建halo用户，以及将halo添加为服务管理
停止halo，查看halo状态，提示状态为failed，那就应该是有什么错误了

就很奇怪昨天都可以，宕机一下，今天就怎么都不行了

### Relevant log output
启动提示的日志：
```
No active profile set, falling back to default profiles: default
```

```shell
● halo.service - Halo Service
   Loaded: loaded (/etc/systemd/system/halo.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2021-09-04 16:29:07 CST; 1min 53s ago
     Docs: https://docs.halo.run
  Process: 2562 ExecStop=/bin/kill -s QUIT $MAINPID (code=exited, status=0/SUCCESS)
  Process: 2533 ExecStart=/usr/bin/java -server -Xms256m -Xmx256m -jar /home/halo/app/halo.jar (code=exited, status=143)
 Main PID: 2533 (code=exited, status=143)

Sep 04 16:29:04 iZhp3661jqu8od84z9g4f8Z java[2533]: from space 8704K,  42% used [0x00000000f4cd0000, 0x00000000f5062f80, 0x00000000f5550000)
Sep 04 16:29:04 iZhp3661jqu8od84z9g4f8Z java[2533]: to   space 8704K,   0% used [0x00000000f4450000, 0x00000000f4450000, 0x00000000f4cd0000)
Sep 04 16:29:04 iZhp3661jqu8od84z9g4f8Z java[2533]: tenured generation   total 174784K, used 18845K [0x00000000f5550000, 0x0000000100000000, 0x0000000100000000)
Sep 04 16:29:04 iZhp3661jqu8od84z9g4f8Z java[2533]: the space 174784K,  10% used [0x00000000f5550000, 0x00000000f67b7750, 0x00000000f67b7800, 0x0000000100000000)
Sep 04 16:29:04 iZhp3661jqu8od84z9g4f8Z java[2533]: Metaspace       used 41991K, capacity 43268K, committed 43560K, reserved 1087488K
Sep 04 16:29:04 iZhp3661jqu8od84z9g4f8Z java[2533]: class space    used 5652K, capacity 6195K, committed 6272K, reserved 1048576K
Sep 04 16:29:07 iZhp3661jqu8od84z9g4f8Z systemd[1]: halo.service: main process exited, code=exited, status=143/n/a
Sep 04 16:29:07 iZhp3661jqu8od84z9g4f8Z systemd[1]: Stopped Halo Service.
Sep 04 16:29:07 iZhp3661jqu8od84z9g4f8Z systemd[1]: Unit halo.service entered failed state.
Sep 04 16:29:07 iZhp3661jqu8od84z9g4f8Z systemd[1]: halo.service failed.
```

### Additional information

阿里云是centos7

**Comment by guqing** [comment]
检查一下halo的启动日志看看有没有什么异常，你贴的日志没法看出问题的原因

**Comment by guqing** [comment]
或者重新启动一下试试: `java  -Xms256m -Xmx256m -jar /home/halo/app/halo.jar > nohup.out 2>&1 &`

**Comment by xiaofengjue** [comment]
还是不行啊，手动启动能访问但是不是原来的了，服务形式重启又无法访问

**Comment by xiaofengjue** [comment]
> 检查一下halo的启动日志看看有没有什么异常，你贴的日志没法看出问题的原因

启动时有提示这个：No active profile set, falling back to default profiles: default
配置文件写的8090端口，但是启动服务后，lsof -i查看该端口没有服务

**Comment by xiaofengjue** [comment]
这个周末的好心情都被搞没了

**Comment by ruibaby** [comment]
> > 检查一下halo的启动日志看看有没有什么异常，你贴的日志没法看出问题的原因
> 
> 启动时有提示这个：No active profile set, falling back to default profiles: default
> 配置文件写的8090端口，但是启动服务后，lsof -i查看该端口没有服务

请提供完整日志。~/.halo/logs/spring.log

**Comment by ruibaby** [comment]
> 这个周末的好心情都被搞没了

那您觉得我们每天面对这些 issue 心情如何？

**Comment by xiaofengjue** [comment]
> > > 检查一下halo的启动日志看看有没有什么异常，你贴的日志没法看出问题的原因
> > 
> > 
> > 启动时有提示这个：No active profile set, falling back to default profiles: default
> > 配置文件写的8090端口，但是启动服务后，lsof -i查看该端口没有服务
> 
> 请提供完整日志。~/.halo/logs/spring.log

您好，希望能提供一下帮助
```
2021-09-05 19:22:01.428  INFO 27586 --- [main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-09-05 19:22:01.467 ERROR 27586 --- [main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty web server
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577) ~[spring-context-5.3.5.jar!/:5.3.5]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:430) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:328) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1314) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at run.halo.app.Application.main(Application.java:21) ~[classes!/:1.4.8]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[halo.jar:1.4.8]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[halo.jar:1.4.8]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[halo.jar:1.4.8]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[halo.jar:1.4.8]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty web server
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:129) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.<init>(JettyWebServer.java:90) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getJettyWebServer(JettyServletWebServerFactory.java:424) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:168) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:159) ~[spring-boot-2.5.0-M3.jar!/:2.5.0-M3]
        ... 16 common frames omitted

```

**Comment by ruibaby** [comment]
@xiaofengjue  不够完整，建议直接上传 spring.log 文件，或者发送到 hi@halo.run 邮箱。

**Comment by xiaofengjue** [comment]
> @xiaofengjue 不够完整，建议直接上传 spring.log 文件，或者发送到 [hi@halo.run](mailto:hi@halo.run) 邮箱。

您好请问您有时间吗，如果可以的话希望您能远程帮助我一下，我和我的小伙伴现在仍未解决这个问题，查看了日志，halo服务一直无限重启，我已经被这个问题折磨了两天了，我会在线等您半小时

**Comment by ruibaby** [comment]
wx: Wry2slp

**Comment by xiaofengjue** [comment]
> wx: Wry2slp

我之前加过你  给你发消息了

**Comment by xiaofengjue** [comment]
> wx: Wry2slp

wx：StarkShadow

**Comment by xiaofengjue** [comment]
问题已经解决

问题原因：直接在配置文件里修改了h2的数据库密码，重启服务后就遇到一系列问题。调试过程中将halo.service里的运行用户由halo改为root忘了改回去导致调试时遇到一些未知错误和现象，如：`java -jar halo.jar`启动halo时提示对应端口为8091，但是访问8090才有halo博客，但8091却没有（已防火墙和安全组策略问题），然后博客css丢失界面异常，而且也丢失了原来博客的数据

解决办法：将配置文件中的h2的数据库密码改为默认的123456，将halo.service中的用户改回halo；并将h2-console关闭，这样就几乎没有什么安全问题。如果需要修改h2相关数据，进入配置文件将下面false都改为true，访问`ip:port/h2-console`即可
```
h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false
```

最后再次感谢`Ryan Wang`深夜的远程帮助。
