### ISSUE TITLE
1.4.12 整站备份失败，提示Failed to backup halo

### ISSUE THREAD

**Issue by hutupro** [halo-dev/halo#1491]
### 是什么版本出现了此问题？

1.4.12

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

点击“整站备份”，提示Failed to backup halo，后台日志发现可能是~/.halo/db/halo.mv.db文件被锁定导致，仅被Java占用。
![image](https://user-images.githubusercontent.com/91881995/136266342-2e1545fe-dafb-4370-b503-dcd31558cecc.png)

直接复制这个数据库文件也提示失败，关闭halo后可以复制。
![image](https://user-images.githubusercontent.com/91881995/136266238-ab90a5ac-42f6-4535-8de2-5e8cd45c7ce4.png)

### 相关日志输出

```shell
run.halo.app.exception.ServiceException: Failed to backup halo
	at run.halo.app.service.impl.BackupServiceImpl.backupWorkDirectory(BackupServiceImpl.java:240) ~[classes!/:1.4.12]
	at run.halo.app.controller.admin.api.BackupController.backupHalo(BackupController.java:85) ~[classes!/:1.4.12]
	at run.halo.app.controller.admin.api.BackupController$$FastClassBySpringCGLIB$$810ea7c7.invoke(<generated>) ~[classes!/:1.4.12]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar!/:5.3.8]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        ...

Caused by: java.io.IOException: 另一个程序已锁定文件的一部分，进程无法访问。
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:54) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
        ...
```

**Comment by hutupro** [comment]
> 请尝试关闭站点后，手动备份：`~/.halo` 文件夹。

这只是规避方式呀，有没有根本解决措施？
