### ISSUE TITLE
启动报错，访问过于频繁

### ISSUE THREAD

**Issue by StarSky1** [halo-dev/halo#1525]
### What is version of Halo has the issue?

1.4.13

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

http://blog.starsky1.cn

### What happened?

使用 systemctl start halo 启动报错。环境: ubuntu16.04 lts

### Relevant log output

```shell
2021-11-13 00:29:53.769  WARN 6531 --- [qtp1601756706-39] run.halo.app.cache.InMemoryCacheStore    : Failed to put the cache, becau
se the key: [cache_lock_public run.halo.app.model.dto.BaseCommentDTO run.halo.app.controller.content.api.PostController.comment(run
.halo.app.model.params.PostCommentParam):121.35.3.225] has been present already
2021-11-13 00:29:53.771 ERROR 6531 --- [qtp1601756706-39] r.h.app.core.ControllerExceptionHandler  : Captured an exception:

run.halo.app.exception.FrequentAccessException: 访问过于频繁，请稍后再试！
        at run.halo.app.cache.lock.CacheLockInterceptor.interceptCacheLock(CacheLockInterceptor.java:67) ~[classes!/:1.4.13]
        at jdk.internal.reflect.GeneratedMethodAccessor511.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[
spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.
3.8.jar!/:5.3.8]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5
.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.8
.jar!/:5.3.8]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop
-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5
.3.8.jar!/:5.3.8]
:
```

**Comment by JohnNiang** [comment]
这个错误是业务错误，不会阻碍程序启动。

**Comment by ruibaby** [comment]
请提供 halo.service 配置内容。

**Comment by StarSky1** [comment]
```
[Unit]
Description=Halo Service
Documentation=https://docs.halo.run
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/root/.sdkman/candidates/java/current/bin/java -server -Xms256m -Xmx256m -jar /home/halo/app/halo.jar
ExecStop=/bin/kill -s QUIT $MAINPID
Restart=always
StandOutput=syslog

StandError=inherit

[Install]
WantedBy=multi-user.target
```
已解决，是因为/usr/bin/java 的版本是jdk8，导致启动失败，当前java版本过低。换成jdk11可以正常运行了。
