### ISSUE TITLE
新版本本地运行报theme文件夹丢失问题

### ISSUE THREAD

**Issue by barry200890** [halo-dev/halo#1579]
### 是什么版本出现了此问题？

最新版本

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

localhost本地部署的

### 发生了什么？

直接使用idea运行报：java.io.FileNotFoundException: class path resource [templates/themes] cannot be resolved to URL because it does not exist

### 相关日志输出

```shell
2021-12-08 11:32:53.824 ERROR 13132 --- [  restartedMain] run.halo.app.listener.StartedListener    : Please check location: classpath:templates/themes
2021-12-08 11:32:53.830 ERROR 13132 --- [  restartedMain] run.halo.app.listener.StartedListener    : Initialize internal theme to user path error!

java.io.FileNotFoundException: class path resource [templates/themes] cannot be resolved to URL because it does not exist
	at org.springframework.util.ResourceUtils.getURL(ResourceUtils.java:137) ~[spring-core-5.3.8.jar:5.3.8]
	at run.halo.app.listener.StartedListener.initThemes(StartedListener.java:152) ~[classes/:na]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:81) ~[classes/:na]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:47) ~[classes/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.8.jar:5.3.8]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:105) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.1.jar:2.5.1]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:344) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.1.jar:2.5.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.1.jar:2.5.1]
	at run.halo.app.Application.main(Application.java:21) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.5.1.jar:2.5.1]
```

**Comment by ruibaby** [comment]
请按照文档 https://docs.halo.run/developer-guide/core/prepare#%E5%85%8B%E9%9A%86%E9%A1%B9%E7%9B%AEoptional 初始化 submodule。
