### ISSUE TITLE
在heroku平台的虚拟机中halo启动报错UnknownHostException

### ISSUE THREAD

**Issue by karma-sun** [halo-dev/halo#1663]
### 是什么版本出现了此问题？

1.4.17

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

在heroku平台的虚拟机中halo启动报错UnknownHostException

### 相关日志输出

```shell
2022-02-18T12:47:33.371392+00:00 app[web.1]: 12:47:33.368 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
2022-02-18T12:47:33.371444+00:00 app[web.1]: java.lang.IllegalStateException: java.net.UnknownHostException: .halo
2022-02-18T12:47:33.371452+00:00 app[web.1]: at org.springframework.beans.factory.config.YamlProcessor.handleProcessError(YamlProcessor.java:221)
2022-02-18T12:47:33.371452+00:00 app[web.1]: at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:213)
2022-02-18T12:47:33.371452+00:00 app[web.1]: at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166)
2022-02-18T12:47:33.371453+00:00 app[web.1]: at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84)
2022-02-18T12:47:33.371453+00:00 app[web.1]: at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
2022-02-18T12:47:33.371453+00:00 app[web.1]: at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:54)
2022-02-18T12:47:33.371453+00:00 app[web.1]: at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:36)
2022-02-18T12:47:33.371454+00:00 app[web.1]: at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:105)
2022-02-18T12:47:33.371454+00:00 app[web.1]: at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:130)
2022-02-18T12:47:33.371454+00:00 app[web.1]: at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:88)
2022-02-18T12:47:33.371458+00:00 app[web.1]: at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:122)
2022-02-18T12:47:33.371461+00:00 app[web.1]: at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:240)
2022-02-18T12:47:33.371462+00:00 app[web.1]: at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:227)
2022-02-18T12:47:33.371465+00:00 app[web.1]: at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
2022-02-18T12:47:33.371466+00:00 app[web.1]: at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
2022-02-18T12:47:33.371473+00:00 app[web.1]: at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
2022-02-18T12:47:33.371474+00:00 app[web.1]: at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
2022-02-18T12:47:33.371474+00:00 app[web.1]: at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
2022-02-18T12:47:33.371474+00:00 app[web.1]: at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
2022-02-18T12:47:33.371474+00:00 app[web.1]: at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
2022-02-18T12:47:33.371475+00:00 app[web.1]: at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
2022-02-18T12:47:33.371475+00:00 app[web.1]: at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
2022-02-18T12:47:33.371475+00:00 app[web.1]: at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
2022-02-18T12:47:33.371479+00:00 app[web.1]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2022-02-18T12:47:33.371479+00:00 app[web.1]: at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
2022-02-18T12:47:33.371479+00:00 app[web.1]: at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
2022-02-18T12:47:33.371479+00:00 app[web.1]: at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
2022-02-18T12:47:33.371480+00:00 app[web.1]: at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374)
2022-02-18T12:47:33.371480+00:00 app[web.1]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
2022-02-18T12:47:33.371480+00:00 app[web.1]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
2022-02-18T12:47:33.371480+00:00 app[web.1]: at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
2022-02-18T12:47:33.371481+00:00 app[web.1]: at run.halo.app.Application.main(Application.java:21)
2022-02-18T12:47:33.371481+00:00 app[web.1]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-02-18T12:47:33.371481+00:00 app[web.1]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-02-18T12:47:33.371482+00:00 app[web.1]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-02-18T12:47:33.371482+00:00 app[web.1]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-02-18T12:47:33.371487+00:00 app[web.1]: at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2022-02-18T12:47:33.371488+00:00 app[web.1]: at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
2022-02-18T12:47:33.371488+00:00 app[web.1]: at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2022-02-18T12:47:33.371488+00:00 app[web.1]: at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
2022-02-18T12:47:33.371492+00:00 app[web.1]: Caused by: java.net.UnknownHostException: .halo
2022-02-18T12:47:33.371492+00:00 app[web.1]: at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
2022-02-18T12:47:33.371493+00:00 app[web.1]: at java.base/java.net.Socket.connect(Socket.java:609)
2022-02-18T12:47:33.371493+00:00 app[web.1]: at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:1062)
2022-02-18T12:47:33.371493+00:00 app[web.1]: at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:1024)
2022-02-18T12:47:33.371493+00:00 app[web.1]: at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1119)
2022-02-18T12:47:33.371494+00:00 app[web.1]: at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1105)
2022-02-18T12:47:33.371494+00:00 app[web.1]: at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:312)
2022-02-18T12:47:33.371494+00:00 app[web.1]: at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:418)
2022-02-18T12:47:33.371494+00:00 app[web.1]: at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:186)
2022-02-18T12:47:33.371495+00:00 app[web.1]: at org.springframework.boot.origin.OriginTrackedResource.getInputStream(OriginTrackedResource.java:61)
2022-02-18T12:47:33.371495+00:00 app[web.1]: at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:197)
2022-02-18T12:47:33.371498+00:00 app[web.1]: ... 38 common frames omitted
```

### 附加信息

启动命令 java -Xms256m -Xmx256m -jar halo.jar
工作目录/.halo

cat /.halo/application.yaml 
server:
  port: 46753

  compression:
    enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx/halo?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: xx
    password: xx

halo:
  admin-path: admin
  cache: memory
  work-dir: /.halo/

**Comment by ruibaby** [comment]
抱歉，目前我们没有针对 heroku 平台进行测试。建议查阅 heroku 官方文档或联系相关客服。

**Comment by JohnNiang** [comment]
如果执行命令 `java -Xms256m -Xmx256m -jar halo.jar` 会从 `~/.halo` 目录下获取 application.yaml 配置文件，如果你的配置文件存放在其他地方，需要手动指定配置文件的地址，

```bash 
java -Xms256m -Xmx256m -jar halo.jar -Dspring.config.location="optional:file:/.halo/
```

请参考：
- https://docs.halo.run/getting-started/config
- https://docs.spring.io/spring-boot/docs/2.5.9/reference/html/features.html#features.external-config.files

**Comment by JohnNiang** [comment]
@karma-sun 请问这个问题是已经解决了么？可以提供一下解决方案么。

**Comment by karma-sun** [comment]
改动配置文件位置就可以了
