### ISSUE TITLE
初始化博客安装时报错

### ISSUE THREAD

**Issue by AlexMahao** [halo-dev/halo#176]
```
2019-06-03 11:52:43.835  WARN 9323 --- [ XNIO-1 task-21] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1366, SQLState: HY000
2019-06-03 11:52:43.835 ERROR 9323 --- [ XNIO-1 task-21] o.h.engine.jdbc.spi.SqlExceptionHelper   : Incorrect string value: '\xE5\xAE\x89\xE5\xBE\x97...' for column 'option_value' at row 1
2019-06-03 11:52:43.842 ERROR 9323 --- [ XNIO-1 task-21] r.h.a.c.base.ControllerExceptionHandler  : Captured an exception

org.springframework.orm.jpa.JpaSystemException: could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:351) ~[spring-orm-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:253) ~[spring-orm-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:527) ~[spring-orm-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153) ~[spring-tx-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135) ~[spring-data-jpa-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) ~[spring-data-commons-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]

```

**Comment by ruibaby** [comment]
应该是你 MySQL 不支持中文的原因。

**Comment by JohnNiang** [comment]
请问，您输入的内容包括表情么？

**Comment by AlexMahao** [comment]
我把数据库重新创建了一下。然后就更加恐怖了...
```
2019-06-03 12:09:53.141  WARN 9323 --- [  XNIO-1 task-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1146, SQLState: 42S02
2019-06-03 12:09:53.141 ERROR 9323 --- [  XNIO-1 task-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table 'halodb.posts' doesn't exist
2019-06-03 12:09:53.144 ERROR 9323 --- [  XNIO-1 task-4] r.h.a.c.base.ControllerExceptionHandler  : Captured an exception
```

**Comment by AlexMahao** [comment]
我能清缓存之类的吗，重新走一下初始化流程

**Comment by JohnNiang** [comment]
你需要把 `halodb` 这个数据库删除掉。

**Comment by AlexMahao** [comment]
我已经删除了，然后报表找不到.

**Comment by AlexMahao** [comment]
```
mysql> show tables;
Empty set (0.00 sec)

```

```
[developer@dingdang .halo]$ cd ~/.halo/
[developer@dingdang .halo]$ ls -l
总用量 4
-rw-rw-r-- 1 developer developer 871 6月   3 12:01 application.yaml
```

**Comment by JohnNiang** [comment]
重启一下 halo 试试

**Comment by AlexMahao** [comment]
已经解决了，感谢。但是我貌似进入到后台管理了。展示页面应该怎么进入呀？

**Comment by JohnNiang** [comment]
管理端右上角有一个链接图标，点击即可。

**Comment by AlexMahao** [comment]
找到了，谢谢啦。我体验体验。

**Comment by JohnNiang** [comment]
> 应该是你 MySQL 不支持中文的原因。

确实是因为创建数据库的时候没有指定编码。

如果仅仅想要支持中文和表情，请使用以下 `SQL` 创建 `halodb`：

```sql
create database halodb character set utf8mb4 collate utf8mb4_bin;
```
