### ISSUE TITLE
更新后无法启动 Halo

### ISSUE THREAD

**Issue by AnotiaWang** [halo-dev/halo#1762]
### 是什么版本出现了此问题？

1.5.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://blog.anotia.top

### 发生了什么？

原先的版本为 1.4.17 ，按照文档的升级指南升级到 1.5.0 正式版后，无法启动 Halo。还请看看是什么原因，谢谢！

### 相关日志输出

```shell
2022-03-23 14:08:30.084 ERROR 531643 --- [           main] o.f.core.internal.command.DbMigrate      : Migration of schema "PUBLIC" to version "6 - migrate create contents table" failed! Please restore backups and roll back database and code!
2022-03-23 14:08:30.140  INFO 531643 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-23 14:08:30.202 ERROR 531643 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V6__migrate_create_contents_table.sql failed
------------------------------------------------------
SQL State  : 23505
Error Code : 23505
Message    : Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [2, TIMESTAMP '2022-03-09 17:24:42.808', TIMESTAMP '2022-03-15 12:09:25.796', SPACE(632 /* table: 74 id: 21552 */), 36, SPACE(344 /* table: 74 id: 21553 */), 36, 0]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
Location   : migration/V6__migrate_create_contents_table.sql (/home/halo/app/file:/home/halo/app/halo.jar!/BOOT-INF/classes!/migration/V6__migrate_create_contents_table.sql)
Line       : 2
Statement  : -- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:103) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:219) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:170) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.Flyway.execute(Flyway.java:586) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:170) ~[flyway-core-7.15.0.jar!/:na]
        at run.halo.app.listener.StartedListener.migrate(StartedListener.java:123) ~[classes!/:1.5.0]
        at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:76) ~[classes!/:1.5.0]
        at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:47) ~[classes!/:1.5.0]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.16.jar!/:5.3.16]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.16.jar!/:5.3.16]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.16.jar!/:5.3.16]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.16.jar!/:5.3.16]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.16.jar!/:5.3.16]
        at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:105) ~[spring-boot-2.5.10.jar!/:2.5.10]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.10.jar!/:2.5.10]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.10.jar!/:2.5.10]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.10.jar!/:2.5.10]
        at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.10.jar!/:2.5.10]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.10.jar!/:2.5.10]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) ~[spring-boot-2.5.10.jar!/:2.5.10]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.10.jar!/:2.5.10]
        at run.halo.app.Application.main(Application.java:21) ~[classes!/:1.5.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[halo.jar:1.5.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[halo.jar:1.5.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[halo.jar:1.5.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[halo.jar:1.5.0]
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V6__migrate_create_contents_table.sql failed
------------------------------------------------------
SQL State  : 23505
Error Code : 23505
Message    : Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [2, TIMESTAMP '2022-03-09 17:24:42.808', TIMESTAMP '2022-03-15 12:09:25.796', SPACE(632 /* table: 74 id: 21552 */), 36, SPACE(344 /* table: 74 id: 21553 */), 36, 0]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
Location   : migration/V6__migrate_create_contents_table.sql (/home/halo/app/file:/home/halo/app/halo.jar!/BOOT-INF/classes!/migration/V6__migrate_create_contents_table.sql)
Line       : 2
Statement  : -- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:277) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:224) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:128) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:78) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:67) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:66) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370) ~[flyway-core-7.15.0.jar!/:na]
        ... 42 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [2, TIMESTAMP '2022-03-09 17:24:42.808', TIMESTAMP '2022-03-15 12:09:25.796', SPACE(632 /* table: 74 id: 21552 */), 36, SPACE(344 /* table: 74 id: 21553 */), 36, 0]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:457) ~[h2-1.4.199.jar!/:na]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2-1.4.199.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.199.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.199.jar!/:na]
        at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:131) ~[h2-1.4.199.jar!/:na]
        at org.h2.mvstore.db.MVTable.addRow(MVTable.java:546) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.dml.Insert.addRowImpl(Insert.java:251) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.dml.Insert.insertRows(Insert.java:207) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.dml.Insert.update(Insert.java:132) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.CommandContainer.update(CommandContainer.java:133) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.Command.executeUpdate(Command.java:267) ~[h2-1.4.199.jar!/:na]
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233) ~[h2-1.4.199.jar!/:na]
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205) ~[h2-1.4.199.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:212) ~[flyway-core-7.15.0.jar!/:na]
        ... 48 common frames omitted

2022-03-23 14:08:30.258  INFO 531643 --- [           main] o.e.jetty.server.AbstractConnector       : Stopped ServerConnector@16423501{HTTP/1.1, (http/1.1)}{0.0.0.0:8090}
2022-03-23 14:08:30.258  INFO 531643 --- [           main] org.eclipse.jetty.server.session         : node0 Stopped scavenging
2022-03-23 14:08:30.260  INFO 531643 --- [           main] o.e.j.s.h.ContextHandler.application     : Destroying Spring FrameworkServlet 'dispatcherServlet'
2022-03-23 14:08:30.261  INFO 531643 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@25470477{application,/,[file:///tmp/jetty-docbase.8090.16570390090191347797/, jar:file:/home/halo/app/halo.jar!/BOOT-INF/lib/springfox-swagger-ui-3.0.0.jar!/META-INF/resources],STOPPED}
2022-03-23 14:08:30.318  INFO 531643 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-03-23 14:08:30.320  INFO 531643 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-03-23 14:08:30.517  INFO 531643 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

### 附加信息

系统：CentOS 8 Stream
Java 版本：openjdk 11.0.14.1 2022-02-08 LTS

**Comment by ruibaby** [comment]
你好 @AnotiaWang ，之前有升级过 1.5.0 测试版吗？

**Comment by AnotiaWang** [comment]
@ruibaby 有的， 使用过 1.5.0-alpha3

**Comment by ruibaby** [comment]
> @ruibaby 有的， 使用过 1.5.0-alpha3

那大概是因为又去执行升级脚本了，因为 contents 表已经有了数据。建议使用 1.4.17 的备份重新升级。

**Comment by AnotiaWang** [comment]
> 那大概是因为又去执行升级脚本了，因为 contents 表已经有了数据。建议使用 1.4.17 的备份重新升级。

好的，我试试

**Comment by AnotiaWang** [comment]
> 那大概是因为又去执行升级脚本了，因为 contents 表已经有了数据。建议使用 1.4.17 的备份重新升级。

这回升级成功了，谢谢
