### ISSUE TITLE
下载最新 jar 后启动数据库报错

### ISSUE THREAD

**Issue by Qxin-X** [halo-dev/halo#1765]
### What is version of Halo has the issue?

1.5

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### What happened?

出现了这个错误 ： Migration V6__migrate_create_contents_table.sql failed

### Relevant log output

```shell
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2m2022-03-23 18:17:58.804[0;39m [31mERROR[0;39m [35m25087[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application run failed

org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V6__migrate_create_contents_table.sql failed
------------------------------------------------------
SQL State  : 23505
Error Code : 23505
Message    : Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [2, TIMESTAMP '2022-01-19 19:42:27.438', TIMESTAMP '2022-03-16 14:04:43.539', SPACE(7537 /* table: 74 id: 17195878 */), 161, SPACE(7493 /* table: 74 id: 17195879 */), 161, 0]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
Location   : migration/V6__migrate_create_contents_table.sql (/www/wwwroot/blog.xieqingxin.com/app/file:/www/wwwroot/blog.xieqingxin.com/app/halo.jar!/BOOT-INF/classes!/migration/V6__migrate_create_contents_table.sql)
Line       : 2
Statement  : -- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:103) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:219) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:170) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:586) ~[flyway-core-7.15.0.jar!/:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:170) ~[flyway-core-7.15.0.jar!/:na]
	at run.halo.app.listener.StartedListener.migrate(StartedListener.java:123) ~[classes!/:1.5.0]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:76) ~[classes!/:1.5.0]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:47) ~[classes!/:1.5.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.16.jar!/:5.3.16]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.16.jar!/:5.3.16]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.16.jar!/:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.16.jar!/:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.16.jar!/:5.3.16]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:105) ~[spring-boot-2.5.10.jar!/:2.5.10]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.10.jar!/:2.5.10]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.10.jar!/:2.5.10]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.10.jar!/:2.5.10]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.10.jar!/:2.5.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.10.jar!/:2.5.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) ~[spring-boot-2.5.10.jar!/:2.5.10]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.10.jar!/:2.5.10]
	at run.halo.app.Application.main(Application.java:21) ~[classes!/:1.5.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[halo.jar:1.5.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[halo.jar:1.5.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[halo.jar:1.5.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[halo.jar:1.5.0]
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V6__migrate_create_contents_table.sql failed
```

**Comment by ruibaby** [comment]
看看和这个是一样的问题吗？

**Comment by Qxin-X** [comment]
> 看看和这个是一样的问题吗？
> 
> #1762

一样的问题，解决了，谢谢

**Comment by Qxin-X** [comment]
> 看看和这个是一样的问题吗？
> 
> #1762

你好这样的话有一部分内容得修改，还有得重新导入，有没有其他可以用最新的数据库的方案，我是之前有用过测试版的

**Comment by ruibaby** [comment]
> 你好这样的话有一部分内容得修改，还有得重新导入，有没有其他可以用最新的数据库的方案，我是之前有用过测试版的

什么内容需要修改呢

**Comment by Qxin-X** [comment]
> > 你好这样的话有一部分内容得修改，还有得重新导入，有没有其他可以用最新的数据库的方案，我是之前有用过测试版的
> 
> 什么内容需要修改呢

由于改动比较大，一些分类调整，还有多篇文章要重新发表，自定义页面也要重新调整，因为我是使用测试版本后就一直使用测试版本，没想到测试版跟正式版不兼容，多数改动都是在测试版本期间的改动，有什么方法能使用现在这个数据库，如果下个版本可以也行，我就先不升级。

建议：在对表的迁移或者新增表的时候添加个判断，如果已近有该表存在就不用新建之类的操作，这样可以避免执行不了抛异常。

**Comment by ruibaby** [comment]
> > > 你好这样的话有一部分内容得修改，还有得重新导入，有没有其他可以用最新的数据库的方案，我是之前有用过测试版的
> > 
> > 
> > 什么内容需要修改呢
> 
> 由于改动比较大，一些分类调整，还有多篇文章要重新发表，自定义页面也要重新调整，因为我是使用测试版本后就一直使用测试版本，没想到测试版跟正式版不兼容，多数改动都是在测试版本期间的改动，有什么方法能使用现在这个数据库，如果下个版本可以也行，我就先不升级。
> 
> 建议：在对表的迁移或者新增表的时候添加个判断，如果已近有该表存在就不用新建之类的操作，这样可以避免执行不了抛异常。

测试版肯定是和正式版兼容的，你的问题是你用 1.4 升级到了 1.5 测试版之后又回到了 1.4 版本，然后再升级 1.5 正式版可能又去执行了迁移脚本，才会导致这样的问题。

你可以提供一下数据库 `flyway_schema_history` 表的信息，我们看看如何解决。

**Comment by Qxin-X** [comment]
> /cc @halo-dev/sig-halo 我们需要测试一下使用 flyway 降级之后是否会导致 `flyway_schema_history` 表的记录恢复到上个版本。



> > > > 你好这样的话有一部分内容得修改，还有得重新导入，有没有其他可以用最新的数据库的方案，我是之前有用过测试版的
> > > 
> > > 
> > > 什么内容需要修改呢
> > 
> > 
> > 由于改动比较大，一些分类调整，还有多篇文章要重新发表，自定义页面也要重新调整，因为我是使用测试版本后就一直使用测试版本，没想到测试版跟正式版不兼容，多数改动都是在测试版本期间的改动，有什么方法能使用现在这个数据库，如果下个版本可以也行，我就先不升级。
> > 建议：在对表的迁移或者新增表的时候添加个判断，如果已近有该表存在就不用新建之类的操作，这样可以避免执行不了抛异常。
> 
> 测试版肯定是和正式版兼容的，你的问题是你用 1.4 升级到了 1.5 测试版之后又回到了 1.4 版本，然后再升级 1.5 正式版可能又去执行了迁移脚本，才会导致这样的问题。
> 
> 你可以提供一下数据库 `flyway_schema_history` 表的信息，我们看看如何解决。

好的，感谢，麻烦了

**Comment by Qxin-X** [comment]
> /cc @halo-dev/sig-halo 我们需要测试一下使用 flyway 降级之后是否会导致 `flyway_schema_history` 表的记录恢复到上个版本。

你好，我登入 h2-console 没有发现有 `flyway_schema_history` 这个表。

![屏幕截图 2022-03-24 153835](https://user-images.githubusercontent.com/66522154/159867757-0eb87e65-a90d-4a07-9f1d-9bba49a17816.png)

**Comment by ruibaby** [comment]
> 你好，我登入 h2-console 没有发现有 flyway_schema_history 这个表。

登录的时候 JDBC URL 是配置文件里面的吗？

**Comment by Qxin-X** [comment]
> > 你好，我登入 h2-console 没有发现有 flyway_schema_history 这个表。
> 
> 登录的时候 JDBC URL 是配置文件里面的吗？

你好，对的  ip:端口/h2-console

**Comment by ruibaby** [comment]
https://docs.halo.run/getting-started/config#h2

**Comment by Qxin-X** [comment]
> https://docs.halo.run/getting-started/config#h2

你好信息如下：

<html>
<body>
<span style="color: rgb(0, 0, 0); font-family: Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 240, 224); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">SELECT * FROM "flyway_schema_history";</span><br style="color: rgb(0, 0, 0); font-family: Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 240, 224); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

installed_rank | version | description | type | script | checksum | installed_by | installed_on | execution_time | success
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
-1 | null | << Flyway Schema History table created >> | TABLE |   | null | ADMIN | 2021-10-09 08:43:40.416 | 0 | TRUE
1 | 1 | << Flyway Baseline >> | BASELINE | << Flyway Baseline >> | null | ADMIN | 2021-10-09 08:43:40.42 | 0 | TRUE
2 | 2 | migrate 1.2.0-beta.1 to 1.2.0-beta.2 | SQL | V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql | 623818472 | ADMIN | 2021-10-09 08:43:40.506 | 9 | TRUE
3 | 3 | migrate 1.3.0-beta.1 to 1.3.0-beta.2 | SQL | V3__migrate_1.3.0-beta.1_to_1.3.0-beta.2.sql | -417975340 | ADMIN | 2021-10-09 08:43:40.604 | 60 | TRUE
4 | 4 | migrate 1.3.0-beta.2 to 1.3.0-beta.3 | SQL | V4__migrate_1.3.0-beta.2_to_1.3.0-beta.3.sql | 589261839 | ADMIN | 2021-10-09 08:43:40.667 | 1 | TRUE
5 | 5 | migrate remove notnull for email in comments table | SQL | V5__migrate_remove_notnull_for_email_in_comments_table.sql | 1816761952 | ADMIN | 2022-02-25 12:47:31.564864 | 33 | TRUE
6 | 6 | migrate create contents table | SQL | V6__migrate_create_contents_table.sql | -1909763072 | ADMIN | 2022-02-25 12:47:31.729424 | 115 | TRUE
7 | 5 | migrate remove notnull for email in comments table | DELETE | V5__migrate_remove_notnull_for_email_in_comments_table.sql | 1816761952 | ADMIN | 2022-03-17 14:48:41.78 | 0 | TRUE
8 | 6 | migrate create contents table | DELETE | V6__migrate_create_contents_table.sql | -1909763072 | ADMIN | 2022-03-17 14:48:41.78 | 0 | TRUE

**Comment by ruibaby** [comment]
将 `installed_rank` 字段的 7 8 条删除再重新运行即可。

**Comment by Qxin-X** [comment]
> 将 `installed_rank` 字段的 7 8 条删除再重新运行即可。

你好，非常感谢，已经顺利升级成功，一如既往支持 halo。
