### ISSUE TITLE
评论在通过和回复时没有邮件通知

### ISSUE THREAD

**Issue by hapke24** [halo-dev/halo#1789]
### 是什么版本出现了此问题？

1.5.0

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 现象
- 访客评论后能够收到博主能够收到待通过的邮件提醒
- 博主通过后访客无法收到通过的邮件提醒
- 博主回复后访客也不能收到邮件体现

### 测试
- 使用H2数据库的1.4.17版本没有问题
- 使用H2数据库全新安装的1.5.0版本没有问题

### 相关日志输出

```shell
2022-03-29 19:16:49.220 ERROR 2154 --- [         task-6] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void run.halo.app.listener.comment.CommentEventListener.handleCommentReplyEvent(run.halo.app.event.comment.CommentReplyEvent)

run.halo.app.exception.NotFoundException: SheetComment was not found or has been deleted
        at run.halo.app.service.base.AbstractCrudService.lambda$getById$0(AbstractCrudService.java:139) ~[classes!/:1.5.0]
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at run.halo.app.service.base.AbstractCrudService.getById(AbstractCrudService.java:138) ~[classes!/:1.5.0]
        at run.halo.app.service.base.AbstractCrudService$$FastClassBySpringCGLIB$$d181db6d.invoke(<generated>) ~[classes!/:1.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at run.halo.app.service.impl.SheetCommentServiceImpl$$EnhancerBySpringCGLIB$$7a05bca5.getById(<generated>) ~[classes!/:1.5.0]
        at run.halo.app.listener.comment.CommentEventListener.handleCommentReplyEvent(CommentEventListener.java:241) ~[classes!/:1.5.0]
        at run.halo.app.listener.comment.CommentEventListener$$FastClassBySpringCGLIB$$7fe2191c.invoke(<generated>) ~[classes!/:1.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2022-03-29 19:25:52.984 ERROR 2154 --- [         task-8] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void run.halo.app.listener.comment.CommentEventListener.handleCommentNewEvent(run.halo.app.event.comment.CommentNewEvent)

run.halo.app.exception.NotFoundException: SheetComment was not found or has been deleted
        at run.halo.app.service.base.AbstractCrudService.lambda$getById$0(AbstractCrudService.java:139) ~[classes!/:1.5.0]
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at run.halo.app.service.base.AbstractCrudService.getById(AbstractCrudService.java:138) ~[classes!/:1.5.0]
        at run.halo.app.service.base.AbstractCrudService$$FastClassBySpringCGLIB$$d181db6d.invoke(<generated>) ~[classes!/:1.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at run.halo.app.service.impl.SheetCommentServiceImpl$$EnhancerBySpringCGLIB$$7a05bca5.getById(<generated>) ~[classes!/:1.5.0]
        at run.halo.app.listener.comment.CommentEventListener.handleCommentNewEvent(CommentEventListener.java:135) ~[classes!/:1.5.0]
        at run.halo.app.listener.comment.CommentEventListener$$FastClassBySpringCGLIB$$7fe2191c.invoke(<generated>) ~[classes!/:1.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

### 附加信息

不成功的博客是从1.4.17升的1.5.0，使用mysql数据库，缓存方式为内存
主题使用的是[https://github.com/qinhua/halo-theme-joe2.0](https://github.com/qinhua/halo-theme-joe2.0)

**Comment by hapke24** [comment]
已解决，是多域名访问和缓存共同导致的。
A.com、B.com两个域名绑定了同一台服务器
博客后台原来设置为A.com，后因域名即将到期更换域名改为B.com
在通过B.com/admin打开博客后台时因为缓存问题，会自动转跳到A.com/admin
通过A.com/admin也能正常访问，但是可能和后台设置大域名有冲突导致发件失败。
通过清空浏览器缓存+cloudflare缓存后用B.com/admin重试，或者将后台域名改回A.com，问题消失。

**Comment by JohnNiang** [comment]
请参考：
- https://github.com/halo-dev/halo/issues/1798#issuecomment-1119313057
