### ISSUE TITLE
评论后发送邮件报错

### ISSUE THREAD

**Issue by hapke24** [halo-dev/halo#1798]
### 是什么版本出现了此问题？

1.5.1

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

多次留言发送邮件会报错
现象：
设置好邮件接收
增加1条评论 ---> 收到邮件提醒
再增加1条评论 ---> 无邮件提醒
再增加1条评论 ---> 无邮件提醒
**前往宝塔后台将反代缓存打开后再关闭**
再增加1条评论 ---> 收到邮件提醒
再增加1条评论 ---> 无邮件提醒
再增加1条评论 ---> 无邮件提醒
**前往宝塔后台将反代缓存打开**
再增加1条评论 ---> 无邮件提醒
再增加1条评论 ---> 无邮件提醒
**前往宝塔后台将反代缓存关闭**
再增加1条评论 ---> 无邮件提醒
再增加1条评论 ---> 无邮件提醒

测试环境：
Windows Server 2019，Nginx 1.12.1，Halo 1.5.0 - 出现
CentOS，Nginx 1.12.1，Halo 1.5.0 - 出现
CentOS，Nginx 1.12.1，Halo 1.5.1 - 出现

一般将反代缓存打开后再关闭就能收一次邮件，Windows每次都可以，但是CentOS的偶尔会失效

### 相关日志输出

```shell
[2m2022-03-31 15:13:09.524[0;39m [33m WARN[0;39m [35m3108[0;39m [2m---[0;39m [2m[        Timer-0][0;39m [36mrun.halo.app.cache.AbstractCacheStore   [0;39m [2m:[0;39m Cache key: [cache_lock_public run.halo.app.model.dto.BaseCommentDTO run.halo.app.controller.content.api.SheetController.comment(run.halo.app.model.params.SheetCommentParam):223.74.22.15] has been expired
[2m2022-03-31 15:24:55.683[0;39m [31mERROR[0;39m [35m3108[0;39m [2m---[0;39m [2m[        task-67][0;39m [36m.a.i.SimpleAsyncUncaughtExceptionHandler[0;39m [2m:[0;39m Unexpected exception occurred invoking async method: public void run.halo.app.listener.comment.CommentEventListener.handleCommentNewEvent(run.halo.app.event.comment.CommentNewEvent)

run.halo.app.exception.NotFoundException: SheetComment was not found or has been deleted
        at run.halo.app.service.base.AbstractCrudService.lambda$getById$0(AbstractCrudService.java:139) ~[classes!/:1.5.0]
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at run.halo.app.service.base.AbstractCrudService.getById(AbstractCrudService.java:138) ~[classes!/:1.5.0]
        at run.halo.app.service.base.AbstractCrudService$$FastClassBySpringCGLIB$$d181db6d.invoke(<generated>) ~[classes!/:1.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at run.halo.app.service.impl.SheetCommentServiceImpl$$EnhancerBySpringCGLIB$$4a383dee.getById(<generated>) ~[classes!/:1.5.0]
        at run.halo.app.listener.comment.CommentEventListener.handleCommentNewEvent(CommentEventListener.java:135) ~[classes!/:1.5.0]
        at run.halo.app.listener.comment.CommentEventListener$$FastClassBySpringCGLIB$$7fe2191c.invoke(<generated>) ~[classes!/:1.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

[2m2022-03-31 15:25:09.520[0;39m [33m WARN[0;39m [35m3108[0;39m [2m---[0;39m [2m[        Timer-0][0;39m [36mrun.halo.app.cache.AbstractCacheStore   [0;39m [2m:[0;39m Cache key: [cache_lock_public run.halo.app.model.dto.BaseCommentDTO run.halo.app.controller.content.api.SheetController.comment(run.halo.app.model.params.SheetCommentParam):223.74.22.15] has been expired
[2m2022-03-31 15:25:17.537[0;39m [32m INFO[0;39m [35m3108[0;39m [2m---[0;39m [2m[pool-4-thread-5][0;39m [36mrun.halo.app.mail.AbstractMailService   [0;39m [2m:[0;39m Sent an email to [[接收邮箱]] successfully, subject: [您的博客页面《关于页面》有了 新的评论。], sent date: [Thu Mar 31 15:25:17 CST 2022]
[2m2022-03-31 15:25:28.996[0;39m [33m WARN[0;39m [35m3108[0;39m [2m---[0;39m [2m[p1296928719-267][0;39m [36mrun.halo.app.cache.AbstractCacheStore   [0;39m [2m:[0;39m Cache key: [cache_lock_public run.halo.app.model.dto.BaseCommentDTO run.halo.app.controller.content.api.SheetController.comment(run.halo.app.model.params.SheetCommentParam):223.74.22.15] has been expired
[2m2022-03-31 15:25:28.996[0;39m [31mERROR[0;39m [35m3108[0;39m [2m---[0;39m [2m[        task-69][0;39m [36m.a.i.SimpleAsyncUncaughtExceptionHandler[0;39m [2m:[0;39m Unexpected exception occurred invoking async method: public void run.halo.app.listener.comment.CommentEventListener.handleCommentNewEvent(run.halo.app.event.comment.CommentNewEvent)

run.halo.app.exception.NotFoundException: SheetComment was not found or has been deleted
        at run.halo.app.service.base.AbstractCrudService.lambda$getById$0(AbstractCrudService.java:139) ~[classes!/:1.5.0]
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at run.halo.app.service.base.AbstractCrudService.getById(AbstractCrudService.java:138) ~[classes!/:1.5.0]
        at run.halo.app.service.base.AbstractCrudService$$FastClassBySpringCGLIB$$d181db6d.invoke(<generated>) ~[classes!/:1.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at run.halo.app.service.impl.SheetCommentServiceImpl$$EnhancerBySpringCGLIB$$4a383dee.getById(<generated>) ~[classes!/:1.5.0]
        at run.halo.app.listener.comment.CommentEventListener.handleCommentNewEvent(CommentEventListener.java:135) ~[classes!/:1.5.0]
        at run.halo.app.listener.comment.CommentEventListener$$FastClassBySpringCGLIB$$7fe2191c.invoke(<generated>) ~[classes!/:1.5.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.16.jar!/:5.3.16]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by hapke24** [comment]
Windows网站：https://txs.9kr.cc/
CentOS网站：https://h.9kr.cc/

**Comment by ruibaby** [comment]
没有明白这和 Nginx 缓存的关系。我们没有能成功复现这个问题。

**Comment by hapke24** [comment]
> 没有明白这和 Nginx 缓存的关系。我们没有能成功复现这个问题。

方便提供一个邮箱吗？我发一个远程桌面账号给你

**Comment by ruibaby** [comment]
> 方便提供一个邮箱吗？我发一个远程桌面账号给你

抱歉，我们不能提供一对一单独支持。

**Comment by jeremy526** [comment]
我也出现了同样的问题，本想本地部署调试复现，但却一切正常，异常信息如下
![image](https://user-images.githubusercontent.com/59838072/163822268-e49b5ad8-3dfd-4255-a1de-255026c0eaf0.png)

**Comment by jeremy526** [comment]
> 我也出现了同样的问题，本想本地部署调试复现，但却一切正常，异常信息如下 ![image](https://user-images.githubusercontent.com/59838072/163822268-e49b5ad8-3dfd-4255-a1de-255026c0eaf0.png)

评论未成功发送过邮件

**Comment by JohnNiang** [comment]
@jeremy526 是的，我在我的博客内评论，未曾出现这个错误。期待进一步反馈。

**Comment by jeremy526** [comment]
@JohnNiang 刚刚尝试重启docker容器 邮件发送成功一次 后面又出现此异常

**Comment by libo-sober** [comment]
我也遇到了，用docker搭建成功后只能发送一次邮件，之后就不再发送了，报错是postcomment方法丢失。

**Comment by cetr** [comment]
遇到了同样的问题，日志上的错误也一样

**Comment by bxbdba** [comment]
使用1.5.2版本中同意遇到了此问题，新评论不会再发送邮件，但在【博客设置】的界面进行测试，发现是能够正常接收邮件的。

**Comment by libo-sober** [comment]
> 环境介绍： MySQL数据库 Nginx代理
> 
> 使用Halo 1.5.2版本中同样遇到了此问题。
> 
> 新评论不会再发送邮件，但在【博客设置】的界面进行测试，发现是能够正常接收邮件的。

把数据库换回使用H2就不会出现这个问题，使用NySql就有这个问题。我已经测试过了，不知道为什么也？表示很无奈，MySql与发邮件不可兼得。。。。

**Comment by JohnNiang** [comment]
Hi @bxbdba @cetr @libo-sober @jeremy526 @hapke24 ，这个问题主要是因为数据库事务和异步发送邮件提醒造成的。

当 Halo 创建了评论后，就发送了新评论或评论回复通知，但此时事务并未提交且评论通知的逻辑是异步执行的，也就导致了评论通知逻辑中查询不到刚刚创建的评论，出现了以上错误。

想要查看如何修复此问题，请参考：
- https://github.com/halo-dev/halo/pull/1916

**Comment by ruibaby** [comment]
已经在 1.5.3 修复，可以升级尝试一下。https://github.com/halo-dev/halo/releases/tag/v1.5.3
