### ISSUE TITLE
H2异常无法启动

### ISSUE THREAD

**Issue by Shaw-cc** [halo-dev/halo#1816]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

Version: 1.4.17

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

更新到halo-1.5.1，[无法启动](https://github.com/halo-dev/halo/issues/1765)
重新下载1.4.17，可以启动
修改H2控制台属性后，无法启动

### 相关日志输出

```shell
java -jar halo-1.4.17.jar 

    __  __      __
   / / / /___ _/ /___
  / /_/ / __ `/ / __ \
 / __  / /_/ / / /_/ /
/_/ /_/\__,_/_/\____/

Version: 1.4.17
2022-04-04 01:21:05.452  INFO 16567 --- [           main] run.halo.app.Application                 : Starting Application v1.4.17 using Java 11.0.14.1 with PID 16567 (/root/halo-1.4.17.jar started by root in /root)
2022-04-04 01:21:05.455  INFO 16567 --- [           main] run.halo.app.Application                 : No active profile set, falling back to default profiles: default
2022-04-04 01:21:07.161  INFO 16567 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-04-04 01:21:07.386  INFO 16567 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 205 ms. Found 22 JPA repository interfaces.
2022-04-04 01:21:08.518  INFO 16567 --- [           main] org.eclipse.jetty.util.log               : Logging initialized @5019ms to org.eclipse.jetty.util.log.Slf4jLog
2022-04-04 01:21:08.776  INFO 16567 --- [           main] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 8081
2022-04-04 01:21:08.785  INFO 16567 --- [           main] org.eclipse.jetty.server.Server          : jetty-9.4.42.v20210604; built: 2021-06-04T17:33:38.939Z; git: 5cd5e6d2375eeab146813b0de9f19eda6ab6e6cb; jvm 11.0.14.1+1-LTS
2022-04-04 01:21:08.824  INFO 16567 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2022-04-04 01:21:08.824  INFO 16567 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3253 ms
2022-04-04 01:21:09.098  INFO 16567 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-04-04 01:21:09.393  INFO 16567 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-04-04 01:21:09.401  INFO 16567 --- [           main] o.s.b.a.h2.H2ConsoleAutoConfiguration    : H2 console available at '/h2-console'. Database available at 'jdbc:h2:file:~/.halo/db/halo'
2022-04-04 01:21:10.506  INFO 16567 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-04-04 01:21:10.585  INFO 16567 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.32.Final
2022-04-04 01:21:10.641  INFO 16567 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-04-04 01:21:10.828  INFO 16567 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2022-04-04 01:21:12.076  INFO 16567 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-04-04 01:21:12.094  INFO 16567 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-04-04 01:21:12.535  INFO 16567 --- [           main] run.halo.app.config.HaloConfiguration    : Halo cache store load impl : [class run.halo.app.cache.InMemoryCacheStore]
2022-04-04 01:21:13.007  INFO 16567 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2022-04-04 01:21:13.008  INFO 16567 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2022-04-04 01:21:13.009  INFO 16567 --- [           main] org.eclipse.jetty.server.session         : node0 Scavenging every 600000ms
2022-04-04 01:21:13.025  INFO 16567 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@15369d73{application,/,[file:///tmp/jetty-docbase.8081.13457857109614151691/, jar:file:/root/halo-1.4.17.jar!/BOOT-INF/lib/springfox-swagger-ui-3.0.0.jar!/META-INF/resources],AVAILABLE}
2022-04-04 01:21:13.025  INFO 16567 --- [           main] org.eclipse.jetty.server.Server          : Started @9528ms
2022-04-04 01:21:14.799  INFO 16567 --- [           main] run.halo.app.handler.file.FileHandlers   : Registered 9 file handler(s)
2022-04-04 01:21:16.992  INFO 16567 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/api/admin/actuator'
2022-04-04 01:21:17.089  WARN 16567 --- [           main] o.e.j.s.h.ContextHandler.application     : unavailable

org.h2.message.DbException: IO Exception: "java.net.UnknownHostException: z5qnpokvdsyuv849.novalocal: z5qnpokvdsyuv849.novalocal: Name or service not known" [90028-197]
        at org.h2.message.DbException.get(DbException.java:168) ~[h2-1.4.197.jar!/:na]
        at org.h2.message.DbException.convert(DbException.java:299) ~[h2-1.4.197.jar!/:na]
        at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:254) ~[h2-1.4.197.jar!/:na]
        at org.h2.server.web.WebServer.updateURL(WebServer.java:331) ~[h2-1.4.197.jar!/:na]
        at org.h2.server.web.WebServer.init(WebServer.java:320) ~[h2-1.4.197.jar!/:na]
        at org.h2.server.web.WebServlet.init(WebServlet.java:52) ~[h2-1.4.197.jar!/:na]
        at javax.servlet.GenericServlet.init(GenericServlet.java:180) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[na:na]
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:220) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:156) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.8.jar!/:5.3.8]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at run.halo.app.Application.main(Application.java:21) ~[classes!/:1.4.17]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[halo-1.4.17.jar:1.4.17]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[halo-1.4.17.jar:1.4.17]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[halo-1.4.17.jar:1.4.17]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[halo-1.4.17.jar:1.4.17]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.net.UnknownHostException: z5qnpokvdsyuv849.novalocal: z5qnpokvdsyuv849.novalocal: Name or service not known" [90028-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar!/:na]
        ... 45 common frames omitted
Caused by: java.net.UnknownHostException: z5qnpokvdsyuv849.novalocal: z5qnpokvdsyuv849.novalocal: Name or service not known
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1646) ~[na:na]
        at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:252) ~[h2-1.4.197.jar!/:na]
        ... 42 common frames omitted
Caused by: java.net.UnknownHostException: z5qnpokvdsyuv849.novalocal: Name or service not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[na:na]
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) ~[na:na]
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[na:na]
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1641) ~[na:na]
        ... 43 common frames omitted

2022-04-04 01:21:17.094  INFO 16567 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-04-04 01:21:17.094  INFO 16567 --- [           main] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-04-04 01:21:17.095  INFO 16567 --- [           main] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2022-04-04 01:21:17.097  INFO 16567 --- [           main] org.eclipse.jetty.server.session         : node0 Stopped scavenging
2022-04-04 01:21:17.098  INFO 16567 --- [           main] o.e.j.s.h.ContextHandler.application     : Destroying Spring FrameworkServlet 'dispatcherServlet'
2022-04-04 01:21:17.099  INFO 16567 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@15369d73{application,/,[file:///tmp/jetty-docbase.8081.13457857109614151691/, jar:file:/root/halo-1.4.17.jar!/BOOT-INF/lib/springfox-swagger-ui-3.0.0.jar!/META-INF/resources],STOPPED}
2022-04-04 01:21:17.099  WARN 16567 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
2022-04-04 01:21:17.121  INFO 16567 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-04-04 01:21:17.138  INFO 16567 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-04-04 01:21:17.145  INFO 16567 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-04-04 01:21:17.174  INFO 16567 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-04-04 01:21:17.197 ERROR 16567 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.8.jar!/:5.3.8]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.8.jar!/:5.3.8]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at run.halo.app.Application.main(Application.java:21) ~[classes!/:1.4.17]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[halo-1.4.17.jar:1.4.17]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[halo-1.4.17.jar:1.4.17]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[halo-1.4.17.jar:1.4.17]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[halo-1.4.17.jar:1.4.17]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:181) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.8.jar!/:5.3.8]
        ... 22 common frames omitted
Caused by: javax.servlet.ServletException: webServlet==org.h2.server.web.WebServlet@aad2f851{jsp=null,order=-1,inst=true,async=true,src=JAVAX_API:null,STARTED}
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:650) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[na:na]
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[na:na]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:220) ~[spring-boot-2.5.1.jar!/:2.5.1]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:156) ~[spring-boot-2.5.1.jar!/:2.5.1]
        ... 24 common frames omitted
Caused by: org.h2.message.DbException: IO Exception: "java.net.UnknownHostException: z5qnpokvdsyuv849.novalocal: z5qnpokvdsyuv849.novalocal: Name or service not known" [90028-197]
        at org.h2.message.DbException.get(DbException.java:168) ~[h2-1.4.197.jar!/:na]
        at org.h2.message.DbException.convert(DbException.java:299) ~[h2-1.4.197.jar!/:na]
        at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:254) ~[h2-1.4.197.jar!/:na]
        at org.h2.server.web.WebServer.updateURL(WebServer.java:331) ~[h2-1.4.197.jar!/:na]
        at org.h2.server.web.WebServer.init(WebServer.java:320) ~[h2-1.4.197.jar!/:na]
        at org.h2.server.web.WebServlet.init(WebServlet.java:52) ~[h2-1.4.197.jar!/:na]
        at javax.servlet.GenericServlet.init(GenericServlet.java:180) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632) ~[jetty-servlet-9.4.42.v20210604.jar!/:9.4.42.v20210604]
        ... 37 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.net.UnknownHostException: z5qnpokvdsyuv849.novalocal: z5qnpokvdsyuv849.novalocal: Name or service not known" [90028-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar!/:na]
        ... 45 common frames omitted
Caused by: java.net.UnknownHostException: z5qnpokvdsyuv849.novalocal: z5qnpokvdsyuv849.novalocal: Name or service not known
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1646) ~[na:na]
        at org.h2.util.NetUtils.getLocalAddress(NetUtils.java:252) ~[h2-1.4.197.jar!/:na]
        ... 42 common frames omitted
Caused by: java.net.UnknownHostException: z5qnpokvdsyuv849.novalocal: Name or service not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[na:na]
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) ~[na:na]
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[na:na]
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1641) ~[na:na]
        ... 43 common frames omitted
```

### 附加信息
```
server:
  port: 8081

  # Response data gzip.
  compression:
    enabled: false
spring:
  datasource:

    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.halo/db/halo
    username: admin
    password: 123456

    # MySQL database configuration.
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456

  # H2 database console configuration.
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true

halo:

  # Your admin client path is https://your-domain/{admin-path}
  admin-path: admin

  # memory or level
  cache: memory
```

**Comment by ruibaby** [comment]
@Shaw-cc 你好，有尝试过使用 1.4 的备份来启动码？

**Comment by guqing** [comment]
是否修改过你服务器的 /etc/hosts 或者 hostname，你可以将你的 .halo 备份换到本地或者另一台服务器试一下升级到1.5.1
