### ISSUE TITLE
SMTP office365

### ISSUE THREAD

**Issue by wangxiaoerYah** [halo-dev/halo#1848]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://www.wangxiaoer.site

### 发生了什么？

邮件发送 smtp设置为office365 连接会报错

### 相关日志输出

```shell
Apr 16 02:48:46 instance-d java[7058]: Exception in thread "pool-4-thread-2" run.halo.app.exception.EmailException: 邮件发送失败，请检查 SMTP 服务配置是否正确                                                    
Apr 16 02:48:46 instance-d java[7058]:         at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:122)      
Apr 16 02:48:46 instance-d java[7058]:         at run.halo.app.mail.AbstractMailService.lambda$sendMailTemplate$0(AbstractMailService.java:137)                                                                   
Apr 16 02:48:46 instance-d java[7058]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 
Apr 16 02:48:46 instance-d java[7058]:         
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) Apr 16 02:48:46 instance-d java[7058]:         
at java.base/java.lang.Thread.run(Thread.java:833)                                           
Apr 16 02:48:46 instance-d java[7058]: Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.office365.com, port: 587;                                          
Apr 16 02:48:46 instance-d java[7058]:   nested exception is:         
Apr 16 02:48:46 instance-d java[7058]:         javax.net.ssl.SSLException: Unsupported or unrecognized SSL message. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.office365.com, port: 587;                                                      
Apr 16 02:48:46 instance-d java[7058]:   nested exception is:         
Apr 16 02:48:46 instance-d java[7058]:         javax.net.ssl.SSLException: Unsupported or unrecognized SSL message; message exceptions (1) are:                                                                   
Apr 16 02:48:46 instance-d java[7058]: Failed message 1: javax.mail.MessagingException: Could not connect to SMTP host: smtp.office365.com, port: 587;                                                            
Apr 16 02:48:46 instance-d java[7058]:   nested exception is:         
Apr 16 02:48:46 instance-d java[7058]:         javax.net.ssl.SSLException: Unsupported or unrecognized SSL message                          
Apr 16 02:48:46 instance-d java[7058]:         at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448)  
Apr 16 02:48:46 instance-d java[7058]:         at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)    
Apr 16 02:48:46 instance-d java[7058]:         at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)    
Apr 16 02:48:46 instance-d java[7058]:         at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:115)      
Apr 16 02:48:46 instance-d java[7058]:         ... 4 more             Apr 16 02:48:46 instance-d java[7058]: Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.office365.com, port: 587;                                                                   
Apr 16 02:48:46 instance-d java[7058]:   nested exception is:         Apr 16 02:48:46 instance-d java[7058]:         javax.net.ssl.SSLException: Unsupported or unrecognized SSL message                          
Apr 16 02:48:46 instance-d java[7058]:         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2212)                       
Apr 16 02:48:46 instance-d java[7058]:         at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)                   
Apr 16 02:48:46 instance-d java[7058]:         at javax.mail.Service.connect(Service.java:342)                                              
Apr 16 02:48:46 instance-d java[7058]:         at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)                                                              
Apr 16 02:48:46 instance-d java[7058]:         at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)  Apr 16 02:48:46 instance-d java[7058]:        
 ... 7 more             
 Apr 16 02:48:46 instance-d java[7058]: Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message                       
 Apr 16 02:48:46 instance-d java[7058]:         at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:451)                                                              
 Apr 16 02:48:46 instance-d java[7058]:         at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)     
 Apr 16 02:48:46 instance-d java[7058]:         at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)                     
 Apr 16 02:48:46 instance-d java[7058]:         at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)                  
 Apr 16 02:48:46 instance-d java[7058]:         at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)    
  Apr 16 02:48:46 instance-d java[7058]:         at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)           
  Apr 16 02:48:46 instance-d java[7058]:         at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)           
  Apr 16 02:48:46 instance-d java[7058]:         at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)                
 Apr 16 02:48:46 instance-d java[7058]:         at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)                      
 Apr 16 02:48:46 instance-d java[7058]:         at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)                         
 Apr 16 02:48:46 instance-d java[7058]:         at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)

```

**Comment by wangxiaoerYah** [comment]
和office365 smtp加密有关

[office smtp](https://support.microsoft.com/zh-tw/office/pop-imap-%E5%92%8C-smtp-%E8%A8%AD%E5%AE%9A-8361e398-8af4-4e97-b147-6c6c4ac95353)

**Comment by JohnNiang** [comment]
@wangxiaoerYah 感谢提供反馈及非常有帮助的链接，这周我尝试复现这个问题。

**Comment by ntdgy** [comment]
开发者您好，我在本机复现了这个问题，并且通过修改代码成功发送并且能够正常接受。请问我能在这周稍晚的时候提交一个相应的pr来完成修复吗？
![image](https://user-images.githubusercontent.com/15956055/163972259-88d328a8-dbd2-47e4-be52-c9f133605264.png)
![image](https://user-images.githubusercontent.com/15956055/163972307-90586450-15b8-47ca-992c-45b7f4ac18d9.png)

**Comment by ruibaby** [comment]
> 请问我能在这周稍晚的时候提交一个相应的pr来完成修复吗？

非常期待。

/kind bug
/milestone 1.5.x

**Comment by AsakusaRinne** [comment]
您好，请问对这个issue的修复是不是尚未作为release发布呢？我使用1.5.4版本仍然遇到了这个问题（使用outlook邮箱）

**Comment by JohnNiang** [comment]
> 您好，请问对这个issue的修复是不是尚未作为release发布呢？我使用1.5.4版本仍然遇到了这个问题（使用outlook邮箱）

好的，近期我们在筹备发布 Halo 2.0 的 Alpha 版本。发布之后会优先发布 Halo 1.5.5。

**Comment by AsakusaRinne** [comment]
> > 您好，请问对这个issue的修复是不是尚未作为release发布呢？我使用1.5.4版本仍然遇到了这个问题（使用outlook邮箱）
> 
> 好的，近期我们在筹备发布 Halo 2.0 的 Alpha 版本。发布之后会优先发布 Halo 1.5.5。

好的，十分感谢！期待新版本的发布

**Comment by ruibaby** [comment]
更正一下，由于这个其实算一个新的特性。所以应该是发布到 1.6。1.6 我们也会和 1.5.5 一起发布。

**Comment by JohnNiang** [comment]
> > > 您好，请问对这个issue的修复是不是尚未作为release发布呢？我使用1.5.4版本仍然遇到了这个问题（使用outlook邮箱）
> > 
> > 
> > 好的，近期我们在筹备发布 Halo 2.0 的 Alpha 版本。发布之后会优先发布 Halo 1.5.5。
> 
> 好的，十分感谢！期待新版本的发布

Hi @AsakusaRinne ，我们刚刚发布了 1.5.5 和 1.6.0，请参考：

- https://github.com/halo-dev/halo/releases/tag/v1.6.0
- https://github.com/halo-dev/halo/releases/tag/v1.5.5

但是当前 PR 属于一个新的功能，所以我们将它发布在了 1.6.0。

**Comment by AsakusaRinne** [comment]
好的，感谢！我去更新到1.6.0试试
