### ISSUE TITLE
采用docker部署，重启镜像后，flyway执行sql文件时报错

### ISSUE THREAD

**Issue by WongLeee** [halo-dev/halo#1855]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

halohub/halo:1.5.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

docker重启镜像后，flyway执行sql文件报错，多个表格均出现如下问题，表没有修改过，都是flyway自动创建出来的

### 相关日志输出

```shell
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V3__migrate_1.3.0-beta.1_to_1.3.0-beta.2.sql failed
-------------------------------------------------------------
SQL State  : 23000
Error Code : 1048
Message    : Column 'slug' cannot be null
Location   : migration/V3__migrate_1.3.0-beta.1_to_1.3.0-beta.2.sql (/application/BOOT-INF/classes/migration/V3__migrate_1.3.0-beta.1_to_1.3.0-beta.2.sql)
Line       : 4
Statement  : -- Migrate 1.3.0-beta.1 to 1.3.0-beta.2

-- Migrate posts Table
update posts set `slug`=`url`

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:154) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:219) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:170) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.Flyway.execute(Flyway.java:586) ~[flyway-core-7.15.0.jar:na]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:170) ~[flyway-core-7.15.0.jar:na]
        at run.halo.app.listener.StartedListener.migrate(StartedListener.java:123) ~[classes/:1.5.1]
        at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:76) ~[classes/:1.5.1]
        at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:47) ~[classes/:1.5.1]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.17.jar:5.3.17]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.17.jar:5.3.17]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.17.jar:5.3.17]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.17.jar:5.3.17]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.17.jar:5.3.17]
        at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:105) ~[spring-boot-2.5.11.jar:2.5.11]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.11.jar:2.5.11]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.11.jar:2.5.11]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.11.jar:2.5.11]
        at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.11.jar:2.5.11]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.11.jar:2.5.11]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) ~[spring-boot-2.5.11.jar:2.5.11]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.11.jar:2.5.11]
        at run.halo.app.Application.main(Application.java:21) ~[classes/:1.5.1]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[application/:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application/:na]
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V3__migrate_1.3.0-beta.1_to_1.3.0-beta.2.sql failed
-------------------------------------------------------------
SQL State  : 23000
```

### 附加信息

请问是否可以禁用flyway启动，我尝试修改application.ymal的配置文件，但是没有生效

**Comment by JohnNiang** [comment]
可以介绍一下重启镜像的原因，比如是从哪个版本升级上来还是正常的维护重启。

从日志上来看，初步怀疑是从 1.2.x 升级到 1.5.x 出现的错误。

**Comment by ruibaby** [comment]
从日志来看，应该是你早期的文章数据中，有包含 url 为空的数据，建议恢复你以前的备份，根据你以前的版本和 https://github.com/halo-dev/halo/tree/master/src/main/resources/migration 进行手动检查数据。

**Comment by ruibaby** [comment]
请问此问题有后续补充吗？

**Comment by ruibaby** [comment]
先关闭这个 issue 了，有后续补充可以 reopen。

/close
