### ISSUE TITLE
halo版本回退后，导致新版halo无法启动

### ISSUE THREAD

**Issue by Camsyn** [halo-dev/halo#1881]
### Checklist

- [X] The issue has been searched in [GitHub Issues](https://github.com/halo-dev/halo/issues)
- [X] The issue has been searched in the [bbs.halo.run](https://bbs.halo.run/)
- [X] Already consulted [document](https://docs.halo.run/)

### What is version of Halo has the issue?

1.5.1

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### What happened?

1. 当新版halo (>=1.5.1) 首次启动，会构建自己的表结构。
2. 此时切换至旧版halo启动（如1.4.17），会污染当前的表结构
3. 此时再切换会新版halo，发现新版halo无法启动（报索引、主键冲突的异常）

### Relevant log output

```shell
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [1, TIMESTAMP '2022-04-23 14:43:56.417', TIMESTAMP '2022-04-23 14:43:56.469', SPACE(642 /* table: 23 id: 23 */), 1, SPACE(452 /* table: 23 id: 24 */), 1, 0]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:457) ~[h2-1.4.199.jar!/:na]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2-1.4.199.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.199.jar!/:na]
        at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.199.jar!/:na]
        at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:131) ~[h2-1.4.199.jar!/:na]
        at org.h2.mvstore.db.MVTable.addRow(MVTable.java:546) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.dml.Insert.addRowImpl(Insert.java:251) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.dml.Insert.insertRows(Insert.java:207) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.dml.Insert.update(Insert.java:132) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.CommandContainer.update(CommandContainer.java:133) ~[h2-1.4.199.jar!/:na]
        at org.h2.command.Command.executeUpdate(Command.java:267) ~[h2-1.4.199.jar!/:na]
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233) ~[h2-1.4.199.jar!/:na]
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205) ~[h2-1.4.199.jar!/:na]
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111) ~[flyway-core-7.15.0.jar!/:na]
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:212) ~[flyway-core-7.15.0.jar!/:na]
```

### Additional information

我认为版本回退和版本回退后再恢复新版本都是很有可能的行为。

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/issues/1765

> 我认为版本回退和版本回退后再恢复新版本都是很有可能的行为。

目前已经无法再修改 1.5.x 的升级脚本。其实在任何情况下，都不建议进行直接降级的操作。如果一定要降级，请使用备份的 1.4.x 进行恢复。

/triage duplicate
