### ISSUE TITLE
删除主题后不能重新导入主题

### ISSUE THREAD

**Issue by CJSoldier** [halo-dev/halo#198]
**我确定我已经查看了**

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

删除主题后用户目录下对应的主题文件夹没有删除，导致不能再次导入主题。
手动删除也不行，停掉服务后文件夹自动消失。
在调试主题的时候需要不停地启/停服务，有点难受。

**Comment by JohnNiang** [comment]
好的，我们排查一下。

如果删除了本地主题文件后，在管理端刷新一下主题可以临时解决问题。

**Comment by JohnNiang** [comment]
经过本地测试，删除主题同时会删除本地文件的。

如果您是手动删除了本地文件，那么请在 `管理端>外观>主题` 右下角刷新主题即可。

> 如果您是通过 `docker` 部署的 `halo`，且配置了 `spring.profiles.active=dev`，那么也请配置一下 `halo.work-dir=${user.home}/.halo/`。否则 `halo` 在开发环境下默认的工作目录是在 `~/halo-dev`。当然，也可以通过 `docker` 映射一下 `volume`。

**Comment by CJSoldier** [comment]
不行啊。我在`win10`本地运行的，只要不停止halo-1.0.1.jar的服务，用户目录下的iissnan_next文件夹就删除不了。手动删除也不行，说没有访问权限。


```
Caused by: java.nio.file.AccessDeniedException: C:\Users\CJSoldier\.halo\templates\themes\iissnan_next
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[na:1.8.0_171]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.8.0_171]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[na:1.8.0_171]
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504) ~[na:1.8.0_171]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[na:1.8.0_171]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[na:1.8.0_171]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[na:1.8.0_171]
        at run.halo.app.utils.FileUtils$1.preVisitDirectory(FileUtils.java:50) ~[classes!/:1.0.1]
        at run.halo.app.utils.FileUtils$1.preVisitDirectory(FileUtils.java:43) ~[classes!/:1.0.1]
        at java.nio.file.Files.walkFileTree(Files.java:2677) ~[na:1.8.0_171]
        at java.nio.file.Files.walkFileTree(Files.java:2742) ~[na:1.8.0_171]
        at run.halo.app.utils.FileUtils.copyFolder(FileUtils.java:43) ~[classes!/:1.0.1]
        at run.halo.app.service.impl.ThemeServiceImpl.add(ThemeServiceImpl.java:426) ~[classes!/:1.0.1]
        at run.halo.app.service.impl.ThemeServiceImpl.upload(ThemeServiceImpl.java:394) ~[classes!/:1.0.1]
        ... 76 common frames omitted
```

 点击主题>>刷新也不行。停掉服务后这个文件夹会自动消失，重启服务后就可以重新导入了。
我觉得再次导入的时候可以线判断文件夹是否已经存在，如果已经存在就把其他文件放进去就好了。

**Comment by JohnNiang** [comment]
好的，我开启虚拟机复现一下。

> BTW： 在 Linux 上确实没有这个问题。

**Comment by CJSoldier** [comment]
我试着用管理员的身份打开PowerShell，然后运行`java -jar halo.jar`，还是删不掉。
后端报`java.nio.file.AccessDeniedException:`。

**Comment by CJSoldier** [comment]
> 在 Linux 上确实没有这个问题。

嗯，感觉是跟系统有关。

**Comment by JohnNiang** [comment]
正在复现......

**Comment by JohnNiang** [comment]
```txt
C:\Users\johnniang\.halo\templates\themes\ghost_casper\.git\objects\pack
λ ls -la
total 1052
drwxr-xr-x 1 johnniang 197121       0 六月 12 00:53 ./
drwxr-xr-x 1 johnniang 197121       0 六月 12 00:54 ../
-r--r--r-- 1 johnniang 197121   12468 六月 12 00:53 pack-12ed2e67036bc663bdea361f444deeb305e2c570.idx
-r--r--r-- 1 johnniang 197121 1056821 六月 12 00:53 pack-12ed2e67036bc663bdea361f444deeb305e2c570.pack
```

问题出在这两个文件是只读，导致无法删除。

**Comment by CJSoldier** [comment]
> 问题出在这两个文件是只读，导致无法删除。
原来如此。你们这回复真神速，佩服。

**Comment by JohnNiang** [comment]
在 `Linux` 下，这个两个文件也是`只读`的，却能够成功删除。

**Comment by CJSoldier** [comment]
嗯，太晚了，早点休息吧。

**Comment by JohnNiang** [comment]
> 嗯，太晚了，早点休息吧。

好的，争取明天解决了。

**Comment by JohnNiang** [comment]
> ```
> C:\Users\johnniang\.halo\templates\themes\ghost_casper\.git\objects\pack
> λ ls -la
> total 1052
> drwxr-xr-x 1 johnniang 197121       0 六月 12 00:53 ./
> drwxr-xr-x 1 johnniang 197121       0 六月 12 00:54 ../
> -r--r--r-- 1 johnniang 197121   12468 六月 12 00:53 pack-12ed2e67036bc663bdea361f444deeb305e2c570.idx
> -r--r--r-- 1 johnniang 197121 1056821 六月 12 00:53 pack-12ed2e67036bc663bdea361f444deeb305e2c570.pack
> ```
> 
> 问题出在这两个文件是只读，导致无法删除。

这里的分析是错误的。

可以手动删除本地的主题文件，这足以说明只读也是能够删除的。问题应该还是在 `halo`。

**Comment by JohnNiang** [comment]
确实是我们 `halo` 的问题，预计今天能够修复这个问题。

修复之后我们将会 release 一个测试版，届时您可以下载测试版进行主题开发。

**Comment by CJSoldier** [comment]
感谢。 我已经仔细阅读“主题开发”文档，按照文档要求，不用每次删主题的。实在抱歉，这个bug纯属意外:)

**Comment by JohnNiang** [comment]
意外的 bug 被意外地修复了 ：P

**Comment by JohnNiang** [comment]
尝试更新一下 `halo v1.0.2-beta.1`。

> <https://github.com/halo-dev/halo/releases>
