### ISSUE TITLE
备份的数据浏览器无法下载

### ISSUE THREAD

**Issue by ZTfred** [halo-dev/halo#2083]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://alialili.cn

### 发生了什么？

![image](https://user-images.githubusercontent.com/53425107/167838644-4e19a4bd-1648-4a06-bc63-db69ad039425.png)
![image](https://user-images.githubusercontent.com/53425107/167838689-93071074-514e-430d-b8bf-d1ded290d970.png)
下载链接：https://alialili.cn/api/admin/backups/markdown/export/halo-backup-markdown-2022-05-11-11-06-53--194835653.zip?ott=5bf0f1e281de4276b093a7059bcc8462~
错误码：400

### 相关日志输出

```shell
INFO   2022-05-11 19:28:38 ( 1652268518 )   Opening LogFile...
INFO   2022-05-11 19:28:38 ( 1652268518 )   DownloadID = 175 , Protocol = HTTPS , OS = WIN , AppVersion = WinVersion1324
INFO   2022-05-11 19:28:38 ( 1652268518 )   DownloadEngine State Changed : Unknown -> Starting...
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   DownloadEngine is Starting...
INFO   2022-05-11 19:28:38 ( 1652268518 )   Trying to Start Download for -> https://alialili.cn/api/admin/backups/markdown/export/halo-backup-markdown-2022-05-11-11-06-53--194835653.zip?ott=62809558a2e5444c9424c21ce9c94add
INFO   2022-05-11 19:28:38 ( 1652268518 )   New Socket(s) Created. MaxAllowedConnection = 32 And ActiveSockets = 1
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   Socket ( 1 )  Connecting to  47.95.115.166:443 ...
INFO   2022-05-11 19:28:38 ( 1652268518 )   Initializing SslHandShake for Socket (1 )
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   Socket ( 1 ) SSLBuffer Reassigned , New Buffer Size = 16413
INFO   2022-05-11 19:28:38 ( 1652268518 )   SslHandShake OK for Socket ( 1 )
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   SegmentManager Created a New Segment and now has 1 Segments.
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   Socket ( 1 ) HttpStatus =  HTTP_STATE_VOID  RoundNumberServer = 0 and RoundNumberProxy = 0
INFO   2022-05-11 19:28:38 ( 1652268518 )   Sending Http-GET  for Socket ( 1 )  Range = 0-
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_VOID  ->  HTTP_STATE_GET_SENT 
INFO   2022-05-11 19:28:38 ( 1652268518 )   GET Sent : 
<< GET /api/admin/backups/markdown/export/halo-backup-markdown-2022-05-11-11-06-53--194835653.zip?ott=62809558a2e5444c9424c21ce9c94add HTTP/1.1
Host: alialili.cn
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
Accept: */*
Accept-Encoding: identity
Accept-Language: en-US,en;q=0.9
Accept-Charset: *
Origin: https://alialili.cn
Referer: https://alialili.cn/admin/index.html#/
Cookie: JSESSIONID=node0rlv3boppzel01dnkn2p65y26t540.node0; Hm_lvt_6b13c347291901d06c4810b8855cfeee=1652141146,1652181260,1652230083,1652267112; Hm_lpvt_6b13c347291901d06c4810b8855cfeee=1652267122
Range: bytes=0-

>>
INFO   2022-05-11 19:28:38 ( 1652268518 )   All Response Headers For Socket ( 1 ) :
INFO   2022-05-11 19:28:38 ( 1652268518 )   
<<HTTP/1.1 400 Bad Request
Server: Tengine/2.3.2
Date: Wed, 11 May 2022 11:28:41 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 140
Connection: keep-alive
Access-Control-Allow-Origin: https://alialili.cn
Access-Control-Allow-Headers: Content-Type,ADMIN-Authorization,API-Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 3600>>

DEBUG  2022-05-11 19:28:38 ( 1652268518 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_GET_SENT  ->  HTTP_STATE_PARSING_HTTP_HEADER 
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   Status Code For Socket (1 ) = 400
ERROR  2022-05-11 19:28:38 ( 1652268518 )   Handling Error - Socket ( 1 ) - SocketState =  HTTP_STATE_PARSING_HTTP_HEADER  ErrorText = HTTP/1.1 400 Bad Request
ERROR  2022-05-11 19:28:38 ( 1652268518 )   HTTP/1.1 400 Bad Request
INFO   2022-05-11 19:28:38 ( 1652268518 )   DownloadEngine State Changed : Starting... ( 4 ) -> Error
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   Socket ( 1 ) All Headers have been Parsed. Now HttpStatus =  HTTP_STATE_PARSING_HTTP_HEADER  And StatusCode = 400
ERROR  2022-05-11 19:28:38 ( 1652268518 )   Error Occurred. HTTP/1.1 400 Bad Request
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   DownloadEngine Is Terminating. EngineState = Error.
DEBUG  2022-05-11 19:28:38 ( 1652268518 )   HttpStatus Changed for Socket (  1 )  HTTP_STATE_PARSING_HTTP_HEADER  ->  HTTP_STATE_VOID 
INFO   2022-05-11 19:28:38 ( 1652268518 )   Closing LogFile.
```

### 附加信息

halo为容器部署，基础镜像是alpine，前端由nginx做代理转发，nginx同为容器部署，配置：
```nginx
server {
        listen       443 ssl http2;
        server_name  alialili.cn www.alialili.cn ;
        ssl_certificate "cert/alialili.cn.pem";
        ssl_certificate_key "cert/alialili.cn.key";
        ssl_session_cache shared:SSL:50m;
        #ssl_session_timeout  5m;
        ssl_protocols TLSv1.3 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ssl_prefer_server_ciphers on;
        add_header Strict-Transport-Security "max-age=31536000";
        # 开启 OCSP Stapling 
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate cert/alialili.cn.pem;
        resolver 233.5.5.5 233.6.6.6 valid=300s;
        resolver_timeout 5s;
        # 设置 ssl_buffer_size
        ssl_buffer_size 4k;
        # 设置 SSL SESSION 缓存
        ssl_session_tickets on;
        access_log  /usr/local/nginx/logs/www_alialili.log  main;
        #access_log  /usr/local/nginx/logs/www_alialili.log  json;

        add_header country  $geoip2_data_country_name-$geoip2_data_province_name-$geoip2_data_city_code;
        #add_header province $geoip2_data_province_name;
        #add_header city $geoip2_data_city_code;

        location / {
                gzip_static on; # 静态压缩
                add_header Cache-Control public,max-age=60,s-maxage=60; # 配置缓存
                proxy_set_header HOST $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://172.17.103.178:8080;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

        }
        # 资源防盗链（指定目录or指定文件类型）
        # location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
        location /upload/ {
          access_log off;
          # 域名白名单，去掉则阻止所有非本站请求
          valid_referers none blocked server_names *.alialili.cn 127.0.0.1 localhost ~\.google\. ~\.baidu\. ~\.qq\.;
          if ($invalid_referer) {
            rewrite ^/ https://cdn.jsdelivr.net/gh/qinhua/cdn_assets/img/robber.jpg;
          }
          proxy_pass http://172.17.103.178:8080;
        }

}
```

**Comment by JohnNiang** [comment]
Hi @ZTfred ，建议提供一下下载备份出错时 halo 的日志。目前只知道出现了 400 错误，但具体原因不明。

**Comment by ZTfred** [comment]
2022-05-11 13:40:02.855  WARN 1 --- [qtp424944647-495] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler run.halo.app.core.ControllerExceptionHandler#handleGlobalException(Exception)

org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class run.halo.app.model.support.BaseResponse] with preset Content-Type 'application/zip'
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:312) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:183) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:428) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:75) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:142) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.handler.HandlerExceptionResolverComposite.resolveException(HandlerExceptionResolverComposite.java:80) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1327) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1138) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:230) ~[websocket-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at run.halo.app.security.filter.AbstractAuthenticationFilter.doFilterInternal(AbstractAuthenticationFilter.java:224) ~[classes!/:1.5.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at run.halo.app.filter.CorsFilter.doFilter(CorsFilter.java:53) ~[classes!/:1.5.3]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.5.12.jar!/:2.5.12]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at run.halo.app.filter.LogFilter.doFilterInternal(LogFilter.java:40) ~[classes!/:1.5.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.45.v20220203.jar!/:9.4.45.v20220203]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-05-11 13:40:06.173  WARN 1 --- [qtp424944647-576] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [113.201.251.2]
2022-05-11 13:40:06.174 ERROR 1 --- [qtp424944647-576] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not exist or has been expired], status: [400 BAD_REQUEST], data: [9fae8cda90714716bb91edf65210e09f]
2022-05-11 13:40:08.007  WARN 1 --- [qtp424944647-618] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [113.201.251.2]
2022-05-11 13:40:08.008 ERROR 1 --- [qtp424944647-618] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not exist or has been expired], status: [400 BAD_REQUEST], data: [9fae8cda90714716bb91edf65210e09f]
2022-05-11 13:40:09.459  WARN 1 --- [qtp424944647-565] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [113.201.251.2]
2022-05-11 13:40:09.460 ERROR 1 --- [qtp424944647-565] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not exist or has been expired], status: [400 BAD_REQUEST], data: [9fae8cda90714716bb91edf65210e09f]
2022-05-11 13:40:10.747  WARN 1 --- [qtp424944647-573] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [113.201.251.2]
2022-05-11 13:40:10.747 ERROR 1 --- [qtp424944647-573] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not exist or has been expired], status: [400 BAD_REQUEST], data: [9fae8cda90714716bb91edf65210e09f]
2022-05-11 13:40:10.956  WARN 1 --- [qtp424944647-495] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [113.201.251.2]
2022-05-11 13:40:10.957 ERROR 1 --- [qtp424944647-495] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not exist or has been expired], status: [400 BAD_REQUEST], data: [9fae8cda90714716bb91edf65210e09f]
2022-05-11 13:40:11.172  WARN 1 --- [qtp424944647-623] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [113.201.251.2]
2022-05-11 13:40:11.174 ERROR 1 --- [qtp424944647-623] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not exist or has been expired], status: [400 BAD_REQUEST], data: [9fae8cda90714716bb91edf65210e09f]
2022-05-11 13:40:11.354  WARN 1 --- [qtp424944647-619] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [113.201.251.2]
2022-05-11 13:40:11.354 ERROR 1 --- [qtp424944647-619] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not exist or has been expired], status: [400 BAD_REQUEST], data: [9fae8cda90714716bb91edf65210e09f]
2022-05-11 13:40:11.542  WARN 1 --- [qtp424944647-575] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [113.201.251.2]
2022-05-11 13:40:11.542 ERROR 1 --- [qtp424944647-575] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [The one-time token does not exist or has been expired], status: [400 BAD_REQUEST], data: [9fae8cda90714716bb91edf65210e09f]

**Comment by JohnNiang** [comment]
```bash
https://johnniang.me/api/admin/backups/work-dir/halo-backup-2022-05-11-22-01-23--565319533.zip?ott=8a5356b5bf0047afba673cb7fbaa8d6a

**Comment by JohnNiang** [comment]
我这边手动测试了一下，无法复现以上错误：

```bash
docker run -it --rm --name halo -p 8090:8090 -v ~/.halo:/root/.halo halohub/halo:1.5.3
```

![image](https://user-images.githubusercontent.com/16865714/167870342-a12dfca8-f8ce-4205-9723-85d52651028a.png)

**Comment by ZTfred** [comment]
> 我这边手动测试了一下，无法复现以上错误：
> 
> ```shell
> docker run -it --rm --name halo -p 8090:8090 -v ~/.halo:/root/.halo halohub/halo:1.5.3
> ```
> 
> ![image](https://user-images.githubusercontent.com/16865714/167870342-a12dfca8-f8ce-4205-9723-85d52651028a.png)

代理了试试

**Comment by JohnNiang** [comment]
目前已经找到大量备份无法下载的问题：

- https://bbs.halo.run/d/1167
- https://bbs.halo.run/d/1116
- https://bbs.halo.run/d/2394-ubuntu2004

@halo-dev/sig-halo ，这个问题需要好好排查一下。

/priority awaiting-more-evidence

**Comment by ruibaby** [comment]
@JohnNiang 似乎都包含了 `The one-time token does not exist`，但下载链接是包含了 ott 参数的。

**Comment by ruibaby** [comment]
由于 Halo 1.x 不再维护，我将关闭此 issue，建议参考 https://github.com/halo-dev/halo/issues/3701#issuecomment-1498565539 来解决此问题。

https://www.halo.run/archives/halo-1.x-eol

/close
