### ISSUE TITLE
更新v1.5.3启动报错

### ISSUE THREAD

**Issue by XM2510136957** [halo-dev/halo#2087]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

启动报错

### 相关日志输出

```shell
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-05-16 16:12:59.577 ERROR 76716 --- [main] o.s.boot.SpringApplication               : Application run failed

org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V6__migrate_create_contents_table.sql failed
------------------------------------------------------
SQL State  : 23505
Error Code : 23505
Message    : Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [1, TIMESTAMP '2021-09-28 14:07:23.998', TIMESTAMP '2021-09-28 14:32:20.783', SPACE(642 /* table: 74 id: 1774774 */), 1, SPACE(452 /* table: 74 id: 1774775 */), 1, 2]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
```

**Comment by ruibaby** [comment]
/triage duplicate
/kind support

see https://github.com/halo-dev/halo/issues/1765

**Comment by XM2510136957** [comment]
> /triage duplicate /kind support
> 
> see #1765
上传文件出现oom的问题
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1375) ~[na:na]
	at java.base/java.lang.StringConcatHelper.newArray(StringConcatHelper.java:494) ~[na:na]
	at java.base/java.lang.String.join(String.java:3264) ~[na:na]
	at java.base/java.lang.System$2.join(System.java:2438) ~[na:na]
	at java.base/java.util.StringJoiner.toString(StringJoiner.java:174) ~[na:na]
	at java.base/java.util.stream.Collectors$$Lambda$46/0x800000054.apply(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:686) ~[na:na]
	at run.halo.app.utils.FileUtils.readString(FileUtils.java:575) ~[classes!/:1.5.3]
	at run.halo.app.service.impl.BackupServiceImpl.importMarkdown(BackupServiceImpl.java:235) ~[classes!/:1.5.3]
	at run.halo.app.controller.admin.api.BackupController.backupMarkdowns(BackupController.java:148) ~[classes!/:1.5.3]

**Comment by ruibaby** [comment]
@XM2510136957 你好，有其他问题请提交新的 issue，当前 issue 只针对这个升级的问题。

**Comment by JohnNiang** [comment]
Hi @XM2510136957 ，这个问题和 https://github.com/halo-dev/halo/issues/1765 重复，我们将关闭此 issue，如果有任何问题，欢迎随时重新打开。

/close
