### ISSUE TITLE
导入zip文件出现oom的问题

### ISSUE THREAD

**Issue by XM2510136957** [halo-dev/halo#2088]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

导入文件出现oom的问题

### 相关日志输出

```shell
Caused by: java.lang.OutOfMemoryError: Java heap space
at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1375) ~[na:na]
at java.base/java.lang.StringConcatHelper.newArray(StringConcatHelper.java:494) ~[na:na]
at java.base/java.lang.String.join(String.java:3264) ~[na:na]
at java.base/java.lang.System$2.join(System.java:2438) ~[na:na]
at java.base/java.util.StringJoiner.toString(StringJoiner.java:174) ~[na:na]
at java.base/java.util.stream.Collectors$$Lambda$46/0x800000054.apply(Unknown Source) ~[na:na]
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:686) ~[na:na]
at run.halo.app.utils.FileUtils.readString(FileUtils.java:575) ~[classes!/:1.5.3]
at run.halo.app.service.impl.BackupServiceImpl.importMarkdown(BackupServiceImpl.java:235) ~[classes!/:1.5.3]
at run.halo.app.controller.admin.api.BackupController.backupMarkdowns(BackupController.java:148) ~[classes!/:1.5.3]
```

**Comment by ruibaby** [comment]
你好 @XM2510136957 ，`导入zip文件` 是指在初始化页面导入数据吗？

**Comment by XM2510136957** [comment]
> 

2核4g腾讯云

**Comment by XM2510136957** [comment]
> 

Markdown 文章导入

**Comment by ruibaby** [comment]
> > 
> 
> Markdown 文章导入

目前不支持上传 ZIP 导入，只能导入纯文本格式（.markdown .md .txt）。虽然可以选择 zip 文件，但是会被当做文本格式去解析，所以会导致 OOM，稍后将新建一个 issue 来限制上传组件的文件后缀。

**Comment by XM2510136957** [comment]
那我现在不能批量导入之前的markdown笔记了

**Comment by XM2510136957** [comment]
>

**Comment by XM2510136957** [comment]
![image](https://user-images.githubusercontent.com/18229485/168622113-4907830b-b667-47c7-a6aa-324afe5577e7.png)

**Comment by JohnNiang** [comment]
@XM2510136957 ，建议提供一下出现错误时的日志信息。
