### ISSUE TITLE
导出文章为markdown文档，出现 “Internal Server Error”

### ISSUE THREAD

**Issue by szgacsaftop** [halo-dev/halo#2121]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

使用数据备份时，导出文章为markdown文档，出现 “Internal Server Error”

**Comment by JohnNiang** [comment]
/kind support
/triage needs-information

请提供对应的错误日志。

**Comment by szgacsaftop** [comment]
[haloService.out.log](https://github.com/halo-dev/halo/files/8790695/haloService.out.log)

这个为运行日志

**Comment by JohnNiang** [comment]
关键错误日志：

```java
java.nio.file.InvalidPathException: Illegal char <|> at index 66: C:\Windows\TEMP\halo-backup-markdown\557725593\�й��µĳ���Ա�ؿ���������Դ����ϵͳ | Gitee��Ŀ�Ƽ�-you-gu-shi-de-cheng-xu-yuan-bi-kan-de-liu-ge-kai-yuan-bo-ke-xi-tong-gitee-xiang-mu-tui-jian.md
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:na]
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229) ~[na:na]
	at java.base/java.nio.file.Path.of(Path.java:147) ~[na:na]
	at java.base/java.nio.file.Paths.get(Paths.java:69) ~[na:na]
	at run.halo.app.service.impl.BackupServiceImpl.exportMarkdowns(BackupServiceImpl.java:631) ~[classes!/:1.5.3]
	at run.halo.app.controller.admin.api.BackupController.exportMarkdowns(BackupController.java:203) ~[classes!/:1.5.3]
```

**Comment by eziosudo** [comment]
本地试了下同样的非法字符windows下才报了这个错。
在编辑页面生成的“文章别名“有时不能过滤非法字符，导致存进了数据库。
导出的时候代码里只有catch IOException，所以InvalidPathException直接抛出去了。

<img width="669" alt="image" src="https://user-images.githubusercontent.com/54128896/172285076-9efa54f2-af37-46b0-8a32-0fe5b60ea5a8.png">


在后台代码里再过滤一遍文件名的非法字符应该就能解决。

**Comment by JohnNiang** [comment]
根据 [Windows 官方文档](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)来看，文件名是有限制的，如果文章名包含特殊字符（如 "|"），则无法正常保存文件到 Windows 上。

出现问题的代码如下：

https://github.com/halo-dev/halo/blob/36b99d24765b78dec0edb24388801a19f1b6f609/src/main/java/run/halo/app/service/impl/BackupServiceImpl.java#L633-L634

#### 可能的解决方案：

1. 对生成的文件名去除或者替换 Windows 文件名保留字符

#### 参考：

- https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
- https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words

**Comment by JohnNiang** [comment]
Hi @eziosudo ，有兴趣修复这个小问题么 : P

如果可以的话，可以回复 `/assign` 可以自动将这个 issue assign 给你 :heart: 。

**Comment by eziosudo** [comment]
@JohnNiang 没问题，正有此意。

**Comment by JohnNiang** [comment]
> @JohnNiang 没问题，正有此意。

非常欢迎 🥳 

如果对于如何参与 Halo，可参考：<https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md>。
