### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by JavaHackSen** [halo-dev/halo#2334]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://91biu.work

### 发生了什么？

502 Bad Gateway

### 相关日志输出

```shell
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
,	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
,	at org.eclipse.jetty.server.Server.doStart(Server.java:387) ~[jetty-server-9.4.45.v20220203.jar:9.4.45.v20220203]
,	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.45.v20220203.jar:9.4.45.v20220203]
,	at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:123) ~[spring-boot-2.5.12.jar:2.5.12]
,	... 21 common frames omitted
,Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl' defined in file [/application/BOOT-INF/classes/run/halo/app/service/impl/UserServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in run.halo.app.repository.UserRepository defined in @EnableJpaRepositories declared on HaloConfiguration: Cannot create inner bean '(inner bean)#58ec8271' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#58ec8271': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
,	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.18.jar:5.3.18]
,	... 52 common frames omitted
,Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in run.halo.app.repository.UserRepository defined in @EnableJpaRepositories declared on HaloConfiguration: Cannot create inner bean '(inner bean)#58ec8271' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#58ec8271': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
,	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:389) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:134) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.18.jar:5.3.18]
,	... 66 common frames omitted
,Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#58ec8271': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
,	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:693) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:510) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:374) ~[spring-beans-5.3.18.jar:5.3.18]
,	... 80 common frames omitted
,Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[spring-beans-5.3.18.jar:5.3.18]
,	... 88 common frames omitted
,Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
,	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:176) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1224) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1255) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.3.18.jar:5.3.18]
,	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.3.18.jar:5.3.18]
,	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-orm-5.3.18.jar:5.3.18]
,	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[spring-orm-5.3.18.jar:5.3.18]
,	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-orm-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.18.jar:5.3.18]
,	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.18.jar:5.3.18]
,	... 95 common frames omitted
,Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
,	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:137) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101) ~[hibernate-core-5.4.33.jar:5.4.33]
,	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) ~[hibernate-core-5.4.33.jar:5.4.33]
,	... 112 common frames omitted
,
,
,    __  __      __
,   / / / /___ _/ /___
,  / /_/ / __ `/ / __ \
, / __  / /_/ / / /_/ /
,/_/ /_/\__,_/_/\____/
,
,Version: 1.5.4
,2022-08-19 09:03:55.811  INFO 7 --- [           main] run.halo.app.Application                 : Starting Application v1.5.4 using Java 11.0.11 on 36509e0e8b6a with PID 7 (/application/BOOT-INF/classes started by root in /application)
,2022-08-19 09:03:55.824  INFO 7 --- [           main] run.halo.app.Application                 : No active profile set, falling back to 1 default profile: "default"
,
```

**Comment by JohnNiang** [comment]
Duplicate with #1743 
/triage duplicate

**Comment by JavaHackSen** [comment]
请问我是通过docker部署的，1、那这个【database-platform: org.hibernate.dialect.MySQL5InnoDBDialect】要怎么添加啊
2、并没有安装数据库，难道是需要安装个MySQL吗？

**Comment by JohnNiang** [comment]
如果能够提供一个复现步骤，可以方便大家排查这个问题。我们并不知道你之前是如何操作的，配置文件具体内容是什么，在什么操作系统上运行的。参考了哪些文档。

**Comment by JavaHackSen** [comment]
我直接通过这种方式【$ docker pull halohub/halo:1.5.4
$ docker run -it -d --name halo -p 8090:8090 -v ~/.halo:/root/.halo】
也并没有做别的操作，昨天突然就502了，我并没碰过配置文件
云服务器centos上面

**Comment by JavaHackSen** [comment]
![image](https://user-images.githubusercontent.com/37896126/185526982-4b3d12a0-6840-4ada-a141-5e83571a8db7.png)
文件夹下并没有见有【application.yaml】，是要手动加一个吗？

**Comment by JohnNiang** [comment]
刚刚我在本地用以下命令运行了一下，没有出现以上问题：

```bash
docker run -it --name halo -p 8090:8090 -v ~/.halo:/root/.halo halohub/halo:1.5.4
```

运行结果如下：

```java
❯ docker run -it -d --name halo -p 8090:8090 -v ~/.halo:/root/.halo halohub/halo:1.5.4
d57a68b6e38c2ca28e0845371ee8e600a2d2bc9a614a35a46a33bd3b61b9eaed
❯ docker logs -f d5

    __  __      __
   / / / /___ _/ /___
  / /_/ / __ `/ / __ \
 / __  / /_/ / / /_/ /
/_/ /_/\__,_/_/\____/

Version: 1.5.4
2022-08-19 10:09:25.596  INFO 7 --- [           main] run.halo.app.Application                 : Starting Application v1.5.4 using Java 11.0.11 on d57a68b6e38c with PID 7 (/application/BOOT-INF/classes started by root in /application)
2022-08-19 10:09:25.599  INFO 7 --- [           main] run.halo.app.Application                 : No active profile set, falling back to 1 default profile: "default"
2022-08-19 10:09:26.709  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2022-08-19 10:09:26.709  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-08-19 10:09:26.993  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 275 ms. Found 24 JPA repository interfaces.
2022-08-19 10:09:27.973  INFO 7 --- [           main] org.eclipse.jetty.util.log               : Logging initialized @3764ms to org.eclipse.jetty.util.log.Slf4jLog
2022-08-19 10:09:28.195  INFO 7 --- [           main] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 8090
2022-08-19 10:09:28.203  INFO 7 --- [           main] org.eclipse.jetty.server.Server          : jetty-9.4.45.v20220203; built: 2022-02-03T09:14:34.105Z; git: 4a0c91c0be53805e3fcffdcdcc9587d5301863db; jvm 11.0.11+9
2022-08-19 10:09:28.247  INFO 7 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2022-08-19 10:09:28.248  INFO 7 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2593 ms
2022-08-19 10:09:28.802  INFO 7 --- [           main] run.halo.app.config.HaloConfiguration    : Halo cache store load impl : [class run.halo.app.cache.InMemoryCacheStore]
2022-08-19 10:09:29.492  INFO 7 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-08-19 10:09:29.589  INFO 7 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.33
2022-08-19 10:09:29.673  INFO 7 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-08-19 10:09:29.827  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-08-19 10:09:30.068  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-08-19 10:09:30.123  INFO 7 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2022-08-19 10:09:31.923  INFO 7 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-08-19 10:09:31.934  INFO 7 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-08-19 10:09:32.851  INFO 7 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2022-08-19 10:09:32.852  INFO 7 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2022-08-19 10:09:32.854  INFO 7 --- [           main] org.eclipse.jetty.server.session         : node0 Scavenging every 600000ms
2022-08-19 10:09:32.863  INFO 7 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@54ad9ff9{application,/,[file:///tmp/jetty-docbase.8090.14093537244195863491/, jar:file:/application/BOOT-INF/lib/springfox-swagger-ui-3.0.0.jar!/META-INF/resources],AVAILABLE}
2022-08-19 10:09:32.863  INFO 7 --- [           main] org.eclipse.jetty.server.Server          : Started @8655ms
2022-08-19 10:09:33.638  INFO 7 --- [           main] run.halo.app.handler.file.FileHandlers   : Registered 9 file handler(s)
2022-08-19 10:09:36.265  INFO 7 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/api/admin/actuator'
2022-08-19 10:09:36.322  INFO 7 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-19 10:09:36.322  INFO 7 --- [           main] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-19 10:09:36.325  INFO 7 --- [           main] o.s.web.servlet.DispatcherServlet        : Completed initialization in 3 ms
2022-08-19 10:09:36.342  INFO 7 --- [           main] o.e.jetty.server.AbstractConnector       : Started ServerConnector@427308f8{HTTP/1.1, (http/1.1)}{0.0.0.0:8090}
2022-08-19 10:09:36.343  INFO 7 --- [           main] o.s.b.web.embedded.jetty.JettyWebServer  : Jetty started on port(s) 8090 (http/1.1) with context path '/'
2022-08-19 10:09:36.370  INFO 7 --- [           main] run.halo.app.Application                 : Started Application in 11.351 seconds (JVM running for 12.161)
2022-08-19 10:09:36.371  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Starting migrate database...
2022-08-19 10:09:36.464  INFO 7 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 7.15.0 by Redgate
2022-08-19 10:09:36.465  INFO 7 --- [           main] o.f.c.i.database.base.BaseDatabaseType   : Database: jdbc:h2:file:/root/.halo//db/halo (H2 1.4)
2022-08-19 10:09:36.487  INFO 7 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Repair of failed migration in Schema History table "PUBLIC"."flyway_schema_history" not necessary as table doesn't exist.
2022-08-19 10:09:36.504  INFO 7 --- [           main] o.f.core.internal.command.DbRepair       : Successfully repaired schema history table "PUBLIC"."flyway_schema_history" (execution time 00:00.021s).
2022-08-19 10:09:36.507  INFO 7 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 7.15.0 by Redgate
2022-08-19 10:09:36.516  INFO 7 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 6 migrations (execution time 00:00.005s)
2022-08-19 10:09:36.532  INFO 7 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table "PUBLIC"."flyway_schema_history" with baseline ...
2022-08-19 10:09:36.557  INFO 7 --- [           main] o.f.core.internal.command.DbBaseline     : Successfully baselined schema with version: 1
2022-08-19 10:09:36.569  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 1
2022-08-19 10:09:36.573  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version "2 - migrate 1.2.0-beta.1 to 1.2.0-beta.2"
2022-08-19 10:09:36.608  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version "3 - migrate 1.3.0-beta.1 to 1.3.0-beta.2"
2022-08-19 10:09:36.652  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version "4 - migrate 1.3.0-beta.2 to 1.3.0-beta.3"
2022-08-19 10:09:36.671  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version "5 - migrate remove notnull for email in comments table"
2022-08-19 10:09:36.692  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version "6 - migrate create contents table"
2022-08-19 10:09:36.713  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Successfully applied 5 migrations to schema "PUBLIC", now at version v6 (execution time 00:00.152s)
2022-08-19 10:09:36.715  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Migrate database succeed.
2022-08-19 10:09:36.715  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Created backup directory: [/tmp/halo-backup]
2022-08-19 10:09:36.716  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Created data export directory: [/tmp/halo-data-export]
2022-08-19 10:09:36.873  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Copied theme folder from [/application/BOOT-INF/classes/templates/themes] to [/root/.halo/templates/themes/caicai_anatole]
2022-08-19 10:09:36.893  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Halo started at         http://127.0.0.1:8090
2022-08-19 10:09:36.894  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Halo admin started at   http://127.0.0.1:8090/admin
2022-08-19 10:09:36.894  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Halo has started successfully!
```

确认一下是否有配置过任何环境变量。

**Comment by JavaHackSen** [comment]
我只是记得前两天改过一篇文章元数据的【enable_copy和enable_read_limit】，别的环境变量，也没有动过~

**Comment by JohnNiang** [comment]
你可以试着更新一个目录重新运行一下 Halo，看看是否还会出现同样的问题。

- 如果正常运行，可能是你的数据库文件有问题
- 如果未正常运行再进行下一步排查

**Comment by ruibaby** [comment]
> ![image](https://user-images.githubusercontent.com/37896126/185526982-4b3d12a0-6840-4ada-a141-5e83571a8db7.png)

建议提供一下这个 logs 目录的日志文件，你上面提供的日志并不是很完整。

**Comment by JavaHackSen** [comment]
[spring (1).log](https://github.com/halo-dev/halo/files/9378831/spring.1.log)

**Comment by JavaHackSen** [comment]
我在新目录重新拉去一个是没有的问题正常运行，那要是数据库文件有问题，该怎么办呢？

**Comment by JavaHackSen** [comment]
[spring.log.2022-08-18.0.txt](https://github.com/halo-dev/halo/files/9379402/spring.log.2022-08-18.0.txt)
这是昨天开始出现问题时候的日志~

**Comment by JavaHackSen** [comment]
大佬们~请问还有救吗😭

**Comment by JohnNiang** [comment]
参考一下：https://bbs.halo.run/d/2717-errorh2/4 ，尝试先自己解决一下呢。

**Comment by Mcayear** [comment]
在 1panel 百分之百复现方法：
1. 应用商店安装 PostgreSQL
2. 应用商店安装 halo 选择 PostgreSQL 作为数据库
3. 经过配置后正常访问。
**下面是重点步骤**
4. 在容器页面编辑 PostgreSQL，将暴露端口的 127.0.0.1 替换为 0.0.0.0
5. 确定，重建
6. 此时访问 halo 显示 502 Bad Gateway

**Comment by Mcayear** [comment]
名称没变，网络ip没变，但是halo就莫名其妙连不上sql。

详细报错信息请查看：[halo bbs](https://bbs.halo.run/d/4854-halo281panel%E9%83%A8%E7%BD%B2mysql%E6%95%B0%E6%8D%AE%E5%BA%93%E4%B9%8B%E5%89%8D%E8%BF%90%E8%A1%8C%E6%AD%A3%E5%B8%B8%E7%8E%B0%E5%9C%A8%E6%8A%A5502%E5%8D%9A%E5%AE%A2%E5%A4%A7%E9%87%8F%E5%86%85%E5%AE%B9%E6%9C%AA%E5%A4%87%E4%BB%BD%E6%B1%82%E5%8A%A9/4)

**Comment by ruibaby** [comment]
@Mcayear 这种问题难道不应该自己检查容器网络问题或者向 1Panel 反馈吗？Halo 都已经提示 UnknownHostException 的异常了，就是找不到这个 Host，难道 Halo 还能有办法解决 Host 找不到的问题？

**Comment by Mcayear** [comment]
仔细看了您的回复。很显然 1panel 正常运行，并且 PostgreSQL 也正常运行。而 halo 未能成功链接，这是为什么呢？
通过 halo 的错误日志，可以初步判断是无法链接而我借助外部工具（PGAdmin4）却可以正常链接说明 PostgreSQL 的运行没有问题。

那这个问题便明了了，为什么其它应用可以连接而 halo 不行呢？错误的地址又是什么原因导致的呢？

综上，我认为向 1panel 反馈无法让 halo 成功链接 PostgreSQL，因为仅需要 Docker、PostgreSQL、Halo 便可复现问题。

1panel 只是方便进行这个复现操作的工具罢了。

**Comment by ruibaby** [comment]
@Mcayear 请提供单纯使用 Docker + PostgreSQL + Halo 复现的完整步骤，我会尝试根据你的步骤复现。

此外，我仍然保持我上面的观点，UnknownHostException 已经说明在 Halo 的容器无法访问到你配置的数据库地址了。

**Comment by ruibaby** [comment]
建议重新提交 issue，这个 issue 已经是两年前了，并且原 issue 的 Halo 版本为 1.x。
