### ISSUE TITLE
在单个分类所属文章页面页面变量中，无法获取子分类中的文章

### ISSUE THREAD

**Issue by hugeleaf** [halo-dev/halo#2368]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

[#1567](https://github.com/halo-dev/halo/pull/1567) 中描述了类似的使用场景。
在单个分类所属文章页面页面变量中，无法获取子分类中的文章，有趣的是分类下的文章个数是对的。

举个例子：
``` bash
media
└── rtc
    └── webrtc
        └── 文章
```
✔️通过模板标签categoryTag，能拿到media、rtc、webrtc三个分类的文章数postCount都是1。
❌在“category.ftl“页面变量中，引用category.postCount会异常。（日志）
❌在“category.ftl“页面变量中，posts.content中没有子分类中的文章，例子中media分类下没有文章。

### 相关日志输出

```shell
FreeMarker template error (DEBUG mode; use RETHROW in production!): The following has evaluated to null or missing: ==> categorie [in template "themes/bigleaf_leaf/category.ftl" at line 7, column 35] ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: ${categorie.postCount} [in template "themes/bigleaf_leaf/category.ftl" at line 7, column 33] ~ Reached through: #nested [in template "themes/bigleaf_leaf/module/macro.ftl" in macro "layout" at line 26, column 1] ~ Reached through: @layout title="${category.name} - ${b... [in template "themes/bigleaf_leaf/category.ftl" at line 2, column 1] ---- Java stack trace (for programmers): ---- freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...] at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85) at freemarker.core.UnexpectedTypeException.(UnexpectedTypeException.java:48) at freemarker.core.NonHashException.(NonHashException.java:49) at freemarker.core.Dot._eval(Dot.java:48) at freemarker.core.Expression.eval(Expression.java:101) at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) at freemarker.core.DollarVariable.accept(DollarVariable.java:63) at freemarker.core.Environment.visit(Environment.java:347) at freemarker.core.Environment.visit(Environment.java:389) at freemarker.core.Environment.invokeNestedContent(Environment.java:633) at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60) at freemarker.core.Environment.visit(Environment.java:383) at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:889) at freemarker.core.Environment.invokeMacro(Environment.java:825) at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84) at freemarker.core.Environment.visit(Environment.java:347) at freemarker.core.Environment.visit(Environment.java:353) at freemarker.core.Environment.process(Environment.java:326) at freemarker.template.Template.process(Template.java:383) at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:391) at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:304) at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:255) at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:179) at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316) at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1401) at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1145) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:230) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at run.halo.app.security.filter.ContentFilter.doAuthenticate(ContentFilter.java:59) at run.halo.app.security.filter.AbstractAuthenticationFilter.doFilterInternal(AbstractAuthenticationFilter.java:229) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at run.halo.app.filter.CorsFilter.doFilter(CorsFilter.java:53) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at run.halo.app.filter.LogFilter.doFilterInternal(LogFilter.java:40) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) at org.eclipse.jetty.server.Server.handle(Server.java:516) at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by guqing** [comment]
hi @hugeleaf，感谢你对此提出 issue，你愿意参数与修复它吗，如果你感兴趣，可以回复 `/assgin` 认领 🥳

**Comment by guqing** [comment]
该问题的改进办法：
模板指令使用到的地方为：
run.halo.app.core.freemarker.tag.PostTagDirective
<img width="722" alt="image" src="https://user-images.githubusercontent.com/38999863/187580341-17663898-d492-4599-8987-6cf77df2d6c1.png">

需要将 run.halo.app.service.impl.PostCategoryServiceImp下的
- listPostBy(String slug, PostStatus status)
- listPostBy(String slug, Set<PostStatus> status)
- listPostBy(Integer categoryId, Set<PostStatus> status)
- listPostBy(Integer categoryId)

都改为连同返回子分类文章数据

**Comment by hugeleaf** [comment]
> hi @hugeleaf，感谢你对此提出 issue，你愿意参与修复它吗，如果你感兴趣，可以回复 `/assgin` 认领 🥳

太抱歉了😢，711板砖党，用咱们工程也是因为没空自己写。话说要是Golang工程我可能抽点时间就直接提PR了，Java都10多年不碰了。

再次抱歉，祝这个伟大工程越来越好。

**Comment by JustinLiang522** [comment]
@guqing 请问是否可以将`run.halo.app.service.impl.PostCategoryServiceImp`下`listPostBy`里的`postCategoryRepository.findAllPostIdsByCategoryId(categoryId)`都改为`categoryService.listPostIdsByCategoryIdRecursively(categoryId)`？

**Comment by guqing** [comment]
> @guqing 请问是否可以将`run.halo.app.service.impl.PostCategoryServiceImp`下`listPostBy`里的`postCategoryRepository.findAllPostIdsByCategoryId(categoryId)`都改为`categoryService.listPostIdsByCategoryIdRecursively(categoryId)`？

建议将 categoryService.listPostIdsByCategoryIdRecursively 方法移动到 PostCategoryServiceImpl，因为 categoryService 依赖了PostCategoryServiceImpl 如果 PostCategoryServiceImpl在反过来依赖categoryService的方法会产生依赖循环问题

**Comment by JustinLiang522** [comment]
`pagePostBy`方法目前也会忽略子分类文章，是否也需要修改？

**Comment by guqing** [comment]
> `pagePostBy`方法目前也会忽略子分类文章，是否也需要修改？

这个分页的方法不改

**Comment by guqing** [comment]
> > `pagePostBy`方法目前也会忽略子分类文章，是否也需要修改？
> 
> 这个分页的方法不用改，这个改起来太麻烦，就保持原样即可

**Comment by JustinLiang522** [comment]
categoryServiceImpl.listAllByParentId 调用了 super.listAll，如果将 categoryServiceImpl.listPostIdsByCategoryIdRecursively 和 listAllByParentId 都移到 PostCategoryServiceImpl 会导致 super 的类型不一样。能否将 listPostBy 都移动到 categoryServiceImpl 中？

**Comment by guqing** [comment]
> categoryServiceImpl.listAllByParentId 调用了 super.listAll，如果将 listAllByParentId 移到 PostCategoryServiceImpl 会导致 super 的类型不一样。能否将 listPostBy 都移动到 categoryServiceImpl 中？

我看了一下发现 PostCategoryServiceImpl 已经依赖了 CategoryService，你直接用 categoryService.listPostIdsByCategoryIdRecursively() 它即可，sorry  之前没主意看😅

**Comment by JustinLiang522** [comment]
> 

哈哈我刚刚也没注意到。不过listPostIdsByCategoryIdRecursively无法传入status参数，我改成这样的话不知道可不可以？
```
Set<Integer> postIds = new HashSet<>();
categoryService.listAllByParentId(category.getId())
.forEach(x -> postIds.addAll(postCategoryRepository.findAllPostIdsByCategoryId(x.getId(), status)));

return postRepository.findAllById(postIds);
```

**Comment by guqing** [comment]
> 
> > > categoryServiceImpl.listAllByParentId 调用了 super.listAll，如果将 listAllByParentId 移到 PostCategoryServiceImpl 会导致 super 的类型不一样。能否将 listPostBy 都移动到 categoryServiceImpl 中？
> > 
> > 我看了一下发现 PostCategoryServiceImpl 已经依赖了 CategoryService，你直接用 categoryService.listPostIdsByCategoryIdRecursively() 它即可，sorry 之前没主意看记错了😅
> 
> 哈哈我刚刚也没注意到。不过listPostIdsByCategoryIdRecursively无法传入status参数，我改成这样的话不知道可不可以？
> ```
> Set<Integer> postIds = new HashSet<>();
> categoryService.listAllByParentId(category.getId())
> .forEach(x -> postIds.addAll(postCategoryRepository.findAllPostIdsByCategoryId(x.getId(), status)));
> 
> return postRepository.findAllById(postIds);
> ```
> 

看起来没什么问题👍，你可以继续写，提交 PR 后统一 review

**Comment by hugeleaf** [comment]
1.6版本：在category.ftl 中使用 paginationTag 发生空指针错误

`org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException`
