### ISSUE TITLE
2.0 sql文件不支持部署时执行

### ISSUE THREAD

**Issue by shiker1996** [halo-dev/halo#2464]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

2.0.0

### 使用的什么数据库？

MySQL 5.7

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

![image](https://user-images.githubusercontent.com/32234876/192089624-3cf60258-d546-4701-94f3-50064d81887f.png)

服务启动直接提示表不存在

### 相关日志输出

```shell
2022-09-24T16:54:13.156+08:00 ERROR 5692 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT extensions.* FROM extensions WHERE extensions.name = $1 LIMIT 2]
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.convertR2dbcException(ConnectionFactoryUtils.java:235) ~[spring-r2dbc-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.r2dbc.core.DefaultDatabaseClient.lambda$inConnectionMany$8(DefaultDatabaseClient.java:150) ~[spring-r2dbc-6.0.0-M5.jar:6.0.0-M5]
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6936) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.Flux.lambda$onErrorResume$29(Flux.java:6989) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredError(FluxUsingWhen.java:398) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.FluxUsingWhen$RollbackInner.onComplete(FluxUsingWhen.java:475) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2058) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:531) ~[reactor-pool-1.0.0-M4.jar:1.0.0-M4]
	at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:761) ~[reactor-pool-1.0.0-M4.jar:1.0.0-M4]
	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4321) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
```

### 附加信息

建议使用flyaway做数据库版本管理，将新增数据表放入migration中。不然更新前还得手动建表

**Comment by shiker1996** [comment]
额，我看master有的，是2.0删了？这next改动挺大啊。。。

**Comment by JohnNiang** [comment]
建议详细描述一下复现步骤。目前我们正常启动没有任何问题。

**Comment by shiker1996** [comment]
> 建议详细描述一下复现步骤。目前我们正常启动没有任何问题。

next分支，使用mysql部署会报这个错，提示没有这张表

**Comment by JohnNiang** [comment]
目前确实只写了 H2 的 [scheme-h2.sql](https://github.com/halo-dev/halo/blob/1da89f04e2bca3cde9c244d960dfddfe888caffb/src/main/resources/schema-h2.sql)。稍后我尝试适配一下 MySQL 和 PostgreSQL。

/kind improvement
/area core
/milestone 2.0
/assign

**Comment by JohnNiang** [comment]
暂时无法支持 MySQL 了（正式发布时会想办法解决）。

我们目前采用了 [R2DBC](https://spring.io/projects/spring-data-r2dbc) 而不是 JDBC 作为数据库连接。支持 R2DBC 的 MySQL 驱动有：<https://github.com/mirromutth/r2dbc-mysql> 和 <https://github.com/jasync-sql/jasync-sql>。

1. mirrormutth/r2dbc-mysql 因为缺乏维护，无法支持 [R2DBC SPI 1.0.0](https://github.com/r2dbc/r2dbc-spi/releases/tag/v1.0.0.RELEASE)，可参考 issue：<https://github.com/mirromutth/r2dbc-mysql/issues/233>。
2. jasync-sql/jasync-sql 无法正常使用，可参考：<https://github.com/jasync-sql/jasync-sql/issues/311>。

**Comment by lunfangyu** [comment]
> 



> 暂时无法支持 MySQL 了（正式发布时会想办法解决）。
> 
> 我们目前采用了 [R2DBC](https://spring.io/projects/spring-data-r2dbc) 而不是 JDBC 作为数据库连接。支持 R2DBC 的 MySQL 驱动有：https://github.com/mirromutth/r2dbc-mysql 和 https://github.com/jasync-sql/jasync-sql。
> 
> 1. mirrormutth/r2dbc-mysql 因为缺乏维护，无法支持 [R2DBC SPI 1.0.0](https://github.com/r2dbc/r2dbc-spi/releases/tag/v1.0.0.RELEASE)，可参考 issue：[Follow up on 1.0.0.RELEASE in R2DBC SPI mirromutth/r2dbc-mysql#233](https://github.com/mirromutth/r2dbc-mysql/issues/233)。
> 2. jasync-sql/jasync-sql 无法正常使用，可参考：[Failed to start Spring Boot(3.0.0-M5) application using jasync-r2dbc-mysql(2.1.1) jasync-sql/jasync-sql#311](https://github.com/jasync-sql/jasync-sql/issues/311)。

请教一下大佬，halo2.0基于何种原因，为何舍弃JDBC而选用支持还不完善的 R2DBC 呢？

**Comment by JohnNiang** [comment]
> 请教一下大佬，halo2.0基于何种原因，为何舍弃JDBC而选用支持还不完善的 R2DBC 呢？

Hi @lunfangyu ，主要原因是我们使用了 WebFlux 框架，如果继续使用 JDBC，无法发挥 WebFlux 的响应式优势。

目前，和 MySQL 的 R2DBC 驱动的上游社区反馈问题后，足以支持 MySQL 了，可参考：<https://github.com/halo-dev/halo/pull/2512>。

**Comment by zhaozhaoyi** [comment]
这个问题最后解决了吗？开发环境运行环境里，想跟着熟悉下代码结构，和数据表结构，发现跑不起来。

https://docs.halo.run/developer-guide/core/run
