### ISSUE TITLE
附件上传4K图片3.5M生成不了缩略图总是失败

### ISSUE THREAD

**Issue by momosnail** [halo-dev/halo#2478]
### 检查清单

- [X] 已经在 [GitHub Issues](https://github.com/halo-dev/halo/issues) 中搜索过该问题
- [X] 已经在[论坛](https://bbs.halo.run/)中搜索过该问题
- [X] 已经查阅过[文档](https://docs.halo.run/)

### 是什么版本出现了此问题？

1.5.4

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

我上传了十几张4k大图片到附件，有几张总是生成不了缩略图，是否对于3.5M及以上的总会出现错误。

**Comment by JohnNiang** [comment]
建议提供一下错误日志供大家分析具体原因。可能的原因如下：

1. 如果服务器资源不足的话，较大的图片可能会导致生成缩略图失败，从而直接使用原图。
2. 图片格式问题

**Comment by momosnail** [comment]
可以加我QQ：550218658  前辈有时间的话 找一天晚上下班我们可以远程试试，今天我和同事两个人都有自己的服务器，都按照了咱的 halo框架 ，我们两个人都在各自的服务器上试了一下 确实是有问题的。不是 1.服务器资源不足 2.图片格式问题 不是这两种原因。

**Comment by ruibaby** [comment]
@momosnail 抱歉，我们不支持一对一处理问题，建议提供日志以便于大家排查问题。

https://github.com/halo-dev/halo/issues/2478#issuecomment-1259669309

查看日志的方式：https://docs.halo.run/user-guide/faq#%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E8%BF%90%E8%A1%8C%E6%97%A5%E5%BF%97

**Comment by momosnail** [comment]
谢谢，找到日志的存放地方了，下面是 向附件上传使用的资源和日志，求帮忙解决。
图片资源：https://www.futurus.top:5544/uploads/landscape/pexels-irina-iriser-1408221.jpg
日志：
`java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferByte.<init>(Unknown Source) ~[na:na]
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Unknown Source) ~[na:na]
	at java.desktop/java.awt.image.BufferedImage.<init>(Unknown Source) ~[na:na]
	at net.coobird.thumbnailator.builders.BufferedImageBuilder.build(Unknown Source) ~[thumbnailator-0.4.14.jar:0.4.14]
	at net.coobird.thumbnailator.resizers.ProgressiveBilinearResizer.resize(Unknown Source) ~[thumbnailator-0.4.14.jar:0.4.14]
	at net.coobird.thumbnailator.resizers.Resizers.resize(Unknown Source) ~[thumbnailator-0.4.14.jar:0.4.14]
	at net.coobird.thumbnailator.makers.ThumbnailMaker.makeThumbnail(Unknown Source) ~[thumbnailator-0.4.14.jar:0.4.14]
	at net.coobird.thumbnailator.makers.FixedSizeThumbnailMaker.make(Unknown Source) ~[thumbnailator-0.4.14.jar:0.4.14]
	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source) ~[thumbnailator-0.4.14.jar:0.4.14]
	at net.coobird.thumbnailator.Thumbnails$Builder.toFile(Unknown Source) ~[thumbnailator-0.4.14.jar:0.4.14]
	at run.halo.app.handler.file.LocalFileHandler.generateThumbnail(LocalFileHandler.java:224) ~[classes/:1.5.4]
	at run.halo.app.handler.file.LocalFileHandler.lambda$upload$1(LocalFileHandler.java:139) ~[classes/:1.5.4]
	at run.halo.app.handler.file.LocalFileHandler$$Lambda$1770/0x0000000100f39440.get(Unknown Source) ~[na:na]
	at run.halo.app.handler.file.FileHandler.handleImageMetadata(FileHandler.java:93) ~[classes/:1.5.4]
	at run.halo.app.handler.file.LocalFileHandler.upload(LocalFileHandler.java:125) ~[classes/:1.5.4]
	at run.halo.app.handler.file.FileHandlers.upload(FileHandlers.java:53) ~[classes/:1.5.4]
	at run.halo.app.service.impl.AttachmentServiceImpl.upload(AttachmentServiceImpl.java:119) ~[classes/:1.5.4]
	at run.halo.app.service.impl.AttachmentServiceImpl$$FastClassBySpringCGLIB$$2d9c80b9.invoke(<generated>) ~[classes/:1.5.4]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.18.jar:5.3.18]
	at run.halo.app.service.impl.AttachmentServiceImpl$$EnhancerBySpringCGLIB$$d72bd7c6.upload(<generated>) ~[classes/:1.5.4]
	at run.halo.app.controller.admin.api.AttachmentController.uploadAttachment(AttachmentController.java:84) ~[classes/:1.5.4]
	at run.halo.app.controller.admin.api.AttachmentController$$FastClassBySpringCGLIB$$8f3ff968.invoke(<generated>) ~[classes/:1.5.4]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.18.jar:5.3.18]
	at run.halo.app.core.ControllerLogAop.controller(ControllerLogAop.java:48) ~[classes/:1.5.4]
	at jdk.internal.reflect.GeneratedMethodAccessor294.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]`

**Comment by ruibaby** [comment]
@momosnail 这应该是在生成缩略图的时候内存资源不够导致了 OOM。建议尝试调高 `-Xms` 和 `-Xmx` 参数再进行尝试。

如果你是使用 Docker 部署，那么你可以添加 `JVM_OPTS` 环境变量，如 `-e JVM_OPTS="-Xmx512m -Xms512m"`

**Comment by momosnail** [comment]
> @momosnail 这应该是在生成缩略图的时候内存资源不够导致了 OOM。建议尝试调高 `-Xms` 和 `-Xmx` 参数再进行尝试。
> 
> 如果你是使用 Docker 部署，那么你可以添加 `JVM_OPTS` 环境变量，如 `-e JVM_OPTS="-Xmx512m -Xms512m"`

是的，我用的是docker，我看docker默认配置都是256m 我都改成了512m，问题已经解决。 非常感谢Thanks♪(･ω･)ﾉ
