### ISSUE TITLE
Could not find pf4j-3.7.0.jar (org.pf4j:pf4j:3.7.0).

### ISSUE THREAD

**Issue by shy-share** [halo-dev/halo#2504]
### 是什么版本出现了此问题？

2.0.0-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

无

### 发生了什么？

将项目git clone到本地，等到构建完毕之后，开始运行之后，会有一个jar包无法从阿里云下载

### 相关日志输出

```shell
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find pf4j-3.7.0.jar (org.pf4j:pf4j:3.7.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/gradle-plugin/org/pf4j/pf4j/3.7.0/pf4j-3.7.0.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### 附加信息

![image](https://user-images.githubusercontent.com/50973219/193432845-ae0d539a-f0f8-4391-905e-c3323a9916a8.png)

我本地maven仓库其实已经有了pf4j 这个jar包 ，当我将gradle的从仓库获取依赖的顺序改为先从本地仓库查找的时候，还是出现了找不到这个jar的错误，很奇怪，
> 右边是我本地的，我是在
![image](https://user-images.githubusercontent.com/50973219/193432940-da5766f1-f2b4-49c6-ba5e-0ad901aa7559.png)
- **下面是错误日志**

```java
2022-10-02T08:28:47.470+08:00 ERROR 21836 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [run.halo.app.Application]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:354) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:262) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:344) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:115) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:755) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:573) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.0.0-M4.jar:3.0.0-M4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-3.0.0-M4.jar:3.0.0-M4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:430) ~[spring-boot-3.0.0-M4.jar:3.0.0-M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.0.0-M4.jar:3.0.0-M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-3.0.0-M4.jar:3.0.0-M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-3.0.0-M4.jar:3.0.0-M4]
	at run.halo.app.Application.main(Application.java:26) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-3.0.0-M4.jar:3.0.0-M4]
**Caused by: java.io.FileNotFoundException: class path resource [org/pf4j/ExtensionPoint.class] cannot be opened because it does not exist**
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:183) ~[spring-core-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:54) ~[spring-core-6.0.0-M5.jar:6.0.0-M5]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:48) ~[spring-core-6.0.0-M5.jar:6.0.0-M5]
```

**Comment by ruibaby** [comment]
可以尝试清空 gradle 缓存再重新 build。

/kind support

**Comment by shy-share** [comment]
> 可以尝试清空 gradle 缓存再重新 build。
> 
> /kind support

好滴 我试试

**Comment by shy-share** [comment]
> /kind support

这个是什么意思  我搜了一下 情况缓存重新build的命令也不是这个呀

**Comment by zjy4fun** [comment]
@shy-share 直接把原项目删掉，重新克隆再打开吧 😄 
（你没发现这个issue已经加上support标签了嘛 👀

**Comment by shy-share** [comment]
> @shy-share 直接把原项目删掉，重新克隆再打开吧 😄 （你没发现这个issue已经加上support标签了嘛 👀

@ruibaby @zjy4fun  现在是下面这个错误了

**Could not find openapi-schema-validator-1.0.7.jar (org.openapi4j:openapi-schema-validator:1.0.7).**
Searched in the following locations:
    https://maven.aliyun.com/repository/gradle-plugin/org/openapi4j/openapi-schema-validator/1.0.7/openapi-schema-validator-1.0.7.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by JohnNiang** [comment]
从日志看，问题出在依赖下载阶段，建议重试几次。如果实在不行，可尝试注释 Aliyun Maven Mirror 配置：

- https://github.com/halo-dev/halo/blob/a89d51e63f81be0b9eccfdfaacd23ecfc73c58d1/settings.gradle#L3-L4
- https://github.com/halo-dev/halo/blob/a89d51e63f81be0b9eccfdfaacd23ecfc73c58d1/build.gradle#L18-L19

**Comment by shy-share** [comment]
> 从日志看，问题出在依赖下载阶段，建议重试几次。如果实在不行，可尝试注释 Aliyun Maven Mirror 配置：
> 
> * https://github.com/halo-dev/halo/blob/a89d51e63f81be0b9eccfdfaacd23ecfc73c58d1/settings.gradle#L3-L4
> * https://github.com/halo-dev/halo/blob/a89d51e63f81be0b9eccfdfaacd23ecfc73c58d1/build.gradle#L18-L19

@JohnNiang  我尝试注释也不行，现在只是我自己本地电脑有问题，你们的都是可以正常启动项目的是吗？

**Comment by ruibaby** [comment]
> 你们的都是可以正常启动项目的是吗？

我们所有提交都必须经过 PR，无法直接推送提交。而 PR 必须通过 CI 才能合并。

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
