### ISSUE TITLE
2.0版本不能使用

### ISSUE THREAD

**Issue by ZTfred** [halo-dev/halo#2505]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://120.24.231.39:8090/

### 发生了什么？

部署后，首页无法访问，500报错，后台无法上传主题，500报错，默认halo-next下没有application.yaml配置文件
![image](https://user-images.githubusercontent.com/53425107/193436093-c3755483-eb88-4a11-a3d7-746718d220f3.png)
![image](https://user-images.githubusercontent.com/53425107/193436111-1f0b2b79-2706-404d-88b0-c3cac7ff3738.png)
![image](https://user-images.githubusercontent.com/53425107/193436122-2d913056-f30e-48a4-b3c9-f62eb9b2379b.png)

使用的4.2版本的podman进行部署，官方镜像，官方命令，未进行任何改动

### 相关日志输出

```shell
*__checkpoint ⇢ HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at run.halo.app.core.extension.endpoint.ThemeEndpoint$ThemeUtils.loadThemeManifest(ThemeEndpoint.java:324) ~[classes/:2.0.0-alpha.1]
                at run.halo.app.core.extension.endpoint.ThemeEndpoint$ThemeUtils.unzipThemeTo(ThemeEndpoint.java:297) ~[classes/:2.0.0-alpha.1]
                at run.halo.app.core.extension.endpoint.ThemeEndpoint$ThemeUtils.unzipThemeTo(ThemeEndpoint.java:273) ~[classes/:2.0.0-alpha.1]
                at run.halo.app.core.extension.endpoint.ThemeEndpoint.lambda$install$11(ThemeEndpoint.java:166) ~[classes/:2.0.0-alpha.1]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerComplete(FluxConcatMapNoPrefetch.java:286) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onComplete(FluxConcatMap.java:887) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:173) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at org.springframework.http.codec.multipart.PartGenerator.emitPart(PartGenerator.java:202) ~[spring-web-6.0.0-M5.jar:6.0.0-M5]
                at org.springframework.http.codec.multipart.PartGenerator$IdleFileState.onComplete(PartGenerator.java:631) ~[spring-web-6.0.0-M5.jar:6.0.0-M5]
                at org.springframework.http.codec.multipart.PartGenerator$WritingFileState.writeComplete(PartGenerator.java:715) ~[spring-web-6.0.0-M5.jar:6.0.0-M5]
                at reactor.core.publisher.LambdaMonoSubscriber.onComplete(LambdaMonoSubscriber.java:135) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onComplete(MonoSubscribeOn.java:162) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:195) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4306) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0-M4.jar:3.5.0-M4]
                at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
                at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by ruibaby** [comment]
你使用的是 1.5 的主题，我们在 release note 已经说明了不兼容 1.x 的主题。

- Release Note：https://github.com/halo-dev/halo/releases/tag/v2.0.0-alpha.1
- 文档使用说明：https://docs.halo.run/2.0.0-SNAPSHOT/getting-started/install/docker#%E4%BD%BF%E7%94%A8

/kind support

**Comment by ZTfred** [comment]
> 

https://github.com/xzhuz/halo-theme-xue/releases
![image](https://user-images.githubusercontent.com/53425107/193446367-c26d6e3d-7fb0-4162-aaa7-d71bed4ddda1.png)
我使用的是文档提供的社区主题，下载的最新的release版本

**Comment by ZTfred** [comment]
还有上传报错500的，这个和主题无关，目前还没有安装上主题的

**Comment by ruibaby** [comment]
> > 
> 
> 
> 
> https://github.com/xzhuz/halo-theme-xue/releases
> 
> ![image](https://user-images.githubusercontent.com/53425107/193446367-c26d6e3d-7fb0-4162-aaa7-d71bed4ddda1.png)
> 
> 我使用的是文档提供的社区主题，下载的最新的release版本

这个主题还正在开发，没有发布 release。你需要在 https://github.com/ruibaby/halo-theme-xue/tree/refactor/migrate-next 分支下载 ZIP。

**Comment by ZTfred** [comment]
> > > 
> > 
> > 
> > https://github.com/xzhuz/halo-theme-xue/releases
> > ![image](https://user-images.githubusercontent.com/53425107/193446367-c26d6e3d-7fb0-4162-aaa7-d71bed4ddda1.png)
> > 我使用的是文档提供的社区主题，下载的最新的release版本
> 
> 这个主题还正在开发，没有发布 release。你需要在 https://github.com/ruibaby/halo-theme-xue/tree/refactor/migrate-next 分支下载 ZIP。

![image](https://user-images.githubusercontent.com/53425107/193446692-4706343d-8fbf-4250-a24d-49a0cbff61fc.png)
next分支还是安装报错
![image](https://user-images.githubusercontent.com/53425107/193446730-bc13b7bf-cbb1-480f-9837-034d89158c8b.png)
插件也是如此

next分支的配置文件在哪里呢

**Comment by zjy4fun** [comment]
![image](https://user-images.githubusercontent.com/106857035/193448948-abf84ed4-23ee-4c15-8534-d0dae3fe5ba5.png)

@ZTfred

**Comment by ruibaby** [comment]
详细说明一下：

1. https://github.com/halo-sigs/awesome-halo 中列出的主题和插件除了 `theme-xue` 还在开发中（标记了 WIP，Work In Progress），其他的库都需要去 release 的 Assets 下载构建产物，插件的后缀为 `.jar`。
2. theme-xue 这个主题你需要下载[refactor/migrate-next](https://github.com/ruibaby/halo-theme-xue/tree/refactor/migrate-next) 分支的源码。而不是 next。

如果还是不太清楚，你可以点击下方链接直接下载：

主题：

- halo-theme-xue : https://github.com/ruibaby/halo-theme-xue/archive/refs/heads/refactor/migrate-next.zip
- halo-theme-anatole: https://github.com/halo-sigs/theme-anatole/releases/download/0.0.10/theme-anatole-0.0.10.zip

**Comment by ZTfred** [comment]
> 详细说明一下：
> 
> 1. https://github.com/halo-sigs/awesome-halo 中列出的主题和插件除了 `theme-xue` 还在开发中（标记了 WIP，Work In Progress），其他的库都需要去 release 的 Assets 下载构建产物，插件的后缀为 `.jar`。
> 2. theme-xue 这个主题你需要下载[refactor/migrate-next](https://github.com/ruibaby/halo-theme-xue/tree/refactor/migrate-next) 分支的源码。而不是 next。
> 
> 如果还是不太清楚，你可以点击下方链接直接下载：
> 
> 主题：
> 
> * halo-theme-xue : https://github.com/ruibaby/halo-theme-xue/archive/refs/heads/refactor/migrate-next.zip
> * halo-theme-anatole: https://github.com/halo-sigs/theme-anatole/releases/download/0.0.10/theme-anatole-0.0.10.zip

可以了，插件要下载jar包，后台才可以正常上传插件。文档只是要去github下载，我下载zip，在后台是无法上传成功的，zip是需要手动编译一下吧
