### ISSUE TITLE
单个分类所属文章页面 category.ftl 调用 paginationTag 异常

### ISSUE THREAD

**Issue by hugeleaf** [halo-dev/halo#2644]
### What is version of Halo has the issue?

1.6.0

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### What happened?

可能是修复 [issues/2368](https://github.com/halo-dev/halo/issues/2368) 引入的新的问题：

（1）在category.ftl 中使用 paginationTag 发生空指针异常。
``` java
org.springframework.web.util.NestedServletException: Request processing failed; 
nested exception is java.lang.NullPointerException
```

（2）在category.ftl中引用category.postCount会异常。
``` java
FreeMarker template error (DEBUG mode; use RETHROW in production!): The following has evaluated to null or missing: ==> category [in template "themes/xxx/index.ftl" 
at line 14, column 16] ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: ${category.postCount} [in template "themes/xxx/index.ftl" 
at line 14, column 14] ~ Reached through: #nested [in template "themes/xxx/module/macro.ftl" in macro "layout" 
at line 26, column 1] ~ Reached through: @layout title="${blog_title!}" [in template "themes/xxx/index.ftl" 
at line 2, column 1] ---- Java stack trace (for programmers): ---- freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...] 
at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) 
at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85) 
at freemarker.core.UnexpectedTypeException.(UnexpectedTypeException.java:48) 
at freemarker.core.NonHashException.(NonHashException.java:49) 
at freemarker.core.Dot._eval(Dot.java:48) 
at freemarker.core.Expression.eval(Expression.java:101) 
at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) 
at freemarker.core.DollarVariable.accept(DollarVariable.java:63) 
at freemarker.core.Environment.visit(Environment.java:383) 
at freemarker.core.Environment.invokeNestedContent(Environment.java:633) 
at freemarker.core.BodyInstruction.accept(BodyInstruction.java:60) 
at freemarker.core.Environment.visit(Environment.java:383) 
at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:889) 
at freemarker.core.Environment.invokeMacro(Environment.java:825) 
at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84) 
at freemarker.core.Environment.visit(Environment.java:347) 
at freemarker.core.Environment.visit(Environment.java:353) 
at freemarker.core.Environment.process(Environment.java:326) 
at freemarker.template.Template.process(Template.java:383) 
at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:391) 
at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:304) 
at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:255) 
at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:179) 
at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316) 
at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1401) 
at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1145) 
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084) 
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) 
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) 
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) 
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) 
at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) 
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) 
at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) 
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:230) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at run.halo.app.security.filter.ContentFilter.doAuthenticate(ContentFilter.java:59) 
at run.halo.app.security.filter.AbstractAuthenticationFilter.doFilterInternal(AbstractAuthenticationFilter.java:229) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at run.halo.app.filter.CorsFilter.doFilter(CorsFilter.java:53) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at run.halo.app.filter.LogFilter.doFilterInternal(LogFilter.java:40) 
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) 
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) 
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) 
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) 
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) 
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) 
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) 
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) 
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) 
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) 
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) 
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) 
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) 
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) 
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) 
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) 
at org.eclipse.jetty.server.Server.handle(Server.java:516) 
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) 
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) 
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) 
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) 
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) 
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) 
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) 
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) 
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) 
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) 
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) 
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) 
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) 
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) 
at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ruibaby** [comment]
/kind bug
/area core

@hugeleaf 可以提供一个可复现的模板代码吗？

**Comment by hugeleaf** [comment]
```
<@layout title="${category.name} - ${blog_title!}">
<main>
    <div class="wrap min">
        <section class="home-title">
            <h1>${category.name}</h1>
            <span>${category.description!}</span>
        </section>

        <#--  文章列表  -->
        <section class="home-posts">
            <@postTag method="listByCategoryId" categoryId="${category.id?c}">
            <#list posts as post>
                <div class="post-item">
                    <h2>
                        <a href="${post.fullPath!}">${post.title}</a>
                    </h2>
                    <p> ${post.summary!} </p>
                    <div class="post-meta">
                        <time class="date">${post.createTime?string["yyyy.MM.dd"]!}</time>
                        <#if (post.categories)?? && post.categories?size !=0>
                            <#list post.categories as categorie>
                                <span class="category">${categorie.name!}</span>
                            </#list>
                        </#if>
                        <span class="comments">${post.commentCount!} ℃</span>
                    </div>
                </div>
            </#list>
            </@postTag>
        </section>

        <#--  分页  -->
        <section class="page-navigator">
            <#-- 这里会异常2 <div>${category.postCount}</div> -->
            <div>${.globals.posts.totalPages}</div>
            <div>${.globals.posts.number}</div>
            <div>${.globals.posts.totalPages}</div>
            <#-- 这里会异常1 <@paginationTag method="categoryPosts" page="${.globals.posts.number}" total="${.globals.posts.totalPages}" display="3">
            </@paginationTag> -->
        </section>
    </div>
</main>
</@layout>```

**Comment by ruibaby** [comment]
我这里似乎没有复现：https://ryanc.cc/categories/about-halo.html

可以提供一下复现的数据吗？或者你已经知道了触发这个 bug 的条件，可以直接发起 PR 哦。

**Comment by hugeleaf** [comment]
@ruibaby 要把上面注释有异常的地方注释去掉 在我看您的例子时 已经没有显示页码等信息 应该是还原了吧

附:
[主题代码](https://bigleaf.top/vod/leaf.tar)
[原站地址](https://bigleaf.top)

**Comment by ruibaby** [comment]
@hugeleaf 有分页也有显示文章数量。Halo 升级到 1.6 之后，我的主题没有修改过。

稍后我会用你的主题测试一下。

**Comment by ruibaby** [comment]
检查了一下，主题端分类归档页面的 API 应该是本来就没有 postCount 字段的。 https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/model/dto/CategoryDTO.java

你可以使用 `${posts.totalElements!}` 获取数量。

至于分页那里，因为需要构造分页的链接，所以需要传入 slug。参考 https://docs.halo.run/developer-guide/theme/template-tag#%E8%8E%B7%E5%8F%96%E5%88%86%E7%B1%BB%E4%B8%8B%E6%96%87%E7%AB%A0%E5%88%97%E8%A1%A8%E7%9A%84%E5%88%86%E9%A1%B5%E6%95%B0%E6%8D%AEcategoryposts

/kind support
/remove-kind bug
