### ISSUE TITLE
Docker运行报错；主键索引？

### ISSUE THREAD

**Issue by war3sxkcs** [halo-dev/halo#2674]
### 是什么版本出现了此问题？

halohub/halo:1.6.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

blog.s-name.com

### 发生了什么？

原版本貌似为 halohub/halo:1.4.* (好像是1.4.2)

因服务器到期，所以把.halo文件夹备份后scp到新服务的~下，再pull了halohub/halo:1.6.0启动发生了报错；以为是版本高了，所以pull了 halohub/halo:1.5.0的版本再启动还是报同样的错。不知道是什么问题，怀疑是备份 .halo 的时候报错 ？？但是看报错的内容文件的时间已经是很久远了。需要支持

### 相关日志输出

```shell
[root@_8_core home]# docker run -it -d --name halo -p 8090:8090 -v ~/.halo:/root/.halo --restart=unless-stopped halohub/halo:1.5.0
60560b352ed6f7b63bd994f335c378c9482e97a8f21acb3c2ca6e9d5a24c5fa5
[root@_8_core home]# docker logs -f 605

    __  __      __
   / / / /___ _/ /___
  / /_/ / __ `/ / __ \
 / __  / /_/ / / /_/ /
/_/ /_/\__,_/_/\____/

Version: 1.6.0
2022-11-08 23:58:03.483  INFO 7 --- [           main] run.halo.app.Application                 : Starting Application v1.6.0 using Java 11.0.16.1 on 60560b352ed6 with PID 7 (/application/BOOT-INF/classes started by root in /application)
2022-11-08 23:58:03.487  INFO 7 --- [           main] run.halo.app.Application                 : No active profile set, falling back to 1 default profile: "default"
2022-11-08 23:58:05.077  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2022-11-08 23:58:05.078  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-11-08 23:58:05.350  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 263 ms. Found 24 JPA repository interfaces.
2022-11-08 23:58:06.333  INFO 7 --- [           main] org.eclipse.jetty.util.log               : Logging initialized @4628ms to org.eclipse.jetty.util.log.Slf4jLog
2022-11-08 23:58:06.549  INFO 7 --- [           main] o.s.b.w.e.j.JettyServletWebServerFactory : Server initialized with port: 8090
2022-11-08 23:58:06.556  INFO 7 --- [           main] org.eclipse.jetty.server.Server          : jetty-9.4.45.v20220203; built: 2022-02-03T09:14:34.105Z; git: 4a0c91c0be53805e3fcffdcdcc9587d5301863db; jvm 11.0.16.1+1
2022-11-08 23:58:06.583  INFO 7 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2022-11-08 23:58:06.583  INFO 7 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3027 ms
2022-11-08 23:58:07.160  INFO 7 --- [           main] run.halo.app.config.HaloConfiguration    : Halo cache store load impl : [class run.halo.app.cache.InMemoryCacheStore]
2022-11-08 23:58:07.857  INFO 7 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-11-08 23:58:07.917  INFO 7 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.33
2022-11-08 23:58:07.958  INFO 7 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-11-08 23:58:08.080  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-11-08 23:58:08.385  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-11-08 23:58:08.451  INFO 7 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2022-11-08 23:58:09.418  INFO 7 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-11-08 23:58:09.426  INFO 7 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-11-08 23:58:10.094  INFO 7 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2022-11-08 23:58:10.094  INFO 7 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2022-11-08 23:58:10.096  INFO 7 --- [           main] org.eclipse.jetty.server.session         : node0 Scavenging every 600000ms
2022-11-08 23:58:10.107  INFO 7 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@5ca8157c{application,/,[file:///tmp/jetty-docbase.8090.12660548962012114809/, jar:file:/application/BOOT-INF/lib/springfox-swagger-ui-3.0.0.jar!/META-INF/resources],AVAILABLE}
2022-11-08 23:58:10.107  INFO 7 --- [           main] org.eclipse.jetty.server.Server          : Started @8404ms
2022-11-08 23:58:10.755  INFO 7 --- [           main] run.halo.app.handler.file.FileHandlers   : Registered 9 file handler(s)
2022-11-08 23:58:13.377  INFO 7 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/api/admin/actuator'
2022-11-08 23:58:13.440  INFO 7 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-11-08 23:58:13.441  INFO 7 --- [           main] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-11-08 23:58:13.442  INFO 7 --- [           main] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2022-11-08 23:58:13.453  INFO 7 --- [           main] o.e.jetty.server.AbstractConnector       : Started ServerConnector@68631b1d{HTTP/1.1, (http/1.1)}{0.0.0.0:8090}
2022-11-08 23:58:13.454  INFO 7 --- [           main] o.s.b.web.embedded.jetty.JettyWebServer  : Jetty started on port(s) 8090 (http/1.1) with context path '/'
2022-11-08 23:58:13.476  INFO 7 --- [           main] run.halo.app.Application                 : Started Application in 10.703 seconds (JVM running for 11.773)
2022-11-08 23:58:13.477  INFO 7 --- [           main] run.halo.app.listener.StartedListener    : Starting migrate database...
2022-11-08 23:58:13.555  INFO 7 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 7.15.0 by Redgate
2022-11-08 23:58:13.556  INFO 7 --- [           main] o.f.c.i.database.base.BaseDatabaseType   : Database: jdbc:h2:file:/root/.halo//db/halo (H2 1.4)
2022-11-08 23:58:13.605  INFO 7 --- [           main] o.f.core.internal.command.DbRepair       : Successfully repaired schema history table "PUBLIC"."flyway_schema_history" (execution time 00:00.030s).
2022-11-08 23:58:13.606  INFO 7 --- [           main] o.f.core.internal.command.DbRepair       : Manual cleanup of the remaining effects of the failed migration may still be required.
2022-11-08 23:58:13.609  INFO 7 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 7.15.0 by Redgate
2022-11-08 23:58:13.618  INFO 7 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 10 migrations (execution time 00:00.006s)
2022-11-08 23:58:13.628  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": 5
2022-11-08 23:58:13.639  INFO 7 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version "6 - migrate create contents table"
2022-11-08 23:58:13.652 ERROR 7 --- [           main] o.f.core.internal.command.DbMigrate      : Migration of schema "PUBLIC" to version "6 - migrate create contents table" failed! Please restore backups and roll back database and code!
2022-11-08 23:58:13.668  INFO 7 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-11-08 23:58:13.686 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V6__migrate_create_contents_table.sql failed
------------------------------------------------------
SQL State  : 23505
Error Code : 23505
Message    : Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [2, TIMESTAMP '2019-12-24 17:04:50.232', TIMESTAMP '2020-03-18 16:21:43.948', SPACE(4104 /* table: 70 id: 501700 */), 2, SPACE(3922 /* table: 70 id: 501701 */), 2, 0]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
Location   : migration/V6__migrate_create_contents_table.sql (/application/BOOT-INF/classes/migration/V6__migrate_create_contents_table.sql)
Line       : 2
Statement  : -- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:271) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:243) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:103) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:219) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:170) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:586) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:170) ~[flyway-core-7.15.0.jar:na]
	at run.halo.app.listener.StartedListener.migrate(StartedListener.java:123) ~[classes/:1.6.0]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:76) ~[classes/:1.6.0]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:47) ~[classes/:1.6.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:105) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.12.jar:2.5.12]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:75) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) ~[spring-boot-2.5.12.jar:2.5.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.12.jar:2.5.12]
	at run.halo.app.Application.main(Application.java:21) ~[classes/:1.6.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[application/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application/:na]
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V6__migrate_create_contents_table.sql failed
------------------------------------------------------
SQL State  : 23505
Error Code : 23505
Message    : Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [2, TIMESTAMP '2019-12-24 17:04:50.232', TIMESTAMP '2020-03-18 16:21:43.948', SPACE(4104 /* table: 70 id: 501700 */), 2, SPACE(3922 /* table: 70 id: 501701 */), 2, 0]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
Location   : migration/V6__migrate_create_contents_table.sql (/application/BOOT-INF/classes/migration/V6__migrate_create_contents_table.sql)
Line       : 2
Statement  : -- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:277) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:224) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:128) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:78) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:67) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:66) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370) ~[flyway-core-7.15.0.jar:na]
	... 42 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.CONTENTS(POST_ID) [2, TIMESTAMP '2019-12-24 17:04:50.232', TIMESTAMP '2020-03-18 16:21:43.948', SPACE(4104 /* table: 70 id: 501700 */), 2, SPACE(3922 /* table: 70 id: 501701 */), 2, 0]"; SQL statement:
-- Migrate post content to contents table
INSERT INTO contents(post_id, status, patch_log_id, head_patch_log_id, content, original_content, create_time,
                     update_time)
SELECT id,
       status,
       id,
       id,
       format_content,
       original_content,
       create_time,
       update_time
FROM posts [23505-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.mvstore.db.MVPrimaryIndex.add(MVPrimaryIndex.java:131) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:546) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.command.dml.Insert.addRowImpl(Insert.java:251) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.command.dml.Insert.insertRows(Insert.java:207) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.command.dml.Insert.update(Insert.java:132) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.command.CommandContainer.update(CommandContainer.java:133) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.command.Command.executeUpdate(Command.java:267) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233) ~[h2-1.4.199.jar:1.4.199]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205) ~[h2-1.4.199.jar:1.4.199]
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111) ~[flyway-core-7.15.0.jar:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:212) ~[flyway-core-7.15.0.jar:na]
	... 48 common frames omitted

2022-11-08 23:58:13.699  INFO 7 --- [           main] o.e.jetty.server.AbstractConnector       : Stopped ServerConnector@68631b1d{HTTP/1.1, (http/1.1)}{0.0.0.0:8090}
2022-11-08 23:58:13.699  INFO 7 --- [           main] org.eclipse.jetty.server.session         : node0 Stopped scavenging
2022-11-08 23:58:13.701  INFO 7 --- [           main] o.e.j.s.h.ContextHandler.application     : Destroying Spring FrameworkServlet 'dispatcherServlet'
2022-11-08 23:58:13.702  INFO 7 --- [           main] o.e.jetty.server.handler.ContextHandler  : Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@5ca8157c{application,/,[file:///tmp/jetty-docbase.8090.12660548962012114809/, jar:file:/application/BOOT-INF/lib/springfox-swagger-ui-3.0.0.jar!/META-INF/resources],STOPPED}
2022-11-08 23:58:13.719  INFO 7 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-11-08 23:58:13.721  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-11-08 23:58:13.730  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/1765

**Comment by war3sxkcs** [comment]
回顾了#1765等绑定的相关问题，解决方案都是打开约束表删除其中的几行再重启即可。

![image](https://user-images.githubusercontent.com/26081968/200893530-f26df597-91c3-400a-a61d-2e6c5b25667c.png)
但是我通过H2的工具去链接数据库的时候报错 [ Unsupported database file version or invalid file header ] 。

因为我是服务器迁移，所以有最开始的备份文件，之前出错是从1.4.2跳跃直接到1.6.0 ；我拿干净的备份文件，从1.4.2重启，再到1.5.0重启，再到1.6.0重启均成功。现已经解决
