### ISSUE TITLE
Halo 2.0-rc.1 启动时的错误

### ISSUE THREAD

**Issue by LeviMarvin** [halo-dev/halo#2784]
### 是什么版本出现了此问题？

2.0.0-rc.1

### 使用的什么数据库？

Other

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://lmsite.eu.org

### 发生了什么？

使用 docker-compose 安装完后启动时，若非全新安装（数据库中有数据）则会出现此错误，删除报错的项，重启后无该项的错误且会自动生成该项，但只要该项存在就会有此错误。

### 相关日志输出

```shell
halo_next  | org.springframework.dao.OptimisticLockingFailureException: Failed to update table [extensions]; Version does not match for row with Id [/registry/roles/anonymous]
halo_next  | 	at org.springframework.data.r2dbc.core.R2dbcEntityTemplate.lambda$doUpdate$13(R2dbcEntityTemplate.java:636) ~[spring-data-r2dbc-3.0.0-RC2.jar:3.0.0-RC2]
halo_next  | 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:268) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2168) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2168) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:531) ~[reactor-pool-1.0.0.jar:1.0.0]
halo_next  | 	at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:761) ~[reactor-pool-1.0.0.jar:1.0.0]
halo_next  | 	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:873) ~[reactor-pool-1.0.0.jar:1.0.0]
halo_next  | 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.0.jar:3.5.0]
halo_next  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.5.0.jar:3.5.0]
```

### 附加信息

数据库：MariaDB 10.8

**Comment by guqing** [comment]
感谢你的反馈 不过此错误为乐观锁冲突提示，非系统功能性问题，系统会自动重试以自愈。

**Comment by JohnNiang** [comment]
确实在更新数据的时候发生了以上错误，不过我们会重试操作的，直到成功。这个错误完全可以忽略掉。不过为了减少这个错误我会尝试优化一下。

/assign

**Comment by minliacom** [comment]
嗯，这里reconciler会一直重试直到成功，但是于用户侧来看这里报出了错误就会认为是有什么问题。我在本地做了一下尝试，效果还不错，看看这样有没有问题：

```
} catch (Throwable t) {
                        if (t instanceof OptimisticLockingFailureException) {
                            log.debug(
                                "Optimistic locking failure when reconciling request: {}",
                                t.getMessage());
                        } else {
                            log.error("Reconciler in " + this.name
                                    + " aborted with an error, re-enqueuing...",
                                t);
                        }
                        result = new Reconciler.Result(true, null);
                    } finally {
                        queue.done(entry.getEntry());
                    }
```
