### ISSUE TITLE
似乎在windows docker中无法上传主题

### ISSUE THREAD

**Issue by Sincejunly** [halo-dev/halo#2821]
### 是什么版本出现了此问题？

2.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

www.homura.top:8090 管理密码是默认的

### 发生了什么？

unload error 

### 相关日志输出

```shell
visits.log文件为空，以下是docker日志

2022-12-02 01:31:14             at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:14             at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:14             at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
2022-12-02 01:31:14             at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
2022-12-02 01:31:14             at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
2022-12-02 01:31:14             at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
2022-12-02 01:31:14             at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2022-12-02 01:31:14 
2022-12-02 01:31:19 2022-12-02T01:31:19.720+08:00 ERROR 7 --- [oundedElastic-2] h.a.i.e.h.GlobalErrorWebExceptionHandler : The [theme.yaml] does not conform to the theme specification.
2022-12-02 01:31:19 
2022-12-02 01:31:19 java.lang.IllegalArgumentException: The [theme.yaml] does not conform to the theme specification.
2022-12-02 01:31:19     at run.halo.app.core.extension.theme.ThemeUtils.loadThemeManifest(ThemeUtils.java:139) ~[classes/:2.0.0]
2022-12-02 01:31:19     Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
2022-12-02 01:31:19 Error has been observed at the following site(s):
2022-12-02 01:31:19     *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ LoginPageGeneratingWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
2022-12-02 01:31:19     *__checkpoint ⇢ HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install" [ExceptionHandlingWebHandler]
2022-12-02 01:31:19 Original Stack Trace:
2022-12-02 01:31:19             at run.halo.app.core.extension.theme.ThemeUtils.loadThemeManifest(ThemeUtils.java:139) ~[classes/:2.0.0]
2022-12-02 01:31:19             at run.halo.app.core.extension.theme.ThemeUtils.lambda$unzipThemeTo$9(ThemeUtils.java:116) ~[classes/:2.0.0]
2022-12-02 01:31:19             at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:19             at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:19             at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:19             at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:19             at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:19             at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:19             at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:19             at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.0.jar:3.5.0]
2022-12-02 01:31:19             at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
2022-12-02 01:31:19             at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
2022-12-02 01:31:19             at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
2022-12-02 01:31:19             at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
2022-12-02 01:31:19             at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2022-12-02 01:31:19
```
```

**Comment by Sincejunly** [comment]
![error](https://user-images.githubusercontent.com/96775034/205123729-286b6e9a-d748-483b-b606-6d8e6ab2ebc7.png)

**Comment by JohnNiang** [comment]
建议参考：https://github.com/halo-sigs/awesome-halo#%E4%B8%BB%E9%A2%98

**Comment by ruibaby** [comment]
@Sincejunly 此问题是否又得到解决呢？

**Comment by Sincejunly** [comment]
> @Sincejunly 此问题是否有得到解决呢？

我觉得已经解决了，不过我目前没有测试感谢解答

**Comment by Sincejunly** [comment]
> @Sincejunly 此问题是否有得到解决呢？

静候更新

**Comment by Sincejunly** [comment]
> @Sincejunly 这个主题我测试过 next 分支，是没有问题的。

额 我找了半天，没找到
