### ISSUE TITLE
本地以源码方式启动Halo项目，安装插件时插件无法启用

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2842]
### 是什么版本出现了此问题？

2.0.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

本地以源码方式启动Halo项目，安装插件时插件无法启用

### 相关日志输出

```shell
2022-12-05 17:15:25.032 ERROR run.halo.app.extension.controller.DefaultController Line:170 - Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
java.lang.IllegalArgumentException: Unknown pluginId PluginUnsplash
	at org.pf4j.AbstractPluginManager.checkPluginId(AbstractPluginManager.java:489)
	at run.halo.app.plugin.HaloPluginManager.doStartPlugin(HaloPluginManager.java:223)
	at run.halo.app.plugin.HaloPluginManager.startPlugin(HaloPluginManager.java:214)
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startPlugin$4(PluginReconciler.java:142)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at run.halo.app.core.extension.reconciler.PluginReconciler.startPlugin(PluginReconciler.java:139)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:114)
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:64)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:58)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:42)
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:162)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-12-05 17:15:25.045 DEBUG run.halo.app.extension.controller.DefaultController Line:157 - run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 >>> Reconciling request Request[name=PluginUnsplash] at 2022-12-05T09:15:25.045324Z
2022-12-05 17:15:25.056 DEBUG run.halo.app.extension.controller.DefaultDelayQueue Line:35  - Adding request Request[name=PluginUnsplash] immediately
2022-12-05 17:15:25.060 ERROR run.halo.app.extension.controller.DefaultController Line:170 - Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
java.lang.IllegalArgumentException: Unknown pluginId PluginUnsplash
	at org.pf4j.AbstractPluginManager.checkPluginId(AbstractPluginManager.java:489)
	at run.halo.app.plugin.HaloPluginManager.doStartPlugin(HaloPluginManager.java:223)
	at run.halo.app.plugin.HaloPluginManager.startPlugin(HaloPluginManager.java:214)
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startPlugin$4(PluginReconciler.java:142)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at run.halo.app.core.extension.reconciler.PluginReconciler.startPlugin(PluginReconciler.java:139)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:114)
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:64)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:58)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:42)
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:162)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-12-05 17:15:25.081 DEBUG run.halo.app.extension.controller.DefaultController Line:157 - run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 >>> Reconciling request Request[name=PluginUnsplash] at 2022-12-05T09:15:25.081209Z
2022-12-05 17:15:25.089 DEBUG run.halo.app.extension.controller.DefaultDelayQueue Line:35  - Adding request Request[name=PluginUnsplash] immediately
```

**Comment by minliacom** [comment]
好的， 我先改为prod模式试试看

**Comment by minliacom** [comment]
改为 deployment 就可以了 感谢啊 折腾一晚上都没搞好 哈哈哈 关了关了
