### ISSUE TITLE
在文章较多时启动会导致很长时间加载缓慢

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2863]
### 是什么版本出现了此问题？

2.0.0

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://demo.halo.run

### 发生了什么？

当文章较多（本测试有 1000 篇 1w 字的的文章）时，会导致在启动的较长时间里，系统执行缓慢，尤其是文章列表。观测日志发现运行 reconcile 的时间比较长，在运行 reconcile 的时候就会导致这个问题，请看日志：

开始运行 reconcile 时：

```
halo      | 2022-12-06T21:35:11.358+08:00  INFO 7 --- [           main] run.halo.app.Application                 : Started Application in 3.444 seconds (process running for 3.711)
halo      | 2022-12-06T21:35:11.702+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Starting controller garbage-collector-controller
halo      | 2022-12-06T21:35:11.702+08:00  INFO 7 --- [-controller-t-1] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-1 started
halo      | 2022-12-06T21:35:11.710+08:00  INFO 7 --- [-controller-t-2] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-2 started
halo      | 2022-12-06T21:35:11.711+08:00  INFO 7 --- [-controller-t-3] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-3 started
halo      | 2022-12-06T21:35:11.730+08:00  INFO 7 --- [-controller-t-5] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-5 started
halo      | 2022-12-06T21:35:11.734+08:00  INFO 7 --- [-controller-t-6] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-6 started
halo      | 2022-12-06T21:35:11.735+08:00  INFO 7 --- [-controller-t-7] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-7 started
halo      | 2022-12-06T21:35:11.735+08:00  INFO 7 --- [-controller-t-8] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-8 started
halo      | 2022-12-06T21:35:11.735+08:00  INFO 7 --- [-controller-t-9] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-9 started
halo      | 2022-12-06T21:35:11.736+08:00  INFO 7 --- [controller-t-10] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-10 started
halo      | 2022-12-06T21:35:11.738+08:00  INFO 7 --- [-controller-t-4] r.h.a.e.controller.DefaultController     : Controller worker garbage-collector-controller-worker-4 started
halo      | 2022-12-06T21:35:11.741+08:00 DEBUG 7 --- [           main] r.h.app.infra.DefaultThemeInitializer    : Skipped initializing default theme because there are themes inside theme root
halo      | 2022-12-06T21:35:11.744+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Starting controller run.halo.app.core.extension.reconciler.CategoryReconciler
halo      | 2022-12-06T21:35:11.748+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Starting controller run.halo.app.core.extension.reconciler.CommentReconciler
halo      | 2022-12-06T21:35:11.749+08:00  INFO 7 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : Controller worker run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 started
```

运行 reconcile 完成之后的日志：

```
halo      | 2022-12-06T21:48:19.442+08:00 DEBUG 7 --- [actor-tcp-nio-1] r.h.a.e.r.selector.SelectorConverter     : Resolving selector: content.halo.run/deleted=false with operator: NotEquals
halo      | 2022-12-06T21:48:19.442+08:00 DEBUG 7 --- [actor-tcp-nio-1] r.h.a.e.r.selector.SelectorConverter     : Resolving selector: content.halo.run/deleted=false with operator: IN
halo      | 2022-12-06T21:48:19.442+08:00 DEBUG 7 --- [actor-tcp-nio-1] r.h.a.e.r.selector.SelectorConverter     : Resolving selector: content.halo.run/deleted=false with operator: Equals
halo      | 2022-12-06T21:48:21.745+08:00 DEBUG 7 --- [mReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.MenuItemReconciler-worker-1 >>> Reconciling request Request[name=35869bd3-33b5-448b-91ee-cf6517a59644] at 2022-12-06T13:48:21.745777002Z
halo      | 2022-12-06T21:48:21.749+08:00 DEBUG 7 --- [mReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.MenuItemReconciler-worker-1 >>> Reconciled request: Request[name=35869bd3-33b5-448b-91ee-cf6517a59644] with result: Result[reEnqueue=true, retryAfter=PT1M]
```

一共大概 13 分钟。

运行 reconcile 时，文章列表接口和首页渲染时长：

<img width="1588" alt="image" src="https://user-images.githubusercontent.com/21301288/205928957-ef75d63e-ce58-4fcd-9e4a-b64a43df4cb7.png">
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/21301288/205928978-1f692878-2251-4fab-a446-6f6114b42c75.png">

运行 reconcile 结束后：

<img width="1589" alt="image" src="https://user-images.githubusercontent.com/21301288/205929703-ae906d6b-5f98-4485-9aa6-6da1acc28d05.png">
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/21301288/205929749-1978d4dd-4ce0-46b9-853a-af74bd4b9b20.png">

系统配置详情：

```
            .-/+oossssoo+/-.               ryanwang@ryanwang-linux 
        `:+ssssssssssssssssss+:`           ----------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.1 LTS aarch64 
    .ossssssssssssssssssdMMMNysssso.       Host: Parallels ARM Virtual Machine 0.1 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-56-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 21 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1787 (dpkg), 15 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8.1 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3840x2160 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.5 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: (2) 
    .ossssssssssssssssssdMMMNysssso.       GPU: 00:0a.0 Red Hat, Inc. Virtio GPU 
      -+sssssssssssssssssyyyssss+-         Memory: 4616MiB / 7929MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   
```

> 需要注意的是，系统运行缓慢仅在运行 reconcile 的时候会发生，reconcile 运行完成之后正常。

期望能对此进行优化。

/kind improvement
/area core
/priority important-longterm

**Comment by ruibaby** [comment]
可以下载 https://halo.run/upload/2022/12/halo-2863.zip 进行测试。直接用 Docker Compose 启动即可，管理员账号密码为：admin / halohalo

**Comment by JohnNiang** [comment]
### 结论

经过一段时间排查，“随着文章数量的增加，页面访问速度变慢”的主要是 Reconciler 频繁地访问数据库以及 list 全量数据导致的。

Reconciler 频繁访问数据库（频繁更新数据，全量查询数据库），导致数据库和 Halo 之间的网络传输压力增加。

数据的每次 List 查询都是全量的，即使添加了过滤条件。这样也会增加网络传输压力。

### 测试场景：

- Halo: 2.2.0-SNAPSHOT
- 数据库：H2（其他数据库延迟太高，不方便测试）

### 测试结果如下：

- 不同文章数量的场景文章列表查询耗时

| 文章数量 | posts list 用时 |
|------|---------------|
| 10   | 3ms/5ms       |
| 100  | 13ms/23ms     |
| 1000 | 115ms/150ms   |

- 访问文章首页所需要的查询结果

> 以下日志是在 1000 篇文章的场景下的结果。

```log
FetchBy/registry/configmaps/system-default usage: 4ms
[e88a0c73-4] View name 'index', model {posts=Mono.map ⇢ at run.halo.app.theme.router.strategy.IndexRouteStrategy.postList(IndexRouteStrategy.java:42), _templateId=index, thymeleafWebSession=Mono.cache ⇢ at org.springframework.web.server.adapter.DefaultServerWebExchange.<init>(DefaultServerWebExchange.java:131), thymeleafWebExchangePrincipal=Mono.map ⇢ at org.springframework.security.web.server.context.SecurityContextServerWebExchange.getPrincipal(SecurityContextServerWebExchange.java:47), _csrf=Mono.doOnSuccess ⇢ at org.thymeleaf.extras.springsecurity6.dialect.SpringSecurityDialect.lambda$static$2(SpringSecurityDialect.java:104), thymeleafSpringSecurityContext=Mono.flatMap ⇢ at org.springframework.security.core.context.ReactiveSecurityContextHolder.getContext(ReactiveSecurityContextHolder.java:48)}
FetchBy/registry/configmaps/system usage: 2ms
FetchBy/registry/configmaps/system-default usage: 2ms
FetchBy/registry/configmaps/system usage: 3ms
ListBy/registry/content.halo.run/posts usage: 90ms
ListBy/registry/content.halo.run/posts usage: 168ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100999 usage: 2ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100999 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100998 usage: 0ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100998 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100997 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 0ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100997 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100996 usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100996 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100995 usage: 0ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100995 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100994 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100994 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100993 usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100993 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100992 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100992 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100991 usage: 2ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100991 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100990 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100990 usage: 1ms
FetchBy/registry/configmaps/system-default usage: 1ms
FetchBy/registry/configmaps/system usage: 1ms
FetchBy/registry/configmaps/system-default usage: 1ms
FetchBy/registry/configmaps/system usage: 1ms
FetchBy/registry/theme.halo.run/themes/theme-earth usage: 1ms
FetchBy/registry/configmaps/theme-earth-configMap usage: 1ms
FetchBy/registry/configmaps/system-default usage: 2ms
FetchBy/registry/configmaps/system usage: 2ms
FetchBy/registry/configmaps/system-default usage: 2ms
FetchBy/registry/configmaps/system usage: 3ms
FetchBy/registry/configmaps/system-default usage: 1ms
FetchBy/registry/configmaps/system usage: 1ms
ListBy/registry/menuitems usage: 3ms
ListBy/registry/menus usage: 2ms
FetchBy/registry/configmaps/system-default usage: 1ms
FetchBy/registry/configmaps/system usage: 1ms
FetchBy/registry/users/anonymousUser usage: 1ms
ListBy/registry/content.halo.run/categories usage: 1ms
ListBy/registry/content.halo.run/posts usage: 154ms
ListBy/registry/content.halo.run/posts usage: 75ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100999 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100999 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100998 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100998 usage: 0ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100997 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100997 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100996 usage: 2ms
FetchBy/registry/users/admin usage: 3ms
FetchBy/registry/users/admin usage: 3ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100996 usage: 3ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100995 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100995 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100994 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 0ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100994 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100993 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 0ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100993 usage: 3ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100992 usage: 3ms
FetchBy/registry/users/admin usage: 3ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100992 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100991 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100991 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100990 usage: 0ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100990 usage: 1ms
ListBy/registry/content.halo.run/categories usage: 4ms
ListBy/registry/content.halo.run/tags usage: 3ms
ListBy/registry/content.halo.run/tags usage: 2ms
```

- 访问某篇文章所需要的查询

> 以下日志是在 1000 篇文章的场景下的结果。

```log
FetchBy/registry/content.halo.run/posts/100000 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100000 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/content.halo.run/posts/100000 usage: 1ms
FetchBy/registry/content.halo.run/snapshots/d1badd0d-3d5a-455e-9085-88ef0df8fca4 usage: 2ms
ListBy/registry/content.halo.run/snapshots usage: 44ms
FetchBy/registry/configmaps/system-default usage: 2ms
[026a3ba9-6] View name 'post', model {plural=posts, _templateId=post, post=PostVo(content=ContentVo(raw=null, content=null)), name=100000, slug=2019090414074529603, groupVersionKind=content.halo.run/v1alpha1/Post, thymeleafWebSession=Mono.cache ⇢ at org.springframework.web.server.adapter.DefaultServerWebExchange.<init>(DefaultServerWebExchange.java:131), thymeleafWebExchangePrincipal=Mono.map ⇢ at org.springframework.security.web.server.context.SecurityContextServerWebExchange.getPrincipal(SecurityContextServerWebExchange.java:47), _csrf=Mono.doOnSuccess ⇢ at org.thymeleaf.extras.springsecurity6.dialect.SpringSecurityDialect.lambda$static$2(SpringSecurityDialect.java:104), thymeleafSpringSecurityContext=Mono.flatMap ⇢ at org.springframework.security.core.context.ReactiveSecurityContextHolder.getContext(ReactiveSecurityContextHolder.java:48)}
FetchBy/registry/configmaps/system usage: 2ms
FetchBy/registry/configmaps/system-default usage: 1ms
FetchBy/registry/configmaps/system usage: 1ms
FetchBy/registry/configmaps/system-default usage: 2ms
FetchBy/registry/configmaps/system usage: 1ms
FetchBy/registry/theme.halo.run/themes/theme-earth usage: 0ms
FetchBy/registry/configmaps/theme-earth-configMap usage: 1ms
FetchBy/registry/content.halo.run/posts/100000 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100000 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/content.halo.run/posts/100000 usage: 1ms
FetchBy/registry/content.halo.run/snapshots/d1badd0d-3d5a-455e-9085-88ef0df8fca4 usage: 1ms
ListBy/registry/content.halo.run/snapshots usage: 89ms
FetchBy/registry/configmaps/system-default usage: 4ms
FetchBy/registry/configmaps/system usage: 4ms
FetchBy/registry/configmaps/system-default usage: 3ms
FetchBy/registry/configmaps/system usage: 2ms
FetchBy/registry/configmaps/system-default usage: 2ms
FetchBy/registry/configmaps/system usage: 2ms
ListBy/registry/menuitems usage: 21ms
ListBy/registry/menus usage: 13ms
FetchBy/registry/configmaps/system-default usage: 4ms
FetchBy/registry/configmaps/system usage: 2ms
FetchBy/registry/users/anonymousUser usage: 3ms
ListBy/registry/content.halo.run/posts usage: 100ms
FetchBy/registry/content.halo.run/posts/100000 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100000 usage: 2ms
FetchBy/registry/users/admin usage: 3ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/content.halo.run/posts/100000 usage: 2ms
FetchBy/registry/content.halo.run/snapshots/d1badd0d-3d5a-455e-9085-88ef0df8fca4 usage: 2ms
ListBy/registry/content.halo.run/snapshots usage: 68ms
FetchBy/registry/content.halo.run/posts/100002 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100002 usage: 2ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/users/admin usage: 3ms
FetchBy/registry/content.halo.run/posts/100002 usage: 3ms
FetchBy/registry/content.halo.run/snapshots/5a2eb526-e661-43d2-a131-d1aafe651221 usage: 1ms
ListBy/registry/content.halo.run/snapshots usage: 63ms
FetchBy/registry/content.halo.run/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/5152aea5-c2e8-4717-8bba-2263d46e19d5 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/content.halo.run/tags/c33ceabb-d8f1-4711-8991-bb8f5c92ad7c usage: 1ms
FetchBy/registry/content.halo.run/categories/76514a40-6ef1-4ed9-b58a-e26945bde3ca usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/content.halo.run/posts/5152aea5-c2e8-4717-8bba-2263d46e19d5 usage: 1ms
FetchBy/registry/content.halo.run/snapshots/dbd70cfd-b3b6-473c-add5-825ee2205d48 usage: 4ms
ListBy/registry/content.halo.run/snapshots usage: 57ms
ListBy/registry/content.halo.run/posts usage: 103ms
ListBy/registry/content.halo.run/posts usage: 104ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100999 usage: 2ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100999 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100998 usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100998 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100997 usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100997 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100996 usage: 1ms
FetchBy/registry/users/admin usage: 0ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100996 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100995 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100995 usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100994 usage: 2ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100994 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100993 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100993 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100992 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100992 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100991 usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/users/admin usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100991 usage: 1ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100990 usage: 1ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/users/admin usage: 2ms
FetchBy/registry/metrics.halo.run/counters/posts.content.halo.run/100990 usage: 0ms
ListBy/registry/content.halo.run/categories usage: 2ms
ListBy/registry/content.halo.run/tags usage: 3ms
ListBy/registry/content.halo.run/tags usage: 3ms
FetchBy/registry/roles/anonymous usage: 2ms
```

### 可能的解决方案

- 缓存 List 数据
    - 优点：List 数据的延迟将大大降低
    - 缺点：消耗更多的内存，且不好保证数据的一致性
- 优化 Reconciler 逻辑
    - 优点：减少 List 查询，降低数据库网络传输压力
    - 缺点：定位需要优化的 List 查询比较困难

**Comment by guqing** [comment]
有些 List 查询可能无法避免，是否需要在下个版本优先考虑建立索引的问题，比如获取某篇文章的所有 Snapshot 记录，获取评论下的回复等，这些 List 查询每次 Reconcile 时都会扫一次表很耗时且浪费。

如果能提供建立索引关系的能力，比如文章 A 关联了 S1...S5 条 SnapShot 有映射关系，则 List 时可以一次得到 names 在 get 会快很多。如果索引还能持久化比如到一个新表或者用 rocksdb 等，那么启动时 Reconciler 的执行就不会阻塞主题端的访问，Reconciler 会慢慢去更新数据或索引。

**Comment by li-guohao** [comment]
没想到`All in one`的性能问题这么快就出现了，
我看源码里，自定义的数据模型Extension里，是直接将整个对象通过jackon的ObjectMapper转成字节数组的
https://github.com/halo-dev/halo/blob/main/src/main/java/run/halo/app/extension/JSONExtensionConverter.java

我的提供下我的优化思路
- 逻辑层面还是 `All in one`，提供的这些接口 `ReactiveExtensionClient` 和 `ExtensionClient` 并不需要变化，
底层可以把一张表拆成多张，将一些固定的字段(比如`Metadata`的)设置成表的列名，在具体的实现层面，针对查询做优化，比如针对经常查询的列加索引啥的
- 不严格使用`All in one`的这种方式，把一些预估单表数据量比较大的比如文章，单独使用一张表进行存储，然后定义接口供插件调用。(这也是我们目前在用的方式，我们目前参考halo设计了自定义模型，`All in one` 就是爽，但是我们的自定义模型计划只用在单表数据量不大的模型上，数据量大的都是单独建表，再提供调用接口，具体可以参考：[Ikaros Entities](https://github.com/ikaros-dev/ikaros/tree/master/src/main/java/run/ikaros/server/store/entity) 和 [Ikaros Custom](https://github.com/ikaros-dev/ikaros/tree/master/src/main/java/run/ikaros/server/custom))

**Comment by JohnNiang** [comment]
在 Halo 2.6 中，已经优化了 PostReconciler，减少了数据库查询次数。具体可参考：<https://github.com/halo-dev/halo/pull/3877>。

Hi @ruibaby ，可以验证一下问题是否还存在呢？

**Comment by ruibaby** [comment]
> 在 Halo 2.6 中，已经优化了 PostReconciler，减少了数据库查询次数。具体可参考：#3877。
> 
> Hi @ruibaby ，可以验证一下问题是否还存在呢？

使用相同的数据（<https://halo.run/upload/2022/12/halo-2863.zip>）进行测试，使用 2.10.0 确实会有量级的提升。

正在进行 reconcile 的时候：

<img width="1851" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/720df627-1b5a-4a51-a140-a883831885d1">
<img width="1863" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/29375572-880e-4da0-bd07-886e3f364e76">

**Comment by JohnNiang** [comment]
当前 Issue 即将被关闭。如果有任何问题请随时重新打开。

/close
/unassign
