### ISSUE TITLE
当以开发模式启动halo项目时 plugins-root 下的插件没有启动

### ISSUE THREAD

**Issue by minliacom** [halo-dev/halo#2908]
### 是什么版本出现了此问题？

2.0.1-SNAPSHOT

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 发生了什么？

当以开发模式启动halo项目时 plugins-root 下的插件没有正常启动

报错： Unknown pluginId halo-plugin-email

可能会出现安装同一个插件的情况

### 相关日志输出

```shell
2022-12-09 18:21:20.733 DEBUG run.halo.app.extension.controller.DefaultController Line:157 - run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 >>> Reconciling request Request[name=halo-plugin-email] at 2022-12-09T10:21:20.733962Z
2022-12-09 18:21:20.741 DEBUG run.halo.app.extension.controller.DefaultDelayQueue Line:35  - Adding request Request[name=halo-plugin-email] immediately
2022-12-09 18:21:20.743 ERROR run.halo.app.extension.controller.DefaultController Line:170 - Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
java.lang.IllegalArgumentException: Unknown pluginId halo-plugin-email
	at org.pf4j.AbstractPluginManager.checkPluginId(AbstractPluginManager.java:489)
	at run.halo.app.plugin.HaloPluginManager.doStartPlugin(HaloPluginManager.java:223)
	at run.halo.app.plugin.HaloPluginManager.startPlugin(HaloPluginManager.java:214)
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startPlugin$4(PluginReconciler.java:142)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at run.halo.app.core.extension.reconciler.PluginReconciler.startPlugin(PluginReconciler.java:139)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:114)
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:64)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:58)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:42)
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:162)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-12-09 18:21:25.864 DEBUG run.halo.app.extension.controller.DefaultController Line:157 - run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 >>> Reconciling request Request[name=halo-plugin-email] at 2022-12-09T10:21:25.864861Z
2022-12-09 18:21:25.873 DEBUG run.halo.app.extension.controller.DefaultDelayQueue Line:35  - Adding request Request[name=halo-plugin-email] immediately
2022-12-09 18:21:25.875 ERROR run.halo.app.extension.controller.DefaultController Line:170 - Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
java.lang.IllegalArgumentException: Unknown pluginId halo-plugin-email
	at org.pf4j.AbstractPluginManager.checkPluginId(AbstractPluginManager.java:489)
	at run.halo.app.plugin.HaloPluginManager.doStartPlugin(HaloPluginManager.java:223)
	at run.halo.app.plugin.HaloPluginManager.startPlugin(HaloPluginManager.java:214)
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startPlugin$4(PluginReconciler.java:142)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at run.halo.app.core.extension.reconciler.PluginReconciler.startPlugin(PluginReconciler.java:139)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:114)
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:64)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:58)
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:42)
```

**Comment by guqing** [comment]
目前以开发模式启动时只会加载项目目录而非 jar所以无法启动 plugins root下的jar，除非将插件启动模式绑定到每一个插件而非全局配置，这还要考虑 plugins 目录下和开发模式都存在同一个插件的问题。后续可以考虑优化它，但优先级不高

**Comment by JohnNiang** [comment]
> 目前以开发模式启动时只会加载项目目录而非 jar所以无法启动 plugins root下的jar，除非将插件启动模式绑定到每一个插件而非全局配置，这还要考虑 plugins 目录下和开发模式都存在同一个插件的问题。后续可以考虑优化它，但优先级不高

期望开发模式下也能支持 Jar 包安装插件。我这里提供两个建议：

- 如果系统中已经存在了正在开发的插件，建议直接报错。
- 通过开发模式安装的插件建议添加一个“开发模式”标识。
