### ISSUE TITLE
打包成jar后运行报错，读不到资源主题文件

### ISSUE THREAD

**Issue by sissie-cc** [halo-dev/halo#2910]
### What is version of Halo has the issue?

2.0

### What database are you using?

H2

### What is your deployment method?

Docker

### What happened?

编译打包成jar后运行报错，读不到资源主题文件

java.nio.file.FileSystemNotFoundException: null
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:173) ~[jdk.zipfs:na]
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:159) ~[jdk.zipfs:na]
        at java.base/java.nio.file.Path.of(Path.java:208) ~[na:na]
        at run.halo.app.infra.DefaultThemeInitializer.onApplicationEvent(DefaultThemeInitializer.java:52) ~[classes!/:2.0.1-SNAPSHOT]
        at run.halo.app.infra.DefaultThemeInitializer.onApplicationEvent(DefaultThemeInitializer.java:17) ~[classes!/:2.0.1-SNAPSHOT]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar!/:6.0.2]
        at run.halo.app.infra.SchemeInitializer.onApplicationEvent(SchemeInitializer.java:79) ~[classes!/:2.0.1-SNAPSHOT]
        at run.halo.app.infra.SchemeInitializer.onApplicationEvent(SchemeInitializer.java:34) ~[classes!/:2.0.1-SNAPSHOT]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:103) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:76) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:76) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at run.halo.app.Application.main(Application.java:25) ~[classes!/:2.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[halo-2.0.2-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[halo-2.0.2-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[halo-2.0.2-SNAPSHOT.jar:2.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[halo-2.0.2-SNAPSHOT.jar:2.0.1-SNAPSHOT]

**Comment by sissie-cc** [comment]
classpath:themes/theme-earth.zip

**Comment by sissie-cc** [comment]
jar包下确实是有这个目录的

**Comment by sissie-cc** [comment]
![image](https://user-images.githubusercontent.com/13584809/206867849-50aa0965-3205-4e85-9fe6-f55719582ff1.png)

**Comment by sissie-cc** [comment]
2022-12-11T01:20:58.896+08:00  INFO 2262 --- [           main] r.h.app.infra.DefaultThemeInitializer    : Initializing default theme from classpath:themes/theme-earth.zip

**Comment by ruibaby** [comment]
可以复现。

/area core
/kind bug

**Comment by Reallyone** [comment]
这个问题是需要怎么解决？我现在还没有研究明白！！！

**Comment by ruibaby** [comment]
> 这个问题是需要怎么解决？我现在还没有研究明白！！！

这是一个 bug，需要等待修复。

**Comment by minliacom** [comment]
如果可以，我愿意来尝试修复一下

**Comment by Reallyone** [comment]
远程么？


***@***.***
 
发件人： will
发送时间： 2022-12-17 20:03
收件人： halo-dev/halo
抄送： stormXu; Comment
主题： Re: [halo-dev/halo] 打包成jar后运行报错，读不到资源主题文件 (Issue #2910)
如果可以，我愿意来尝试修复一下

**Comment by minliacom** [comment]
在本地做了些验证，可以在 `DefaultThemeInitializer中` 使用
 `PathMatchingResourcePatternResolver resolver =
                new PathMatchingResourcePatternResolver();` 

可以兼容在jar包，开发环境等不同场景的文件读取操作，并在下面使用
`themeService.install(resolver.getResource(location).getInputStream())`
进行安装，如有不妥当欢迎指正。

**Comment by minliacom** [comment]
> 远程么？ ***@***.*** 发件人： will 发送时间： 2022-12-17 20:03 收件人： halo-dev/halo 抄送： stormXu; Comment 主题： Re: [halo-dev/halo] 打包成jar后运行报错，读不到资源主题文件 (Issue #2910) 如果可以，我愿意来尝试修复一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

你先按这样修改一下看能不能使用

**Comment by Reallyone** [comment]
好的， 非常感谢



***@***.***
 
发件人： will
发送时间： 2022-12-17 20:09
收件人： halo-dev/halo
抄送： stormXu; Comment
主题： Re: [halo-dev/halo] 打包成jar后运行报错，读不到资源主题文件 (Issue #2910)
在本地做了些验证，可以在 DefaultThemeInitializer中 使用
PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
可以兼容在jar包，开发环境等不同场景的文件读取操作，并在下面使用
themeService.install(resolver.getResource(location).getInputStream())
进行安装，如有不妥当欢迎指正。

**Comment by Reallyone** [comment]
我查看了下代码，不知道是否和这里有点关系：ThemePathPolicy



***@***.***
 
发件人： will
发送时间： 2022-12-17 20:10
收件人： halo-dev/halo
抄送： stormXu; Comment
主题： Re: [halo-dev/halo] 打包成jar后运行报错，读不到资源主题文件 (Issue #2910)
远程么？ @.*** 发件人： will 发送时间： 2022-12-17 20:03 收件人： halo-dev/halo 抄送： stormXu; Comment 主题： Re: [halo-dev/halo] 打包成jar后运行报错，读不到资源主题文件 (Issue #2910) 如果可以，我愿意来尝试修复一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>
你先按这样修改一下看能不能使用

**Comment by minliacom** [comment]
跟这个没关系，那个是警告有被废除的接口而以，这个不影响

**Comment by Reallyone** [comment]
已经解决：
![image](https://user-images.githubusercontent.com/40932714/208241892-2e600e45-9d17-4e8d-9fe3-147e1d2b8510.png)
![image](https://user-images.githubusercontent.com/40932714/208241908-7eddee5f-f56b-4136-95fe-635aa3df38e4.png)

PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();

可以兼容在jar包，开发环境等不同场景的文件读取操作，并在下面使用
themeService.install(resolver.getResource(location).getInputStream())

感谢 [minliacom](https://github.com/minliacom)

**Comment by Reallyone** [comment]
已经正常启动，感谢！！！！



***@***.***
 
发件人： will
发送时间： 2022-12-17 20:27
收件人： halo-dev/halo
抄送： stormXu; Comment
主题： Re: [halo-dev/halo] 打包成jar后运行报错，读不到资源主题文件 (Issue #2910)
跟这个没关系，那个是警告有被废除的接口而以，这个不影响

**Comment by minliacom** [comment]
好的Halo愉快

**Comment by ruibaby** [comment]
> 在本地做了些验证，可以在 `DefaultThemeInitializer` 中
> 
> 1. 修改50行为:
>    `PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();`
> 2. 并在下面52行修改为：
>    `themeService.install(resolver.getResource(location).getInputStream());`
> 3. 删除53行中的：`URISyntaxException |`
> 
> 进行安装，要导入需要的包，
> 
> 再运行类似命令进行启动：
> 
> `rm -rf build/libs && rm -rf ~/.halo2 &&gradle clean build -x test && java -jar build/libs/halo-2.1.0-SNAPSHOT.jar`
> 
> 如有不妥欢迎指正。

PR first，不推荐使用者修改代码再编译。
