### ISSUE TITLE
在提交文章后，突然提示后端报错，（日志放在下面）

### ISSUE THREAD

**Issue by Jimecc** [halo-dev/halo#2914]
### 是什么版本出现了此问题？

2.0.0

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://blog.shary.cc

### 发生了什么？

# 问题描述
提交文章后，突然提示服务器出错，随后控制台那里便无法加载文章（提示`无文章|服务器报错`）
<div align=center><img src="https://files.catbox.moe/4c0nt5.png" style="border-radius:15px"></div>

# 文章描述
是一篇无标题文章，非常简单地一个小文章

# 细节描述
我是使用的本地机器(frp)内网穿透到腾讯云主机，随后加三级域名实现的博客

### 相关日志输出

```shell
2022-12-11T17:55:40.897+08:00 ERROR 7 --- [or-http-epoll-1] a.w.r.e.AbstractErrorWebExceptionHandler : [819e4513-82]  500 Server Error for HTTP GET "/apis/api.console.halo.run/v1alpha1/posts?keyword=&size=20&page=1&labelSelector=content.halo.run%2Fdeleted%3Dfalse"

java.lang.ClassCastException: class run.halo.app.content.Contributor cannot be cast to class java.lang.Comparable (run.halo.app.content.Contributor is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @61bbe9ba; java.lang.Comparable is in module java.base of loader 'bootstrap')
        at java.base/java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source) ~[na:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ LoginPageGeneratingWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/apis/api.console.halo.run/v1alpha1/posts?keyword=&size=20&page=1&labelSelector=content.halo.run%2Fdeleted%3Dfalse" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at java.base/java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source) ~[na:na]
                at java.base/java.util.ComparableTimSort.sort(Unknown Source) ~[na:na]
                at java.base/java.util.Arrays.sort(Unknown Source) ~[na:na]
                at java.base/java.util.Arrays.sort(Unknown Source) ~[na:na]
                at java.base/java.util.ArrayList.sort(Unknown Source) ~[na:na]
                at reactor.core.publisher.Flux.lambda$collectSortedList$16(Flux.java:3840) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:196) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2034) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:894) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:997) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:270) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.0.jar:3.5.0]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.0.jar:3.5.0]
```

### 附加信息

请问什么时候可以支持Markdown呀

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/2854 中修复，请升级到 2.0.1 再尝试一下。

https://github.com/halo-dev/halo/releases/tag/v2.0.1

/triage duplicate
