### ISSUE TITLE
附件上传异常错误提示不明确

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#2931]
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://demo.halo.run

### 发生了什么？

如图，上传失败只能得到失败的提示，没有具体原因（这里是因为文件重名）：

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/21301288/207255817-b97a55ae-c304-42ad-af3e-750994e2c961.png">

异常返回体：

```json
{
  "type": "about:blank",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "/Users/ryanwang/halo2-dev/attachments/upload/application.properties"
}
```

/area core
/area console
/kind improvement
/milestone 2.1.x

**Comment by ruibaby** [comment]
> /unassign /assign @ruibaby

这个问题可能需要后端捕获一下异常哦，现在这个异常不是很明确。

**Comment by JohnNiang** [comment]
是的，后端确实需要处理一下常见的错误。

**Comment by ZhuccIvan** [comment]
`2022-12-17T08:53:12.929+08:00  INFO 7 --- [undedElastic-38] r.halo.alioss.AliOssAttachmentHandler    : Uploading 102904236_p0.jpg into AliOSS oss-cn-hangzhou.aliyuncs.com/halo-ivan/attachments/upload/102904236_p0.jpg
2022-12-17T08:53:43.466+08:00  WARN 7 --- [undedElastic-38] com.aliyun.oss                           : [Client]Unable to execute HTTP request: null
[ErrorCode]: Unknown
[RequestId]: Unknown
2022-12-17T08:53:43.466+08:00 ERROR 7 --- [undedElastic-38] r.halo.alioss.AliOssAttachmentHandler    : Caught an ClientException, which means the client encountered a serious internal
problem while trying to communicate with OSS, such as not being able to access
the network.

2022-12-17T08:53:44.466+08:00 ERROR 7 --- [undedElastic-36] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.core.Exceptions$ErrorCallbackNotImplemented: java.io.IOException: Pipe closed
Caused by: java.io.IOException: Pipe closed
	at java.base/java.io.PipedInputStream.checkStateForReceive(Unknown Source) ~[na:na]
	at java.base/java.io.PipedInputStream.receive(Unknown Source) ~[na:na]
	at java.base/java.io.PipedOutputStream.write(Unknown Source) ~[na:na]
	at java.base/java.nio.channels.Channels$WritableByteChannelImpl.write(Unknown Source) ~[na:na]
	at org.springframework.core.io.buffer.DataBufferUtils$WritableByteChannelSubscriber.hookOnNext(DataBufferUtils.java:1053) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.core.io.buffer.DataBufferUtils$WritableByteChannelSubscriber.hookOnNext(DataBufferUtils.java:1032) ~[spring-core-6.0.2.jar:6.0.2]
	at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:160) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:151) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:353) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.next(FluxGenerate.java:178) ~[reactor-core-3.5.0.jar:3.5.0]
	at org.springframework.core.io.buffer.DataBufferUtils$ReadableByteChannelGenerator.accept(DataBufferUtils.java:916) ~[spring-core-6.0.2.jar:6.0.2]
	at org.springframework.core.io.buffer.DataBufferUtils$ReadableByteChannelGenerator.accept(DataBufferUtils.java:891) ~[spring-core-6.0.2.jar:6.0.2]
	at reactor.core.publisher.FluxGenerate.lambda$new$1(FluxGenerate.java:58) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:271) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:213) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.request(FluxUsing.java:320) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onSubscribe(FluxUsing.java:347) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:85) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxUsing.subscribe(FluxUsing.java:102) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0.jar:3.5.0]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0.jar:3.5.0]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
`
我也出现了这个问题，上面是log，小文件能正常上传成功，8m就上传不了了，nginx我也设置了1024m

**Comment by JohnNiang** [comment]
Hi @ZhuccIvan ，我在本地测试了一下 300+MB 的文件通过本地策略上传，能够成功。

![image](https://user-images.githubusercontent.com/16865714/208607085-321c5ee4-a023-43b1-87e4-14a0841cb017.png)

从提供的日志中看，可能是服务器和阿里云之间网络的问题。

> Caught an ClientException, which means the client encountered a serious internal
problem while trying to communicate with OSS, such as not being able to access
the network.

**Comment by ZhuccIvan** [comment]
Hi @JohnNiang ,
是的，本地策略是没什么问题的，但是OSS怎么都不行，有时候上传成功但是显示还是失败附件也无法使用，更多时候是没上传成功。
我的服务器就是阿里云的，不应该会有网络的问题吧， 而且小文件是可以成功的

**Comment by ruibaby** [comment]
/close

see https://github.com/halo-dev/halo/pull/3042

**Comment by ruibaby** [comment]
@ZhuccIvan 如果是仅在阿里云 OSS 有问题，建议向 https://github.com/halo-sigs/plugin-alioss 提交 issue。

这个 issue 已经完成使命。
