### ISSUE TITLE
生成缩略图OOM

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#294]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

---

错误栈终于找到了，之前使用 `thumbnailator` 的时候由于没有打印出错误栈，仅仅是显示了 `Caused by: java.lang.OutOfMemoryError: Java heap space` 错误，导致无法精准定位问题。

完整错误栈如下：

```java
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.desktop/java.awt.image.DataBufferByte.<init>(DataBufferByte.java:92) ~[na:na]
        at java.desktop/java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:439) ~[na:na]
        at java.desktop/java.awt.image.Raster.createWritableRaster(Raster.java:1005) ~[na:na]
        at java.desktop/javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1074) ~[na:na]
        at java.desktop/javax.imageio.ImageReader.getDestination(ImageReader.java:2877) ~[na:na]
        at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1142) ~[na:na]
        at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1110) ~[na:na]
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468) ~[na:na]
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315) ~[na:na]
        at cn.hutool.core.img.ImgUtil.read(ImgUtil.java:1559) ~[hutool-core-4.6.3.jar!/:na]
        at cn.hutool.core.img.ImgUtil.scale(ImgUtil.java:74) ~[hutool-core-4.6.3.jar!/:na]
        at run.halo.app.handler.file.LocalFileHandler.generateThumbnail(LocalFileHandler.java:230) ~[classes!/:1.1.0-beta.3]
        at run.halo.app.handler.file.LocalFileHandler.upload(LocalFileHandler.java:155) ~[classes!/:1.1.0-beta.3]
        at run.halo.app.handler.file.FileHandlers.upload(FileHandlers.java:54) ~[classes!/:1.1.0-beta.3]
        at run.halo.app.service.impl.AttachmentServiceImpl.upload(AttachmentServiceImpl.java:105) ~[classes!/:1.1.0-beta.3]
        at run.halo.app.service.impl.AttachmentServiceImpl$$FastClassBySpringCGLIB$$2d9c80b9.invoke(<generated>) ~[classes!/:1.1.0-beta.3]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at run.halo.app.service.impl.AttachmentServiceImpl$$EnhancerBySpringCGLIB$$f033e75e.upload(<generated>) ~[classes!/:1.1.0-beta.3]
        at run.halo.app.controller.admin.api.AttachmentController.uploadAttachment(AttachmentController.java:86) ~[classes!/:1.1.0-beta.3]
        at run.halo.app.controller.admin.api.AttachmentController$$FastClassBySpringCGLIB$$8f3ff968.invoke(<generated>) ~[classes!/:1.1.0-beta.3]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at run.halo.app.core.ControllerLogAop.controller(ControllerLogAop.java:41) ~[classes!/:1.1.0-beta.3]
        at jdk.internal.reflect.GeneratedMethodAccessor240.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
```

**Comment by JohnNiang** [comment]
![image](https://user-images.githubusercontent.com/16865714/64546999-4c2e4c80-d35e-11e9-9637-943bc137421d.png)

上传的文件大小为 `8.8MB`，这里的开销需要 `68585472B`，如果内存太小，会直接 OOM 的。
