### ISSUE TITLE
启动2.0中遇到的一个问题

### ISSUE THREAD

**Issue by Reallyone** [halo-dev/halo#2989]
### What is version of Halo has the issue?

2.0

### What database are you using?

MySQL 8.x

### What is your deployment method?

Fat Jar

### What happened?

yaml.配置
![image](https://user-images.githubusercontent.com/40932714/208219556-a89a2655-cd7e-4832-a0b8-02ef98c6dba3.png)
mysql配置
![image](https://user-images.githubusercontent.com/40932714/208219581-1d772b8e-9fb1-44af-bf5a-93816479a661.png)

~.halo2目录
![image](https://user-images.githubusercontent.com/40932714/208219628-ecb497c5-c144-47c2-8456-9fcf68215bd7.png)

项目: java -jar halo-2.1.0-SNAPSHOT.jarjava -jar halo-2.1.0-SNAPSHOT.jar
![image](https://user-images.githubusercontent.com/40932714/208219679-ec034d7e-f3a2-44a5-9e14-ad37151b69ee.png)

![image](https://user-images.githubusercontent.com/40932714/208219691-dded5d34-8b3f-4d13-b0b8-f5232b9e787a.png)

### Relevant log output

```shell
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2022-12-17T10:35:33.422+08:00 ERROR 241132 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.nio.file.FileSystemNotFoundException: null
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156) ~[jdk.zipfs:na]
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142) ~[jdk.zipfs:na]
        at java.base/java.nio.file.Path.of(Path.java:208) ~[na:na]
        at run.halo.app.infra.DefaultThemeInitializer.onApplicationEvent(DefaultThemeInitializer.java:52) ~[classes!/:2.1.0-SNAPSHOT]
        at run.halo.app.infra.DefaultThemeInitializer.onApplicationEvent(DefaultThemeInitializer.java:17) ~[classes!/:2.1.0-SNAPSHOT]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar!/:6.0.2]
        at run.halo.app.infra.SchemeInitializer.onApplicationEvent(SchemeInitializer.java:79) ~[classes!/:2.1.0-SNAPSHOT]
        at run.halo.app.infra.SchemeInitializer.onApplicationEvent(SchemeInitializer.java:34) ~[classes!/:2.1.0-SNAPSHOT]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.2.jar!/:6.0.2]
        at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:103) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:76) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:76) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.0.jar!/:3.0.0]
        at run.halo.app.Application.main(Application.java:25) ~[classes!/:2.1.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[halo-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[halo-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[halo-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[halo-2.1.0-SNAPSHOT.jar:2.1.0-SNAPSHOT]
```

### Additional information

请问是我配置少了东西么？ 1.5我没有关闭所以端口改了

**Comment by minliacom** [comment]
Halo建议以docker方式启动， [具体参见文档](https://docs.halo.run/)

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-dev/halo/issues/2910

**Comment by minliacom** [comment]
是以代码方式启动的还是打包成jar方式启动的？详细描述一下情况呢？

**Comment by ruibaby** [comment]
> 是以代码方式启动的还是打包成jar方式启动的？详细描述一下情况呢？

jar，这是已知问题，请看 #2910

/close

**Comment by Reallyone** [comment]
是的，是项目拉取后手动打包的，不知道是否是哪里出了问题：




***@***.***
 
发件人： will
发送时间： 2022-12-17 19:04
收件人： halo-dev/halo
抄送： stormXu; Author
主题： Re: [halo-dev/halo] 启动2.0中遇到的一个问题 (Issue #2989)
是以代码方式启动的还是打包成jar方式启动的？详细描述一下情况呢？
