### ISSUE TITLE
除了首页和后台页，其他页面无法访问，切换主题之后首页500错误

### ISSUE THREAD

**Issue by BronzedOreo** [halo-dev/halo#2998]
### 是什么版本出现了此问题？

2.0.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

首次进入后台点击主题栏的时候，只有安装主题功能页面，没有主题配置菜单页面（图一），首页标注的子页面都不能访问图二，首次拖拽上传安装主题报错（图三），第二次上传切换主题之后首页500错误了（图四）

### 相关日志输出

```shell
Original Stack Trace:
halo    |               at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292) ~[thymeleaf-spring6-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at run.halo.app.theme.ReactiveSpelVariableExpressionEvaluator.evaluate(ReactiveSpelVariableExpressionEvaluator.java:29) ~[classes/:2.0.2]
halo    |               at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.standard.processor.StandardIfTagProcessor.isVisible(StandardIfTagProcessor.java:59) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.standard.processor.AbstractStandardConditionalVisibilityTagProcessor.doProcess(AbstractStandardConditionalVisibilityTagProcessor.java:61) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |               at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:2.0.2]
halo    |               at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |               at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |               at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |               at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |               at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |               at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo    |               at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
halo    |               at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo    |               at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo    |               at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo    | Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1021E: A problem occurred whilst attempting to access the property 'other': 'Can't happen. Check SUPPORTED_CLASSES'
halo    |       at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:209) ~[spring-expression-6.0.2.jar:6.0.2]
halo    |       at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104) ~[spring-expression-6.0.2.jar:6.0.2]
halo    |       at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:92) ~[spring-expression-6.0.2.jar:6.0.2]
halo    |       at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:61) ~[spring-expression-6.0.2.jar:6.0.2]
halo    |       at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:91) ~[spring-expression-6.0.2.jar:6.0.2]
halo    |       at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:112) ~[spring-expression-6.0.2.jar:6.0.2]
halo    |       at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:338) ~[spring-expression-6.0.2.jar:6.0.2]
halo    |       at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:265) ~[thymeleaf-spring6-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at run.halo.app.theme.ReactiveSpelVariableExpressionEvaluator.evaluate(ReactiveSpelVariableExpressionEvaluator.java:29) ~[classes/:2.0.2]
halo    |       at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.standard.processor.StandardIfTagProcessor.isVisible(StandardIfTagProcessor.java:59) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.standard.processor.AbstractStandardConditionalVisibilityTagProcessor.doProcess(AbstractStandardConditionalVisibilityTagProcessor.java:61) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.0.RELEASE.jar:3.1.0.RELEASE]
halo    |       at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:2.0.2]
halo    |       at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |       at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |       at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |       at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0.jar:3.5.0]
halo    |       at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo    |       at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo    | Caused by: java.lang.IllegalStateException: Can't happen. Check SUPPORTED_CLASSES
halo    |       at org.springframework.integration.json.JsonPropertyAccessor.asJson(JsonPropertyAccessor.java:104) ~[spring-integration-core-6.0.0.jar:6.0.0]
halo    |       at org.springframework.integration.json.JsonPropertyAccessor.canRead(JsonPropertyAccessor.java:75) ~[spring-integration-core-6.0.0.jar:6.0.0]
halo    |       at run.halo.app.theme.ReactivePropertyAccessor.canRead(ReactivePropertyAccessor.java:39) ~[classes/:2.0.2]
halo    |       at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:198) ~[spring-expression-6.0.2.jar:6.0.2]
halo    |       ... 46 common frames omitted
```

### 附加信息

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/71474660/208307590-45132db5-eb96-4a06-9590-71899fcc673b.png">
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/71474660/208307697-e1479452-8373-49df-acd1-dd7455eb5299.png">
<img width="796" alt="image" src="https://user-images.githubusercontent.com/71474660/208307745-72546df7-c081-49ef-a09a-8393f56e440d.png">
<img width="685" alt="image" src="https://user-images.githubusercontent.com/71474660/208307932-8c094c41-e0f2-4d92-99cd-9bca8b14cb72.png">

**Comment by ruibaby** [comment]
可以复现，这个问题和 Console 有关，你刷新一下页面应该就可以看到激活的主题了。上传主题拖拽导致页面崩溃应该是和上传组件有关，稍后我会提交一个新的 issue。

/kind bug
/area console

**Comment by BronzedOreo** [comment]
这个问题有被修复吗

**Comment by ruibaby** [comment]
@BronzedOreo 首次初始化没有激活主题的问题确实存在，会在下一个 2.0 的 patch 版本修复，页面无法访问的问题无法复现。拖拽上传导致浏览器崩溃的问题请看：

1. https://github.com/transloadit/uppy/issues/976
2. https://github.com/transloadit/uppy/issues/4133

**Comment by JohnNiang** [comment]
Hi @BronzedOreo ，建议提供一下完整的错误站，目前提供的可能缺少重要的错误信息。

参考：
- https://github.com/halo-dev/halo/issues/2992
