### ISSUE TITLE
文章内容超过256KB时无法保存

### ISSUE THREAD

**Issue by MiniDay** [halo-dev/halo#2999]
### 是什么版本出现了此问题？

2.0.2

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://www.hamster3.cn

### 发生了什么？

我尝试发布一个新的文章，但由于我直接在文章中使用ctrl+v粘贴图片，所以导致这篇文章的大小超过了256kb，然后返回400 Bad Request。

### 相关日志输出

```shell
halo  | 2022-12-19T11:47:32.885+08:00 ERROR 7 --- [or-http-epoll-2] h.a.i.e.h.GlobalErrorWebExceptionHandler : Exceeded limit on max bytes to buffer : 262144
halo  |
halo  | org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144
halo  |         at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:99) ~[spring-core-6.0.2.jar:6.0.2]
halo  |         Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
halo  | Error has been observed at the following site(s):
halo  |         *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ LoginPageGeneratingWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
halo  |         *__checkpoint ⇢ HTTP PUT "/apis/api.console.halo.run/v1alpha1/posts/9ea10797-4d01-40a8-b35c-1964e719da14/content" [ExceptionHandlingWebHandler]
halo  | Original Stack Trace:
halo  |                 at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:99) ~[spring-core-6.0.2.jar:6.0.2]
halo  |                 at org.springframework.core.io.buffer.LimitedDataBufferList.updateCount(LimitedDataBufferList.java:92) ~[spring-core-6.0.2.jar:6.0.2]
halo  |                 at org.springframework.core.io.buffer.LimitedDataBufferList.add(LimitedDataBufferList.java:58) ~[spring-core-6.0.2.jar:6.0.2]
halo  |                 at reactor.core.publisher.MonoCollect$CollectSubscriber.onNext(MonoCollect.java:103) ~[reactor-core-3.5.0.jar:3.5.0]
halo  |                 at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.0.jar:3.5.0]
halo  |                 at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.5.0.jar:3.5.0]
halo  |                 at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.0.jar:3.5.0]
halo  |                 at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:377) ~[reactor-netty-core-1.1.0.jar:1.1.0]
halo  |                 at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411) ~[reactor-netty-core-1.1.0.jar:1.1.0]
halo  |                 at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:598) ~[reactor-netty-http-1.1.0.jar:1.1.0]
halo  |                 at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113) ~[reactor-netty-core-1.1.0.jar:1.1.0]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:266) ~[reactor-netty-http-1.1.0.jar:1.1.0]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
halo  |                 at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### 附加信息

{"type":"about:blank","title":"Bad Request","status":400,"detail":"Exceeded limit on max bytes to buffer : 262144","instance":"/apis/api.console.halo.run/v1alpha1/posts/9ea10797-4d01-40a8-b35c-1964e719da14/content"}

**Comment by JohnNiang** [comment]
/triage duplicate

请参考：<https://github.com/halo-dev/halo/issues/2861>。

**Comment by JohnNiang** [comment]
如果你是通过 Docker Compose 部署的话，可试着修改 docker-compose.yaml：

```diff
services:
  halo:
    image: halohub/halo:2.0.2
+   command: |
+     --spring.codec.max-in-memory-size=10MB
```

**Comment by MiniDay** [comment]
> 

ok，感谢。
我直接在`docker-compose.yaml`文件同目录下新建一个`application.properties`文件，然后把`spring.codec.max-in-memory-size=10MB`写进去也成功了。
不过更改后又报错说`executeMany; SQL [INSERT INTO extensions (name, data, version) VALUES (?, ?, ?)]; Data too long for column 'data' at row 1`
接着我再去数据库手动把表格中的那一列更改为 MEDIUMBLOB，才终于保存成功了。
然后我发现网站的访问速度变得巨慢无比......最后还是放弃了，改了回来决定继续用附件的形式上传图片吧= =
