### ISSUE TITLE
新建文章时，拖动上传图片异常

### ISSUE THREAD

**Issue by Lx0815** [halo-dev/halo#3008]
### 是什么版本出现了此问题？

2.0.2

### 使用的什么数据库？

mysql8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

http://43.142.113.254:9898/

### 发生了什么？

文件上传问题：（由于长度限制，日志最后一部分被截断）
拖动文件进行上传时，浏览器页面异常，错误代码RESULT_CODE_KILLED_BAD_MESSAGE。edge 和 Google 均如此。
奇怪的是，手动选择文件进行上传可以正常上传。

### 相关日志输出

```shell
halo      | 2022-12-19T22:31:05.715+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][category] Deprecated unwrapped fragment expression "modules/layouts/layout :: layout(content = ~{::content}, htmlType = 'category')" found in template category, line 2, col 17. Please use the complete syntax of fragment expressions instead ("~{modules/layouts/layout :: layout(content = ~{::content}, htmlType = 'category')}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.716+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/head :: head(metas = null, links = null, scripts =  ~{::head/script})" found in template modules/layouts/layout, line 5, col 7. Please use the complete syntax of fragment expressions instead ("~{modules/head :: head(metas = null, links = null, scripts =  ~{::head/script})}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.722+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/loading-box :: loading-box" found in template modules/layouts/layout, line 38, col 6. Please use the complete syntax of fragment expressions instead ("~{modules/loading-box :: loading-box}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.722+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/widgets/console :: console" found in template modules/layouts/layout, line 44, col 6. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/console :: console}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.722+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/sidebar :: sidebar" found in template modules/layouts/layout, line 46, col 6. Please use the complete syntax of fragment expressions instead ("~{modules/sidebar :: sidebar}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.724+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][category] Deprecated unwrapped fragment expression "modules/nav :: nav" found in template category, line 8, col 18. Please use the complete syntax of fragment expressions instead ("~{modules/nav :: nav}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.724+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/nav] Deprecated unwrapped fragment expression "modules/widgets/nav-left :: nav-left" found in template modules/nav, line 7, col 14. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/nav-left :: nav-left}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.724+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/nav] Deprecated unwrapped fragment expression "modules/widgets/nav-menu :: nav-menu" found in template modules/nav, line 14, col 14. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/nav-menu :: nav-menu}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.727+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/nav] Deprecated unwrapped fragment expression "modules/widgets/nav-right :: nav-right" found in template modules/nav, line 17, col 14. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/nav-right :: nav-right}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.729+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][category] Deprecated unwrapped fragment expression "modules/aside :: aside(${theme.config.sidebar.categoryWidgets})" found in template category, line 69, col 18. Please use the complete syntax of fragment expressions instead ("~{modules/aside :: aside(${theme.config.sidebar.categoryWidgets})}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.729+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/aside] Deprecated unwrapped fragment expression "'modules/widgets/aside/'+ ${widget}" found in template modules/aside, line 13, col 27. Please use the complete syntax of fragment expressions instead ("~{'modules/widgets/aside/'+ ${widget}}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.730+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/aside] Deprecated unwrapped fragment expression "'modules/widgets/aside/'+ ${widget}" found in template modules/aside, line 13, col 27. Please use the complete syntax of fragment expressions instead ("~{'modules/widgets/aside/'+ ${widget}}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.733+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/aside] Deprecated unwrapped fragment expression "'modules/widgets/aside/'+ ${widget}" found in template modules/aside, line 13, col 27. Please use the complete syntax of fragment expressions instead ("~{'modules/widgets/aside/'+ ${widget}}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.734+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/aside] Deprecated unwrapped fragment expression "'modules/widgets/aside/'+ ${widget}" found in template modules/aside, line 17, col 31. Please use the complete syntax of fragment expressions instead ("~{'modules/widgets/aside/'+ ${widget}}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.734+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/widgets/aside/tags-stat] Deprecated unwrapped fragment expression "modules/widgets/aside/tags :: tags" found in template modules/widgets/aside/tags-stat, line 10, col 23. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/aside/tags :: tags}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.735+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/widgets/aside/tags-stat] Deprecated unwrapped fragment expression "modules/widgets/aside/stat :: stat" found in template modules/widgets/aside/tags-stat, line 14, col 23. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/aside/stat :: stat}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.738+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][category] Deprecated unwrapped fragment expression "modules/footer :: footer" found in template category, line 73, col 17. Please use the complete syntax of fragment expressions instead ("~{modules/footer :: footer}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.740+08:00  WARN 7 --- [undedElastic-28] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-28][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/right-menu :: right-menu" found in template modules/layouts/layout, line 64, col 6. Please use the complete syntax of fragment expressions instead ("~{modules/right-menu :: right-menu}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.950+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][category] Deprecated unwrapped fragment expression "modules/layouts/layout :: layout(content = ~{::content}, htmlType = 'category')" found in template category, line 2, col 17. Please use the complete syntax of fragment expressions instead ("~{modules/layouts/layout :: layout(content = ~{::content}, htmlType = 'category')}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.950+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/head :: head(metas = null, links = null, scripts =  ~{::head/script})" found in template modules/layouts/layout, line 5, col 7. Please use the complete syntax of fragment expressions instead ("~{modules/head :: head(metas = null, links = null, scripts =  ~{::head/script})}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.958+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/loading-box :: loading-box" found in template modules/layouts/layout, line 38, col 6. Please use the complete syntax of fragment expressions instead ("~{modules/loading-box :: loading-box}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.958+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/widgets/console :: console" found in template modules/layouts/layout, line 44, col 6. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/console :: console}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.959+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/sidebar :: sidebar" found in template modules/layouts/layout, line 46, col 6. Please use the complete syntax of fragment expressions instead ("~{modules/sidebar :: sidebar}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.962+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][category] Deprecated unwrapped fragment expression "modules/nav :: nav" found in template category, line 8, col 18. Please use the complete syntax of fragment expressions instead ("~{modules/nav :: nav}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.962+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/nav] Deprecated unwrapped fragment expression "modules/widgets/nav-left :: nav-left" found in template modules/nav, line 7, col 14. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/nav-left :: nav-left}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.962+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/nav] Deprecated unwrapped fragment expression "modules/widgets/nav-menu :: nav-menu" found in template modules/nav, line 14, col 14. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/nav-menu :: nav-menu}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.966+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/nav] Deprecated unwrapped fragment expression "modules/widgets/nav-right :: nav-right" found in template modules/nav, line 17, col 14. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/nav-right :: nav-right}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.968+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][category] Deprecated unwrapped fragment expression "modules/aside :: aside(${theme.config.sidebar.categoryWidgets})" found in template category, line 69, col 18. Please use the complete syntax of fragment expressions instead ("~{modules/aside :: aside(${theme.config.sidebar.categoryWidgets})}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.968+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/aside] Deprecated unwrapped fragment expression "'modules/widgets/aside/'+ ${widget}" found in template modules/aside, line 13, col 27. Please use the complete syntax of fragment expressions instead ("~{'modules/widgets/aside/'+ ${widget}}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.969+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/aside] Deprecated unwrapped fragment expression "'modules/widgets/aside/'+ ${widget}" found in template modules/aside, line 13, col 27. Please use the complete syntax of fragment expressions instead ("~{'modules/widgets/aside/'+ ${widget}}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.973+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/aside] Deprecated unwrapped fragment expression "'modules/widgets/aside/'+ ${widget}" found in template modules/aside, line 13, col 27. Please use the complete syntax of fragment expressions instead ("~{'modules/widgets/aside/'+ ${widget}}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.975+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/aside] Deprecated unwrapped fragment expression "'modules/widgets/aside/'+ ${widget}" found in template modules/aside, line 17, col 31. Please use the complete syntax of fragment expressions instead ("~{'modules/widgets/aside/'+ ${widget}}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.975+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/widgets/aside/tags-stat] Deprecated unwrapped fragment expression "modules/widgets/aside/tags :: tags" found in template modules/widgets/aside/tags-stat, line 10, col 23. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/aside/tags :: tags}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.976+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/widgets/aside/tags-stat] Deprecated unwrapped fragment expression "modules/widgets/aside/stat :: stat" found in template modules/widgets/aside/tags-stat, line 14, col 23. Please use the complete syntax of fragment expressions instead ("~{modules/widgets/aside/stat :: stat}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.981+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][category] Deprecated unwrapped fragment expression "modules/footer :: footer" found in template category, line 73, col 17. Please use the complete syntax of fragment expressions instead ("~{modules/footer :: footer}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:05.981+08:00  WARN 7 --- [undedElastic-27] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-27][modules/layouts/layout] Deprecated unwrapped fragment expression "modules/right-menu :: right-menu" found in template modules/layouts/layout, line 64, col 6. Please use the complete syntax of fragment expressions instead ("~{modules/right-menu :: right-menu}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
halo      | 2022-12-19T22:31:06.237+08:00 ERROR 7 --- [or-http-epoll-2] o.s.w.s.adapter.HttpWebHandlerAdapter    : [4e76a21d-1632] Error [java.nio.file.NoSuchFileException: /root/.halo2/themes/theme-hao/templates/assets/libs/swiper/swiper-bundle.min.js.map] for HTTP GET "/themes/theme-hao/assets/libs/swiper/swiper-bundle.min.js.map", but ServerHttpResponse already committed (200 OK)
halo      | 2022-12-19T22:31:06.237+08:00 ERROR 7 --- [or-http-epoll-2] r.n.http.server.HttpServerOperations     : [4e76a21d-2, L:/172.19.0.3:8090 - R:/120.229.62.167:2053] Error finishing response. Closing connection
halo      |
halo      | java.nio.file.NoSuchFileException: /root/.halo2/themes/theme-hao/templates/assets/libs/swiper/swiper-bundle.min.js.map
halo      |     at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[na:na]
halo      |     Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
halo      | Error has been observed at the following site(s):
halo      |     *__checkpoint ⇢ Handler run.halo.app.theme.ThemeConfiguration$$Lambda$1245/0x0000000801328f68@7c984cb3 [DispatcherHandler]
halo      |     *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ LoginPageGeneratingWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
halo      |     *__checkpoint ⇢ HTTP GET "/themes/theme-hao/assets/libs/swiper/swiper-bundle.min.js.map" [ExceptionHandlingWebHandler]
halo      | Original Stack Trace:
halo      |             at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[na:na]
halo      |             at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[na:na]
halo      |             at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[na:na]
halo      |             at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source) ~[na:na]
halo      |             at java.base/java.nio.channels.FileChannel.open(Unknown Source) ~[na:na]
halo      |             at java.base/java.nio.channels.FileChannel.open(Unknown Source) ~[na:na]
halo      |             at reactor.netty.NettyOutbound.lambda$sendFile$0(NettyOutbound.java:169) ~[reactor-netty-core-1.1.0.jar:1.1.0]
halo      |             at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:75) ~[reactor-core-3.5.0.jar:3.5.0]
halo      |             at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.5.0.jar:3.5.0]
halo      |             at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.5.0.jar:3.5.0]
halo      |             at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.0.jar:3.5.0]
halo      |             at reactor.netty.FutureMono.doSubscribe(FutureMono.java:122) ~[reactor-netty-core-1.1.0.jar:1.1.0]
```

### 附加信息

![image](https://user-images.githubusercontent.com/89496228/208467247-38e2ee57-08ae-4b85-9ceb-0af7abd79c10.png)

如上图，问题第一次发生于半小时前，第二次则是刚刚测试。现在拖动上传时日志少了下面的 ERROR 部分。
在此期间只发布过两篇文章，并且其中的图片没有使用拖动上传，而是手动选择上传。

**Comment by JohnNiang** [comment]
从提供的日志中看，该错误可能是因为主题确实对应的文件导致的，至少不是因为拖动上传图片导致的。

建议提供一个稳定的复现步骤，并且抓取最新相关的日志。

/triage needs-information

**Comment by ruibaby** [comment]
> 拖动文件进行上传时，浏览器页面异常，错误代码RESULT_CODE_KILLED_BAD_MESSAGE。edge 和 Google 均如此。

这个 issue 说的是上传组件使用拖动上传时，会导致浏览器崩溃。这个和后端没有关系。

/kind bug
/area console

**Comment by ruibaby** [comment]
see https://github.com/halo-dev/halo/issues/3017

**Comment by ruibaby** [comment]
/close

see https://github.com/halo-dev/halo/issues/3017 for more
