### ISSUE TITLE
上传文件临时目录 在 /tmp/ 下，然而系统定时清空 /tmp/run.talo.app/

### ISSUE THREAD

**Issue by owen-jia** [halo-dev/halo#3025]
### What is version of Halo has the issue?

1.5.4

### What database are you using?

H2

### What is your deployment method?

Fat Jar

### Your site address.

https://blog.shareworld.vip

### What happened?

**上传文件的临时目录，linux会定期清楚 run.halo.app。**

建议 代码中增加创建目录 逻辑，判处 run.halo.app 不存在，就主动创建一个。

**error log:**
```java
Caused by: java.io.FileNotFoundException: /tmp/run.halo.app/upload_2db47834_bc15_49cd_9cc5_a66ef85a9d36_00000009.tmp (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[na:na]
        at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:178) ~[commons-io-2.4.jar!/:2.4]
        at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:224) ~[commons-io-2.4.jar!/:2.4]
        at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:128) ~[commons-io-2.4.jar!/:2.4]
        at org.apache.commons.fileupload.util.Streams.copy(Streams.java:105) ~[commons-fileupload-1.4.jar!/:1.4]
        at org.apache.commons.fileupload.util.Streams.copy(Streams.java:68) ~[commons-fileupload-1.4.jar!/:1.4]
        at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:346) ~[commons-fileupload-1.4.jar!/:1.4]
        ... 91 common frames omitted
```

### Relevant log output

```shell
**error log:**
Caused by: java.io.FileNotFoundException: /tmp/run.halo.app/upload_2db47834_bc15_49cd_9cc5_a66ef85a9d36_00000009.tmp (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[na:na]
        at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:178) ~[commons-io-2.4.jar!/:2.4]
        at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:224) ~[commons-io-2.4.jar!/:2.4]
        at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:128) ~[commons-io-2.4.jar!/:2.4]
        at org.apache.commons.fileupload.util.Streams.copy(Streams.java:105) ~[commons-fileupload-1.4.jar!/:1.4]
        at org.apache.commons.fileupload.util.Streams.copy(Streams.java:68) ~[commons-fileupload-1.4.jar!/:1.4]
        at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:346) ~[commons-fileupload-1.4.jar!/:1.4]
        ... 91 common frames omitted
```

### Additional information

增加 run.talo.app 目录判处逻辑，不存在，主动创建

**Comment by JohnNiang** [comment]
重新上传文件，问题还存在么？

**Comment by ruibaby** [comment]
此问题是否得到解决？
