### ISSUE TITLE
迁移插件报错

### ISSUE THREAD

**Issue by aierx** [halo-dev/halo#3097]
### 是什么版本出现了此问题？

main分支

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

我在添加migrate插件时出现如下报错
插件版本为 ：[plugin-migrate-1.0.2.jar](https://github.com/halo-sigs/plugin-migrate/releases)
PluginNotFound:Plugin PluginMigrate not found in plugin manager

### 相关日志输出

```shell
2023-01-02T19:43:33.980+08:00 DEBUG 25512 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 >>> Reconciling request Request[name=PluginMigrate] at 2023-01-02T11:43:33.980527700Z
2023-01-02T19:43:33.982+08:00 DEBUG 25512 --- [nReconciler-t-1] r.h.a.e.controller.DefaultDelayQueue     : Adding request Request[name=PluginMigrate] immediately
2023-01-02T19:43:33.986+08:00 ERROR 25512 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...

java.lang.IllegalArgumentException: Unknown pluginId PluginMigrate
        at org.pf4j.AbstractPluginManager.checkPluginId(AbstractPluginManager.java:489) ~[pf4j-3.8.0.jar:3.8.0]
        at run.halo.app.plugin.HaloPluginManager.doStartPlugin(HaloPluginManager.java:220) ~[main/:na]
        at run.halo.app.plugin.HaloPluginManager.startPlugin(HaloPluginManager.java:211) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startPlugin$4(PluginReconciler.java:142) ~[main/:na]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.startPlugin(PluginReconciler.java:139) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:114) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:64) ~[main/:na]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:58) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:42) ~[main/:na]
        at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[main/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by guqing** [comment]
是本地运行还是按照官网的Docker命令运行的 Halo呢，使用jar包安装插件需要确保 halo 中的 halo.plugin.runtime-mode=deployment

**Comment by ruibaby** [comment]
目前开发环境不支持上传 JAR 来安装插件。请参考：https://github.com/halo-sigs/plugin-migrate#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83

**Comment by ruibaby** [comment]
是否已经解决此问题呢？
