### ISSUE TITLE
博客无法访问，并没有任何提示管理员功能

### ISSUE THREAD

**Issue by lnsane** [halo-dev/halo#315]
日志的最后几条记录
```
2019-09-26 10:10:35.550  WARN 15377 --- [Timer-0] run.halo.app.cache.AbstractCacheStore    : Cache key: [cache_lock_public run.halo.app.security.token.AuthToken run.halo.app.controller.admin.api.AdminController.refresh(java.lang.String)] has been expired
2019-09-26 10:26:25.957  INFO 15377 --- [XNIO-1 task-1] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-09-26 10:31:35.551  WARN 15377 --- [Timer-0] run.halo.app.cache.AbstractCacheStore    : Cache key: [cache_lock_public run.halo.app.security.token.AuthToken run.halo.app.controller.admin.api.AdminController.auth(run.halo.app.model.params.LoginParam)] has been expired
2019-09-26 10:35:33.696 ERROR 15377 --- [XNIO-1 Accept] org.xnio.nio.tcp.server                  : Exception accepting request, closing server channel TCP server (NIO) <1036bc83>

java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_222]
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_222]
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_222]
        at org.xnio.nio.QueuedNioTcpServer.handleReady(QueuedNioTcpServer.java:467) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.nio.QueuedNioTcpServerHandle.handleReady(QueuedNioTcpServerHandle.java:38) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) [xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
```

网站无法工作

**Comment by JohnNiang** [comment]
尝试执行`ulimit -n`，看看结果呢。

**Comment by JohnNiang** [comment]
> https://www.tecmint.com/increase-set-open-file-limits-in-linux/

建议根据这个教程修改一下服务器的配置。

**Comment by lnsane** [comment]
> 尝试执行`ulimit -n`，看看结果呢。
1024

http 请求返回Resposen

`org.apache.http.conn.HttpHostConnectException: Connect to 54.250.202.69:80 [/54.250.202.69] failed: Connection timed out: connect`

**Comment by lnsane** [comment]
是否可以加入同一MAC设备在同一时刻访问次数过多限制访问，不然blog服务器都是small VPS 很容易瘫痪。

**Comment by JohnNiang** [comment]
我们是不可能做到获取访问者的 Mac 地址的，最多只能获取到 IP，但又不能单纯的根据 IP 限制。某些接口是做了简单的保护措施的。

**Comment by JohnNiang** [comment]
> > 尝试执行`ulimit -n`，看看结果呢。
> > 1024
> 
> http 请求返回Resposen
> 
> `org.apache.http.conn.HttpHostConnectException: Connect to 54.250.202.69:80 [/54.250.202.69] failed: Connection timed out: connect`

请问这个错误是什么时候出触发的呢？拉取主题的时候？

**Comment by ruibaby** [comment]
@JohnNiang 超时了

**Comment by lnsane** [comment]
> > > 尝试执行`ulimit -n`，看看结果呢。
> > > 1024
> > 
> > 
> > http 请求返回Resposen
> > `org.apache.http.conn.HttpHostConnectException: Connect to 54.250.202.69:80 [/54.250.202.69] failed: Connection timed out: connect`
> 
> 请问这个错误是什么时候出触发的呢？拉取主题的时候？

就是出现网站崩溃的时候请求首页信息，返回的，虽然很多blog同一时刻访问量不大，但是我希望能有一个有效机制去判断当前访客大量请求是不是存在恶意的行为。这样至少可以保证blog的稳定性，不然随便一个人做并发测试就可能使一个small VPS崩溃，这个我想大家都不希望发生。

**Comment by JohnNiang** [comment]
@lnsane 你提的这个特性确实应该具备，我们会加入到下一个大版本开发计划中。

**Comment by NGLSL** [comment]
> > 尝试执行`ulimit -n`，看看结果呢。
> > 1024
> 
> http 请求返回Resposen
> 
> `org.apache.http.conn.HttpHostConnectException: Connect to 54.250.202.69:80 [/54.250.202.69] failed: Connection timed out: connect`

你服务器IP暴露了...

**Comment by lnsane** [comment]
> @lnsane 你提的这个特性确实应该具备，我们会加入到下一个大版本开发计划中。

嗨，我想加入你们这个项目一起开发可以嘛？但是我不知道项目什么功能需要完善，假设我刚才哪个问题，我有一个简单思路，就是在本地存个Id，然后通过算法来验证Id和计算点击量，只是思路其中有很多东西要考虑的，不知道我的思路是不是能达到项目者的要求，以及代码质量是不是符合项目规范。😋

**Comment by lnsane** [comment]
> > > 尝试执行`ulimit -n`，看看结果呢。
> > > 1024
> > 
> > 
> > http 请求返回Resposen
> > `org.apache.http.conn.HttpHostConnectException: Connect to 54.250.202.69:80 [/54.250.202.69] failed: Connection timed out: connect`
> 
> 你服务器IP暴露了...

嗨嗨，测试用的实例，IP属于AWS所有~

**Comment by ruibaby** [comment]
@lnsane 可以，主要是处理 issues，你可以先尝试提交 pr。

**Comment by JohnNiang** [comment]
> > > 尝试执行`ulimit -n`，看看结果呢。
> > > 1024
> > 
> > 
> > http 请求返回Resposen
> > `org.apache.http.conn.HttpHostConnectException: Connect to 54.250.202.69:80 [/54.250.202.69] failed: Connection timed out: connect`
> 
> 你服务器IP暴露了...

这应该是 Github 某个服务器的 IP，所以不用担心。

**Comment by JohnNiang** [comment]
> > @lnsane 你提的这个特性确实应该具备，我们会加入到下一个大版本开发计划中。
> 
> 嗨，我想加入你们这个项目一起开发可以嘛？但是我不知道项目什么功能需要完善，假设我刚才哪个问题，我有一个简单思路，就是在本地存个Id，然后通过算法来验证Id和计算点击量，只是思路其中有很多东西要考虑的，不知道我的思路是不是能达到项目者的要求，以及代码质量是不是符合项目规范。

首先，你得 fork 项目，并在 dev 分支上进行开发，开发完成之后，向 halo-dev/halo:dev 提交 Pull Request，由我们 Review 之后，决定是否合并代码，合并完成之后就算是一次成功的 Contribution。

**Comment by lnsane** [comment]
> > > @lnsane 你提的这个特性确实应该具备，我们会加入到下一个大版本开发计划中。
> > 
> > 
> > 嗨，我想加入你们这个项目一起开发可以嘛？但是我不知道项目什么功能需要完善，假设我刚才哪个问题，我有一个简单思路，就是在本地存个Id，然后通过算法来验证Id和计算点击量，只是思路其中有很多东西要考虑的，不知道我的思路是不是能达到项目者的要求，以及代码质量是不是符合项目规范。
> 
> 首先，你得 fork 项目，并在 dev 分支上进行开发，开发完成之后，向 halo-dev/halo:dev 提交 Pull Request，由我们 Review 之后，决定是否合并代码，合并完成之后就算是一次成功的 Contribution。

听起来非常棒，我会在未来的几天去解决这个问题😏

**Comment by JohnNiang** [comment]
请问博客无法访问的问题是否解决了呢？

**Comment by lnsane** [comment]
> 请问博客无法访问的问题是否解决了呢？

我真的非常想解决这个问题，但是我之前没有接触过springboot项目，对此我要做大量的知识去补充，我目前不断在了解这个项目，对此我非常抱歉😭，但是你如果相信我，我会在将来解决这个问题。

**Comment by JohnNiang** [comment]
关于访问限制这个功能就交给你了😁

**Comment by lnsane** [comment]
> 关于访问限制这个功能就交给你了😁

我一定会尽快的去解决这个问题的。fighting 🤗

**Comment by ruibaby** [comment]
@lnsane 加油↖(^ω^)↗

**Comment by lnsane** [comment]
@JohnNiang 你好，我目前看了大部分的源码，我发现整体都非常不错，我有些疑问能否直接在这边提吗？
1.mates数据表是干什么用的，我尝试过blog所有功能，我也查看了相关meta代码，还是不明白这个表的实际作用。我非常的困惑，请你告诉我一下，非常感谢

**Comment by ruibaby** [comment]
@lnsane 暂时无用，这是后面的功能。参考 https://github.com/halo-dev/halo/issues/95
