### ISSUE TITLE
halo 2.1 安装主题报错

### ISSUE THREAD

**Issue by willstar1976** [halo-dev/halo#3189]
### 是什么版本出现了此问题？

2.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

一直停留在100%
![图片](https://user-images.githubusercontent.com/124017332/215656766-ad0fbc5b-76b3-4701-9194-2ad85833ae75.png)

### 相关日志输出

```shell
Connecting to 222.71.183.188:22...
Connection established.
To escape to local shell, press 'Ctrl+Alt+]'.

Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-60-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

1 device has a firmware upgrade available.
Run `fwupdmgr get-upgrades` for more information.


 * Introducing Expanded Security Maintenance for Applications.
   Receive updates to over 25,000 software packages with your
   Ubuntu Pro subscription. Free for personal use.

     https://ubuntu.com/pro

Expanded Security Maintenance for Applications is not enabled.

4 updates can be applied immediately.
4 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


1 device has a firmware upgrade available.
Run `fwupdmgr get-upgrades` for more information.

Last login: Tue Jan 31 10:48:46 2023 from 222.71.183.186
root@mail:~# docker logs -f halo2 -n 200
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	... 31 common frames omitted

2023-01-31T10:48:14.118+08:00 ERROR 7 --- [ndedElastic-103] o.s.w.s.adapter.HttpWebHandlerAdapter    : [fea6dcdf-899] 500 Server Error for HTTP GET "/"

org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.spring6.processor.SpringHrefTagProcessor' (template: "modules/header" - line 30, col 13)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:117) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:294) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:1204) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.StandaloneElementTag.beHandled(StandaloneElementTag.java:228) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:202) ~[classes/:2.1.0]
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.1.jar:3.5.1]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.1.jar:3.5.1]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.1.jar:3.5.1]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.1.jar:3.5.1]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.1.jar:3.5.1]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.IllegalArgumentException: [http:/archives/hello-halo] is not a valid HTTP URL
	at org.springframework.web.util.UriComponentsBuilder.fromUriString(UriComponentsBuilder.java:256) ~[spring-web-6.0.3.jar:6.0.3]
	at run.halo.app.theme.ThemeLinkBuilder.processLink(ThemeLinkBuilder.java:48) ~[classes/:2.1.0]
	at org.thymeleaf.linkbuilder.StandardLinkBuilder.buildLink(StandardLinkBuilder.java:138) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.context.AbstractEngineContext.buildLink(AbstractEngineContext.java:167) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.standard.expression.LinkExpression.executeLinkExpression(LinkExpression.java:292) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:85) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
	... 31 common frames omitted

2023-01-31T10:52:50.495+08:00 ERROR 7 --- [or-tcp-epoll-12] io.netty.util.ResourceLeakDetector       : LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:403)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:174)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:108)
	org.springframework.core.io.buffer.NettyDataBufferFactory.allocateBuffer(NettyDataBufferFactory.java:66)
	org.springframework.core.io.buffer.NettyDataBufferFactory.allocateBuffer(NettyDataBufferFactory.java:39)
	run.halo.app.theme.engine.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:194)
	reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58)
	reactor.core.publisher.Mono.subscribe(Mono.java:4444)
	reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
	reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	java.base/java.lang.Thread.run(Unknown Source)
2023-01-31T11:02:11.965+08:00  WARN 7 --- [eReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.SinglePageReconciler-worker-1/Request[name=d253e106-018d-4572-8373-8f9673879b54]
2023-01-31T11:17:50.145+08:00 ERROR 7 --- [ndedElastic-114] o.s.w.s.adapter.HttpWebHandlerAdapter    : [b8a9dec8-1000] 500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install"

java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LoginPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ? CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source) ~[na:na]
		at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.util.zip.ZipInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.io.InputStream.transferTo(Unknown Source) ~[na:na]
		at java.base/java.nio.file.Files.copy(Unknown Source) ~[na:na]
		at run.halo.app.infra.utils.FileUtils.unzip(FileUtils.java:67) ~[classes/:2.1.0]
		at run.halo.app.core.extension.theme.ThemeUtils.lambda$unzipThemeTo$8(ThemeUtils.java:118) ~[classes/:2.1.0]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:180) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.1.jar:3.5.1]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-01-31T11:27:13.972+08:00 ERROR 7 --- [ndedElastic-119] o.s.w.s.adapter.HttpWebHandlerAdapter    : [e58defad-1073] 500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install"

java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LoginPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ? CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source) ~[na:na]
		at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.util.zip.ZipInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.io.InputStream.transferTo(Unknown Source) ~[na:na]
		at java.base/java.nio.file.Files.copy(Unknown Source) ~[na:na]
		at run.halo.app.infra.utils.FileUtils.unzip(FileUtils.java:67) ~[classes/:2.1.0]
		at run.halo.app.core.extension.theme.ThemeUtils.lambda$unzipThemeTo$8(ThemeUtils.java:118) ~[classes/:2.1.0]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:180) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.1.jar:3.5.1]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-01-31T11:28:34.047+08:00  WARN 7 --- [or-http-epoll-2] r.n.http.server.HttpServerOperations     : [d3c582e1, L:/172.25.0.3:8090 - R:/167.94.138.63:55186] Decoding failed: REQUEST(decodeResult: failure(java.lang.IllegalStateException: Unexpected request [PRI * HTTP/2.0]), version: HTTP/2.0)
PRI * HTTP/2.0
2023-01-31T11:36:37.945+08:00 ERROR 7 --- [ndedElastic-126] o.s.w.s.adapter.HttpWebHandlerAdapter    : [f7e28ba1-1114] 500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install"

java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ? SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? LoginPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ? CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ? HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ? ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ? HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/java.util.zip.InflaterInputStream.fill(Unknown Source) ~[na:na]
		at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.util.zip.ZipInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.io.InputStream.transferTo(Unknown Source) ~[na:na]
		at java.base/java.nio.file.Files.copy(Unknown Source) ~[na:na]
		at run.halo.app.infra.utils.FileUtils.unzip(FileUtils.java:67) ~[classes/:2.1.0]
		at run.halo.app.core.extension.theme.ThemeUtils.lambda$unzipThemeTo$8(ThemeUtils.java:118) ~[classes/:2.1.0]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:180) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.1.jar:3.5.1]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.1.jar:3.5.1]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Un
```

**Comment by ruibaby** [comment]
由于此 issue 已过时，且未在最新版本复现此问题，所以我将关闭此 issue。后续有任何问题可以随时重新打开或者新建 issue。

/close
