### ISSUE TITLE
项目启动过程中，默认主题包安装出现错误

### ISSUE THREAD

**Issue by zev-223** [halo-dev/halo#3253]
### What is version of Halo has the issue?

2.2

### What database are you using?

MySQL 5.7

### What is your deployment method?

Fat Jar

### What happened?

本地用idea启动项目时，出现主题包解压错误

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalArgumentException: malformed input off : 601, length : 1
Caused by: java.lang.IllegalArgumentException: malformed input off : 601, length : 1
	at java.base/java.lang.String.throwMalformed(String.java:1240) ~[na:na]
	at java.base/java.lang.String.decodeUTF8_UTF16(String.java:1148) ~[na:na]
	at java.base/java.lang.String.newStringUTF8NoRepl(String.java:728) ~[na:na]
	at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2398) ~[na:na]
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(ZipCoder.java:199) ~[na:na]
	at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:66) ~[na:na]
	at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:302) ~[na:na]
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:124) ~[na:na]
	at cn.irked.bus.bbs.infra.utils.FileUtils.unzip(FileUtils.java:53) ~[classes/:na]
	at cn.irked.bus.bbs.core.extension.theme.ThemeUtils.lambda$unzipThemeTo$8(ThemeUtils.java:118) ~[classes/:na]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:180) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.2.jar:3.5.2]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	... 19 common frames omitted
```

网上查询说是编码问题，但尝试了很多方法都无法解决，求大神帮助

**Comment by guqing** [comment]
你可以尝试按照官网文档尝试 mysql 8.0.31 试试

**Comment by ruibaby** [comment]
请提供你安装的主题以供我们排查。

/triage needs-information

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
