### ISSUE TITLE
halo版本2.2安装主题报错，具体错误代码如下

### ISSUE THREAD

**Issue by jiandyb** [halo-dev/halo#3303]
### 是什么版本出现了此问题？

安装主题报错

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://halo.jiandyb9834.xyz

### 发生了什么？

试用halo版本为2.2，在安装该主题时“halo-theme-joe2.0-1.0.10”办错。
![e74de192301df58857c4f1905e4691c](https://user-images.githubusercontent.com/45814226/218656115-908b18b6-55b2-4337-b23a-ab82c8beae9d.png)

### 相关日志输出

```shell
2023-02-14T14:19:12.434+08:00 ERROR 7 --- [undedElastic-90] a.w.r.e.AbstractErrorWebExceptionHandler : [c50a8d72-537]  500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install"
halo    | 
halo    | java.lang.IllegalArgumentException: The [theme.yaml] does not conform to the theme specification.
halo    |       at run.halo.app.core.extension.theme.ThemeUtils.loadThemeManifest(ThemeUtils.java:152) ~[classes/:2.2.0]
halo    |       Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
halo    | Error has been observed at the following site(s):
halo    |       *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ LoginPageGeneratingWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
halo    |       *__checkpoint ⇢ HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/install" [ExceptionHandlingWebHandler]
halo    | Original Stack Trace:
halo    |               at run.halo.app.core.extension.theme.ThemeUtils.loadThemeManifest(ThemeUtils.java:152) ~[classes/:2.2.0]
halo    |               at run.halo.app.core.extension.theme.ThemeUtils.lambda$unzipThemeTo$11(ThemeUtils.java:128) ~[classes/:2.2.0]
halo    |               at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.5.2.jar:3.5.2]
halo    |               at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.2.jar:3.5.2]
halo    |               at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245) ~[reactor-core-3.5.2.jar:3.5.2]
halo    |               at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305) ~[reactor-core-3.5.2.jar:3.5.2]
halo    |               at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128) ~[reactor-core-3.5.2.jar:3.5.2]
halo    |               at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) ~[reactor-core-3.5.2.jar:3.5.2]
halo    |               at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.2.jar:3.5.2]
halo    |               at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.2.jar:3.5.2]
halo    |               at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo    |               at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
halo    |               at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo    |               at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo    |               at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### 附加信息

![e74de192301df58857c4f1905e4691c](https://user-images.githubusercontent.com/45814226/218656426-05f9c08f-67d1-4e6c-a97c-b5649b0ecdb9.png)
![bcd3d3b6926d3090bfc3eb87e268d29](https://user-images.githubusercontent.com/45814226/218656438-6b6eab29-dcc1-423d-b256-27ea21b635ca.png)

**Comment by ruibaby** [comment]
你安装的这个主题：https://github.com/qinhua/halo-theme-joe2.0

似乎没有适配 2.0。

/kind support

**Comment by jiandyb** [comment]
用的就是这个仓库的主题~
刚才试了“halo-theme-joe2.0-1.0.9”和“halo-theme-joe2.0-1.0.10”这两个版本，都是同样的错误

**Comment by ruibaby** [comment]
> 用的就是这个仓库的主题~
> 
> 刚才试了“halo-theme-joe2.0-1.0.9”和“halo-theme-joe2.0-1.0.10”这两个版本，都是同样的错误

这个主题没有适配 Halo 2.0 以上的版本，无法上传使用。

**Comment by guqing** [comment]
建议到此主题仓库提 issue，让主题去兼容 2.0，如果没有适配 halo 2 是无法使用的
