### ISSUE TITLE
在更新文章的时候出现服务器内部错误

### ISSUE THREAD

**Issue by jtpYz** [halo-dev/halo#3339]
### 是什么版本出现了此问题？

2.2.1

### 使用的什么数据库？

Mysql5.7

### 使用的哪种方式部署？

Docker-Compose

### 在线站点地址

http://39.101.66.20:8090/

### 发生了什么？

想对文章进行更新，保存完后，点击发布会出现服务器内部错误

### 相关日志输出

```shell
hannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-02-18T21:47:28.466+08:00  WARN 7 --- [tReconciler-t-7] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PostReconciler-worker-7/Request[name=dfaded95-d1b5-4692-b883-71096ce77dd5]
```

### 附加信息

![Snipaste_2023-02-18_21-35-50](https://user-images.githubusercontent.com/114967302/219869180-e6d044fb-ac13-4a20-8670-1db5436f6745.png)

**Comment by JohnNiang** [comment]
/kind bug

目前在 2.2.1 上还是存在这个问题么？此前我已经针对这个问题尝试修复过，请看：<https://github.com/halo-dev/halo/pull/3210>。

参考：
- https://github.com/halo-dev/halo/issues/2860

**Comment by lixuejun725** [comment]
> 

还存在这个问题，另外新建分类也有这个问题
