### ISSUE TITLE
使用docker-compose启动，数据库启动异常

### ISSUE THREAD

**Issue by nondevops** [halo-dev/halo#3400]
### 是什么版本出现了此问题？

2.2.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

使用docker-compose部署启动时，数据库启动异常，docker-compose配置如下：
[root@aliyun halo]# cat docker-compose.yaml

```yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.2.0
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      halo_network:
    volumes:
      - ./:/root/.halo2
    ports:
      - "8090:8090"
    command:
      - --spring.r2dbc.url=r2dbc:pool:mysql://halodba:3307/halo
      - --spring.r2dbc.username=root
      # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=1Qaz2*ws8
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=https://www.devops.press/
      # 初始化的超级管理员用户名
      - --halo.security.initializer.superadminusername=admin
      # 初始化的超级管理员密码
      - --halo.security.initializer.superadminpassword=admin

  halodb:
    image: mysql:8.0.31
    container_name: halodb
    restart: on-failure:3
    networks:
      halo_network:
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlBackup:/data/mysqlBackup
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      # 请修改此密码，并对应修改上方 Halo 服务的 SPRING_R2DBC_PASSWORD 变量值
      - MYSQL_ROOT_PASSWORD=1Qaz2*ws8
      - MYSQL_DATABASE=halo

networks:
  halo_network:
```

现有服务器情况如下：
1.centos7.x
2. docker-compose 1.27.4
3. docker 20.10.17
4. 使用nginx作为代理
5. 

### 相关日志输出

```shell
halo      | 2023-02-26T10:05:36.717+08:00  INFO 7 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Disabled plugins: []
halo      | 2023-02-26T10:05:36.720+08:00  INFO 7 --- [           main] org.pf4j.DefaultPluginManager            : PF4J version 3.9.0 in 'deployment' mode
halo      | 2023-02-26T10:05:38.957+08:00  INFO 7 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/actuator'
halo      | 2023-02-26T10:05:39.314+08:00  WARN 7 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/R2dbcInitializationConfiguration.class]: Failed to execute database script
halo      | 2023-02-26T10:05:39.317+08:00  INFO 7 --- [           main] r.h.a.e.c.DefaultControllerManager       : Shutting down 0 controllers...
halo      | 2023-02-26T10:05:39.318+08:00  INFO 7 --- [           main] r.h.a.e.c.DefaultControllerManager       : Shutdown 0 controllers.
halo      | 2023-02-26T10:05:39.318+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Disposing controller garbage-collector-controller
halo      | 2023-02-26T10:05:39.318+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Controller garbage-collector-controller is disposed
halo      | 2023-02-26T10:05:39.319+08:00  WARN 7 --- [pool-5-thread-1] run.halo.app.metrics.VisitLogWriter      : VisitLogWrite thread [pool-5-thread-1] interrupted
halo      | 2023-02-26T10:05:39.364+08:00  INFO 7 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :
halo      |
halo      | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
halo      | 2023-02-26T10:05:39.383+08:00 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
halo      |
halo      | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/R2dbcInitializationConfiguration.class]: Failed to execute database script
halo      |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-context-6.0.4.jar:6.0.4]
halo      |     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4]
halo      |     at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |     at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |     at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |     at run.halo.app.Application.main(Application.java:28) ~[classes/:2.2.0]
halo      |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
halo      |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo      |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo      |     at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
halo      |     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
halo      |     at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[application/:na]
halo      |     at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
halo      |     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[application/:na]
halo      | Caused by: org.springframework.r2dbc.connection.init.UncategorizedScriptException: Failed to execute database script
halo      |     at org.springframework.r2dbc.connection.init.DatabasePopulator.lambda$populate$4(DatabasePopulator.java:65) ~[spring-r2dbc-6.0.4.jar:6.0.4]
halo      |     at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3749) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3839) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.MonoUsingWhen$ResourceSubscriber.onError(MonoUsingWhen.java:203) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:95) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475) ~[reactor-pool-1.0.0.jar:1.0.0]
halo      |     at reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:429) ~[reactor-pool-1.0.0.jar:1.0.0]
halo      |     at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onError(FluxMapFuseable.java:340) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:114) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:64) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[na:na]
halo      |     at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[na:na]
halo      |     at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[na:na]
halo      |     at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[na:na]
halo      |     at com.github.jasync.sql.db.util.FutureUtilsKt.failed(FutureUtils.kt:18) ~[jasync-pool-2.1.23.jar:na]
halo      |     at com.github.jasync.sql.db.mysql.MySQLConnection$connect$$inlined$onFailureAsync$1.accept(FutureUtils.kt:108) ~[jasync-mysql-2.1.23.jar:na]
halo      |     at com.github.jasync.sql.db.mysql.MySQLConnection$connect$$inlined$onFailureAsync$1.accept(FutureUtils.kt:81) ~[jasync-mysql-2.1.23.jar:na]
halo      |     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[na:na]
halo      |     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[na:na]
halo      |     at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[na:na]
halo      |     at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo      |     Suppressed: java.lang.Exception: #block terminated with an error
halo      |             at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |             at reactor.core.publisher.Mono.block(Mono.java:1710) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |             at org.springframework.boot.r2dbc.init.R2dbcScriptDatabaseInitializer.runScripts(R2dbcScriptDatabaseInitializer.java:68) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.runScripts(AbstractScriptDatabaseInitializer.java:146) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyScripts(AbstractScriptDatabaseInitializer.java:108) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applySchemaScripts(AbstractScriptDatabaseInitializer.java:98) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:76) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.afterPropertiesSet(AbstractScriptDatabaseInitializer.java:66) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.4.jar:6.0.4]
halo      |             at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-context-6.0.4.jar:6.0.4]
halo      |             at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4]
halo      |             at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150) ~[spring-boot-3.0.2.jar:3.0.2]
halo      |             at run.halo.app.Application.main(Application.java:28) ~[classes/:2.2.0]
halo      |             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
halo      |             at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo      |             at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo      |             at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
halo      |             at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
halo      |             at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[application/:na]
halo      |             at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
halo      |             at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[application/:na]
halo      | Caused by: org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection
halo      |     at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:90) ~[spring-r2dbc-6.0.4.jar:6.0.4]
halo      |     at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3763) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.2.jar:3.5.2]
halo      |     ... 20 common frames omitted
halo      | Caused by: java.net.UnknownHostException: halodba
halo      |     at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[na:na]
halo      |     at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[na:na]
halo      |     at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]
halo      |     at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]
halo      |     at java.base/java.net.InetAddress.getByName(Unknown Source) ~[na:na]
halo      |     at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at java.base/java.security.AccessController.doPrivileged(Unknown Source) ~[na:na]
halo      |     at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41) ~[netty-resolver-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61) ~[netty-resolver-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53) ~[netty-resolver-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55) ~[netty-resolver-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31) ~[netty-resolver-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106) ~[netty-resolver-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
halo      |     ... 1 common frames omitted
```

### 附加信息

![image](https://user-images.githubusercontent.com/12181410/221388413-3a5022d9-a6c4-4832-a613-1cf2c3f9fd08.png)

**Comment by guqing** [comment]
你的数据库容器名称叫 halodb 而连接名称中 pool:mysql://halodba:3307/halo 写的是 halodba，你应该是写错了多了个a

/kind support

**Comment by nondevops** [comment]
> 
已经修改了，但现在报这个错误了：
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: halodb/172.27.0.2:3307
halo      | Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused

我的防火墙未开启。

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/3389#issuecomment-1443394638

/close
