### ISSUE TITLE
idea 启动报错 NoClassDefFoundError: ApplicationStartup

### ISSUE THREAD

**Issue by wa3926** [halo-dev/halo#3586]
### 是什么版本出现了此问题？

2.3

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

window10 使用idea clone 项目 jdk 环境也是17 版本依赖也都打进来了  启动就是报错 感觉哪个版本依赖不对 又不知道哪个错了

### 相关日志输出

```shell
D:\softwear\java-17-openjdk-17.0.6.0.10-1.win.x86_64\bin\java.exe -Dspring.profiles.active=dev,win -Dspring.output.ansi.enabled=always -Didea.launcher.port=29499 "-Didea.launcher.bin.path=C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.2\bin" -Dfile.encoding=UTF-8 -classpath "D:\workspace\2022\halo\build\classes\java\test;D:\workspace\2022\halo\build\resources\test;D:\workspace\2022\halo\build\classes\java\main;D:\workspace\2022\halo\build\resources\main;C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.2\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMainV2 run.halo.app.Application
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:104)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 3 more
```

### 附加信息

![image](https://user-images.githubusercontent.com/53547082/227727466-9853ad4f-0a53-4853-ac19-13513afddbd8.png)

**Comment by JohnNiang** [comment]
/kind support

是否有尝试用 Gradle 工具进行构建。IDEA 配置路径：`Preferences | Build, Execution, Deployment | Build Tools | Gradle`。

**Comment by wa3926** [comment]
@JohnNiang 
![image](https://user-images.githubusercontent.com/53547082/227815098-38287567-00e6-4753-bcee-989e36caa9c0.png)

**Comment by JohnNiang** [comment]
Hi @wa3926 ，

尝试直接执行以下命令：

```bash
./gradlew
```

**Comment by ruibaby** [comment]
如果没有后续动态，我暂时关闭此 issue，后续有补充可以随时打开。

/close
