### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by spider-warrior** [halo-dev/halo#3628]
### 是什么版本出现了此问题？

c9a5a01bf19fc0f437506ed4ab205096c57ade68

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

弹窗提示：
**登录失败，用户名或密码错误**

### 相关日志输出

```shell
2023-03-29T07:48:28.813Z ERROR 2395407 --- [or-http-epoll-3] o.s.w.s.adapter.HttpWebHandlerAdapter    : [2df1edde-22] Error [java.lang.UnsupportedOperationException] for HTTP POST "/login", but ServerHttpResponse already committed (401 UNAUTHORIZED)
2023-03-29T07:48:28.814Z ERROR 2395407 --- [or-http-epoll-3] r.n.http.server.HttpServerOperations     : [2df1edde-1, L:/127.0.0.1:8090 - R:/127.0.0.1:33910] Error finishing response. Closing connection

java.lang.UnsupportedOperationException: null
	at org.springframework.http.ReadOnlyHttpHeaders.set(ReadOnlyHttpHeaders.java:107) ~[spring-web-6.0.7.jar!/:6.0.7]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/login" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.http.ReadOnlyHttpHeaders.set(ReadOnlyHttpHeaders.java:107) ~[spring-web-6.0.7.jar!/:6.0.7]
		at org.springframework.http.HttpHeaders.setOrRemove(HttpHeaders.java:1693) ~[spring-web-6.0.7.jar!/:6.0.7]
		at org.springframework.http.HttpHeaders.setLocation(HttpHeaders.java:1325) ~[spring-web-6.0.7.jar!/:6.0.7]
		at org.springframework.security.web.server.DefaultServerRedirectStrategy.lambda$sendRedirect$0(DefaultServerRedirectStrategy.java:55) ~[spring-security-web-6.0.2.jar!/:6.0.2]
		at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49) ~[reactor-core-3.5.4.jar!/:3.5.4]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.4.jar!/:3.5.4]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[reactor-core-3.5.4.jar!/:3.5.4]
```

**Comment by JohnNiang** [comment]
/close

Close in favor of <https://github.com/halo-dev/halo/issues/3553>.
