### ISSUE TITLE
后台登录，输入账号密码进去后，设置站点名称的时候，后台log异常

### ISSUE THREAD

**Issue by rtsbtx** [halo-dev/halo#3856]
### 是什么版本出现了此问题？

image: halohub/halo:2.4

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

后台登录，输入账号密码进去后，设置站点名称的时候，后台log异常

### 相关日志输出

```shell
halo    | 2023-04-25T18:42:47.830+08:00  INFO 7 --- [         task-1] run.halo.app.search.IndicesInitializer   : Initialized post indices. Usage: StopWatch 'PostIndicesWatch': running time = 2209259708 ns; [rebuild] took 2209259708 ns = 100%
halo    | 2023-04-25T18:42:48.652+08:00  WARN 7 --- [gReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.SystemSettingReconciler-worker-1/Request[name=system-default]
halo    | 2023-04-25T18:42:48.761+08:00  WARN 7 --- [rReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.UserReconciler-worker-1/Request[name=root]
halo    | 2023-04-25T18:44:25.129+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-9> onResultSet - called without active query
halo    | 2023-04-25T18:44:25.153+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-6> onResultSet - called without active query
halo    | 2023-04-25T18:45:05.587+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-3> onResultSet - called without active query
halo    | 2023-04-25T18:45:05.875+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-5> onResultSet - called without active query
halo    | 2023-04-25T18:45:05.973+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-2> onResultSet - called without active query
halo    | 2023-04-25T18:45:06.370+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-11> onResultSet - called without active query
halo    | 2023-04-25T18:45:06.371+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-16> onResultSet - called without active query
halo    | 2023-04-25T18:45:06.797+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-14> onResultSet - called without active query
halo    | 2023-04-25T18:45:06.798+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-4> onResultSet - called without active query
halo    | 2023-04-25T18:45:06.907+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-13> onResultSet - called without active query
halo    | 2023-04-25T18:45:07.168+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-24> onResultSet - called without active query
halo    | 2023-04-25T18:45:15.717+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-18> onResultSet - called without active query
halo    | 2023-04-25T18:45:15.718+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-25> onResultSet - called without active query
halo    | 2023-04-25T18:45:15.854+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-21> onResultSet - called without active query
halo    | 2023-04-25T18:45:15.854+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-22> onResultSet - called without active query
halo    | 2023-04-25T18:45:15.914+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-20> onResultSet - called without active query
halo    | 2023-04-25T18:45:15.914+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-23> onResultSet - called without active query
halo    | 2023-04-25T18:45:16.414+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-28> onResultSet - called without active query
halo    | 2023-04-25T18:45:16.414+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-31> onResultSet - called without active query
halo    | 2023-04-25T18:45:16.822+08:00  WARN 7 --- [tReconciler-t-2] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PostReconciler-worker-2/Request[name=5152aea5-c2e8-4717-8bba-2263d46e19d5]
halo    | 2023-04-25T18:45:16.899+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-27> onResultSet - called without active query
halo    | 2023-04-25T18:45:16.900+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-26> onResultSet - called without active query
halo    | 2023-04-25T18:45:16.940+08:00  WARN 7 --- [tReconciler-t-2] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PostReconciler-worker-2/Request[name=5152aea5-c2e8-4717-8bba-2263d46e19d5]
halo    | 2023-04-25T18:45:17.061+08:00 ERROR 7 --- [-netty-thread-2] reactor.core.publisher.Operators         : Operator called default onErrorDropped
halo    | 
halo    | java.lang.RuntimeException: Async resource cleanup failed after onComplete
halo    |       at reactor.core.publisher.FluxUsingWhen$CommitInner.onError(FluxUsingWhen.java:520) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators.reportThrowInSubscribe(Operators.java:232) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4488) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:384) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:159) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmitScalar(FluxFlatMap.java:489) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:422) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxBuffer$BufferExactSubscriber.onComplete(FluxBuffer.java:185) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredComplete(FluxUsingWhen.java:392) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:531) ~[reactor-pool-1.0.0.jar:1.0.0]
halo    |       at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:761) ~[reactor-pool-1.0.0.jar:1.0.0]
halo    |       at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:873) ~[reactor-pool-1.0.0.jar:1.0.0]
halo    |       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:238) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2547) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:259) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onSubscribe(MonoIgnoreElements.java:72) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onSubscribe(FluxHandleFuseable.java:163) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxFilter$FilterSubscriber.onError(FluxFilter.java:157) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onError(FluxFilter.java:291) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:384) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:847) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:589) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:466) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerComplete(FluxConcatMapNoPrefetch.java:286) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onComplete(FluxConcatMap.java:887) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:121) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:64) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[na:na]
halo    |       at com.github.jasync.sql.db.util.FutureUtilsKt.success(FutureUtils.kt:16) ~[jasync-pool-2.1.23.jar:na]
halo    |       at com.github.jasync.sql.db.mysql.MySQLConnection.succeedQueryPromise$lambda-14(MySQLConnection.kt:421) ~[jasync-mysql-2.1.23.jar:na]
halo    |       at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
halo    |       at com.github.jasync.sql.db.mysql.MySQLConnection.succeedQueryPromise(MySQLConnection.kt:420) ~[jasync-mysql-2.1.23.jar:na]
halo    |       at com.github.jasync.sql.db.mysql.MySQLConnection.onResultSet(MySQLConnection.kt:432) ~[jasync-mysql-2.1.23.jar:na]
halo    |       at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.handleEOF(MySQLConnectionHandler.kt:447) ~[jasync-mysql-2.1.23.jar:na]
halo    |       at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.kt:131) ~[jasync-mysql-2.1.23.jar:na]
halo    |       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
halo    |       at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo    | Caused by: java.lang.IllegalArgumentException: Permalink must not be blank
halo    |       at org.springframework.util.Assert.hasText(Assert.java:294) ~[spring-core-6.0.7.jar:6.0.7]
halo    |       at run.halo.app.search.post.PostDoc.<init>(PostDoc.java:18) ~[api-2.4.3.jar:2.4.3]
halo    |       at run.halo.app.search.PostDocUtils.from(PostDocUtils.java:17) ~[classes/:2.4.3]
halo    |       at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:246) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:268) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.4.jar:3.5.4]
halo    |       ... 100 common frames omitted
halo    | 
halo    | 2023-04-25T18:45:17.339+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-19> onResultSet - called without active query
halo    | 2023-04-25T18:45:18.408+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-36> onResultSet - called without active query
halo    | 2023-04-25T18:45:18.426+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-40> onResultSet - called without active query
halo    | 2023-04-25T18:45:18.447+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-1> onResultSet - called without active query
halo    | 2023-04-25T18:45:18.893+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-30> onResultSet - called without active query
halo    | 2023-04-25T18:45:19.123+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-39> onResultSet - called without active query
halo    | 2023-04-25T18:45:19.406+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-37> onResultSet - called without active query
halo    | 2023-04-25T18:45:19.805+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginCommentWidget@1.5.0' resolved
halo    | 2023-04-25T18:45:19.807+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginSitemap@1.0.0' resolved
halo    | 2023-04-25T18:45:19.808+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginSearchWidget@1.0.0' resolved
halo    | 2023-04-25T18:45:19.809+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginFeed@1.0.0-beta.1' resolved
halo    | 2023-04-25T18:45:19.993+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-49> onResultSet - called without active query
halo    | 2023-04-25T18:45:20.006+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-51> onResultSet - called without active query
halo    | 2023-04-25T18:45:20.058+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-54> onResultSet - called without active query
halo    | 2023-04-25T18:45:20.583+08:00  WARN 7 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PluginReconciler-worker-1/Request[name=PluginSitemap]
halo    | 2023-04-25T18:45:20.639+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-48> onResultSet - called without active query
halo    | 2023-04-25T18:45:20.731+08:00  WARN 7 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PluginReconciler-worker-1/Request[name=PluginSearchWidget]
halo    | 2023-04-25T18:45:20.755+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-58> onResultSet - called without active query
halo    | 2023-04-25T18:45:20.941+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-60> onResultSet - called without active query
halo    | 2023-04-25T18:45:21.292+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginFeed@1.0.0-beta.1'
halo    | 2023-04-25T18:45:21.326+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginFeed
halo    | 2023-04-25T18:45:21.437+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginCommentWidget@1.5.0'
halo    | 2023-04-25T18:45:21.441+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginCommentWidget
halo    | 2023-04-25T18:45:21.606+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginSitemap@1.0.0'
halo    | 2023-04-25T18:45:21.644+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginSitemap
halo    | 2023-04-25T18:45:21.977+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginSearchWidget@1.0.0'
halo    | 2023-04-25T18:45:21.981+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginSearchWidget
```

**Comment by ruibaby** [comment]
页面上有异常提示或者使用异常吗？

/kind support
/triage needs-information

**Comment by rtsbtx** [comment]
> 页面上有异常提示或者使用异常吗？
> 
> /kind support /triage needs-information

页面上显示正常

**Comment by JohnNiang** [comment]
建议提供详细的复现步骤、安装步骤和环境信息，尤其是 MySQL 的版本。

**Comment by rtsbtx** [comment]
> 建议提供详细的复现步骤、安装步骤和环境信息，尤其是 MySQL 的版本。

使用的是官方部署文档上面的docker-compose.yaml，halo+mysql
