### ISSUE TITLE
异常log

### ISSUE THREAD

**Issue by rtsbtx** [halo-dev/halo#3860]
### 是什么版本出现了此问题？

image: halohub/halo:2.4

### 使用的什么数据库？

MYSQL 8.x

### 使用的哪种方式部署？

Docker Compose ，按照官方文档上halo+mysql部署

### 发生了什么？

好像是在操作附件，上传图片的时候发生异常，不太确定

### 相关日志输出

```shell
halo    | 2023-04-26T10:28:37.267+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-272> onResultSet - called without active query
halo    | 2023-04-26T10:28:37.448+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-279> onResultSet - called without active query
halo    | 2023-04-26T10:28:37.449+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-278> onResultSet - called without active query
halo    | 2023-04-26T10:28:56.227+08:00  WARN 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-281> onResultSet - called without active query
halo    | 2023-04-26T10:28:56.247+08:00  INFO 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-285> Transport failure after connection close: Buffer was not fully consumed by decoder, 1059 bytes to read
halo    | 2023-04-26T10:28:56.247+08:00 ERROR 7 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-285> Transport failure 
halo    | 
halo    | com.github.jasync.sql.db.exceptions.BufferNotFullyConsumedException: Buffer was not fully consumed by decoder, 1059 bytes to read
halo    |       at com.github.jasync.sql.db.mysql.binary.BinaryRowDecoder.decode(BinaryRowDecoder.kt:55) ~[jasync-mysql-2.1.23.jar:na]
halo    |       at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.kt:181) ~[jasync-mysql-2.1.23.jar:na]
halo    |       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
halo    |       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.90.Final.jar:4.1.90.Final]
halo    |       at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo    | 
halo    | 2023-04-26T10:28:56.256+08:00 ERROR 7 --- [-netty-thread-2]
```

**Comment by heyzqq** [comment]
我的 halo 日志也都是 `onResultSet - called without active query`，数据库是使用连接池的吗，这个日志刷屏了

**Comment by JohnNiang** [comment]
建议尝试一下：[Halo 2.6.0](https://github.com/halo-dev/halo/releases/tag/v2.6.0)。这个版本我们替换了 [R2DBC MySQL 驱动](https://github.com/halo-dev/halo/pull/3918)。

**Comment by JohnNiang** [comment]
/close

I'm going to close the issue due to no more feedback.
