### ISSUE TITLE
最新测试版 v1.1.3-beta.1 存在文件流未关闭问题

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo#387]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

---

由于备份博客的时候需要压缩目录，打开太多的文件而未关闭，从而导致以下错误：

```java
2019-11-19 09:05:01.329 ERROR 24651 --- [XNIO-1 Accept] org.xnio.nio.tcp.server                  : Exception accepting request, closing server channel TCP server (NIO) <2fa63774>

java.io.IOException: Too many open files
        at java.base/sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:525) ~[na:na]
        at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:277) ~[na:na]
        at org.xnio.nio.QueuedNioTcpServer.handleReady(QueuedNioTcpServer.java:467) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.nio.QueuedNioTcpServerHandle.handleReady(QueuedNioTcpServerHandle.java:38) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
```

进一步造成博客的 Socket 连接关闭，博客无法访问。

**Comment by JohnNiang** [comment]
最新错误情况：

```java
Caused by: java.nio.file.FileSystemException: /tmp/halo-backup: Too many open files
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432) ~[na:na]
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:474) ~[na:na]
        at java.base/java.nio.file.Files.list(Files.java:3769) ~[na:na]
        at run.halo.app.service.impl.BackupServiceImpl.listHaloBackups(BackupServiceImpl.java:172) ~[classes!/:1.1.3-beta.1]
```

**Comment by JohnNiang** [comment]
备份文件时触发错误：

```java
Caused by: java.nio.file.FileSystemException: /home/xxx/.halo: Too many open files
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432) ~[na:na]
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:474) ~[na:na]
        at java.base/java.nio.file.Files.list(Files.java:3769) ~[na:na]
        at run.halo.app.utils.FileUtils.zip(FileUtils.java:168) ~[classes!/:1.1.3-beta.1]
        at run.halo.app.utils.FileUtils.zip(FileUtils.java:146) ~[classes!/:1.1.3-beta.1]
        at run.halo.app.utils.FileUtils.zip(FileUtils.java:133) ~[classes!/:1.1.3-beta.1]
        at run.halo.app.service.impl.BackupServiceImpl.zipWorkDirectory(BackupServiceImpl.java:159) ~[classes!/:1.1.3-beta.1]
        ... 88 common frames omitted
```

**Comment by JohnNiang** [comment]
使用 `Files.list` 遍历文件的时候，需要关闭返回的 `Stream<Path>`。
