### ISSUE TITLE
在初始化时，预设插件可能无法正常安装和启动

### ISSUE THREAD

**Issue by ruibaby** [halo-dev/halo#3893]
### 是什么版本出现了此问题？

2.5.1

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式部署？

Docker Compose

### 在线站点地址

https://ryanc.cc

### 发生了什么？

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/21301288/236132780-0b9de4a3-6659-49ce-a251-75e8931b1525.png">

如图，有一定几率导致部分预设插件安装失败。

/kind bug
/area core
/milestone 2.6.x

### 相关日志输出

```shell
halo  | 2023-05-04T14:42:11.683+08:00  INFO 7 --- [tReconciler-t-1] org.wltea.analyzer.dic.Dictionary        : 加载扩展停止词典:org/wltea/analyzer/dic/stopword.dic
halo  | 2023-05-04T14:42:11.978+08:00 ERROR 7 --- [ctor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [7794b292-84]  500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/plugins/install"
halo  |
halo  | java.nio.file.ClosedFileSystemException: null
halo  | 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(Unknown Source) ~[jdk.zipfs:na]
halo  | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
halo  | Error has been observed at the following site(s):
halo  | 	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
halo  | 	*__checkpoint ⇢ HTTP POST "/apis/api.console.halo.run/v1alpha1/plugins/install" [ExceptionHandlingWebHandler]
halo  | Original Stack Trace:
halo  | 		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(Unknown Source) ~[jdk.zipfs:na]
halo  | 		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(Unknown Source) ~[jdk.zipfs:na]
halo  | 		at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(Unknown Source) ~[jdk.zipfs:na]
halo  | 		at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
halo  | 		at java.base/java.io.FilterInputStream.read(Unknown Source) ~[na:na]
halo  | 		at java.base/java.io.PushbackInputStream.read(Unknown Source) ~[na:na]
halo  | 		at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[na:na]
halo  | 		at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[na:na]
halo  | 		at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source) ~[na:na]
halo  | 		at java.base/java.io.InputStreamReader.read(Unknown Source) ~[na:na]
halo  | 		at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:176) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:112) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:155) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.yaml.snakeyaml.Yaml$1.hasNext(Yaml.java:494) ~[snakeyaml-1.33.jar:na]
halo  | 		at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:199) ~[spring-beans-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166) ~[spring-beans-6.0.8.jar:6.0.8]
halo  | 		at run.halo.app.infra.utils.YamlUnstructuredLoader.load(YamlUnstructuredLoader.java:44) ~[classes/:na]
halo  | 		at run.halo.app.plugin.YamlPluginFinder.unstructuredToPlugin(YamlPluginFinder.java:98) ~[classes/:2.5.0-SNAPSHOT]
halo  | 		at run.halo.app.plugin.YamlPluginFinder.readPluginDescriptor(YamlPluginFinder.java:89) ~[classes/:2.5.0-SNAPSHOT]
halo  | 		at run.halo.app.plugin.YamlPluginFinder.find(YamlPluginFinder.java:65) ~[classes/:2.5.0-SNAPSHOT]
halo  | 		at run.halo.app.core.extension.service.impl.PluginServiceImpl.lambda$getPresets$0(PluginServiceImpl.java:61) ~[classes/:2.5.0-SNAPSHOT]
halo  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:283) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxArray$ArrayConditionalSubscription.fastPath(FluxArray.java:340) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxArray$ArrayConditionalSubscription.request(FluxArray.java:263) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxFilter$FilterSubscriber.request(FluxFilter.java:186) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxFilter$FilterSubscriber.onSubscribe(FluxFilter.java:85) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:50) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:59) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.Mono.subscribe(Mono.java:4470) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:240) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.checkTerminated(FluxWindowPredicate.java:540) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.drainLoop(FluxWindowPredicate.java:488) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.drain(FluxWindowPredicate.java:432) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onComplete(FluxWindowPredicate.java:312) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:460) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:805) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:753) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:247) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:213) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:204) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.emitComplete(MultipartParser.java:185) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser$HeadersState.onNext(MultipartParser.java:383) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser$BodyState.onNext(MultipartParser.java:562) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser$HeadersState.onNext(MultipartParser.java:398) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser$BodyState.onNext(MultipartParser.java:562) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser$HeadersState.onNext(MultipartParser.java:398) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser$PreambleState.onNext(MultipartParser.java:328) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.hookOnNext(MultipartParser.java:120) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.hookOnNext(MultipartParser.java:52) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:160) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292) ~[reactor-netty-core-1.1.6.jar:1.1.6]
halo  | 		at reactor.netty.channel.FluxReceive.request(FluxReceive.java:131) ~[reactor-netty-core-1.1.6.jar:1.1.6]
halo  | 		at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.BaseSubscriber.request(BaseSubscriber.java:214) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.requestBuffer(MultipartParser.java:193) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at org.springframework.http.codec.multipart.MultipartParser.hookOnSubscribe(MultipartParser.java:114) ~[spring-web-6.0.8.jar:6.0.8]
halo  | 		at reactor.core.publisher.BaseSubscriber.onSubscribe(BaseSubscriber.java:148) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:171) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.5.jar:3.5.5]
halo  | 		at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:170) ~[reactor-netty-core-1.1.6.jar:1.1.6]
halo  | 		at reactor.netty.channel.FluxReceive.lambda$subscribe$2(FluxReceive.java:148) ~[reactor-netty-core-1.1.6.jar:1.1.6]
halo  | 		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
halo  | 		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
halo  | 		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
halo  | 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
halo  | 		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
halo  | 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
halo  | 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
halo  | 		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  |
halo  | 2023-05-04T14:42:12.062+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginSitemap@1.0.2' resolved
halo  | 2023-05-04T14:42:12.101+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginCommentWidget@1.5.0' resolved
halo  | 2023-05-04T14:42:12.165+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginSearchWidget@1.0.0' resolved
```

**Comment by ruibaby** [comment]
/assign

我将尝试在 Console 端进行重试操作。
