### ISSUE TITLE
2.4->2.5  升级启动

### ISSUE THREAD

**Issue by rtsbtx** [halo-dev/halo#3900]
### 是什么版本出现了此问题？

2.5

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

log exception

### 相关日志输出

```shell
halo    | 2023-05-05T16:07:58.174+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginCommentWidget@1.5.0' resolved
halo    | 2023-05-05T16:07:59.216+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginCommentWidget@1.5.0'
halo    | 2023-05-05T16:07:59.235+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginCommentWidget
halo    | 2023-05-05T16:08:00.877+08:00  INFO 7 --- [-netty-thread-2] org.wltea.analyzer.dic.Dictionary        : 加载扩展停止词典:org/wltea/analyzer/dic/stopword.dic
halo    | 2023-05-05T16:08:01.457+08:00  INFO 7 --- [         task-1] run.halo.app.search.IndicesInitializer   : Initialized post indices. Usage: StopWatch 'PostIndicesWatch': running time = 7311680421 ns; [rebuild] took 7311680421 ns = 100%
halo    | 2023-05-05T16:08:01.673+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginSitemap@1.0.0' resolved
halo    | 2023-05-05T16:08:01.964+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginSitemap@1.0.0'
halo    | 2023-05-05T16:08:01.978+08:00  WARN 7 --- [nReconciler-t-1] r.h.app.plugin.PluginApplicationContext  : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run.halo.sitemap.CachedSitemapGetter': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo    | 2023-05-05T16:08:01.979+08:00 ERROR 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Unable to start plugin 'PluginSitemap@1.0.0'
halo    | 
halo    | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run.halo.sitemap.CachedSitemapGetter': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-6.0.8.jar:6.0.8]
halo    |       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.8.jar:6.0.8]
halo    |       at run.halo.app.plugin.PluginApplicationInitializer.initApplicationContext(PluginApplicationInitializer.java:105) ~[classes/:2.5.2]
halo    |       at run.halo.app.plugin.PluginApplicationInitializer.onStartUp(PluginApplicationInitializer.java:124) ~[classes/:2.5.2]
halo    |       at run.halo.app.plugin.HaloPluginManager.doStartPlugin(HaloPluginManager.java:265) ~[classes/:2.5.2]
halo    |       at run.halo.app.plugin.HaloPluginManager.startPlugin(HaloPluginManager.java:216) ~[classes/:2.5.2]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$doStart$15(PluginReconciler.java:420) ~[classes/:2.5.2]
halo    |       at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.doStart(PluginReconciler.java:416) ~[classes/:2.5.2]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startAction$11(PluginReconciler.java:268) ~[classes/:2.5.2]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.stateTransition(PluginReconciler.java:302) ~[classes/:2.5.2]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.startAction(PluginReconciler.java:262) ~[classes/:2.5.2]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcilePluginState$17(PluginReconciler.java:522) ~[classes/:2.5.2]
halo    |       at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:511) ~[classes/:2.5.2]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:105) ~[classes/:2.5.2]
halo    |       at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:93) ~[classes/:2.5.2]
halo    |       at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:75) ~[classes/:2.5.2]
halo    |       at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.5.2.jar:na]
halo    |       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo    |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo    |       at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo    | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       ... 35 common frames omitted
halo    | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:493) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       ... 49 common frames omitted
halo    | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo    |       at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       ... 63 common frames omitted
halo    | Caused by: java.lang.IllegalArgumentException: URI is not absolute
halo    |       at java.base/java.net.URL.fromURI(Unknown Source) ~[na:na]
halo    |       at java.base/java.net.URI.toURL(Unknown Source) ~[na:na]
halodb  | 2023-05-05 08:07:28+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
halodb  | 2023-05-05 08:07:28+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
halodb  | 2023-05-05 08:07:28+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
halodb  | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
halodb  | 2023-05-05T08:07:29.027544Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
halodb  | 2023-05-05T08:07:29.029333Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
halodb  | 2023-05-05T08:07:29.029361Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.31) starting as process 1
halodb  | 2023-05-05T08:07:29.035939Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
halodb  | 2023-05-05T08:07:29.993675Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
halodb  | 2023-05-05T08:07:30.478771Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
halodb  | 2023-05-05T08:07:30.478813Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
halodb  | 2023-05-05T08:07:30.480831Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
halodb  | 2023-05-05T08:07:30.505831Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.31'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
halodb  | 2023-05-05T08:07:30.505876Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
halo    |       at run.halo.sitemap.SitemapPluginConfig.sitemapGeneratorOptions(SitemapPluginConfig.java:36) ~[na:na]
halo    |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
halo    |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo    |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo    |       at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
halo    |       at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.8.jar:6.0.8]
halo    |       ... 64 common frames omitted
halo    | 
halo    | 2023-05-05T16:08:02.376+08:00 ERROR 7 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
halo    |
```

**Comment by ruibaby** [comment]
升级 sitemap 插件即可。

https://github.com/halo-sigs/plugin-sitemap/releases

/kind support

**Comment by rtsbtx** [comment]
> 升级 sitemap 插件即可。
> 
> https://github.com/halo-sigs/plugin-sitemap/releases
> 
> /kind support

升级插件功能好像用不了，怎么升级版本号都没变化，最后是卸载重新安装，版本号才显示1.0.2

**Comment by ruibaby** [comment]
> 升级插件功能好像用不了，怎么升级版本号都没变化，最后是卸载重新安装，版本号才显示1.0.2

这个似乎是因为插件异常之后就无法更新，只能卸载重装，如果可以请新提交一个 issue。

/close
