### ISSUE TITLE
项目更改 R2DBC 数据库连接程序后无法运行在arm服务器上

### ISSUE THREAD

**Issue by laiqinghua** [halo-dev/halo#4034]
### 是什么版本出现了此问题？

2.5

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

你们项目更改 R2DBC 数据库连接程序后无法运行在arm服务器上
因为R2DBC 数据库连接程序这个是x86架构的包 

### 相关日志输出

```shell
2023-06-04T02:01:42.664177480+08:00     __  __      __
2023-06-04T02:01:42.664181760+08:00    / / / /___ _/ /___
2023-06-04T02:01:42.664185480+08:00   / /_/ / __ `/ / __ \
2023-06-04T02:01:42.664188000+08:00  / __  / /_/ / / /_/ /
2023-06-04T02:01:42.664190360+08:00 /_/ /_/\__,_/_/\____/

Version: 2.5.2
2023-06-04T02:01:42.955+08:00  INFO 6 --- [           main] run.halo.app.Application                 : Starting Application v2.5.2 using Java 17.0.7 with PID 6 (/application/BOOT-INF/classes started by root in /application)
2023-06-04T02:01:42.960619160+08:00 2023-06-04T02:01:42.960+08:00  INFO 6 --- [           main] run.halo.app.Application                 : No active profile set, falling back to 1 default profile: "default"
2023-06-04T02:01:48.655296520+08:00 2023-06-04T02:01:48.654+08:00  INFO 6 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2023-06-04T02:01:48.657355640+08:00 2023-06-04T02:01:48.657+08:00  INFO 6 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data R2DBC repositories in DEFAULT mode.
2023-06-04T02:01:49.373855560+08:00 2023-06-04T02:01:49.373+08:00  INFO 6 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 703 ms. Found 1 R2DBC repository interfaces.
2023-06-04T02:01:52.955419200+08:00 2023-06-04T02:01:52.955+08:00  INFO 6 --- [           main] c.g.j.r.m.MysqlConnectionFactoryProvider : set jasync.mysql.CLIENT_FOUND_ROWS=true
2023-06-04T02:01:52.985714080+08:00 2023-06-04T02:01:52.985+08:00  INFO 6 --- [           main] c.github.jasync.sql.db.util.NettyUtils   : jasync selected transport - nio
2023-06-04T02:01:58.876681560+08:00 2023-06-04T02:01:58.875+08:00  INFO 6 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Enabled plugins: []
2023-06-04T02:01:58.877565960+08:00 2023-06-04T02:01:58.877+08:00  INFO 6 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Disabled plugins: []
2023-06-04T02:01:58.880314160+08:00 2023-06-04T02:01:58.880+08:00  INFO 6 --- [           main] org.pf4j.DefaultPluginManager            : PF4J version 3.9.0 in 'deployment' mode
2023-06-04T02:02:05.763003280+08:00 2023-06-04T02:02:05.762+08:00  INFO 6 --- [    
       main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 5 endpoint(s) beneath base path '/actuator'
2023-06-04T02:02:07.374+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-1> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.653984520+08:00 2023-06-04T02:02:07.653+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-2> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.655168280+08:00 2023-06-04T02:02:07.654+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-3> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.656071760+08:00 2023-06-04T02:02:07.655+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-4> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.656817640+08:00 2023-06-04T02:02:07.656+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-5> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.657643040+08:00 2023-06-04T02:02:07.657+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-6> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.658+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-7> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.659209040+08:00 2023-06-04T02:02:07.659+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-8> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.659927720+08:00 2023-06-04T02:02:07.659+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-9> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.660589320+08:00 2023-06-04T02:02:07.660+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-10> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (using password: YES))
2023-06-04T02:02:07.661128280+08:00 2023-06-04T02:02:07.660+08:00  WARN 6 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/R2dbcInitializationConfiguration.class]: Failed to execute database script
2023-06-04T02:02:07.661657800+08:00 2023-06-04T02:02:07.661+08:00 ERROR 6 --- [-netty-thread-2] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-11> Received an error message -> ErrorMessage(errorCode=1045, sqlState=#28000, errorMessage=Access denied for user 'halo'@'172.17.0.1' (us
ing password: YES))
2023-06-04T02:02:07.663342360+08:00 2023-06-04T02:02:07.663+08:00  INFO 6 --- [           main] r.h.a.e.c.DefaultControllerManager       : Shutting down 0 controllers...
2023-06-04T02:02:07.665118600+08:00 2023-06-04T02:02:07.664+08:00  INFO 6 --- [           main] r.h.a.e.c.DefaultControllerManager       : Shutdown 0 controllers.
2023-06-04T02:02:07.665603600+08:00 2023-06-04T02:02:07.665+08:00  INFO 6 --- [           main] r.h.a.e.controller.DefaultController     : Disposing controller garbage-collector-controller
2023-06-04T02:02:07.665747760+08:00 2023-06-04T02:02:07.665+08:00  INFO 6 --- [           main] r.h.a.e.controller.DefaultController     : Controller garbage-collector-controller is disposed
2023-06-04T02:02:07.778311200+08:00 2023-06-04T02:02:07.777+08:00  INFO 6 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
2023-06-04T02:02:07.778467200+08:00 
2023-06-04T02:02:07.778473480+08:00 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-06-04T02:02:07.953410920+08:00 2023-06-04T02:02:07.871+08:00 ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application run failed
2023-06-04T02:02:07.953437760+08:00 
2023-06-04T02:02:07.953457840+08:00 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/R2dbcInitializationConfiguration.class]: Failed to execute database script
2023-06-04T02:02:07.953472680+08:00 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953478360+08:00 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953480920+08:00 	at org.springf
ramework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953483600+08:00 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953485920+08:00 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953488640+08:00 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953494240+08:00 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953496600+08:00 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953499000+08:00 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953501240+08:00 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953503400+08:00 	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953505600+08:00 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953507880+08:00 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953510880+08:00 	at org.springframework.boot.S
pringApplication.run(SpringApplication.java:310) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953513080+08:00 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953515360+08:00 	at run.halo.app.Application.main(Application.java:28) ~[classes/:2.5.2]
2023-06-04T02:02:07.953517680+08:00 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2023-06-04T02:02:07.953519760+08:00 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2023-06-04T02:02:07.953521920+08:00 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
2023-06-04T02:02:07.953524040+08:00 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2023-06-04T02:02:07.953526440+08:00 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
2023-06-04T02:02:07.953528600+08:00 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[application/:na]
2023-06-04T02:02:07.953530720+08:00 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
2023-06-04T02:02:07.953535920+08:00 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[application/:na]
2023-06-04T02:02:07.953538360+08:00 Caused by: org.springframework.r2dbc.connection.init.UncategorizedScriptException: Failed to execute database script
2023-06-04T02:02:07.953540600+08:00 	at org.springframework.r2dbc.connection.init.DatabasePopulator.lambda$populate$4(DatabasePopulator.java:65) ~[spring-r2dbc-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953542920+08:00 	at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3759) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953545080+08:00 	at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3849) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953547400+08:00 	at reactor.core.publisher.FluxOnErr
orResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953553040+08:00 	at reactor.core.publisher.MonoUsingWhen$ResourceSubscriber.onError(MonoUsingWhen.java:203) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953555720+08:00 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953558000+08:00 	at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953560320+08:00 	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953562520+08:00 	at reactor.core.publisher.Mono.subscribe(Mono.java:4485) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953564840+08:00 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953567120+08:00 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953569640+08:00 	at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:95) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953571880+08:00 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953574080+08:00 	at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475) ~[reactor-pool-1.0.0.jar:1.0.0]
2023-06-04T02:02:07.953576280+08:00 	at reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:429) ~[reactor-pool-1.0.0.jar:1.0.0]
2023-06-04T02:02:07.953578520+08:00 	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953580680+08:00 	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02
:07.953582920+08:00 	at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:119) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953585120+08:00 	at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:71) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953587360+08:00 	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source) ~[na:na]
2023-06-04T02:02:07.953589520+08:00 	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source) ~[na:na]
2023-06-04T02:02:07.953591600+08:00 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[na:na]
2023-06-04T02:02:07.953593800+08:00 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[na:na]
2023-06-04T02:02:07.953596160+08:00 	at com.github.jasync.sql.db.util.FutureUtilsKt.failed(FutureUtils.kt:18) ~[jasync-pool-2.1.23.jar:na]
2023-06-04T02:02:07.953600720+08:00 	at com.github.jasync.sql.db.mysql.MySQLConnection.setException(MySQLConnection.kt:217) ~[jasync-mysql-2.1.23.jar:na]
2023-06-04T02:02:07.953603080+08:00 	at com.github.jasync.sql.db.mysql.MySQLConnection.onError(MySQLConnection.kt:212) ~[jasync-mysql-2.1.23.jar:na]
2023-06-04T02:02:07.953605360+08:00 	at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.kt:128) ~[jasync-mysql-2.1.23.jar:na]
2023-06-04T02:02:07.953607680+08:00 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953609920+08:00 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953612160+08:00 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.
Final]
2023-06-04T02:02:07.953614400+08:00 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953616640+08:00 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953618800+08:00 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953623120+08:00 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953625400+08:00 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953627720+08:00 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953631200+08:00 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953633560+08:00 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953638160+08:00 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953640600+08:00 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953642920+08:00 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.91.Final.j
ar:4.1.91.Final]
2023-06-04T02:02:07.953645280+08:00 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953647440+08:00 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953649800+08:00 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953651960+08:00 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953654120+08:00 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953660200+08:00 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.91.Final.jar:4.1.91.Final]
2023-06-04T02:02:07.953663120+08:00 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
	Suppressed: java.lang.Exception: #block terminated with an error
2023-06-04T02:02:07.953667480+08:00 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953669640+08:00 		at reactor.core.publisher.Mono.block(Mono.java:1710) ~[reactor-core-3.5.5.jar:3.5.5]
2023-06-04T02:02:07.953671960+08:00 		at org.springframework.boot.r2dbc.init.R2dbcScriptDatabaseInitializer.runScripts(R2dbcScriptDatabaseInitializer.java:68) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953674440+08:00 		at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.runScripts(AbstractScriptDatabaseInitializer.java:146) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953676600+08:00 		at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyScripts(AbstractScriptDatabaseInitializer.java:108) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953678760+08:00 		at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applySchemaScripts(AbstractScriptDatabaseInitializer.java:98) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953680960+08:00 		at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:76) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953683040+08:00 		at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.afterPropertiesSet(AbstractScriptDatabaseInitializer.java:66) ~[spring-boot-3.0.6.jar:3.0.6]
2023-06-04T02:02:07.953685720+08:00 		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953687840+08:00 		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953690240+08:00 		at or
g.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953692320+08:00 		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953694680+08:00 		at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953696920+08:00 		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953699120+08:00 		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.8.jar:6.0.8]
2023-06-04T02:02:07.953702480+08:00 		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.8.jar:6.0.8]
```

**Comment by ruibaby** [comment]
> 你们项目更改 R2DBC 数据库连接程序后无法运行在arm服务器上

想知道这个结论是如何得出的，我觉得这个日志才是重点：

```
Access denied for user 'halo'@'172.17.0.1' (using password: YES)
```

这个日志要么是无法链接到 MySQL 服务，要么是用户名密码错误。

此外，在我的 Arm 架构的电脑上运行没有任何问题。

/triage needs-information

**Comment by laiqinghua** [comment]
经过验证确实是我的问题，因为无法连接数据库导致的问题。
