### ISSUE TITLE
docker版无法使用SMTP发信

### ISSUE THREAD

**Issue by samondlee** [halo-dev/halo#407]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

配置信息如下
SMTP 地址：
smtp.exmail.qq.com
发送协议：
smtp
SSL 端口：
465
邮箱账号：

相同的设置在wordpress下可以发信

halo直接提示发信失败请检查smtp设置

**Comment by ruibaby** [comment]
可否提供下日志。在 ~/.halo/logs/spring.log

**Comment by samondlee** [comment]
> 可否提供下日志。在 ~/.halo/logs/spring.log

群晖映射卷如下，目录有没有发现日志

是不是要在~/.halo 后面加/
![捕获](https://user-images.githubusercontent.com/8521327/69841879-ee920800-129b-11ea-9f26-4063378a38c8.PNG)

**Comment by ruibaby** [comment]
不用呀

**Comment by samondlee** [comment]
> 不用呀

Emmmm奇怪，目录下没有发现日志，我再研究一下怎么让他写日志emmmm

另外用电脑访问后台可以访问，用手机访问的时候
http://halo:9988/admin/index.html

提示 无法访问响应时间过长。。。
首页正常，不知道是不是故意这样设置的。。。

我是用群晖搭的docker用局域网另一台服务器 反代的emmmm

**Comment by JohnNiang** [comment]
> > 可否提供下日志。在 ~/.halo/logs/spring.log
> 
> 群晖映射卷如下，目录有没有发现日志
> 
> 是不是要在~/.halo 后面加/
> ![捕获](https://user-images.githubusercontent.com/8521327/69841879-ee920800-129b-11ea-9f26-4063378a38c8.PNG)

可能需要加上 /

**Comment by samondlee** [comment]
> > > 可否提供下日志。在 ~/.halo/logs/spring.log
> > 
> > 
> > 群晖映射卷如下，目录有没有发现日志
> > 是不是要在~/.halo 后面加/
> > ![捕获](https://user-images.githubusercontent.com/8521327/69841879-ee920800-129b-11ea-9f26-4063378a38c8.PNG)
> 
> 可能需要加上 /

EMMM 加上了，并且给目录everyone控制权限了，还是没有日志导出。

使用SMTP发信是不是还要开什么端口。。。我只开了8090

**Comment by guqing** [comment]
@samondlee 把你的配置application.yml配置文件贴出来看看，记得把里面的密码清了在贴出来

**Comment by samondlee** [comment]
> @samondlee 把你的配置application.yml配置文件贴出来看看，记得把里面的密码清了在贴出来
都是默认的 没有改过

server:
  port: 8090
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 Database 配置，如果你需要使用 MySQL，请注释掉该配置并取消注释 MySQL 的配置。
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.halo/db/halo
    username: admin
    password: 231124214123123123
    # MySQL 配置，如果你需要使用 H2Database，请注释掉该配置并取消注释上方 H2Database 的配置。
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    password: 321312321321312312312312

  # H2 Database 的控制台相关配置，如果你使用的是 MySQL ，请注释掉下方内容。
  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false

**Comment by JohnNiang** [comment]
从错误详情来看，是你的 smtp 的地址填写错误导致的吧。

**Comment by JohnNiang** [comment]
@samondlee https://service.exmail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1000585

**Comment by JohnNiang** [comment]
> > > > 可否提供下日志。在 ~/.halo/logs/spring.log
> > > 
> > > 
> > > 群晖映射卷如下，目录有没有发现日志
> > > 是不是要在~/.halo 后面加/
> > > ![捕获](https://user-images.githubusercontent.com/8521327/69841879-ee920800-129b-11ea-9f26-4063378a38c8.PNG)
> > 
> > 
> > 可能需要加上 /
> 
> EMMM 加上了，并且给目录everyone控制权限了，还是没有日志导出。
> 
> 使用SMTP发信是不是还要开什么端口。。。我只开了8090
> 
> ```java
> io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.0.23.Final.jar!/:2.0.23.Final]
> 
> 	Caused by: io.github.biezhi.ome.SendMailException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.exmail.qq.com, 587; timeout -1; 
> 	Caused by: java.net.UnknownHostException: ssl://smtp.exmail.qq.com
> 	Caused by: io.github.biezhi.ome.SendMailException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: ssl://smtp.exmail.qq.com, 465; timeout -1;
> ```
> 
> docker镜像的日志只有这样的
> 
> 感觉就像是DOCKER无法与外网通信的样子= = docker 我可以确定在群晖防火墙上打开了8090 访问权限

这里的装载路径应该是： `/root/.halo` 而不是 `/.halo`

**Comment by samondlee** [comment]
> > > > > 可否提供下日志。在 ~/.halo/logs/spring.log
> > > > 
> > > > 
> > > > 群晖映射卷如下，目录有没有发现日志
> > > > 是不是要在~/.halo 后面加/
> > > > ![捕获](https://user-images.githubusercontent.com/8521327/69841879-ee920800-129b-11ea-9f26-4063378a38c8.PNG)
> > > 
> > > 
> > > 可能需要加上 /
> > 
> > 
> > EMMM 加上了，并且给目录everyone控制权限了，还是没有日志导出。
> > 使用SMTP发信是不是还要开什么端口。。。我只开了8090
> > ```java
> > io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.0.23.Final.jar!/:2.0.23.Final]
> > 
> > 	Caused by: io.github.biezhi.ome.SendMailException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.exmail.qq.com, 587; timeout -1; 
> > 	Caused by: java.net.UnknownHostException: ssl://smtp.exmail.qq.com
> > 	Caused by: io.github.biezhi.ome.SendMailException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: ssl://smtp.exmail.qq.com, 465; timeout -1;
> > ```
> > 
> > 
> > docker镜像的日志只有这样的
> > 感觉就像是DOCKER无法与外网通信的样子= = docker 我可以确定在群晖防火墙上打开了8090 访问权限
> 
> 这里的装载路径应该是： `/root/.halo` 而不是 `/.halo`

2333 按照大佬的装在路径现在有log了
我把它上传上来
smtp.exmail.qq.com填写的没错呀= =
[spring.log](https://github.com/halo-dev/halo/files/3904276/spring.log)

**Comment by JohnNiang** [comment]
@samondlee 确认你的服务器能上网？错误详情是没办法解析 smtp... 域名。

**Comment by samondlee** [comment]
> @samondlee 确认你的服务器能上网？错误详情是没办法解析 smtp... 域名。

emmm 外网可以正常访问呀,内网用的OVERTURE DNS= =而且 同一台机器的非DOCKER WORDPRESS可以发信emmm
给DOCKER的 8090也打开端口了 是不是还需要打开额外的端口= =

我在改一下DNS试试= =

**Comment by JohnNiang** [comment]
@samondlee 推荐你在本地运行试试。

**Comment by joune90** [comment]
我也发不了邮件，有没有大佬帮忙看看

**Comment by joune90** [comment]
Exception in thread "pool-4-thread-3" run.halo.app.exception.EmailException: 邮件发送失败，请检查 SMTP 服务配置是否正确
        at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:114)
        at run.halo.app.mail.AbstractMailService.lambda$sendMailTemplate$0(AbstractMailService.java:128)
        at run.halo.app.mail.AbstractMailService$$Lambda$1273/0x00000000b8041110.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:823)
Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: stmp.qq.com, 587; timeout -1;
  nested exception is:
        java.net.UnknownHostException: stmp.qq.com. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: stmp.qq.com, 587; timeout -1;
  nested exception is:
        java.net.UnknownHostException: stmp.qq.com; message exceptions (1) are:
Failed message 1: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: stmp.qq.com, 587; timeout -1;
  nested exception is:
        java.net.UnknownHostException: stmp.qq.com
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
        at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:107)

**Comment by joune90** [comment]
Caused by: org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: smtp.exmail.qq.com, port: 587;
  nested exception is:
        javax.net.ssl.SSLException: Unsupported or unrecognized SSL message. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: smtp.exmail.qq.com, port: 587;
  nested exception is:
        javax.net.ssl.SSLException: Unsupported or unrecognized SSL message; message exceptions (1) are:
Failed message 1: javax.mail.MessagingException: Could not connect to SMTP host: smtp.exmail.qq.com, port: 587;
  nested exception is:
        javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:448)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
        at run.halo.app.mail.AbstractMailService.sendMailTemplate(AbstractMailService.java:107)
        ... 5 more
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.exmail.qq.com, port: 587;
  nested exception is:
        javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2212)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
        at javax.mail.Service.connect(Service.java:342)
        at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
        ... 8 more
Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:448)
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:184)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)

**Comment by JohnNiang** [comment]
@joune90 https://service.exmail.qq.com/cgi-bin/help?subtype=1&id=28&no=1000585

**Comment by Jonathanmns** [comment]
大佬们，这个问题解决了吗？我也是都设置没问题了但不知道怎么的都上不去～看了上面的内容也不成
