### ISSUE TITLE
docker-compose up -d 启动后 Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister

### ISSUE THREAD

**Issue by blankhang** [halo-dev/halo#4094]
### 是什么版本出现了此问题？

2.6

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker Compose

### 发生了什么？

启动日志报错 但网站能正常打开运行

### 相关日志输出

```shell
halo  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	... 35 common frames omitted
halo  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:493) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	... 49 common frames omitted
halo  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	... 63 common frames omitted
halo  | Caused by: java.lang.IllegalArgumentException: URI is not absolute
halo  | 	at java.base/java.net.URL.fromURI(Unknown Source) ~[na:na]
halo  | 	at java.base/java.net.URI.toURL(Unknown Source) ~[na:na]
halo  | 	at run.halo.sitemap.SitemapPluginConfig.sitemapGeneratorOptions(SitemapPluginConfig.java:36) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
halo  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.9.jar:6.0.9]
halo  | 	... 64 common frames omitted
halo  | 
halo  | 2023-06-19T14:33:18.231+08:00 ERROR 7 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
halo  | 
halo  | java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.CachedSitemapGetter': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$doStart$15(PluginReconciler.java:424) ~[classes/:2.6.0]
halo  | 	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.doStart(PluginReconciler.java:416) ~[classes/:2.6.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startAction$11(PluginReconciler.java:268) ~[classes/:2.6.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.stateTransition(PluginReconciler.java:302) ~[classes/:2.6.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.startAction(PluginReconciler.java:262) ~[classes/:2.6.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcilePluginState$17(PluginReconciler.java:522) ~[classes/:2.6.0]
halo  | 	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:511) ~[classes/:2.6.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:105) ~[classes/:2.6.0]
halo  | 	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:93) ~[classes/:2.6.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:75) ~[classes/:2.6.0]
halo  | 	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.6.0.jar:na]
halo  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### 附加信息

![image](https://github.com/halo-dev/halo/assets/3981276/7f526aaa-d7b6-4c86-9636-1e289d5fb6ca)

**Comment by JohnNiang** [comment]
/triage needs-information

建议提供一下具体的复现步骤。最重要的是 sitemap 插件的版本。

**Comment by ruibaby** [comment]
此 issue 已经没有后续动态，我将关闭此 issue。

/close
