### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by spider-warrior** [halo-dev/halo#4134]
### 是什么版本出现了此问题？

d0526ec592a73178fabf8226b05a58f528c656b6

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

登录报错

### 相关日志输出

```shell
2023-06-28T14:34:32.111+08:00 ERROR 32781 --- [oundedElastic-3] a.w.r.e.AbstractErrorWebExceptionHandler : [279a4c55-26]  500 Server Error for HTTP POST "/login"

java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
	at run.halo.app.infra.utils.IpAddressUtils.getClientIp(IpAddressUtils.java:49) ~[classes!/:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/login" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at run.halo.app.infra.utils.IpAddressUtils.getClientIp(IpAddressUtils.java:49) ~[classes!/:na]
		at run.halo.app.security.authentication.login.UsernamePasswordAuthenticator.createIPBasedRateLimiter(UsernamePasswordAuthenticator.java:124) ~[classes!/:2.7.0-SNAPSHOT]
		at run.halo.app.security.authentication.login.UsernamePasswordAuthenticator$UsernamePasswordAuthenticationWebFilter.onAuthenticationSuccess(UsernamePasswordAuthenticator.java:170) ~[classes!/:2.7.0-SNAPSHOT]
		at org.springframework.security.web.server.authentication.AuthenticationWebFilter.lambda$authenticate$7(AuthenticationWebFilter.java:124) ~[spring-security-web-6.1.0.jar!/:6.1.0]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.6.jar!/:3.5.6]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by JohnNiang** [comment]
/kind bug
/area core

感谢提交这个问题！

目前我们在 Kubernetes （IngressController 为 Traefik）环境中也遇到类似的问题。

该问题是在 https://github.com/halo-dev/halo/pull/4062 中产生的，主要是因为没有获取 `X-Real-IP` header，导致无法从 headers 中获取 IP 地址，最终只能获取 `java.net.InetAddress.getHostAddress()`，但尚不清楚为什么它是 null。
