### ISSUE TITLE
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL

### ISSUE THREAD

**Issue by liuguoping1024** [halo-dev/halo#417]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/docs)
- [x] [Halo 论坛](https://bbs.halo.run)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [x] 请求技术支持

以下为场景：

- 腾讯云
- Linux:
Linux VM_0_3_centos 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- MySQL:
Package 1:mariadb-server-5.5.64-1.el7.x86_64 already installed and latest version

问题:
2019-12-10 15:25:36.320  INFO 5060 --- [main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.10.Final}
2019-12-10 15:25:36.334  INFO 5060 --- [main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2019-12-10 15:25:36.894  INFO 5060 --- [main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
2019-12-10 15:25:37.924  INFO 5060 --- [main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2019-12-10 15:25:41.364  WARN 5060 --- [main] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL "create table attachments (id integer not null auto_increment, create_time timestamp default CURRENT_TIMESTAMP, deleted TINYINT default 0, update_time timestamp default CURRENT_TIMESTAMP, file_key varchar(2047) default '', height int default 0, media_type varchar(50) not null, name varchar(255) not null, path varchar(1023) not null, size bigint not null, suffix varchar(50) default '', thumb_path varchar(1023) default '', type int default 0, width int default 0, primary key (id)) engine=MyISAM" via JDBC Statement

**org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table** attachments (id integer not null auto_increment, create_time timestamp default CURRENT_TIMESTAMP, deleted TINYINT default 0, update_time timestamp default CURRENT_TIMESTAMP, file_key varchar(2047) default '', height int default 0, media_type varchar(50) not null, name varchar(255) not null, path varchar(1023) not null, size bigint not null, suffix varchar(50) default '', thumb_path varchar(1023) default '', type int default 0, width int default 0, primary key (id)) **engine=MyISAM**" via JDBC Statement
        at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67) ~[hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]
        at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:559) [hibernate-core-5.3.10.Final.jar!/:5.3.10.Final]

请问有什么建议？

**Comment by ruibaby** [comment]
@liuguoping1024 mysql 5.7+

**Comment by liuguoping1024** [comment]
可是centos上没有mysql，只有mariadb，咋办？

下面的也没有用：
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MariaDBDialect
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect

**Comment by JohnNiang** [comment]
建议先用 h2 跑起来，体验体验。

**Comment by ruibaby** [comment]
没有 MySQL 是什么意思，没有 MySQL 的 yum 源吗？，那也有其他方法安装 MySQL 呀，MariaDB 我们目前还没测试过...

同上，建议直接用 h2。

**Comment by JohnNiang** [comment]
@liuguoping1024 你可以删除 application.yml 重启，先体验一下。不建议做无谓的折腾。

**Comment by liuguoping1024** [comment]
> @liuguoping1024 你可以删除 application.yml 重启，先体验一下。不建议做无谓的折腾。

确实无谓的折腾了很久，在 centos上折腾mysql， 版本8.0，十分不顺。在多个平台上都折腾过这个版本，没想到在centos上掉坑里去了。建议你也不折腾了。
最后使用H2，谢谢诸位！
