### ISSUE TITLE
未收到社区激活邮件， 前端运行报错，

### ISSUE THREAD

**Issue by frankelyns** [halo-dev/halo#4213]
### 是什么版本出现了此问题？

2.7

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 在线站点地址

https://bbs.halo.run

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/37787156/678f94b2-6a29-40a7-a0ea-fe3df638d0d3)
未收到激活邮件，前端运行报错， 提示
 [vite] Internal server error: Failed to resolve import "@halo-dev/components/dist/style.css" from "src\setup\setupStyles.ts". Does the file exist?  Plugin: vite:import-analysis
  File: F:/work/halo/console/src/setup/setupStyles.ts:2:7
  1  |  import "@halo-dev/richtext-editor/dist/style.css";
  2  |  import "@halo-dev/components/dist/style.css";
     |          ^
  3  |  import "@/styles/tailwind.css";
  4  |  import "@/styles/index.css";
      at formatError (file:///F:/work/halo/console/node_modules/.pnpm/vite@4.0.4_@types+node@18.13.0_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41235:46)
      at TransformContext.error (file:///F:/work/halo/console/node_modules/.pnpm/vite@4.0.4_@types+node@18.13.0_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41231:19)
      at normalizeUrl (file:///F:/work/halo/console/node_modules/.pnpm/vite@4.0.4_@types+node@18.13.0_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39540:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (file:///F:/work/halo/console/node_modules/.pnpm/vite@4.0.4_@types+node@18.13.0_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39673:47)
      at async Object.transform (file:///F:/work/halo/console/node_modules/.pnpm/vite@4.0.4_@types+node@18.13.0_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41506:30)
      at async loadAndTransform (file:///F:/work/halo/console/node_modules/.pnpm/vite@4.0.4_@types+node@18.13.0_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39313:29)

本机node版本：v16.20.0、 npm版本：8.19.4

**Comment by ruibaby** [comment]
请参考：https://docs.halo.run/developer-guide/core/run#%E8%BF%90%E8%A1%8C-console

/kind support

**Comment by frankelyns** [comment]
> 请参考：https://docs.halo.run/developer-guide/core/run#%E8%BF%90%E8%A1%8C-console
> 
> /kind support

我在文档上看到了这个， 现在还未收到社区激活邮件。

**Comment by ruibaby** [comment]
> 我在文档上看到了这个， 现在还未收到社区激活邮件。

尝试重新发也没有用吗？

**Comment by ruibaby** [comment]
这个 issue 并不是一个问题，我将转为 Discussion。
