### ISSUE TITLE
Uncaught TypeError: Cannot perform 'get' on a proxy that has been revoked

### ISSUE THREAD

**Issue by shariqshahab** [halo-dev/halo#4435]
### What is version of Halo has the issue?

2.8.0

### What database are you using?

H2

### What is your deployment method?

Docker

### Your site address.

http://d2.h.chapaltech.com/console/setup

### What happened?

在 Halo 设置页面上，当我输入详细的用户名时，它在控制台上显示错误，因此我无法提交表单
我目前正在使用开发安装
**Error**:

index-f82a1094.js:74 Uncaught TypeError: Cannot perform 'get' on a proxy that has been revoked
    at Object.listener (index-f82a1094.js:74:26042)
    at index-f82a1094.js:37:17755
    at Array.forEach (<anonymous>)
    at Object.o [as _e] (index-f82a1094.js:37:17695)
    at Rre (index-f82a1094.js:37:18394)
    at Proxy.<anonymous> (index-f82a1094.js:37:24891)
    at uS (index-f82a1094.js:37:26019)

**Comment by ruibaby** [comment]
最新的提交已经修复。

https://github.com/halo-dev/halo/pull/4428

/traige duplicate

**Comment by shariqshahab** [comment]
@ruibaby thanks its working fine now

**Comment by wan92hen** [comment]
Hi @shariqshahab, I'm curious about how do you find this project. The readme file, description and docs of Halo are all in Chinese.

**Comment by shariqshahab** [comment]
Hi @wan92hen,

I came across this project on Github through browsing and then I visited Halo's website and learned more about this project's demonstration and I got quite intrigued about its speed, structure, performance and modern technology. To understand the project in depth, I translated its readme file, description and all the documents in English Language.

**Comment by wan92hen** [comment]
> Hi @wan92hen,
> 
> I came across this project on Github through browsing and then I visited Halo's website and learned more about this project's demonstration and I got quite intrigued about its speed, structure, performance and modern technology. To understand the project in depth, I translated its readme file, description and all the documents in English Language.

Thanks for your reply, and hope you can enjoy this project and then share it to others.
