### ISSUE TITLE
apis/api.console.halo.run/v1alpha1/plugin-presets 500 (Internal Server Error)

### ISSUE THREAD

**Issue by shariqshahab** [halo-dev/halo#4437]
### What is version of Halo has the issue?

2.8.0

### What database are you using?

H2

### What is your deployment method?

Docker

### Your site address.

http://d2.h.chapaltech.com/apis/api.console.halo.run/v1alpha1/plugin-presets

### What happened?

我目前使用的是开发者环境

你能帮我解决我所缺少的东西以及其他什么吗

2023-08-16T09:34:25.003Z ERROR 2281413 --- [reactor-http-epoll-4] a.w.r.e.AbstractErrorWebExceptionHandler : [f6d6224c-75]  500 Server Error for HTTP GET "/apis/api.console.halo.run/v1alpha1/plugin-presets"

java.io.FileNotFoundException: class path resource [presets/plugins/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:226) ~[spring-core-6.0.11.jar:6.0.11]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler run.halo.app.core.extension.endpoint.PluginEndpoint$$Lambda$1347/0x00007f71fc7a3390@6f04ad8 [DispatcherHandler]
	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/apis/api.console.halo.run/v1alpha1/plugin-presets" [ExceptionHandlingWebHandler]

**Comment by ruibaby** [comment]
see https://github.com/halo-dev/halo/issues/4418#issuecomment-1677354115

new document: https://github.com/halo-dev/docs/pull/243/files

**Comment by SereinRan** [comment]
@ruibaby 你好，我在使用` ./gradlew.bat downloadPluginPresets`下载预设插件之后再运行出现了以下两个报错，我的环境是本地运行的2.8.0，使用h2和mysql都出现了报错

      2023-08-16T17:15:53.185+08:00 ERROR 15960 --- [ctor-http-nio-2] o.s.w.s.adapter.HttpWebHandlerAdapter    : [7246d40f-585] 500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/plugins/install"
      
      java.lang.IllegalArgumentException: `detail` is required
	      at org.springframework.util.Assert.notNull(Assert.java:204) ~[spring-core-6.0.11.jar:6.0.11]
	      at org.springframework.web.DefaultErrorResponseBuilder.<init>(DefaultErrorResponseBuilder.java:57) ~[spring-web-6.0.11.jar:6.0.11]
	      at org.springframework.web.ErrorResponse.builder(ErrorResponse.java:177) ~[spring-web-6.0.11.jar:6.0.11]
	      at run.halo.app.infra.exception.Exceptions.createErrorResponse(Exceptions.java:59) ~[main/:na]
	      at run.halo.app.infra.exception.handlers.ProblemDetailErrorAttributes.getErrorAttributes(ProblemDetailErrorAttributes.java:35) ~[main/:na]
	      at org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler.getErrorAttributes(AbstractErrorWebExceptionHandler.java:146) ~[spring-boot-autoconfigure-3.1.2.jar:3.1.2]
	      at run.halo.app.infra.exception.handlers.HaloErrorWebExceptionHandler.renderErrorResponse(HaloErrorWebExceptionHandler.java:55) ~[main/:na]
	      at org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler.lambda$handle$0(AbstractErrorWebExceptionHandler.java:303) ~[spring-boot-autoconfigure-3.1.2.jar:3.1.2]
	      at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.5.8.jar:3.5.8]
	      at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.8.jar:3.5.8]
	      at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.5.8.jar:3.5.8]
	      at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:201) ~[reactor-core-3.5.8.jar:3.5.8]
	      at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545) ~[reactor-core-3.5.8.jar:3.5.8]
	      at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onSubscribe(FluxConcatArray.java:193) ~[reactor-core-3.5.8.jar:3.5.8]
	      at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.5.8.jar:3.5.8]
	      at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.5.8.jar:3.5.8]
	      at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.8.jar:3.5.8]
然后下载的四个预设插件出现了以下同样的报错

        2023-08-16T17:15:53.281+08:00 ERROR 15960 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
        java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:\Users\86189\halo2-dev\plugins/PluginFeed-1.1.1.jar
	        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:na]
	        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:na]
	        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:na]
	        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[na:na]
	        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[na:na]
	        at java.base/java.nio.file.Path.of(Path.java:147) ~[na:na]
	        at java.base/java.nio.file.Paths.get(Paths.java:69) ~[na:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.determinePluginLocation(PluginReconciler.java:736) ~[main/:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$ensurePluginLoaded$19(PluginReconciler.java:617) ~[main/:na]
	        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.ensurePluginLoaded(PluginReconciler.java:612) ~[main/:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.getPluginWrapper(PluginReconciler.java:350) ~[main/:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.lookupPluginSetting(PluginReconciler.java:175) ~[main/:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.waitForSettingCreation(PluginReconciler.java:214) ~[main/:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$readinessDetection$3(PluginReconciler.java:137) ~[main/:na]
	        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.readinessDetection(PluginReconciler.java:136) ~[main/:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:101) ~[main/:na]
	        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:93) ~[main/:na]
	        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:75) ~[main/:na]
	        at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[main/:na]
	        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

并且console也报了个警告

        A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.

**Comment by ruibaby** [comment]
cc @halo-dev/sig-halo

**Comment by shariqshahab** [comment]
@ruibaby Its working fine

**Comment by ruibaby** [comment]
@SereinRan 你这个问题可能和 Windows 平台的路径有关，你可以尝试不下载预设插件， 仅创建 `application/src/main/resources/presets/plugins` 目录试试。

**Comment by ruibaby** [comment]
/triage duplicate

see https://github.com/halo-dev/halo/issues/4418

**Comment by shariqshahab** [comment]
@ruibaby Please kindly close this issue

**Comment by SereinRan** [comment]
@ruibaby 我尝试了你的方法，但是后台安装插件之后无法正常使用
![image](https://github.com/halo-dev/halo/assets/128444032/2d2b799f-46b3-4759-a547-e4ec84f7b757)


        java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:\Users\86189\halo2-dev\plugins/PluginFeed-1.1.1.jar
                at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:na]
                at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:na]
                at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:na]
                at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[na:na]
                at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[na:na]
                at java.base/java.nio.file.Path.of(Path.java:147) ~[na:na]
                at java.base/java.nio.file.Paths.get(Paths.java:69) ~[na:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.determinePluginLocation(PluginReconciler.java:736) ~[main/:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$ensurePluginLoaded$19(PluginReconciler.java:617) ~[main/:na]
                at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.ensurePluginLoaded(PluginReconciler.java:612) ~[main/:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.getPluginWrapper(PluginReconciler.java:350) ~[main/:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.lookupPluginSetting(PluginReconciler.java:175) ~[main/:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.waitForSettingCreation(PluginReconciler.java:214) ~[main/:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$readinessDetection$3(PluginReconciler.java:137) ~[main/:na]
                at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.readinessDetection(PluginReconciler.java:136) ~[main/:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:101) ~[main/:na]
                at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:93) ~[main/:na]
                at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:75) ~[main/:na]
                at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[main/:na]
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
                at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by guqing** [comment]
> @ruibaby 我尝试了你的方法，但是后台安装插件之后无法正常使用

我去 windows 尝试复现一下这个问题，稍后回复你🫡

**Comment by guqing** [comment]
> @ruibaby 我尝试了你的方法，但是后台安装插件之后无法正常使用 ![image](https://user-images.githubusercontent.com/128444032/262312293-2d2b799f-46b3-4759-a547-e4ec84f7b757.png)

已经复现了 确实有这个问题，建议重新提一个 issue
