### ISSUE TITLE
Plugin PluginCommentWidget not found in plugin manager

### ISSUE THREAD

**Issue by hlovingness** [halo-dev/halo#4504]
### 是什么版本出现了此问题？

2.9

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Fat Jar

### 发生了什么？

所有插件报错
```
java.lang.IllegalStateException: run.halo.app.core.extension.reconciler.PluginReconciler$DoNotRetryException: Plugin PluginCommentWidget not found in plugin manager.
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$updateStatus$17(PluginReconciler.java:383) ~[main/:na]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-2.0.2.jar:na]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-2.0.2.jar:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.updateStatus(PluginReconciler.java:378) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$readinessDetection$4(PluginReconciler.java:147) ~[main/:na]
        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.readinessDetection(PluginReconciler.java:141) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:103) ~[main/:na]
        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:95) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:77) ~[main/:na]
        at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.9.0-SNAPSHOT.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: run.halo.app.core.extension.reconciler.PluginReconciler$DoNotRetryException: Plugin PluginCommentWidget not found in plugin manager.
        at run.halo.app.core.extension.reconciler.PluginReconciler.getPluginWrapper(PluginReconciler.java:371) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$readinessDetection$3(PluginReconciler.java:153) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$doUpdateStatus$18(PluginReconciler.java:401) ~[main/:na]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.doUpdateStatus(PluginReconciler.java:398) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$updateStatus$17(PluginReconciler.java:380) ~[main/:na]
        ... 16 common frames omitted
```

### 相关日志输出

```shell
2023-08-28T14:51:31.131+08:00 ERROR 18136 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...

java.lang.IllegalStateException: run.halo.app.core.extension.reconciler.PluginReconciler$DoNotRetryException: Plugin PluginCommentWidget not found in plugin manager.
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$updateStatus$17(PluginReconciler.java:383) ~[main/:na]
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-2.0.2.jar:na]
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-2.0.2.jar:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.updateStatus(PluginReconciler.java:378) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$readinessDetection$4(PluginReconciler.java:147) ~[main/:na]
        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.readinessDetection(PluginReconciler.java:141) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:103) ~[main/:na]
        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:95) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:77) ~[main/:na]
        at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.9.0-SNAPSHOT.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: run.halo.app.core.extension.reconciler.PluginReconciler$DoNotRetryException: Plugin PluginCommentWidget not found in plugin manager.
        at run.halo.app.core.extension.reconciler.PluginReconciler.getPluginWrapper(PluginReconciler.java:371) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$readinessDetection$3(PluginReconciler.java:153) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$doUpdateStatus$18(PluginReconciler.java:401) ~[main/:na]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.doUpdateStatus(PluginReconciler.java:398) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$updateStatus$17(PluginReconciler.java:380) ~[main/:na]
        ... 16 common frames omitted

2023-08-28T14:51:31.131+08:00 DEBUG 18136 --- [nReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=PluginCommentWidget] after PT0.02S
2023-08-28T14:51:31.131+08:00 DEBUG 18136 --- [nReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=PluginCommentWidget] after PT0.02S
2023-08-28T14:51:31.131+08:00 DEBUG 18136 --- [nReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=PluginSearchWidget] at 2023-08-28T06:51:31.131309700Z
2023-08-28T14:51:31.131+08:00 DEBUG 18136 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 >>> Reconciling request Request[name=PluginSearchWidget] at 2023-08-28T06:51:31.131309700Z
2023-08-28T14:51:31.414+08:00 DEBUG 18136 --- [actor-tcp-nio-5] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=PluginSearchWidget-system-generated-reverse-proxy] immediately
2023-08-28T14:51:31.414+08:00 DEBUG 18136 --- [actor-tcp-nio-5] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=PluginSearchWidget-system-generated-reverse-proxy] after PT0.005S
2023-08-28T14:51:31.414+08:00 DEBUG 18136 --- [actor-tcp-nio-5] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=PluginSearchWidget-system-generated-reverse-proxy] after PT0.005S
2023-08-28T14:51:31.430+08:00 DEBUG 18136 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=PluginSearchWidget-system-generated-reverse-proxy] at 2023-08-28T06:51:31.430414100Z
2023-08-28T14:51:31.430+08:00 DEBUG 18136 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.ReverseProxyReconciler-worker-1 >>> Reconciling request Request[name=PluginSearchWidget-system-generated-reverse-proxy] at 2023-08-28T06:51:31.430414100Z
2023-08-28T14:51:31.633+08:00 DEBUG 18136 --- [actor-tcp-nio-4] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=PluginSearchWidget-system-generated-reverse-proxy] immediately
2023-08-28T14:51:31.634+08:00 DEBUG 18136 --- [actor-tcp-nio-4] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=PluginSearchWidget-system-generated-reverse-proxy] after PT0.005S
```

**Comment by guqing** [comment]
你是在本地开发环境运行的吗，插件开发模式改为 deployment 模式运行可以安装插件 JAR 包，https://docs.halo.run/developer-guide/plugin/runtime-mode

**Comment by hlovingness** [comment]
对的，win本地开发环境，改了也不行嘛，这些是内置插件

**Comment by hlovingness** [comment]
> 你是在本地开发环境运行的吗，插件开发模式改为 deployment 模式运行可以安装插件 JAR 包，https://docs.halo.run/developer-guide/plugin/runtime-mode
对的，win本地开发环境，改了也不行嘛，这些是内置插件

**Comment by hlovingness** [comment]
> 你是在本地开发环境运行的吗，插件开发模式改为 deployment 模式运行可以安装插件 JAR 包，https://docs.halo.run/developer-guide/plugin/runtime-mode

对的，win本地开发环境，改了也不行嘛，这些是内置插件

**Comment by guqing** [comment]
> > 你是在本地开发环境运行的吗，插件开发模式改为 deployment 模式运行可以安装插件 JAR 包，[docs.halo.run/developer-guide/plugin/runtime-mode](https://docs.halo.run/developer-guide/plugin/runtime-mode)
> 
> 对的，win本地开发环境，改了也不行嘛，这些是内置插件 ![image](https://user-images.githubusercontent.com/16331459/263631144-2be149c7-0f6c-44df-b36c-c0d1c0b2c46b.png)

在 application-dev.yaml 中`halo.plugin.runtime-mode`的值改为 deployment 就可以了

**Comment by hlovingness** [comment]
> > > 你是在本地开发环境运行的吗，插件开发模式改为 deployment 模式运行可以安装插件 JAR 包，[docs.halo.run/developer-guide/plugin/runtime-mode](https://docs.halo.run/developer-guide/plugin/runtime-mode)
> > 
> > 
> > 对的，win本地开发环境，改了也不行嘛，这些是内置插件 ![image](https://user-images.githubusercontent.com/16331459/263631144-2be149c7-0f6c-44df-b36c-c0d1c0b2c46b.png)
> 
> 在 application-dev.yaml 中将 `halo.plugin.runtime-mode`的值改为 deployment 就可以了,改了需要重启

我用命令行重新运行的，但是还是报错 win 环境

**Comment by guqing** [comment]
> 我用命令行重新运行的，但是还是报错 win 环境

./gradlew bootRun --args="--spring.profiles.active=dev,win --halo.plugin.runtime-mode=deployment"

**Comment by hlovingness** [comment]
> ./gradlew bootRun --args="--spring.profiles.active=dev,win --halo.plugin.runtime-mode=deployment"

还是不行

**Comment by hlovingness** [comment]
这种错误
```
2023-08-28T17:56:47.839+08:00 ERROR 11508 --- [nReconciler-t-1] r.h.a.c.e.reconciler.PluginReconciler    : Failed to reconcile plugin: [PluginFeed]
> :application:bootRun
run.halo.app.core.extension.reconciler.PluginReconciler$DoNotRetryException: Plugin PluginFeed not found in plugin manager.
        at run.halo.app.core.extension.reconciler.PluginReconciler.getPluginWrapper(PluginReconciler.java:371) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lookupPluginSetting(PluginReconciler.java:186) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.waitForSettingCreation(PluginReconciler.java:218) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$readinessDetection$4(PluginReconciler.java:142) ~[main/:na]
        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.readinessDetection(PluginReconciler.java:141) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:103) ~[main/:na]
        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:95) ~[main/:na]
        at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:77) ~[main/:na]
        at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.9.0-SNAPSHOT.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by guqing** [comment]
打开 halo 项目，在下图 1步骤处的 application-dev.yaml 中修改下图 步骤3 中标识的位置为 deployment
<img width="1263" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/4915b8b0-ad74-4394-80f0-f002fe0ffa24">
然后运行项目并初始化，结果如下

https://github.com/halo-dev/halo/assets/38999863/2d0dbf42-d0ad-4c89-8f4d-a693329da3ba


插件列表一切正常
请问你的错误怎么复现呢？

**Comment by hlovingness** [comment]
我也是这样操作的

**Comment by guqing** [comment]
把启动日志贴出来看看，刚启动时开头的日志

**Comment by hlovingness** [comment]
[halo.log](https://github.com/halo-dev/halo/files/12470933/halo.log)

**Comment by hlovingness** [comment]
> 把启动日志贴出来看看，刚启动时开头的日志

[halo.log](https://github.com/halo-dev/halo/files/12470941/halo.log)

**Comment by guqing** [comment]
> > 把启动日志贴出来看看，刚启动时开头的日志
> 
> [halo.log](https://github.com/halo-dev/halo/files/12470941/halo.log)

日志看起来确实没有问题，你检查一下在 halo 的 workdir 中是否存在出错的插件的 jar 文件，如 PluginCommentWidget-{version}.jar，或者把 halo 的 workdir 清理掉然后重新初始化 halo 看看

**Comment by guqing** [comment]
> > 日志看起来确实没有问题，你检查一下在 halo 的 workdir 中是否存在出错的插件的 jar 文件，如 PluginCommentWidget-{version}.jar
> 
> 
> 
> halo2-dev 目录下plugin 目录下没有任何文件
> 

可能是首次启动时插件时开发模式初始化数据后由于是开发模式而无法安装预设插件但数据已经初始化进去了导致，解决办法：
1. 选择删除halo工作目录重新以deployment模式启动后初始化
2. 卸载插件手动安装

**Comment by liuchengts** [comment]
我也遇到了这个问题,但是我通过很笨的办法解决了.

环境: 
docker-compose,完全按照halo文档mysql的模式部署(没有将.halo做外部挂载),halo docker版本 2.10

发生问题的操作:
服务器多次重启

问题:
所有的插件全部是“Plugin PluginCommentWidget not found in plugin manager”(包括halo内置插件)

尝试操作1:
删除docker halo容器,更新至 2.11,数据库还是原来的mysql,问题依旧存在

尝试操作2:
进入halo的console页面,在插件列表中将所有插件全部卸载(选择 “卸载并删除配置”),然后在halo应用市场搜索插件重新安装

经过第二种尝试操作后,插件都可用了

我猜测可能是服务器停机时,halo的插件数据处理与mysql存储之间出现了一些问题,问题数据被保存在了mysql中.通过卸载插件再安装的方式,将错误的插件数据矫正了

**Comment by ruibaby** [comment]
> (没有将.halo做外部挂载)

为什么不挂载 .halo2 工作目录？这里面保存着插件文件、主题文件、附件等。如果不挂载，容器删除之后就会丢失。

> 完全按照halo文档mysql的模式部署

这真的是完全按照吗？

建议使用之前一定要看看文档。https://docs.halo.run/getting-started/prepare#%E5%B7%A5%E4%BD%9C%E7%9B%AE%E5%BD%95

**Comment by liuchengts** [comment]
> > (没有将.halo做外部挂载)
> 
> 不挂载 .halo2 工作目录？这里面保存着插件文件、主题文件、附件等。如果不挂载，容器删除之后就会丢失。
> 
> > 完全按照halo文档mysql的模式部署
> 
> 这真的完全符合吗？
> 
> 建议使用之前一定要看看文档。https://docs.halo.run/getting-started/prepare#%E5%B7%A5%E4%BD%9C%E7%9B%AE%E5%BD%95

嗯,感谢提醒.
我知道删除容器后这些数据都会丢失,我有备份.不挂载这个目录仅仅是个人使用docker的一些原因.按文档的示例,我删除了挂载的内容,其他的一样.
