### ISSUE TITLE
路径：「仪表盘-个人资料-修改头像-上传」上传作者头像时候出错

### ISSUE THREAD

**Issue by broommonk** [halo-dev/halo#4525]
### 是什么版本出现了此问题？

2.8.0

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://www.mibashuo.com

### 发生了什么？

操作路径：「仪表盘-个人资料-修改头像-上传」上传作者头像时候出错：
Extension storage.halo.run/v1alpha1/Policy/default-policy was not found.
上传头像失败

### 相关日志输出

```shell
2023-08-30T11:49:37.566+08:00 ERROR 7 --- [boundedElastic-15] a.w.r.e.AbstractErrorWebExceptionHandler : [88ccf2b2-2849]  500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/attachments/upload"

software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 403, Request ID: 17800CA874E7FBC7, Extended Request ID: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/apis/api.console.halo.run/v1alpha1/attachments/upload" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156) ~[na:na]
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108) ~[na:na]
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85) ~[na:na]
		at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43) ~[na:na]
		at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:95) ~[na:na]
		at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:266) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[na:na]
		at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[na:na]
		at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[na:na]
		at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[na:na]
		at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193) ~[na:na]
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103) ~[na:na]
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171) ~[na:na]
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82) ~[na:na]
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179) ~[na:na]
		at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76) ~[na:na]
		at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[na:na]
		at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56) ~[na:na]
		at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:5438) ~[na:na]
		at run.halo.s3os.S3OsAttachmentHandler.lambda$checkFileExistsAndRename$29(S3OsAttachmentHandler.java:367) ~[na:na]
		at reactor.core.publisher.MonoSupplier$MonoSupplierSubscription.request(MonoSupplier.java:126) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:48) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4480) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:258) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:78) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:109) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.8.jar:3.5.8]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.8.jar:3.5.8]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-08-30T11:51:03.843+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/avatar_miba.jpg, UploadId=64eebca767361db6d8995c2eregion02z2)
2023-08-30T11:51:04.167+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="572989fdd0374bd44589aecfd88756b6")
2023-08-30T11:51:04.415+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://material18.s3.cn-south-1.qiniucs.com/atlas/avatar_miba.jpg, Bucket=material18, Key=atlas/avatar_miba.jpg, ETag="467246774f623051587969387066696e577163554246725a4c423768-1")
2023-08-30T11:51:04.468+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: getMetadata, result: HeadObjectResponse(AcceptRanges=bytes, LastModified=2023-08-30T03:51:04Z, ContentLength=70800, ETag="467246774f623051587969387066696e577163554246725a4c423768-1", ContentType=image/jpeg, Metadata={})
2023-08-30T11:51:04.474+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : Upload object atlas/avatar_miba.jpg to bucket material18 successfully
2023-08-30T11:51:37.610+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/favicon.ico, UploadId=64eebcc967361db6d8995cderegion02z2)
2023-08-30T11:51:37.835+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="dacad0aace9fa90a9bfa78b1b2f9c6f1")
2023-08-30T11:51:37.910+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://material18.s3.cn-south-1.qiniucs.com/atlas/favicon.ico, Bucket=material18, Key=atlas/favicon.ico, ETag="467132715333705f5f556d70733843384f523147452d4d7364643178-1")
2023-08-30T11:51:37.949+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: getMetadata, result: HeadObjectResponse(AcceptRanges=bytes, LastModified=2023-08-30T03:51:37Z, ContentLength=67646, ETag="467132715333705f5f556d70733843384f523147452d4d7364643178-1", ContentType=image/x-icon, Metadata={})
2023-08-30T11:51:37.951+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : Upload object atlas/favicon.ico to bucket material18 successfully
2023-08-30T11:52:34.518+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: delete object, result: DeleteObjectResponse()
2023-08-30T11:52:34.519+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : Delete object atlas/logo.png from bucket material18 successfully
2023-08-30T11:52:41.501+08:00  INFO 7 --- [boundedElastic-15] h.a.c.e.a.e.LocalAttachmentUploadHandler : Trying to delete 1d4c737a-04f3-48fd-9f61-2be3f1d96d83 from local
2023-08-30T11:52:41.502+08:00  INFO 7 --- [boundedElastic-15] h.a.c.e.a.e.LocalAttachmentUploadHandler : /root/.halo2/attachments/upload/favicon.ico is being deleted
2023-08-30T11:52:41.502+08:00  INFO 7 --- [boundedElastic-15] h.a.c.e.a.e.LocalAttachmentUploadHandler : Attachment(super=AbstractExtension(apiVersion=storage.halo.run/v1alpha1, kind=Attachment, metadata=Metadata(name=1d4c737a-04f3-48fd-9f61-2be3f1d96d83, generateName=null, labels=null, annotations={storage.halo.run/uri=/upload/favicon.ico, storage.halo.run/local-relative-path=upload/favicon.ico}, version=2, creationTimestamp=2022-12-24T10:31:04.597397482Z, deletionTimestamp=2023-08-30T03:52:41.485121217Z, finalizers=[attachment-manager])), spec=Attachment.AttachmentSpec(displayName=favicon.ico, groupName=attachment-group-BuOPn, policyName=default-policy, ownerName=broommonk, mediaType=image/x-icon, size=67646, tags=null), status=Attachment.AttachmentStatus(permalink=/upload/favicon.ico)) was deleted successfully
2023-08-30T11:52:41.514+08:00  INFO 7 --- [boundedElastic-15] h.a.c.e.a.e.LocalAttachmentUploadHandler : Trying to delete 4a9687be-61de-45bc-a610-1795f78f8e5e from local
2023-08-30T11:52:41.515+08:00  INFO 7 --- [boundedElastic-15] h.a.c.e.a.e.LocalAttachmentUploadHandler : /root/.halo2/attachments/upload/avatar_miba.jpg is being deleted
2023-08-30T11:52:41.515+08:00  INFO 7 --- [boundedElastic-15] h.a.c.e.a.e.LocalAttachmentUploadHandler : Attachment(super=AbstractExtension(apiVersion=storage.halo.run/v1alpha1, kind=Attachment, metadata=Metadata(name=4a9687be-61de-45bc-a610-1795f78f8e5e, generateName=null, labels=null, annotations={storage.halo.run/uri=/upload/avatar_miba.jpg, storage.halo.run/local-relative-path=upload/avatar_miba.jpg}, version=2, creationTimestamp=2022-12-24T10:28:40.191176782Z, deletionTimestamp=2023-08-30T03:52:41.487111915Z, finalizers=[attachment-manager])), spec=Attachment.AttachmentSpec(displayName=avatar_miba.jpg, groupName=attachment-group-BuOPn, policyName=default-policy, ownerName=broommonk, mediaType=image/jpeg, size=70800, tags=null), status=Attachment.AttachmentStatus(permalink=/upload/avatar_miba.jpg)) was deleted successfully
2023-08-30T12:15:25.429+08:00  INFO 7 --- [boundedElastic-17] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301102042820.png, UploadId=64eec25d59885e4a730b412cregion02z2)
2023-08-30T12:15:25.440+08:00  INFO 7 --- [boundedElastic-18] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301102045261.png, UploadId=64eec25d67361db6d89981e8region02z2)
2023-08-30T12:15:25.440+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301102041923.png, UploadId=64eec25d67361db6d89981e6region02z2)
2023-08-30T12:15:25.647+08:00  INFO 7 --- [boundedElastic-19] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301102042040.png, UploadId=64eec25d59885e4a730b412fregion02z2)
2023-08-30T12:15:25.761+08:00  INFO 7 --- [boundedElastic-20] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301102043819.png, UploadId=64eec25d59885e4a730b4134region02z2)
2023-08-30T12:15:25.888+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="65a73d485e1a0f0843fd33107e26dbd7")
2023-08-30T12:15:25.903+08:00  INFO 7 --- [boundedElastic-17] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="2cd43dd0cd53b920519eb4a060333347")
2023-08-30T12:15:25.942+08:00  INFO 7 --- [boundedElastic-19] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="89c54e8ab65dc03105082574a49c64f9")
2023-08-30T12:15:25.961+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://material18.s3.cn-south-1.qiniucs.com/atlas/202301102041923.png, Bucket=material18, Key=atlas/202301102041923.png, ETag="466a6d58646d463862515067354c32614d43772d503852734763754f-1")
2023-08-30T12:15:25.963+08:00  INFO 7 --- [boundedElastic-17] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://material18.s3.cn-south-1.qiniucs.com/atlas/202301102042820.png, Bucket=material18, Key=atlas/202301102042820.png, ETag="46766f385a4f796a774575715a634644645450345548473758647476-1")
2023-08-30T12:15:25.971+08:00  INFO 7 --- [boundedElastic-18] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="9353bf9ceccb6e03f74da17e4c181eb4")
2023-08-30T12:15:26.000+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : operation: getMetadata, result: HeadObjectResponse(AcceptRanges=bytes, LastModified=2023-08-30T04:15:25Z, ContentLength=27195, ETag="466a6d58646d463862515067354c32614d43772d503852734763754f-1", ContentType=image/png, Metadata={})
2023-08-30T12:15:26.002+08:00  INFO 7 --- [boundedElastic-15] run.halo.s3os.S3OsAttachmentHandler      : Upload object atlas/202301102041923.png to bucket material18 successfully
2023-08-30T12:15:26.011+08:00  INFO 7 --- [boundedElastic-17] run.halo.s3os.S3OsAttachmentHandler      : operation: getMetadata, result: HeadObjectResponse(AcceptRanges=bytes, LastModified=2023-08-30T04:15:25Z, ContentLength=38941, ETag="46766f385a4f796a774575715a634644645450345548473758647476-1", ContentType=image/png, Metadata={})
2023-08-30T12:15:26.013+08:00  INFO 7 --- [boundedElastic-17] run.halo.s3os.S3OsAttachmentHandler      : Upload object atlas/202301102042820.png to bucket material18 successfully
2023-08-30T12:15:26.042+08:00  INFO 7 --- [boundedElastic-18] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://material18.s3.cn-south-1.qiniucs.com/atlas/202301102045261.png, Bucket=material18, Key=atlas/202301102045261.png, ETag="46726835643331557466586e42346f487a43646257686e4749685676-1")
2023-08-30T12:15:26.213+08:00  INFO 7 --- [boundedElastic-20] run.halo.s3os.S3OsAttachmentHandler      : operation: uploadPart, result: UploadPartResponse(ETag="d1ea6dd8c43df51b19bb4abb6a2b7377")
2023-08-30T12:15:26.212+08:00  INFO 7 --- [boundedElastic-19] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://material18.s3.cn-south-1.qiniucs.com/atlas/202301102042040.png, Bucket=material18, Key=atlas/202301102042040.png, ETag="46716a746a57436e4a484f79752d794b754d7a41715a7239545a6461-1")
2023-08-30T12:15:26.278+08:00  INFO 7 --- [boundedElastic-19] run.halo.s3os.S3OsAttachmentHandler      : operation: getMetadata, result: HeadObjectResponse(AcceptRanges=bytes, LastModified=2023-08-30T04:15:25Z, ContentLength=80633, ETag="46716a746a57436e4a484f79752d794b754d7a41715a7239545a6461-1", ContentType=image/png, Metadata={})
2023-08-30T12:15:26.280+08:00  INFO 7 --- [boundedElastic-19] run.halo.s3os.S3OsAttachmentHandler      : Upload object atlas/202301102042040.png to bucket material18 successfully
2023-08-30T12:15:26.275+08:00  INFO 7 --- [boundedElastic-18] run.halo.s3os.S3OsAttachmentHandler      : operation: getMetadata, result: HeadObjectResponse(AcceptRanges=bytes, LastModified=2023-08-30T04:15:26Z, ContentLength=54169, ETag="46726835643331557466586e42346f487a43646257686e4749685676-1", ContentType=image/png, Metadata={})
2023-08-30T12:15:26.287+08:00  INFO 7 --- [boundedElastic-18] run.halo.s3os.S3OsAttachmentHandler      : Upload object atlas/202301102045261.png to bucket material18 successfully
2023-08-30T12:15:26.312+08:00  INFO 7 --- [boundedElastic-20] run.halo.s3os.S3OsAttachmentHandler      : operation: completeUpload, result: CompleteMultipartUploadResponse(Location=http://material18.s3.cn-south-1.qiniucs.com/atlas/202301102043819.png, Bucket=material18, Key=atlas/202301102043819.png, ETag="466d6a45327a6133393765445a5062736737337461787244466b6355-1")
2023-08-30T12:15:26.385+08:00  INFO 7 --- [boundedElastic-20] run.halo.s3os.S3OsAttachmentHandler      : operation: getMetadata, result: HeadObjectResponse(AcceptRanges=bytes, LastModified=2023-08-30T04:15:26Z, ContentLength=81706, ETag="466d6a45327a6133393765445a5062736737337461787244466b6355-1", ContentType=image/png, Metadata={})
2023-08-30T12:15:26.388+08:00  INFO 7 --- [boundedElastic-20] run.halo.s3os.S3OsAttachmentHandler      : Upload object atlas/202301102043819.png to bucket material18 successfully
2023-08-30T12:15:26.688+08:00  INFO 7 --- [boundedElastic-20] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301102019764.png, UploadId=64eec25e67361db6d89981f5region02z2)
2023-08-30T12:15:26.771+08:00  INFO 7 --- [boundedElastic-19] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301101957705.png, UploadId=64eec25e55e9bf3e41dc57faregion02z2)
2023-08-30T12:15:26.772+08:00  INFO 7 --- [boundedElastic-17] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301102016413.png, UploadId=64eec25e67361db6d89981faregion02z2)
2023-08-30T12:15:26.774+08:00  INFO 7 --- [boundedElastic-18] run.halo.s3os.S3OsAttachmentHandler      : operation: createMultipartUpload, result: CreateMultipartUploadResponse(Bucket=material18, Key=atlas/202301102037233.png, UploadId=64eec25e67361db6d89981f7region02z2)
```

### 附加信息

![](https://s1.ax1x.com/2023/08/30/pPdf6AA.png)

**Comment by ruibaby** [comment]
从界面提示来看，你应该是删除了默认的本地存储策略，但在系统设置的用户设置中的**头像存储位置**还是使用的默认存储策略。两个解决方案：

1. 在**头像存储位置**选项中选择一个正常的存储策略。
2. 重启 Halo，会自动恢复默认的存储策略。

相关讨论：https://bbs.halo.run/d/4237-%E7%94%A8%E6%88%B7%E4%B8%8A%E4%BC%A0%E5%A4%B4%E5%83%8F%E9%94%99%E8%AF%AF

/kind support

**Comment by broommonk** [comment]
好严谨，必须点赞。
我找到了，原来头像有个默认储存策略的选项。
