### ISSUE TITLE
docker启动时出现异常警告:java.time.zone.ZoneRulesException: Unknown time-zone ID: EDT

### ISSUE THREAD

**Issue by codecodeing** [halo-dev/halo#4555]
### What is version of Halo has the issue?

2.9

### What database are you using?

MySQL 8.x

### What is your deployment method?

Docker

### Your site address.

https://www.qsbx.com

### What happened?

时区获取失败
java.time.zone.ZoneRulesException: Unknown time-zone ID: EDT

### Relevant log output

```shell
2023-09-06T10:36:34.669+08:00  WARN 8 --- [reactor-tcp-epoll-2] io.asyncer.r2dbc.mysql.MySqlConnection   : The server timezone is unknown <EDT>, trying to use system default timezone

java.time.zone.ZoneRulesException: Unknown time-zone ID: EDT
        at java.base/java.time.zone.ZoneRulesProvider.getProvider(Unknown Source) ~[na:na]
        at java.base/java.time.zone.ZoneRulesProvider.getRules(Unknown Source) ~[na:na]
        at java.base/java.time.ZoneRegion.ofId(Unknown Source) ~[na:na]
        at java.base/java.time.ZoneId.of(Unknown Source) ~[na:na]
        at java.base/java.time.ZoneId.of(Unknown Source) ~[na:na]
        at java.base/java.time.ZoneId.of(Unknown Source) ~[na:na]
        at io.asyncer.r2dbc.mysql.MySqlConnection.convertZoneId(MySqlConnection.java:513) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at io.asyncer.r2dbc.mysql.MySqlConnection.lambda$null$2(MySqlConnection.java:100) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at io.asyncer.r2dbc.mysql.MySqlResult.lambda$map$1(MySqlResult.java:94) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:179) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableConditionalSubscriber.onNext(FluxHandleFuseable.java:505) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.5.9.jar:3.5.9]
        at io.asyncer.r2dbc.mysql.internal.util.DiscardOnCancelSubscriber.onNext(DiscardOnCancelSubscriber.java:66) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:670) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:748) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:790) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:268) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.5.9.jar:3.5.9]
        at io.asyncer.r2dbc.mysql.internal.util.DiscardOnCancelSubscriber.onNext(DiscardOnCancelSubscriber.java:66) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:343) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:471) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.SinkManyEmitterProcessor.tryEmitNext(SinkManyEmitterProcessor.java:269) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.5.9.jar:3.5.9]
        at io.asyncer.r2dbc.mysql.client.ReactorNettyClient$ResponseSink.next(ReactorNettyClient.java:356) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at io.asyncer.r2dbc.mysql.client.ReactorNettyClient.lambda$new$0(ReactorNettyClient.java:115) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.5.9.jar:3.5.9]
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292) ~[reactor-netty-core-1.1.10.jar:1.1.10]
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:401) ~[reactor-netty-core-1.1.10.jar:1.1.10]
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411) ~[reactor-netty-core-1.1.10.jar:1.1.10]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.10.jar:1.1.10]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.asyncer.r2dbc.mysql.client.MessageDuplexCodec.handleDecoded(MessageDuplexCodec.java:178) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at io.asyncer.r2dbc.mysql.client.MessageDuplexCodec.channelRead(MessageDuplexCodec.java:81) ~[r2dbc-mysql-1.0.2.jar:1.0.2]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1466) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1329) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1378) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by JohnNiang** [comment]
请问有办法稳定复现该问题么？比如提供一下数据库连接字符串等信息。

/triage needs-information

**Comment by codecodeing** [comment]
> 请问有一种稳定恢复现该问题么？ 或者提供一下数据库连接字符串等信息。
> 
> /分类需求信息

运行环境:debian 11.6
mysql数据库的字符编码:utf8mb4_general_ci

复现执行命令如下:
docker run   -it -d   --name halo   -p 8090:8090   -v ~/.halo2:/root/.halo2   halohub/halo:2.9   --spring.r2dbc.url=r2dbc:pool:mysql://10.0.0.3:3306/halo  --spring.r2dbc.username=halo   --spring.r2dbc.password=xxxxxxx   --spring.sql.init.platform=mysql   --halo.external-url=https://www.qsbx.com/   --halo.security.initializer.superadminusername=xxxxxxx   --halo.security.initializer.superadminpassword=xxxxxxxx


执行命令后:观察log日志会发现此报错

**Comment by codecodeing** [comment]
> 请问有一种稳定恢复现该问题么？ 或者提供一下数据库连接字符串等信息。
> 
> /分类需求信息

运行环境:debian 11.6
mysql数据库的字符编码:utf8mb4_general_ci

复现执行命令如下:
docker run   -it -d   --name halo   -p 8090:8090   -v ~/.halo2:/root/.halo2   halohub/halo:2.9   --spring.r2dbc.url=r2dbc:pool:mysql://10.0.0.3:3306/halo  --spring.r2dbc.username=halo   --spring.r2dbc.password=xxxxxxx   --spring.sql.init.platform=mysql   --halo.external-url=https://www.qsbx.com/   --halo.security.initializer.superadminusername=xxxxxxx   --halo.security.initializer.superadminpassword=xxxxxxxx


执行命令后:观察log日志会发现此报错

**Comment by JohnNiang** [comment]
可以提供一下 MySQL 服务器的时区信息么？可以执行以下 SQL 脚本查看：

```bash
show variables where Variable_name like '%zone%';
```

目测是 MySQL 的时区为 EDT 导致的。目前有两个解决方案：

1. 修改 MySQL 的时区
    
    可参考：<https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html>。

2. 修改数据库链接字符串

    `--spring.r2dbc.url=r2dbc:pool:mysql://10.0.0.3:3306/halo?serverZoneId=Asia/Shanghai`

**Comment by codecodeing** [comment]
> 可以提供一下MySQL服务器的时区信息吗？可以执行以下SQL脚本查看：
> 
> ```shell
> show variables where Variable_name like '%zone%';
> ```
> 
> 目测是MySQL的时区为EDT导致的。目前有两个解决方案：
> 
> 1. 修改MySQL的时区
>    可参考：https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html。
> 2. 修改数据库链接字符串
>    `--spring.r2dbc.url=r2dbc:pool:mysql://10.0.0.3:3306/halo?serverZoneId=Asia/Shanghai`

<img width="324" alt="image" src="https://github.com/halo-dev/halo/assets/44698239/c9fe03e5-b519-445e-b38a-090585dfb194">
确实EDT ,我这是mysql默认安装就是这个,我改一下吧

**Comment by codecodeing** [comment]
> 可以提供一下 MySQL 服务器的时区信息么？可以执行以下 SQL 脚本查看：
> 
> ```shell
> show variables where Variable_name like '%zone%';
> ```
> 
> 目测是 MySQL 的时区为 EDT 导致的。目前有两个解决方案：
> 
> 1. 修改 MySQL 的时区
>    可参考：https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html。
> 2. 修改数据库链接字符串
>    `--spring.r2dbc.url=r2dbc:pool:mysql://10.0.0.3:3306/halo?serverZoneId=Asia/Shanghai`

采取使用方法2可以解决报错
数据库连接字符串后面加下面任意一个都行
serverZoneId=Asia/Shanghai
or
serverTimezone=Asia/Shanghai
