### ISSUE TITLE
无法正常启动，启动报错

### ISSUE THREAD

**Issue by blankhang** [halo-dev/halo#4712]
### 是什么版本出现了此问题？

2.10.0

### 使用的什么数据库？

H2

### 使用的哪种方式运行？

Docker

### 发生了什么？

最近没专注网站 刚刚收到google通知网站无法被索引 发现网站打不开 重启 也是一样报这个错，
从2.6.2 升到最新的2.10.0 还是一样
请问有解决办法能先用吗

### 相关日志输出

```shell
halo  | 2023-10-11T19:50:53.091+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginSitemap@1.0.0'
halo  | 2023-10-11T19:50:53.096+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginSitemap
halo  | 2023-10-11T19:50:53.097+08:00  WARN 7 --- [nReconciler-t-1] r.h.app.plugin.PluginApplicationContext  : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 2023-10-11T19:50:53.097+08:00 ERROR 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Unable to start plugin 'PluginSitemap@1.0.0'
halo  | 
halo  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:240) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[spring-context-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.12.jar:6.0.12]
halo  | 	at run.halo.app.plugin.PluginApplicationInitializer.initApplicationContext(PluginApplicationInitializer.java:128) ~[classes/:2.10.0]
halo  | 	at run.halo.app.plugin.PluginApplicationInitializer.onStartUp(PluginApplicationInitializer.java:158) ~[classes/:2.10.0]
halo  | 	at run.halo.app.plugin.HaloPluginManager.doStartPlugin(HaloPluginManager.java:280) ~[classes/:2.10.0]
halo  | 	at run.halo.app.plugin.HaloPluginManager.startPlugin(HaloPluginManager.java:227) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.doStart(PluginReconciler.java:441) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startAction$13(PluginReconciler.java:274) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.stateTransition(PluginReconciler.java:307) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.startAction(PluginReconciler.java:268) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcilePluginState$21(PluginReconciler.java:539) ~[classes/:2.10.0]
halo  | 	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:528) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:108) ~[classes/:2.10.0]
halo  | 	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:96) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:78) ~[classes/:2.10.0]
halo  | 	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.10.0.jar:na]
halo  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:654) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:488) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:910) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	... 33 common frames omitted
halo  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	... 47 common frames omitted
halo  | Caused by: java.lang.IllegalArgumentException: URI is not absolute
halo  | 	at java.base/java.net.URL.fromURI(Unknown Source) ~[na:na]
halo  | 	at java.base/java.net.URI.toURL(Unknown Source) ~[na:na]
halo  | 	at run.halo.sitemap.SitemapPluginConfig.sitemapGeneratorOptions(SitemapPluginConfig.java:36) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
halo  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.12.jar:6.0.12]
halo  | 	... 48 common frames omitted
halo  | 
halo  | 2023-10-11T19:50:53.105+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginSitemap@1.0.0'
halo  | 2023-10-11T19:50:53.106+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginSitemap@1.0.0'
halo  | 2023-10-11T19:50:53.107+08:00 ERROR 7 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
halo  | 
halo  | java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.doStart(PluginReconciler.java:447) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$startAction$13(PluginReconciler.java:274) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.stateTransition(PluginReconciler.java:307) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.startAction(PluginReconciler.java:268) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcilePluginState$21(PluginReconciler.java:539) ~[classes/:2.10.0]
halo  | 	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcilePluginState(PluginReconciler.java:528) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:108) ~[classes/:2.10.0]
halo  | 	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:96) ~[classes/:2.10.0]
halo  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:78) ~[classes/:2.10.0]
halo  | 	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.10.0.jar:na]
halo  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
halo  | Caused by: java.lang.IllegalStateException: Error creating bean with name 'run.halo.sitemap.DefaultSitemapEntryLister': Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'sitemapGeneratorOptions' defined in run.halo.sitemap.SitemapPluginConfig: Failed to instantiate [run.halo.sitemap.SitemapGeneratorOptions]: Factory method 'sitemapGeneratorOptions' threw exception with message: URI is not absolute
halo  | 	... 17 common frames omitted
```

### 附加信息

PluginSitemap 这个插件导致的？

**Comment by guqing** [comment]
打不开网站了吗？如果打不开可以先降级到你原先的 2.6.2 然后卸载 sitemap 这个插件在升级试试

**Comment by JohnNiang** [comment]
建议提供一下 sitemap 插件版本。如果不是最新的建议更新至最新。

/triage needs-information

**Comment by blankhang** [comment]
> 打不开网站了吗？如果打不开可以先降级到你原先的 2.6.2 然后卸载 sitemap 这个插件在升级 halo 试试

2.6.2就打不开了= = 不知道为啥，2.10也不行 ，有没有手动卸载插件的方法？
这个插件版本好像是1.0

**Comment by JohnNiang** [comment]
Hi @blankhang ，建议更新一下 sitemap 插件。

可参考：
- https://www.halo.run/store/apps/app-QDFMI?tab=releases

**Comment by blankhang** [comment]
> Hi @blankhang ，建议更新一下 sitemap 插件。
> 
> 可参考：
> 
> * https://www.halo.run/store/apps/app-QDFMI?tab=releases

升级到1.1.1已经解决问题，可以正常打开了
