### ISSUE TITLE
编辑器可以渲染，文章中无法正常显示公式

### ISSUE THREAD

**Issue by wt12318** [halo-dev/halo#4845]
### 是什么版本出现了此问题？

2.10

### 使用的什么数据库？

PostgreSQL

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://wutaoblog.com.cn/

### 发生了什么？

编辑器中可以正常渲染，但是文章中就不行了（使用的编辑器为 StackEdit）：
编辑器：
![图片](https://github.com/halo-dev/halo/assets/39486023/0ef35ddf-9175-4a42-a976-ee45f068cc3b)
文章：
![图片](https://github.com/halo-dev/halo/assets/39486023/30945dcc-bf3b-47cb-9170-cc1f23306913)

Katex 插件设置：
![图片](https://github.com/halo-dev/halo/assets/39486023/4b63fd85-d232-4fc5-b165-5ad9f6420168)

### 相关日志输出

```shell
$ sudo  docker logs -f halo -n 200
2023-11-11T14:58:02.541+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginSitemap@1.1.1' resolved
2023-11-11T14:58:02.597+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginSitemap@1.1.1'
2023-11-11T14:58:02.632+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginFeed@1.2.0' resolved
2023-11-11T14:58:02.658+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginFeed@1.2.0'
2023-11-11T14:58:03.048+08:00 ERROR 7 --- [tor-tcp-epoll-3] a.w.r.e.AbstractErrorWebExceptionHandler : [bca86d93-80]  500 Server Error for HTTP PUT "/apis/plugin.halo.run/v1alpha1/plugins/PluginFeed"

org.springframework.dao.OptimisticLockingFailureException: Failed to update table [extensions]; Version does not match for row with Id [/registry/plugin.halo.run/plugins/PluginFeed]
        at org.springframework.data.r2dbc.core.R2dbcEntityTemplate.lambda$doUpdate$13(R2dbcEntityTemplate.java:636) ~[spring-data-r2dbc-3.1.5.jar:3.1.5]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
        *__checkpoint ⇢ run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
        *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP PUT "/apis/plugin.halo.run/v1alpha1/plugins/PluginFeed" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at org.springframework.data.r2dbc.core.R2dbcEntityTemplate.lambda$doUpdate$13(R2dbcEntityTemplate.java:636) ~[spring-data-r2dbc-3.1.5.jar:3.1.5]
                at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:113) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:268) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:527) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:537) ~[reactor-pool-1.0.3.jar:1.0.3]
                at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:767) ~[reactor-pool-1.0.3.jar:1.0.3]
                at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:879) ~[reactor-pool-1.0.3.jar:1.0.3]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:239) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoSupplier$MonoSupplierSubscription.request(MonoSupplier.java:148) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:260) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onSubscribe(MonoIgnoreElements.java:72) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onSubscribe(FluxHandleFuseable.java:164) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:48) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxFilter$FilterSubscriber.onError(FluxFilter.java:157) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onError(FluxFilter.java:291) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:384) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2072) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoStreamCollector$StreamCollectorSubscriber.onComplete(MonoStreamCollector.java:159) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:847) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerComplete(FluxFlatMap.java:895) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxFlatMap$FlatMapInner.onComplete(FluxFlatMap.java:998) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:239) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2072) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:223) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:239) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onComplete(FluxFilterFuseable.java:391) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940) ~[reactor-core-3.5.11.jar:3.5.11]
                at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onComplete(FluxDiscardOnCancel.java:104) ~[r2dbc-postgresql-1.0.2.RELEASE.jar:1.0.2.RELEASE]
                at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:128) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:223) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:463) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:869) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:817) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:247) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:213) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:204) ~[reactor-core-3.5.11.jar:3.5.11]
                at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.complete(ReactorNettyClient.java:668) ~[r2dbc-postgresql-1.0.2.RELEASE.jar:1.0.2.RELEASE]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:934) ~[r2dbc-postgresql-1.0.2.RELEASE.jar:1.0.2.RELEASE]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:810) ~[r2dbc-postgresql-1.0.2.RELEASE.jar:1.0.2.RELEASE]
                at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:716) ~[r2dbc-postgresql-1.0.2.RELEASE.jar:1.0.2.RELEASE]
                at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[reactor-core-3.5.11.jar:3.5.11]
                at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292) ~[reactor-netty-core-1.1.12.jar:1.1.12]
                at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:401) ~[reactor-netty-core-1.1.12.jar:1.1.12]
                at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:424) ~[reactor-netty-core-1.1.12.jar:1.1.12]
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.12.jar:1.1.12]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
                at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2023-11-11T14:58:03.060+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginSitemap@1.1.1'
2023-11-11T14:58:03.077+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginSitemap
2023-11-11T14:58:03.743+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginSearchWidget@1.2.0' resolved
2023-11-11T14:58:03.750+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginSearchWidget@1.2.0'
2023-11-11T14:58:03.770+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'app-store-integration@1.0.0-beta.2' resolved
2023-11-11T14:58:03.789+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'app-store-integration@1.0.0-beta.2'
2023-11-11T14:58:03.814+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginCommentWidget@1.8.0' resolved
2023-11-11T14:58:03.821+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginCommentWidget@1.8.0'
2023-11-11T14:58:04.139+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginSearchWidget@1.2.0'
2023-11-11T14:58:04.145+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginSearchWidget
2023-11-11T14:58:04.167+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginCommentWidget@1.8.0'
2023-11-11T14:58:04.173+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginCommentWidget
2023-11-11T14:58:04.200+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'app-store-integration@1.0.0-beta.2'
2023-11-11T14:58:04.206+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin app-store-integration
2023-11-11T14:58:04.447+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginFeed@1.2.0'
2023-11-11T14:58:04.457+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginFeed
2023-11-11T15:06:49.174+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginSitePush@1.3.1' resolved
2023-11-11T15:06:49.199+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginSitePush@1.3.1'
2023-11-11T15:07:19.015+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginSitePush@1.3.1'
2023-11-11T15:07:19.038+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginSitePush
2023-11-11T15:07:19.085+08:00  INFO 7 --- [nReconciler-t-1] com.stonewu.sitepush.SitePushPlugin      : 成功读取已推送链接 0 个
2023-11-11T15:07:19.091+08:00  INFO 7 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Starting controller com.stonewu.sitepush.reconciler.SinglePagePushReconciler
2023-11-11T15:07:19.091+08:00  INFO 7 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Starting controller com.stonewu.sitepush.reconciler.PostPushReconciler
2023-11-11T15:07:19.092+08:00  INFO 7 --- [hReconciler-t-1] r.h.a.e.controller.DefaultController     : Controller worker com.stonewu.sitepush.reconciler.SinglePagePushReconciler-worker-1 started
2023-11-11T15:07:19.092+08:00  INFO 7 --- [hReconciler-t-1] r.h.a.e.controller.RequestSynchronizer   : Starting request(class run.halo.app.core.extension.content.SinglePage) synchronizer...
2023-11-11T15:07:19.094+08:00  INFO 7 --- [hReconciler-t-1] r.h.a.e.controller.DefaultController     : Controller worker com.stonewu.sitepush.reconciler.PostPushReconciler-worker-1 started
2023-11-11T15:07:19.094+08:00  INFO 7 --- [hReconciler-t-1] r.h.a.e.controller.RequestSynchronizer   : Starting request(class run.halo.app.core.extension.content.Post) synchronizer...
2023-11-11T15:07:19.099+08:00  INFO 7 --- [hReconciler-t-1] r.h.a.e.controller.RequestSynchronizer   : Started request(class run.halo.app.core.extension.content.Post) synchronizer.
2023-11-11T15:07:19.100+08:00  INFO 7 --- [hReconciler-t-1] r.h.a.e.controller.RequestSynchronizer   : Started request(class run.halo.app.core.extension.content.SinglePage) synchronizer.
2023-11-11T15:17:09.006+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'ToolBench@1.0.4' resolved
2023-11-11T15:17:09.044+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'ToolBench@1.0.4'
2023-11-11T15:17:47.527+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginBytemd@1.4.0' resolved
2023-11-11T15:17:47.548+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginBytemd@1.4.0'
2023-11-11T15:18:17.846+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'plugin-katex@2.0.0' resolved
2023-11-11T15:18:17.863+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'plugin-katex@2.0.0'
2023-11-11T15:18:48.440+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'ToolBench@1.0.4'
2023-11-11T15:18:48.490+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin ToolBench
2023-11-11T15:18:48.520+08:00  INFO 7 --- [nReconciler-t-1] r.h.t.config.ConfigFolderConfiguration   : detected config directory /root/.halo2/plugins/tool-bench
2023-11-11T15:18:48.552+08:00  INFO 7 --- [onPool-worker-4] r.halo.toolbench.util.FutureDownloader   : start downloading gz file GeoLite2-City.mmdb.gz from server
2023-11-11T15:18:52.790+08:00  INFO 7 --- [onPool-worker-4] r.halo.toolbench.util.FutureDownloader   : gz file GeoLite2-City.mmdb.gz has been successfully downloaded, start unpacking
2023-11-11T15:18:53.535+08:00  INFO 7 --- [onPool-worker-4] r.halo.toolbench.util.FutureDownloader   : deleting gz file GeoLite2-City.mmdb.gz
2023-11-11T15:20:07.125+08:00  WARN 7 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PostReconciler-worker-1/Request[name=781f38d6-3fe8-4b10-bb4b-4fe59e2b89d9]
2023-11-11T15:21:54.180+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginBytemd@1.4.0'
2023-11-11T15:21:54.184+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginBytemd
2023-11-11T15:22:01.969+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'plugin-katex@2.0.0'
2023-11-11T15:22:01.976+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin plugin-katex
2023-11-11T15:23:09.340+08:00  WARN 7 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PostReconciler-worker-1/Request[name=89e5593a-30cb-49ea-ad08-e49eb4a7903c]
2023-11-11T15:26:15.627+08:00  INFO 7 --- [      Thread-25] h.a.c.e.a.e.LocalAttachmentUploadHandler : Wrote attachment bayes.jpg into /root/.halo2/attachments/upload/bayes.jpg
2023-11-11T15:35:39.746+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'PluginStackEdit@1.1.1' resolved
2023-11-11T15:35:39.751+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginStackEdit@1.1.1'
2023-11-11T15:35:48.489+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginStackEdit@1.1.1'
2023-11-11T15:35:48.494+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginStackEdit
2023-11-11T15:36:00.718+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'PluginBytemd@1.4.0'
2023-11-11T15:38:14.133+08:00  WARN 7 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.PostReconciler-worker-1/Request[name=53623ebc-30c9-4a33-806f-525adbac1f0a]
```

**Comment by ruibaby** [comment]
建议根据这两个 issue 提供的方式进行排查，很可能是其他插件的干扰。

- https://github.com/halo-dev/halo/issues/4841#issuecomment-1803898906
- https://github.com/halo-dev/halo/issues/4825

/triage needs-information

**Comment by wt12318** [comment]
感谢，是 ToolBench 插件的问题，关闭了就正常了
