### ISSUE TITLE
新版本1.2.0 不支持mariaDB 10.1

### ISSUE THREAD

**Issue by wangjianan1103** [halo-dev/halo#485]
## 我的环境
升级1.2.0 版本

---

## 错误日志

rted by Flyway Pro Edition.
	at org.flywaydb.core.internal.database.base.Database.ensureDatabaseNotOlderThanOtherwiseRecommendUpgradeToFlywayEdition(Database.java:169) ~[flyway-core-6.1.0.jar!/:na]
	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.ensureSupported(MySQLDatabase.java:278) ~[flyway-core-6.1.0.jar!/:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:495) ~[flyway-core-6.1.0.jar!/:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-6.1.0.jar!/:na]
	at run.halo.app.listener.StartedListener.migrate(StartedListener.java:86) ~[classes!/:1.2.0]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:58) ~[classes!/:1.2.0]
	at run.halo.app.listener.StartedListener.onApplicationEvent(StartedListener.java:33) ~[classes!/:1.2.0]
	at run.halo.app.listener.StartedListener$$EnhancerBySpringCGLIB$$da984ac1.onApplicationEvent(<generated>) ~[classes!/:1.2.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) ~[spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:98) ~[spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:71) ~[spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) [spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at run.halo.app.Application.main(Application.java:35) [classes!/:1.2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [halo-latest.jar:1.2.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [halo-latest.jar:1.2.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [halo-latest.jar:1.2.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [halo-latest.jar:1.2.0]
---

## 期望行为

这个会修复嘛。

**Comment by ruibaby** [comment]
抱歉 ，这个问题我们无法修复。 Flyway 社区办不支持旧版本 mariaDB 10.1。

**Comment by wangjianan1103** [comment]
好的，谢谢
