### ISSUE TITLE
路由器掉电后，重新启动不了在Docker下的Halo了

### ISSUE THREAD

**Issue by xyblue135** [halo-dev/halo#4982]
### 你当前使用的版本

halo:2.11

### 描述一下此特性
```java
stdout: Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: "/root/.halo2/db/halo-next.mv.db". Possible solution: use the recovery tool [90030-224]
stdout: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.message.DbException.get(DbException.java:212) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:163) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.mvstore.db.Store.<init>(Store.java:142) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.engine.Database.<init>(Database.java:326) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.engine.Engine.openSession(Engine.java:92) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.engine.Engine.openSession(Engine.java:222) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.engine.Engine.createSession(Engine.java:201) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at io.r2dbc.h2.client.SessionClient.<init>(SessionClient.java:58) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
stdout: 	at io.r2dbc.h2.H2ConnectionFactory.getSessionClient(H2ConnectionFactory.java:117) ~[r2dbc-h2-1.0.0.RELEASE.jar:1.0.0.RELEASE]
stdout: 	... 16 common frames omitted
stdout: Caused by: org.h2.mvstore.MVStoreException: File is corrupted - unable to recover a valid set of chunks [2.2.224/6]
stdout: 	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.mvstore.RandomAccessStore.readStoreHeader(RandomAccessStore.java:320) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.mvstore.FileStore.start(FileStore.java:916) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.mvstore.MVStore.<init>(MVStore.java:289) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035) ~[h2-2.2.224.jar:2.2.224]
stdout: 	at org.h2.mvstore.db.Store.<init>(Store.java:133) ~[h2-2.2.224.jar:2.2.224]
stdout: 	... 23 common frames omitted
stdout: 
```

**Comment by ruibaby** [comment]
看起来是 h2 物理文件损坏，目前你只能尝试通过 h2 恢复工具，相关 issue：https://github.com/halo-dev/halo/issues/4060

此外，我们并不推荐在生产环境使用 h2 数据库，如果一定要用请定时备份数据。

<img width="1029" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/40146289-c940-478c-9c97-859b723f8cf8">

/triage duplicate
/kind bug
