### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by xiaopengzzc** [halo-dev/halo#4990]
### System information

![image](https://github.com/halo-dev/halo/assets/136769452/430b5fb6-b110-45d0-8451-9c55cee24808)
- 外部访问地址: https://chovy.cn/
- 启动时间: 2023-12-04 14:55
- 版本: 2.11.1
- 构建时间: 2023-12-02 22:53
- Git Commit: 54f77d5
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.4.0-47-generic
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [prism.js 代码高亮](https://github.com/liuzhihang/plugin-prismjs)
  - [无色界](https://github.com/guqing/halo-plugin-colorless)
  - [WordPress导入](https://github.com/wan92hen/plugin-wordpress)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - 联系表单
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### What is the project operation method?

Docker Compose

### Your site address.

https://chovy.cn/   ----  http://47.100.93.202:8096/

### What happened?

后台页面可以登录，但是前端页面无法进入，ip地址也试了，和域名地址显示一样，
![image](https://github.com/halo-dev/halo/assets/136769452/8129a5e8-c7f4-4c5e-aa42-89f53f48e2f9)
![image](https://github.com/halo-dev/halo/assets/136769452/cc354353-e300-4311-9ef4-14477bbe9695)

### Relevant log output

```shell
Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.publisher.Mono.block(Mono.java:1728) ~[reactor-core-3.6.0.jar:3.6.0]
                at run.halo.app.theme.ReactiveSpelVariableExpressionEvaluator.evaluate(ReactiveSpelVariableExpressionEvaluator.java:37) ~[classes/:2.11.1]
                at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.standard.processor.StandardWithTagProcessor.doProcess(StandardWithTagProcessor.java:93) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:222) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
                at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.0.jar:3.6.0]
                at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
                ... 1 common frames omitted
```

### Additional information

![image](https://github.com/halo-dev/halo/assets/136769452/27f18959-d11f-4350-a78f-765605c47083)

**Comment by ruibaby** [comment]
<img width="675" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/645c903c-a6f0-47dc-ae8e-3f2229bafdf2">

你可以尝试换一个主题试试，从这个日志来看，似乎是主题请求了一个不存在的页面。

**Comment by ruibaby** [comment]
看了一下他们的代码：https://github.com/search?q=repo%3Aliuzhihang%2Fhalo-theme-hao%20equipment&type=code

你似乎需要安装一个 https://github.com/chengzhongxue/plugin-equipments 插件或者关闭掉侧边评论模块。具体建议查询一下这个主题是否有这样的 issue，或者向这个主题提交新 issue。
