### ISSUE TITLE
附件上传不了

### ISSUE THREAD

**Issue by a12cn** [halo-dev/halo#4998]
### 系统信息

Debian 12 有宝塔waf(已设置成观察模式)

### 使用的哪种方式运行？

Docker Compose

### 在线站点地址

www.a12x.cn

### 发生了什么？

![747A38D1CB45EA71375A77413451A108](https://github.com/halo-dev/halo/assets/143017744/4efa0dea-5ebc-45ff-a205-1d6e147b78fb)

### 相关日志输出

```shell
2023-12-05T18:33:39.717+08:00 ERROR 8 --- [boundedElastic-70] o.t.spring6.SpringWebFluxTemplateEngine  : [THYMELEAF][boundedElastic-70] Exception processing template "post": Error during execution of processor 'org.thymeleaf.standard.processor.StandardWithTagProcessor' (template: "post" - line 123, col 5)

org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.standard.processor.StandardWithTagProcessor' (template: "post" - line 123, col 5)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:117) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.0.jar:3.6.0]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions$ReactiveException.fillInStackTrace(Exceptions.java:734) ~[reactor-core-3.6.0.jar:3.6.0]
	at java.base/java.lang.Throwable.<init>(Unknown Source) ~[na:na]
	at java.base/java.lang.Throwable.<init>(Unknown Source) ~[na:na]
	at java.base/java.lang.Exception.<init>(Unknown Source) ~[na:na]
	at java.base/java.lang.RuntimeException.<init>(Unknown Source) ~[na:na]
	at reactor.core.Exceptions$ReactiveException.<init>(Exceptions.java:724) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.Exceptions.propagate(Exceptions.java:408) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:95) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.publisher.Mono.block(Mono.java:1728) ~[reactor-core-3.6.0.jar:3.6.0]
	at run.halo.app.theme.ReactiveSpelVariableExpressionEvaluator.evaluate(ReactiveSpelVariableExpressionEvaluator.java:37) ~[classes/:2.11.1]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.processor.StandardWithTagProcessor.doProcess(StandardWithTagProcessor.java:93) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	... 25 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountDownLatch.await(Unknown Source) ~[na:na]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:90) ~[reactor-core-3.6.0.jar:3.6.0]
	... 34 common frames omitted

2023-12-05T21:08:33.062+08:00  INFO 8 --- [reactor-tcp-epoll-3] run.halo.toolbench.util.PostUtil         : raw -> <h1 style="" id="heading-1">随机动漫</h1><p style=""><iframe src="https://tuapi.eees.cc/api.php?category=dongman&amp;px= " width="100%" height="1000px" frameborder="0" allowfullscreen="true" framespacing="0" style="display: inline-block"></iframe></p><h1 style="" id="heading-2">随机风景</h1><p style=""><iframe src="https://tuapi.eees.cc/api.php?category=fengjing&amp;px= " width="100%" height="1000px" frameborder="0" allowfullscreen="true" framespacing="0" style="display: inline-block"></iframe></p><h1 style="" id="heading-3">随机小姐姐</h1><p style=""><iframe src="https://tuapi.eees.cc/api.php?category=meinv&amp;px=" width="100%" height="1000px" frameborder="0" allowfullscreen="true" framespacing="0" style="display: inline-block"></iframe></p>

2023-12-05T21:08:33.088+08:00  INFO 8 --- [reactor-tcp-epoll-3] run.halo.toolbench.util.PostUtil         : raw -> <h1 style="" id="heading-1">随机动漫</h1><p style=""><iframe src="https://tuapi.eees.cc/api.php?category=dongman&amp;px= " width="100%" height="1000px" frameborder="0" allowfullscreen="true" framespacing="0" style="display: inline-block"></iframe></p><h1 style="" id="heading-2">随机风景</h1><p style=""><iframe src="https://tuapi.eees.cc/api.php?category=fengjing&amp;px= " width="100%" height="1000px" frameborder="0" allowfullscreen="true" framespacing="0" style="display: inline-block"></iframe></p><h1 style="" id="heading-3">随机小姐姐</h1><p style=""><iframe src="https://tuapi.eees.cc/api.php?category=meinv&amp;px=" width="100%" height="1000px" frameborder="0" allowfullscreen="true" framespacing="0" style="display: inline-block"></iframe></p>
```

**Comment by a12cn** [comment]
已解决，WAF问题
