### ISSUE TITLE
docker-compose启动时报错：ERROR 7 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController...

### ISSUE THREAD

**Issue by ChengJianfei4505** [halo-dev/halo#5026]
### 系统信息

- 外部访问地址: https://blog.alwayshere.top
- 启动时间: 
- 版本: 2.11.2
- 构建时间: 2023-12-07 16:29
- Git Commit: 97b5f72
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.1.0
- 操作系统: Linux / 3.10.0-1160.92.1.el7.x86_64
- 已激活主题: [Dream](https://github.com/nineya/halo-theme-dream2.0.git)
- 已启动插件:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在使用docker-compose启动时，日志出现如下的报错信息，这会导致什么问题吗？

### 相关日志输出

```shell
2023-12-09T18:57:58.612+08:00 ERROR 7 --- [run.halo.app.search.post.PostEventReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.search.post.PostEventReconciler-worker-1 aborted with an error, re-enqueuing...

reactor.core.Exceptions$ReactiveException: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /root/.halo2/indices/posts/write.lock
        at reactor.core.Exceptions$ReactiveException.fillInStackTrace(Exceptions.java:734) ~[reactor-core-3.6.0.jar:3.6.0]
        at java.base/java.lang.Throwable.<init>(Unknown Source) ~[na:na]
        at java.base/java.lang.Throwable.<init>(Unknown Source) ~[na:na]
        at java.base/java.lang.Exception.<init>(Unknown Source) ~[na:na]
        at java.base/java.lang.RuntimeException.<init>(Unknown Source) ~[na:na]
        at reactor.core.Exceptions$ReactiveException.<init>(Exceptions.java:724) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.Exceptions.propagate(Exceptions.java:408) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.Mono.block(Mono.java:1728) ~[reactor-core-3.6.0.jar:3.6.0]
        at run.halo.app.search.post.PostEventReconciler.addPostDoc(PostEventReconciler.java:101) ~[classes/:2.11.2]
        at run.halo.app.search.post.PostEventReconciler.reconcile(PostEventReconciler.java:56) ~[classes/:2.11.2]
        at run.halo.app.search.post.PostEventReconciler.reconcile(PostEventReconciler.java:29) ~[classes/:2.11.2]
        at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.11.2.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103) ~[reactor-core-3.6.0.jar:3.6.0]
                ... 10 common frames omitted
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /root/.halo2/indices/posts/write.lock
        at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:126) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:43) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:44) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:947) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at run.halo.app.search.post.LucenePostSearchService.addDocuments(LucenePostSearchService.java:122) ~[classes/:2.11.2]
        at run.halo.app.search.post.PostEventReconciler.lambda$addPostDoc$0(PostEventReconciler.java:94) ~[classes/:2.11.2]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onComplete(FluxHandle.java:223) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onComplete(FluxFilter.java:300) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:139) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onComplete(FluxFilterFuseable.java:171) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:246) ~[reactor-core-3.6.0.jar:3.6.0]
```

**Comment by JohnNiang** [comment]
出现以上错误后，会重试之前的操作（建立文章索引），知道文章索引构建成功。

只要不是持续打印以上错误，是不会有任何影响的。

/triage needs-information

**Comment by ChengJianfei4505** [comment]
> 出现以上错误后，会重试之前的操作（建立文章索引），知道文章索引构建成功。
> 
> 只要不是持续打印以上错误，是不会有任何影响的。
> 
> /triage needs-information

好的，谢谢
