### ISSUE TITLE
文章内容不显示

### ISSUE THREAD

**Issue by fenhuahua** [halo-dev/halo#5049]
### 系统信息

不太方便粘贴

### 使用的哪种方式运行？

Docker

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/153573296/d940ca69-c553-4a9f-84d1-8960932ecb2c)
正常是有东西的，
![image](https://github.com/halo-dev/halo/assets/153573296/4b7c9139-d2fc-4b68-97af-ac31ac4fc05f)
而且最离谱的是文章发布也不是显示的人
![image](https://github.com/halo-dev/halo/assets/153573296/4a9fa3f4-d8f9-44bc-9ec0-aed002e2f614)
![image](https://github.com/halo-dev/halo/assets/153573296/fe98decf-17d9-48c3-a9eb-a185ebbf7eee)
是哪里出问题了？？？

### 相关日志输出

```shell
1Panel-halo-8QY5  | 	at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:476) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.SinkManyEmitterProcessor.tryEmitNext(SinkManyEmitterProcessor.java:273) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at io.asyncer.r2dbc.mysql.client.ReactorNettyClient$ResponseSink.next(ReactorNettyClient.java:383) ~[r2dbc-mysql-1.0.5.jar:1.0.5]
1Panel-halo-8QY5  | 	at io.asyncer.r2dbc.mysql.client.ReactorNettyClient.lambda$new$0(ReactorNettyClient.java:121) ~[r2dbc-mysql-1.0.5.jar:1.0.5]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:294) ~[reactor-netty-core-1.1.13.jar:1.1.13]
1Panel-halo-8QY5  | 	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:403) ~[reactor-netty-core-1.1.13.jar:1.1.13]
1Panel-halo-8QY5  | 	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:426) ~[reactor-netty-core-1.1.13.jar:1.1.13]
1Panel-halo-8QY5  | 	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.13.jar:1.1.13]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.asyncer.r2dbc.mysql.client.MessageDuplexCodec.handleDecoded(MessageDuplexCodec.java:162) ~[r2dbc-mysql-1.0.5.jar:1.0.5]
1Panel-halo-8QY5  | 	at io.asyncer.r2dbc.mysql.client.MessageDuplexCodec.channelRead(MessageDuplexCodec.java:73) ~[r2dbc-mysql-1.0.5.jar:1.0.5]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475) ~[netty-handler-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338) ~[netty-handler-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387) ~[netty-handler-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
1Panel-halo-8QY5  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 
1Panel-halo-8QY5  | 2023-12-15T17:25:40.344+08:00  WARN 7 --- [tor-tcp-epoll-3] r.h.h.HighlightJSHeadProcessor           : Parse route pattern [/app/{admin,user}/**] failed
1Panel-halo-8QY5  | 
1Panel-halo-8QY5  | org.springframework.web.util.pattern.PatternParseException: Char ',' is not allowed in a captured variable name
1Panel-halo-8QY5  | 	at org.springframework.web.util.pattern.InternalPathPatternParser.parse(InternalPathPatternParser.java:179) ~[spring-web-6.1.1.jar:6.1.1]
1Panel-halo-8QY5  | 	at org.springframework.web.util.pattern.PathPatternParser.parse(PathPatternParser.java:129) ~[spring-web-6.1.1.jar:6.1.1]
1Panel-halo-8QY5  | 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at org.springframework.web.util.pattern.PathPatternRouteMatcher.getPathPattern(PathPatternRouteMatcher.java:95) ~[spring-web-6.1.1.jar:6.1.1]
1Panel-halo-8QY5  | 	at org.springframework.web.util.pattern.PathPatternRouteMatcher.match(PathPatternRouteMatcher.java:79) ~[spring-web-6.1.1.jar:6.1.1]
1Panel-halo-8QY5  | 	at run.halo.highlightjs.HighlightJSHeadProcessor.isMatchedRoute(HighlightJSHeadProcessor.java:125) ~[na:na]
1Panel-halo-8QY5  | 	at run.halo.highlightjs.HighlightJSHeadProcessor.lambda$mismatchedRoute$2(HighlightJSHeadProcessor.java:120) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at java.base/java.util.stream.ReferencePipeline.noneMatch(Unknown Source) ~[na:na]
1Panel-halo-8QY5  | 	at run.halo.highlightjs.HighlightJSHeadProcessor.mismatchedRoute(HighlightJSHeadProcessor.java:120) ~[na:na]
1Panel-halo-8QY5  | 	at run.halo.highlightjs.HighlightJSHeadProcessor.lambda$process$0(HighlightJSHeadProcessor.java:51) ~[na:na]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:269) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:528) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:385) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:159) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2842) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2231) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredComplete(FluxUsingWhen.java:393) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:528) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2231) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2231) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:210) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:210) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:537) ~[reactor-pool-1.0.3.jar:1.0.3]
1Panel-halo-8QY5  | 	at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:767) ~[reactor-pool-1.0.3.jar:1.0.3]
1Panel-halo-8QY5  | 	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:879) ~[reactor-pool-1.0.3.jar:1.0.3]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:241) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.6.0.jar:3.6.0]
1Panel-halo-8QY5  | 	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:264) ~[reactor-core-3.6.0.jar:3.6.0]
```

**Comment by ruibaby** [comment]
根据描述没有理解到问题所在，根据当前的异常日志似乎是代码高亮的路径匹配规则有问题。

```
1Panel-halo-8QY5  | 2023-12-15T17:25:40.344+08:00  WARN 7 --- [tor-tcp-epoll-3] r.h.h.HighlightJSHeadProcessor           : Parse route pattern [/app/{admin,user}/**] failed
1Panel-halo-8QY5  | 
1Panel-halo-8QY5  | org.springframework.web.util.pattern.PatternParseException: Char ',' is not allowed in a captured variable name
```

/triage needs-information

**Comment by fenhuahua** [comment]
问题:点入一篇文章进行编辑，文章为已发布文章，但是我不能进行二次编辑，进去编辑页面为灰色，不显示其内容，无法编辑，应该怎么办？

**Comment by guqing** [comment]
可以新建一篇文章不涉及敏感信息的复现一下录个屏上传到这里吗，很难想象到 😅， 因为目前我们根据你的步骤无法复现且你没有提供了你安装插件的信息与版本信息

**Comment by lan-yonghui** [comment]
我这边遇到了同样的问题，原因是我使用了[Markdown / HTML 内容块](https://github.com/halo-sigs/plugin-hybrid-edit-block)这个插件，然后在编辑文章的时候内容我填写了"<br>"，导致再次编辑不能显示文章内容。
![image](https://github.com/halo-dev/halo/assets/81747598/870ae972-e2d1-4feb-9e7c-534d36c51424)

**Comment by ruibaby** [comment]
后续可关注：https://github.com/halo-sigs/plugin-hybrid-edit-block/issues/5

/close
