### ISSUE TITLE
设置微软邮箱和163邮箱都无法正常发送邮件

### ISSUE THREAD

**Issue by TaCraft-Sociality** [halo-dev/halo#5052]
### 系统信息

- 外部访问地址: https://www.tcsserver.top/
- 启动时间: 2023-12-16 05:21
- 版本: 2.11.0
- 构建时间: 2023-12-01 12:01
- Git Commit: 0351a67
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.10.0-26-amd64
- 已激活主题: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- 已启动插件:
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

设置微软邮箱和163邮箱都无法正常发送邮件

### 相关日志输出

```shell
设置微软邮箱和163邮箱都无法正常发送邮件
```

**Comment by ruibaby** [comment]
请提供日志。

/triage needs-information

**Comment by wangruikang12** [comment]
org.springframework.mail.MailSendException: Failed messages: org.eclipse.angus.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail [KU1PR03CA0029.apcprd03.prod.outlook.com 2023-12-20T01:43:02.560Z 08DC0095293DB393]

	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:453) ~[spring-context-support-6.1.1.jar:6.1.1]
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:350) ~[spring-context-support-6.1.1.jar:6.1.1]
	at org.springframework.mail.javamail.JavaMailSender.send(JavaMailSender.java:158) ~[spring-context-support-6.1.1.jar:6.1.1]
	at org.springframework.mail.javamail.JavaMailSender.send(JavaMailSender.java:132) ~[spring-context-support-6.1.1.jar:6.1.1]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.6.0.jar:3.6.0]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.6.0.jar:3.6.0]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.Mono.block(Mono.java:1728) ~[reactor-core-3.6.0.jar:3.6.0]
		at run.halo.app.notification.DefaultNotificationSender.lambda$sendNotification$0(DefaultNotificationSender.java:61) ~[classes/:2.11.2]
		at run.halo.app.notification.DefaultNotificationSender.reconcile(DefaultNotificationSender.java:87) ~[classes/:2.11.2]
		at run.halo.app.notification.DefaultNotificationSender.reconcile(DefaultNotificationSender.java:30) ~[classes/:2.11.2]
		at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.11.2.jar:na]
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		... 3 common frames omitted

2023-12-20T09:43:03.405+08:00 ERROR 6 --- [ationSender-t-2] r.h.a.n.DefaultNotificationSender        : Failed to send notification after retrying 3 times, discard it.

**Comment by wan92hen** [comment]
微软邮箱参考配置，可以看下加密方式是否是 TLS
![image](https://github.com/halo-dev/halo/assets/27671436/14800d69-221d-4cc8-9ac1-5e1676479308)

**Comment by wangruikang12** [comment]
https://support.microsoft.com/zh-cn/office/outlook-com-%E7%9A%84-pop-imap-%E5%92%8C-smtp-%E8%AE%BE%E7%BD%AE-d088b986-291d-42b8-9564-9c414e2aa040

**Comment by wangruikang12** [comment]
官网要坑我 我用的
SMTP 服务器名称 | smtp-mail.outlook.com
-- | --

**Comment by wan92hen** [comment]
> 官网要坑我 我用的
> 
> SMTP 服务器名称	smtp-mail.outlook.com

所以现在可以了吗？看报错应该是加密方式的问题，我的邮箱是 hotmail 的，页面给的是 smtp.office365.com 那个。

**Comment by wangruikang12** [comment]
可以了 我@outlook.com的邮件也可以用

> > 官网要坑我 我用的
> > SMTP 服务器名称	smtp-mail.outlook.com
> 
> 所以现在可以了吗？看报错应该是加密方式的问题，我的邮箱是 hotmail 的，页面给的是 smtp.office365.com 那个。

可以了 我@outlook.com的邮件也可以用smtp.office365.com
