### ISSUE TITLE
本地服务器在开发环境运行后，恢复从我的云服务器上的数据，导致错误，无法访问，如何解决，或者怎么清除开发环境的所有数据

### ISSUE THREAD

**Issue by juwenyi** [halo-dev/halo#5084]
### System information

![屏幕截图 2023-12-20 105509](https://github.com/halo-dev/halo/assets/117093096/d487dcf3-ca76-490d-9f38-60a04632dc8d)

### What is the project operation method?

Source Code

### What happened?

我就恢复了一个备份包
![屏幕截图 2023-12-20 105509](https://github.com/halo-dev/halo/assets/117093096/b2d5c343-48de-4281-a795-4895ffb43b43)
但是他现在把我云服务器上的所有备份包都在恢复，而且还备份失败，是在不断同步吗？能否在开发环境清除所有数据，我准备重新启动

### Relevant log output

```shell
ith result: Result[reEnqueue=true, retryAfter=PT1M], usage: 14
2023-12-20T10:54:09.357+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=category-ffljx] after PT1M
2023-12-20T10:54:09.357+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=category-ffljx] after PT1M
2023-12-20T10:54:09.684+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=category-GCiaP] at 2023-12-20T02:54:09.684748600Z
2023-12-20T10:54:09.684+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 >>> Reconciling request Request[name=category-GCiaP] a
t 2023-12-20T02:54:09.684748600Z
2023-12-20T10:54:09.699+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 >>> Reconciled request: Request[name=category-GCiaP] w
ith result: Result[reEnqueue=true, retryAfter=PT1M], usage: 14
2023-12-20T10:54:09.699+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=category-GCiaP] after PT1M
2023-12-20T10:54:09.699+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=category-GCiaP] after PT1M
2023-12-20T10:54:09.888+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=category-YiOhy] at 2023-12-20T02:54:09.888854900Z
2023-12-20T10:54:09.888+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 >>> Reconciling request Request[name=category-YiOhy] a
t 2023-12-20T02:54:09.888854900Z
2023-12-20T10:54:09.901+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 >>> Reconciled request: Request[name=category-YiOhy] w
ith result: Result[reEnqueue=true, retryAfter=PT1M], usage: 13
2023-12-20T10:54:09.902+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=category-YiOhy] after PT1M
2023-12-20T10:54:09.902+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=category-YiOhy] after PT1M
2023-12-20T10:54:09.968+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=category-YpYXG] at 2023-12-20T02:54:09.968499300Z
2023-12-20T10:54:09.968+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 >>> Reconciling request Request[name=category-YpYXG] a
t 2023-12-20T02:54:09.968499300Z
2023-12-20T10:54:09.983+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 >>> Reconciled request: Request[name=category-YpYXG] w
ith result: Result[reEnqueue=true, retryAfter=PT1M], usage: 14
2023-12-20T10:54:09.983+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=category-YpYXG] after PT1M
2023-12-20T10:54:09.983+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=category-YpYXG] after PT1M
2023-12-20T10:54:10.137+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Take request Request[name=category-YcNeG] at 2023-12-20T02:54:10.137748600Z
2023-12-20T10:54:10.137+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 >>> Reconciling request Request[name=category-YcNeG] a
t 2023-12-20T02:54:10.137748600Z
2023-12-20T10:54:10.149+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.e.controller.DefaultController     : run.halo.app.core.extension.reconciler.CategoryReconciler-worker-1 >>> Reconciled request: Request[name=category-YcNeG] w
ith result: Result[reEnqueue=true, retryAfter=PT1M], usage: 11
2023-12-20T10:54:10.149+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Adding request Request[name=category-YcNeG] after PT1M
2023-12-20T10:54:10.149+08:00 DEBUG 18524 --- [yReconciler-t-1] r.h.a.extension.controller.DefaultQueue  : Added request Request[name=category-YcNeG] after PT1M
<============-> 92% EXECUTING [6m 41s] 
运行结果日记没有问题
```

**Comment by guqing** [comment]
这里的备份列表只是因为你从备份恢复过来的数据记录，备份失败的原因你可以鼠标挪到红点上面看一下是因为什么

**Comment by juwenyi** [comment]
> 这里的备份列表只是因为你从备份恢复过来的数据记录，备份失败的原因你可以鼠标挪到红点上面看一下是因为什么

![image](https://github.com/halo-dev/halo/assets/117093096/cd873045-3b84-441b-9d52-33320b73c193)

**Comment by juwenyi** [comment]
主要我就恢复了云服务器上的一个备份包，恢复完我感觉他就和我云服务器连通了，我云服务器上备份操作这边也会显示

**Comment by juwenyi** [comment]
而且现在我本地服务器无法再进行恢复或者备份操作了

**Comment by juwenyi** [comment]
我现在选择上传文件 会报错 日记：
 [e32110b1-1033] Resolved [FileSystemException: C:\Users\administrator.HRC\halo2-dev\plugins\app-store-integration-1.0.0-b
eta.2.jar: 另一个程序正在使用此文件，进程无法访问。] for HTTP POST /apis/api.console.migration.halo.run/v1alpha1/restorations
2023-12-20T11:16:05.111+08:00 ERROR 18524 --- [undedElastic-16] a.w.r.e.AbstractErrorWebExceptionHandler : [e32110b1-1033]  500 Server Error for HTTP POST "/apis/api.console.migration.halo.run/v1alpha1/restorations"

java.nio.file.FileSystemException: C:\Users\administrator.HRC\halo2-dev\plugins\app-store-integration-1.0.0-beta.2.jar: 另一个程序正在使用此文件，进程无法访问。
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[na:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ? run.halo.app.console.ProxyFilter [DefaultWebFilterChain]
        *__checkpoint ? run.halo.app.console.ProxyFilter [DefaultWebFilterChain]
        *__checkpoint ? run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
        *__checkpoint ? run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
        *__checkpoint ? run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
        *__checkpoint ? run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
        *__checkpoint ? AuthorizationWebFilter [DefaultWebFilterChain]
        *__checkpoint ? ExceptionTranslationWebFilter [DefaultWebFilterChain]
        *__checkpoint ? LogoutWebFilter [DefaultWebFilterChain]
        *__checkpoint ? ServerRequestCacheWebFilter [DefaultWebFilterChain]
        *__checkpoint ? SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
        *__checkpoint ? AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ? AuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ? ReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ? CsrfWebFilter [DefaultWebFilterChain]
        *__checkpoint ? CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ? HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        *__checkpoint ? ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ? OrderedWebFilter [DefaultWebFilterChain]
        *__checkpoint ? OrderedWebFilter [DefaultWebFilterChain]
        *__checkpoint ? OrderedWebFilter [DefaultWebFilterChain]
        *__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint ? HTTP POST "/apis/api.console.migration.halo.run/v1alpha1/restorations" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[na:na]
                at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[na:na]
                at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[na:na]
                at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:171) ~[na:na]
                at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:284) ~[na:na]
                at java.base/java.nio.file.Files.copy(Files.java:1305) ~[na:na]
                at org.springframework.util.FileSystemUtils$2.visitFile(FileSystemUtils.java:139) ~[spring-core-6.1.1.jar:6.1.1]
                at org.springframework.util.FileSystemUtils$2.visitFile(FileSystemUtils.java:130) ~[spring-core-6.1.1.jar:6.1.1]
                at java.base/java.nio.file.Files.walkFileTree(Files.java:2811) ~[na:na]
                at org.springframework.util.FileSystemUtils.copyRecursively(FileSystemUtils.java:130) ~[spring-core-6.1.1.jar:6.1.1]
                at run.halo.app.migration.impl.MigrationServiceImpl.lambda$restoreWorkdir$10(MigrationServiceImpl.java:171) ~[main/:na]
                at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.0.jar:3.6.0]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.0.jar:3.6.0]
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
                at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

**Comment by guqing** [comment]
> 主要我就恢复了云服务器上的一个备份包，恢复完我感觉他就和我云服务器连通了，我云服务器上备份操作这边也会显示

你使用的什么数据库？ 备份恢复之后本地和服务器都使用的同一个服务器的公网数据库？

**Comment by guqing** [comment]
> 我现在选择上传文件 会报错 日记： [e32110b1-1033] Resolved [FileSystemException: C:\Users\administrator.HRC\halo2-dev\plugins\app-store-integration-1.0.0-b eta.2.jar: 另一个程序正在使用此文件，进程无法访问。] for HTTP POST 

这应该是你的 windows 系统问题和 halo 无关，可能是有另外一个进程正在占用它，可以选择结束所有 java 进程然后重启 halo 不行就重启电脑
