### ISSUE TITLE
重启报错

### ISSUE THREAD

**Issue by xiedeacc** [halo-dev/halo#5090]
### System information

- External url: 
- Start time: 2023-12-20 16:35
- Version: 2.12.0-SNAPSHOT
- Build time: 2023-12-19 22:03
- Git Commit: d6dc2a7
- Java: Java(TM) SE Runtime Environment / 17.0.9+11-LTS-201
- Database: (Ubuntu) / 8.0.35-0ubuntu0.20.04.1
- Operating system: Linux / 5.15.0-1051-aws
- Activated theme: [Earth](https://github.com/halo-dev/theme-earth.git)
- Enabled plugins: 

### What is the project operation method?

Fat Jar

### What happened?

重启后报错

```
2023-12-20T16:35:53.972+08:00 ERROR 76797 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.search.post.PostEventReconciler-worker-1 aborted with an error, re-enqueuing...

reactor.core.Exceptions$ReactiveException: java.nio.file.AccessDeniedException: /home/ubuntu/.halo2/indices/posts/_7.cfs
        at reactor.core.Exceptions.propagate(Exceptions.java:408) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.Mono.block(Mono.java:1728) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at run.halo.app.search.post.PostEventReconciler.addPostDoc(PostEventReconciler.java:101) ~[!/:2.12.0-SNAPSHOT]
        at run.halo.app.search.post.PostEventReconciler.reconcile(PostEventReconciler.java:56) ~[!/:2.12.0-SNAPSHOT]
        at run.halo.app.search.post.PostEventReconciler.reconcile(PostEventReconciler.java:29) ~[!/:2.12.0-SNAPSHOT]
        at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.12.0-SNAPSHOT.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103) ~[reactor-core-3.6.0.jar!/:3.6.0]
                ... 10 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /home/ubuntu/.halo2/indices/posts/_7.cfs
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181) ~[na:na]
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298) ~[na:na]
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357) ~[na:na]
        at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:465) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.store.FSDirectory.fsync(FSDirectory.java:303) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.store.FSDirectory.sync(FSDirectory.java:255) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.store.LockValidatingDirectoryWrapper.sync(LockValidatingDirectoryWrapper.java:68) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:5536) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3733) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:4061) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.index.IndexWriter.shutdown(IndexWriter.java:1324) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1362) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]

```
2023-12-20T16:35:54.098+08:00  INFO 76797 --- [         task-1] run.halo.app.search.IndicesInitializer   : Initialize post indices...
2023-12-20T16:35:54.583+08:00 ERROR 76797 --- [tReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.search.post.PostEventReconciler-worker-1 aborted with an error, re-enqueuing...

reactor.core.Exceptions$ReactiveException: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /home/ubuntu/.halo2/indices/posts/write.lock
        at reactor.core.Exceptions.propagate(Exceptions.java:408) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.Mono.block(Mono.java:1728) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at run.halo.app.search.post.PostEventReconciler.addPostDoc(PostEventReconciler.java:101) ~[!/:2.12.0-SNAPSHOT]
        at run.halo.app.search.post.PostEventReconciler.reconcile(PostEventReconciler.java:56) ~[!/:2.12.0-SNAPSHOT]
        at run.halo.app.search.post.PostEventReconciler.reconcile(PostEventReconciler.java:29) ~[!/:2.12.0-SNAPSHOT]
        at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.12.0-SNAPSHOT.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103) ~[reactor-core-3.6.0.jar!/:3.6.0]
                ... 10 common frames omitted
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /home/ubuntu/.halo2/indices/posts/write.lock
        at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:126) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:43) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:44) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:947) ~[lucene-core-9.7.0.jar!/:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
        at run.halo.app.search.post.LucenePostSearchService.addDocuments(LucenePostSearchService.java:122) ~[!/:2.12.0-SNAPSHOT]
        at run.halo.app.search.post.PostEventReconciler.lambda$addPostDoc$0(PostEventReconciler.java:94) ~[!/:2.12.0-SNAPSHOT]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:129) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.6.0.jar!/:3.6.0]
```




### Relevant log output

_No response_

### Additional information

_No response_

**Comment by xiedeacc** [comment]
翻了下issue， 应该和https://github.com/halo-dev/halo/issues/5026一样的问题
