### ISSUE TITLE
切换joe3主题后报错

### ISSUE THREAD

**Issue by xiedeacc** [halo-dev/halo#5105]
### System information

- External url: 
- Start time: 2023-12-24 11:41
- Version: 2.12.0-SNAPSHOT
- Build time: 2023-12-19 22:03
- Git Commit: d6dc2a7
- Java: Java(TM) SE Runtime Environment / 17.0.9+11-LTS-201
- Database: (Ubuntu) / 8.0.35-0ubuntu0.20.04.1
- Operating system: Linux / 5.15.0-1051-aws
- Activated theme: [Theme Joe3](https://github.com/jiewenhuang/halo-theme-joe3.0)
- Enabled plugins:
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

### What is the project operation method?

Fat Jar

### Your site address.

https://blog.xiedeacc.com

### What happened?

访问提示500，后台日志存在两个exception, 看起来是joe3主题不兼容导致
```
2023-12-24T11:42:16.167+08:00 ERROR 94592 --- [tor-tcp-epoll-2] o.s.c.e.ApplicationListenerMethodAdapter : Unexpected error occurred in asynchronous listener

org.springframework.dao.OptimisticLockingFailureException: Failed to update table [extensions]; Version does not match for row with Id [/registry/plugin.halo.run/reverseproxies/reverse-proxy-comment-widget]
        at org.springframework.data.r2dbc.core.R2dbcEntityTemplate.lambda$doUpdate$12(R2dbcEntityTemplate.java:627) ~[spring-data-r2dbc-3.2.0.jar!/:3.2.0]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:113) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredComplete(MonoUsingWhen.java:269) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.FluxUsingWhen$CommitInner.onComplete(FluxUsingWhen.java:528) ~[reactor-core-3.6.0.jar!/:3.6.0]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2231) ~[reactor-core-3.6.0.jar!/:3.6.0]

```

```
2023-12-24T11:42:18.851+08:00  INFO 94592 --- [         task-1] run.halo.app.search.IndicesInitializer   : Initialized post indices. Usage: StopWatch 'PostIndicesWatch': 0.0 seconds
2023-12-24T11:43:19.084+08:00 ERROR 94592 --- [oundedElastic-2] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-2] Exception processing template "index": An error happened during template rendering

org.thymeleaf.exceptions.TemplateOutputException: An error happened during template rendering
        at org.thymeleaf.engine.OutputTemplateHandler.handleText(OutputTemplateHandler.java:75) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleText(ProcessorTemplateHandler.java:587) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.Text.beHandled(Text.java:97) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "(#strings.trim(theme.config.basic.source_link) !='' && theme.config.basic.enable_source_link)? theme.config.basic.source_link : '/themes/theme-Joe3'" (template: "modules/themeSettingVariable" - line 82, col 28)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1001E: Type conversion problem, cannot convert from null to boolean
        at org.springframework.expression.spel.ast.OpAnd.assertValueNotNull(OpAnd.java:69) ~[spring-expression-6.1.1.jar!/:6.1.1]
        at org.springframework.expression.spel.ast.OpAnd.getBooleanValue(OpAnd.java:58) ~[spring-expression-6.1.1.jar!/:6.1.1]
        at org.springframework.expression.spel.ast.OpAnd.getValueInternal(OpAnd.java:52) ~[spring-expression-6.1.1.jar!/:6.1.1]
        at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:212) ~[spring-expression-6.1.1.jar!/:6.1.1]


```

**Comment by ruibaby** [comment]
```
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "(#strings.trim(theme.config.basic.source_link) !='' && theme.config.basic.enable_source_link)? theme.config.basic.source_link : '/themes/theme-Joe3'" (template: "modules/themeSettingVariable" - line 82, col 28)
```

建议向 https://github.com/jiewenhuang/halo-theme-joe3.0 提交 issue，这不属于 Halo 的问题。

/kind support

**Comment by xiedeacc** [comment]
> org.springframework.dao.OptimisticLockingFailureException: Failed to update table [extensions]; Version does not match for row with Id [/registry/plugin.halo.run/reverseproxies/reverse-proxy-comment-widget]

这个异常看起来是你们的org.springframework.dao.OptimisticLockingFailureException: Failed to update table [extensions]; Version does not match for row with Id [/registry/plugin.halo.run/reverseproxies/reverse-proxy-comment-widget]

**Comment by ruibaby** [comment]
这是符合预期的逻辑异常，并不会导致你页面访问异常。

**Comment by xiedeacc** [comment]
好的，感谢哈
