### ISSUE TITLE
启动时，如果没有找到目标主题将会启动失败

### ISSUE THREAD

**Issue by CodeLunatic** [halo-dev/halo#520]
## 我的环境

Server 版本：1.2.0
Admin 版本：1.2.0
数据库：H2
运行模式：production
UA 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

---

## 错误日志

```log
run.halo.app.exception.NotFoundException: 没有找到 id 为 codelunatic_simple 的主题
        at run.halo.app.service.impl.ThemeServiceImpl.lambda$getThemeOfNonNullBy$0(ThemeServiceImpl.java:108) ~[classes!/:1.2.0]
        at java.base/java.util.Optional.orElseThrow(Optional.java:408) ~[na:na]
        at run.halo.app.service.impl.ThemeServiceImpl.getThemeOfNonNullBy(ThemeServiceImpl.java:108) ~[classes!/:1.2.0]
        at run.halo.app.service.impl.ThemeServiceImpl.getActivatedTheme(ThemeServiceImpl.java:374) ~[classes!/:1.2.0]
        at run.halo.app.listener.freemarker.FreemarkerConfigAwareListener.loadThemeConfig(FreemarkerConfigAwareListener.java:99) ~[classes!/:1.2.0]
        at run.halo.app.listener.freemarker.FreemarkerConfigAwareListener.onApplicationStartedEvent(FreemarkerConfigAwareListener.java:58) ~[classes!/:1.2.0]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
```

---

## 期望行为

没有找到目标主题启动就会失败，不太完美，如果没有找到目标主题就默认设置为anatole主题，这样将不会因为主题原因而导致的启动失败。

## 当前行为

当前启动的时候会自动初始化anatole主题，但是并不会在没有找到目标主题的情况下自动设置为anatole主题，而是导致启动失败。

**Comment by ruibaby** [comment]
@CodeLunatic https://github.com/halo-dev/halo/issues/479

**Comment by CodeLunatic** [comment]
谢谢，刚才没看到😄 @ruibaby

**Comment by ruibaby** [comment]
@CodeLunatic 会在下个版本修复。
