### ISSUE TITLE
删除菜单后无法正常访问页面

### ISSUE THREAD

**Issue by qdriven** [halo-dev/halo#5225]
### System information

Docker，Halo 2.11

### What is the project operation method?

Docker

### What happened?

1. 删除菜单之后出现Halo不能访问

### Relevant log output

```shell
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  | 	Suppressed: java.lang.Exception: #block terminated with an error
halo  | 		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103) ~[reactor-core-3.6.0.jar:3.6.0]
halo  | 		at reactor.core.publisher.Mono.block(Mono.java:1728) ~[reactor-core-3.6.0.jar:3.6.0]
halo  | 		... 33 common frames omitted
halo  | 
halo  | 2024-01-22T00:49:57.117+08:00 ERROR 7 --- [ndedElastic-137] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-137] Exception processing template "error/500": Error during execution of processor 'org.thymeleaf.standard.processor.StandardWithTagProcessor' (template: "modules/sidebar" - line 14, col 19)
halo  | 
halo  | org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.standard.processor.StandardWithTagProcessor' (template: "modules/sidebar" - line 14, col 19)
halo  | 	at org.thymeleaf.processor.e

halo  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  | Caused by: run.halo.app.infra.exception.NotFoundException: 404 NOT_FOUND "Menu with name menu-ykSLW not found"
halo  | 	at run.halo.app.theme.finders.impl.MenuFinderImpl.lambda$getByName$1(MenuFinderImpl.java:47) ~[classes/:2.11.0]
halo  | 	at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55) ~[reactor-core-3.6.0.jar:3.6.0]
halo  | 	at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.0.jar:3.6.0]
```

**Comment by JohnNiang** [comment]
/retitle 删除菜单后无法正常访问页面

建议去菜单处新增一个菜单并设置为主菜单。或者去主题设置页面选择菜单。

/triage needs-information

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue。

/close
