### ISSUE TITLE
Invalid character '/' for PATH_SEGMENT in "/notify.png"

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo#5253]
### What happened?

当 logo 的路径以 `/` 开头时会出现如标题所述异常，应该是由于 https://github.com/halo-dev/halo/pull/5148 改动所致

问题出现在：https://github.com/halo-dev/halo/blob/22104fe636fc0c2a01dac1cf03668dfd523a6d77/application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java#L250-L255

能复现问题的插件： https://github.com/monyuan/notify-me

<details>
<summary>点击查看异常信息</summary>

```
java.lang.IllegalArgumentException: Invalid character '/' for PATH_SEGMENT in "/notify.png"
	at org.springframework.web.util.HierarchicalUriComponents.verifyUriComponent(HierarchicalUriComponents.java:422) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.util.HierarchicalUriComponents$PathSegmentComponent.verify(HierarchicalUriComponents.java:974) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.util.HierarchicalUriComponents.verify(HierarchicalUriComponents.java:386) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.util.HierarchicalUriComponents.<init>(HierarchicalUriComponents.java:146) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.util.UriComponentsBuilder.buildInternal(UriComponentsBuilder.java:445) ~[spring-web-6.1.3.jar:6.1.3]
	at org.springframework.web.util.UriComponentsBuilder.build(UriComponentsBuilder.java:433) ~[spring-web-6.1.3.jar:6.1.3]
	at run.halo.app.core.extension.reconciler.PluginReconciler.resolveStaticResources(PluginReconciler.java:254) ~[classes/:na]
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:116) ~[classes/:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:96) ~[classes/:na]
	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:65) ~[classes/:na]
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[classes/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

</details>

### Additional information

/kind bug
/area core
/milestone 2.12.x

**Comment by JohnNiang** [comment]
这里需要确认一下 logo 的规则：

1. HTTP [URL](https://datatracker.ietf.org/doc/html/rfc1738). e.g.: <https://www.halo.run/logo>.
2. Relative Path to `resources` folder. e.g.: `/logo.png`, `logo.png`
3. [Image data URL](https://www.rfc-editor.org/rfc/rfc2397). e.g.: `data:image/png;xxx`

/ping @halo-dev/sig-halo

**Comment by guqing** [comment]
> 这里需要确认一下 logo 的规则：
> 
> 1. HTTP [URL](https://datatracker.ietf.org/doc/html/rfc1738). e.g.: [halo.run/logo](https://www.halo.run/logo).
> 2. Relative Path to `resources` folder. e.g.: `/logo.png`, `logo.png`
> 3. [Image data URL](https://www.rfc-editor.org/rfc/rfc2397). e.g.: `data:image/png;xxx`
> 
> /ping @halo-dev/sig-halo

是的
