### ISSUE TITLE
加载插件入口失败

### ISSUE THREAD

**Issue by txbxxx** [halo-dev/halo#5255]
### 系统信息

- 外部访问地址: http://blog.tanc.fun:9999/
- 启动时间: 2024-01-23 16:07
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MariaDB Server / 5.5.5-10.4.32-MariaDB
- 操作系统: Linux / 3.10.0-1160.105.1.el7.x86_64
- 已激活主题: [彼岸](https://github.com/guqing/halo-theme-higan)
- 已启动插件:
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - AI 助手
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://blog.tanc.fun:9999

### 发生了什么？

在进入console界面后貌似插件都无法可用了
![image](https://github.com/halo-dev/halo/assets/79389617/e56c3a80-0bb7-4965-84f9-e6aad41774e7)

### 相关日志输出

```shell
2024-01-26T16:53:21.403+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'export2doc@1.2.1'
2024-01-26T16:53:21.433+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin export2doc
2024-01-26T16:56:18.378+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'export2doc@1.2.1'
2024-01-26T16:56:21.943+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'export2doc@1.2.1'
2024-01-26T16:56:21.981+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin export2doc
2024-01-26T16:57:10.641+08:00 ERROR 7 --- [ndedElastic-162] a.w.r.e.AbstractErrorWebExceptionHandler : [cf679f6d-4552]  500 Server Error for HTTP GET "/plugins/plugin-docsme/assets/logo.svg?version=1.0.0-alpha.2"

java.util.zip.ZipException: invalid stored block lengths
	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler run.halo.app.plugin.resources.ReverseProxyRouterFunctionFactory$$Lambda$2563/0x0000000090092dd8@becd38b2 [DispatcherHandler]
	*__checkpoint ? run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ? run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
	*__checkpoint ? run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? HTTP GET "/plugins/plugin-docsme/assets/logo.svg?version=1.0.0-alpha.2" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.io.FilterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.nio.channels.Channels$ReadableByteChannelImpl.read(Unknown Source) ~[na:na]
		at org.springframework.core.io.buffer.DataBufferUtils$ReadableByteChannelGenerator.accept(DataBufferUtils.java:999) ~[spring-core-6.1.1.jar:6.1.1]
		at org.springframework.core.io.buffer.DataBufferUtils$ReadableByteChannelGenerator.accept(DataBufferUtils.java:975) ~[spring-core-6.1.1.jar:6.1.1]
		at reactor.core.publisher.FluxGenerate.lambda$new$1(FluxGenerate.java:58) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:274) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:216) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.request(FluxUsing.java:320) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2331) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxLimitRequest$FluxLimitRequestSubscriber.onSubscribe(FluxLimitRequest.java:132) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.0.jar:3.6.0]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2024-01-26T16:57:19.290+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'text-diagram@1.1.0'
插件停止！
2024-01-26T16:57:19.292+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Unload plugin 'text-diagram@1.1.0'
2024-01-26T16:57:19.300+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'text-diagram@1.2.0' resolved
2024-01-26T16:57:19.501+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'text-diagram@1.2.0'
2024-01-26T16:57:19.525+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin text-diagram
插件启动成功！
2024-01-26T16:57:22.766+08:00 ERROR 7 --- [ndedElastic-164] a.w.r.e.AbstractErrorWebExceptionHandler : [ae9ee838-4576]  500 Server Error for HTTP GET "/plugins/PluginSearchWidget/assets/logo.svg?version=1.3.1"

java.util.zip.ZipException: invalid stored block lengths
	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ? Handler run.halo.app.plugin.resources.ReverseProxyRouterFunctionFactory$$Lambda$2563/0x0000000090092dd8@ec0e3403 [DispatcherHandler]
	*__checkpoint ? run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ? run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
	*__checkpoint ? run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ? run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
	*__checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ? HTTP GET "/plugins/PluginSearchWidget/assets/logo.svg?version=1.3.1" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.io.FilterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.nio.channels.Channels$ReadableByteChannelImpl.read(Unknown Source) ~[na:na]
		at org.springframework.core.io.buffer.DataBufferUtils$ReadableByteChannelGenerator.accept(DataBufferUtils.java:999) ~[spring-core-6.1.1.jar:6.1.1]
		at org.springframework.core.io.buffer.DataBufferUtils$ReadableByteChannelGenerator.accept(DataBufferUtils.java:975) ~[spring-core-6.1.1.jar:6.1.1]
		at reactor.core.publisher.FluxGenerate.lambda$new$1(FluxGenerate.java:58) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:274) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:216) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.request(FluxUsing.java:320) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2331) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxLimitRequest$FluxLimitRequestSubscriber.onSubscribe(FluxLimitRequest.java:132) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.0.jar:3.6.0]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2024-01-26T16:57:46.720+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'export2doc@1.2.1'
2024-01-26T16:57:46.723+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Unload plugin 'export2doc@1.2.1'
2024-01-26T16:57:46.734+08:00  INFO 7 --- [nReconciler-t-1] org.pf4j.AbstractPluginManager           : Plugin 'export2doc@1.2.3' resolved
2024-01-26T16:57:46.911+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'export2doc@1.2.3'
2024-01-26T16:57:47.020+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin export2doc
2024-01-26T16:58:04.667+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'PluginLinks@1.3.2'
2024-01-26T16:58:04.821+08:00  INFO 7 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin PluginLinks
```

**Comment by guqing** [comment]
看起来是你的插件文件都损坏了，你做了什么操作呢

**Comment by ruibaby** [comment]
没有在你的网站上复现这个问题。

<img width="793" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/5b47052a-ca17-447c-9d47-750a2ea2dbbb">

**Comment by ruibaby** [comment]
如果没有后续动态，我将关闭此 issue，后续如果能稳定复现该问题，请提交新 issue。


/close
