### ISSUE TITLE
2.12.0版本归档页500报错

### ISSUE THREAD

**Issue by Saoforest** [halo-dev/halo#5305]
### 系统信息

- 外部访问地址: https://xiaolinz.top
- 启动时间: 2024-02-02 11:21
- 版本: 2.12.0
- 构建时间: 2024-02-01 10:29
- Git Commit: e85a55e
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: PostgreSQL / 16.1
- 操作系统: Linux / 6.1.0-16-amd64
- 已激活主题: [Chirpy](https://github.com/AirboZH/halo-theme-chirpy.git)
- 已启动插件:
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [通知我](https://github.com/monyuan/notify-me)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Webhook](https://github.com/wxyShine/halo-plugin-webhook)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 在线站点地址

https://xiaolinz.top/

### 发生了什么？

访问/archives报错500
<img width="667" alt="image" src="https://github.com/halo-dev/halo/assets/46656157/7252f4d7-b778-46a2-9b16-be9319242da4">

### 相关日志输出

```shell
2024-02-02T12:03:57.820+08:00 ERROR 8 --- [undedElastic-24] a.w.r.e.AbstractErrorWebExceptionHandler : [d790d828-317]  500 Server Error for HTTP GET "/archives"

org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "postFinder.archives(1,-1).items" (template: "archives" - line 14, col 15)
	at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler run.halo.app.theme.router.factories.ArchiveRouteFactory$$Lambda$2887/0x00000000571f1b68@f720a4e2 [DispatcherHandler]
	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HaloAnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/archives" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at run.halo.app.theme.ReactiveSpelVariableExpressionEvaluator.evaluate(ReactiveSpelVariableExpressionEvaluator.java:29) ~[classes/:2.12.0]
		at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.standard.processor.StandardEachTagProcessor.doProcess(StandardEachTagProcessor.java:73) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:1204) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.StandaloneElementTag.beHandled(StandaloneElementTag.java:228) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.2.jar:3.6.2]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.2.jar:3.6.2]
		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.2.jar:3.6.2]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.2.jar:3.6.2]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.2.jar:3.6.2]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.IllegalArgumentException: Page size must not be less than one!
	at org.springframework.util.Assert.isTrue(Assert.java:111) ~[spring-core-6.1.3.jar:6.1.3]
	at run.halo.app.extension.PageRequestImpl.<init>(PageRequestImpl.java:17) ~[api-2.12.0.jar:2.12.0]
	at run.halo.app.extension.PageRequestImpl.of(PageRequestImpl.java:28) ~[api-2.12.0.jar:2.12.0]
	at run.halo.app.theme.finders.impl.PostFinderImpl.archives(PostFinderImpl.java:199) ~[classes/:2.12.0]
	at run.halo.app.theme.finders.impl.PostFinderImpl.archives(PostFinderImpl.java:179) ~[classes/:2.12.0]
	at jdk.internal.reflect.GeneratedMethodAccessor610.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:139) ~[spring-expression-6.1.3.jar:6.1.3]
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:124) ~[spring-expression-6.1.3.jar:6.1.3]
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:107) ~[spring-expression-6.1.3.jar:6.1.3]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:67) ~[spring-expression-6.1.3.jar:6.1.3]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:97) ~[spring-expression-6.1.3.jar:6.1.3]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:114) ~[spring-expression-6.1.3.jar:6.1.3]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:338) ~[spring-expression-6.1.3.jar:6.1.3]
	at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:265) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at run.halo.app.theme.ReactiveSpelVariableExpressionEvaluator.evaluate(ReactiveSpelVariableExpressionEvaluator.java:29) ~[classes/:2.12.0]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.processor.StandardEachTagProcessor.doProcess(StandardEachTagProcessor.java:73) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:1204) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.StandaloneElementTag.beHandled(StandaloneElementTag.java:228) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.2.jar:3.6.2]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by ruibaby** [comment]
/triage duplicate

异常原因可参考：https://github.com/halo-dev/halo/issues/5298#issuecomment-1920614720

cc @AirboZH，[Chirpy](https://github.com/AirboZH/halo-theme-chirpy.git) 的归档页面 size 使用 -1 的原因应该是查询所有数据，这个方式是从何而来呢？这里似乎用 0 也是一样的效果。

此外，这个页面用[模板变量](https://docs.halo.run/developer-guide/theme/template-variables/archives)或许更好。

**Comment by JohnNiang** [comment]
Close in favor of <https://github.com/halo-dev/halo/issues/5298>.

/close

**Comment by AirboZH** [comment]
> /triage duplicate
> 
> 异常原因可参考：[#5298 (comment)](https://github.com/halo-dev/halo/issues/5298#issuecomment-1920614720)
> 
> cc @AirboZH，[Chirpy](https://github.com/AirboZH/halo-theme-chirpy.git) 的归档页面 size 使用 -1 的原因应该是查询所有数据，这个方式是从何而来呢？这里似乎用 0 也是一样的效果。
> 
> 此外，这个页面用[模板变量](https://docs.halo.run/developer-guide/theme/template-variables/archives)或许更好。

收到，我会尽快处理这个问题的！

**Comment by AirboZH** [comment]
ref https://github.com/AirboZH/halo-theme-chirpy/commit/3f1008de52b252f304c4ee49ee01c4b8a46bab7a

**Comment by AirboZH** [comment]
@ruibaby 
> 此外，这个页面用[模板变量](https://docs.halo.run/developer-guide/theme/template-variables/archives)或许更好。

模板变量会分页，原主题这个地方似乎需要一个 listAll 的方法
