### ISSUE TITLE
应用商店安装或更新提示服务器内部发生错误，请稍候再试

### ISSUE THREAD

**Issue by gaofangye** [halo-dev/halo#5377]
### System information

2.12.2

### What is the project operation method?

Docker

### What happened?

使用 curl、curl -I 是可以访问该地址的，但是 ping 无法通。

### Relevant log output

```shell
Caused by: java.net.UnknownHostException: Failed to resolve 'halo-store-assets.031150231bf47fe490654f9e3d11f01d.r2.cloudflarestorage.com' [A(1)]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1120) ~[netty-resolver-dns-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1067) ~[netty-resolver-dns-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:440) ~[netty-resolver-dns-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:68) ~[netty-resolver-dns-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:508) ~[netty-resolver-dns-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.resolver.dns.DnsQueryContext.finishFailure(DnsQueryContext.java:373) ~[netty-resolver-dns-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.resolver.dns.DnsQueryContext$5.run(DnsQueryContext.java:308) ~[netty-resolver-dns-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[netty-transport-classes-epoll-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.105.Final.jar:4.1.105.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by JohnNiang** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/5259#issuecomment-1913260208 for more.

**Comment by gaofangye** [comment]
> /triage duplicate
> 
> See [#5259 (comment)](https://github.com/halo-dev/halo/issues/5259#issuecomment-1913260208) for more.

看里面描述了多个问题，没理解错的话，是需要降级版本到 2.11.3 吗？

**Comment by JohnNiang** [comment]
1. 建议提供完整的错误日志，不仅仅是片段。
2. 建议去 Halo 容器内确认能否正常访问外网。

**Comment by gaofangye** [comment]
> 1. 建议提供完整的错误日志，不仅仅是片段。
> 2. 建议去 Halo 容器内确认能否正常访问外网。

问题已经解决，服务是使用 1Panel 应用商店部署的，删除后自行使用 docker-compose 部署再次访问 Halo 商店正常。
