### ISSUE TITLE
搜索功能BUG

### ISSUE THREAD

**Issue by HeLongaa** [halo-dev/halo#5433]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-02-06 17:07
- 版本: 2.12.2
- 构建时间: 2024-02-05 15:14
- Git Commit: 46efa87
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.4.0-153-generic
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [增强备份（Backup IMproved）](https://halo.run/store/apps/app-dHakX)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

搜索到已经删除的文章。

### 附加信息

![image](https://github.com/halo-dev/halo/assets/71657914/63d8ceaf-c072-4f57-8812-0ad62ed51af5)

**Comment by HeLongaa** [comment]
刷新搜索引擎出现服务器错误，重装后依旧

**Comment by HeLongaa** [comment]
相关日志输出：

2024-03-04T12:15:25.019+08:00 ERROR 6 --- [com.stonewu.sitepush.reconciler.SinglePagePushReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in com.stonewu.sitepush.reconciler.SinglePagePushReconciler-worker-1 aborted with an error, re-enqueuing...

org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:100) ~[spring-r2dbc-6.1.3.jar:6.1.3]
	at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3799) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:96) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:488) ~[reactor-pool-1.0.5.jar:1.0.5]
	at reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:297) ~[reactor-pool-1.0.5.jar:1.0.5]
	at reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:436) ~[reactor-pool-1.0.5.jar:1.0.5]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:725) ~[reactor-pool-1.0.5.jar:1.0.5]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxRetry$RetrySubscriber.resubscribe(FluxRetry.java:120) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoRetry.subscribeOrReturn(MonoRetry.java:50) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4496) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:105) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.MonoUsingWhen.subscribe(MonoUsingWhen.java:87) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.2.jar:3.6.2]
	at reactor.core.publisher.Mono.blockOptional(Mono.java:1777) ~[reactor-core-3.6.2.jar:3.6.2]
	at com.stonewu.sitepush.reconciler.SinglePagePushReconciler.reconcile(SinglePagePushReconciler.java:41) ~[na:na]
	at com.stonewu.sitepush.reconciler.SinglePagePushReconciler.reconcile(SinglePagePushReconciler.java:21) ~[na:na]
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.12.2.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:128) ~[reactor-core-3.6.2.jar:3.6.2]
		at reactor.core.publisher.Mono.blockOptional(Mono.java:1778) ~[reactor-core-3.6.2.jar:3.6.2]
		... 8 common frames omitted
Caused by: reactor.pool.PoolShutdownException: Pool has been shut down
	... 32 common frames omitted

**Comment by JohnNiang** [comment]
Hi @HeLongaa , thank you for reaching out here!

建议重新点击“刷新本地搜索引擎”按钮，如果发生错误，请上传完整的错误日志，不要只提供日志片段。

/triage needs-information
