### ISSUE TITLE
halo后台设置--邮件通知功能bug

### ISSUE THREAD

**Issue by Orange-AFK** [halo-dev/halo#5454]
### 系统信息

- 外部访问地址: https://apoptoxin4869.com
- 启动时间: 2024-03-06 14:43
- 版本: 2.13.0
- 构建时间: 2024-03-01 10:35
- Git Commit: 6ea7abe
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.4.0-172-generic
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [朋友圈](https://github.com/chengzhongxue/plugin-friends)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Umami](https://github.com/halo-sigs/plugin-umami)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

1.访客及注册账户在自定义模板页面留下评论，邮件提醒未收到，但在文章页面留下评论可以正常收到；评论均会显示在管理后台中，此处显示”未知“位置的评论是在自定义模板页面留下的评论
<img width="471" alt="image_93" src="https://github.com/halo-dev/halo/assets/38914772/3063b44b-3a22-43a4-8928-6a9a01d7bcc2">
2.管理员账户在自定义模板页面以及文章页面留下评论，邮件提醒未收到；评论均会显示在管理后台中

3.额外补充：自定义模板页面留下评论【访客、注册账号、管理员账号】均会在halo日志输出中看到错误日志；管理员账号在文章中留下评论，尽管邮件提醒无法收到，但不会报告错误日志

### 相关日志输出

```shell
2024-03-06T16:01:26.420+08:00 ERROR 7 --- [        task-37] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void run.halo.app.content.comment.CommentNotificationReasonPublisher.onNewComment(run.halo.app.event.post.CommentCreatedEvent)

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
	at run.halo.app.content.comment.CommentNotificationReasonPublisher$NewCommentOnPageReasonPublisher.publishReasonBy(CommentNotificationReasonPublisher.java:161) ~[classes/:2.13.0]
	at run.halo.app.content.comment.CommentNotificationReasonPublisher.onNewComment(CommentNotificationReasonPublisher.java:64) ~[classes/:2.13.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113) ~[spring-aop-6.1.4.jar:6.1.4]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by guqing** [comment]
针对你给出的第一点建议给出一个复现步骤，目前根据你的描述无法得知如何复现

/triage needs-information

**Comment by Orange-AFK** [comment]
> 针对你给出的第一点建议给出一个复现步骤，目前根据你的描述无法得知如何复现
> 
> /triage needs-information

复现步骤很简单，只需要以访客或则注册账号在自定义模板页面例如友情链接页面https://apoptoxin4869.com/links留下评论，即可复现报告的错误日志

**Comment by Orange-AFK** [comment]
经网友提醒，更换了几套主题进行测试，最终在使用官方earth主题时该issue的问题得到解决，可以确定是主题的问题，同时也得到比较确定的回复https://github.com/halo-dev/plugin-comment-widget/issues/90，关闭issue，我会向hao主题作者报告该问题

**Comment by Orange-AFK** [comment]
> 经网友提醒，更换了几套主题进行测试，最终在使用官方earth主题时该issue的问题得到解决，可以确定是主题的问题，同时也得到比较确定的回复[https://github.com/halo-dev/plugin-comment-widget/issues/90，关闭issue，我会向hao主题作者报告该问题](https://github.com/halo-dev/plugin-comment-widget/issues/90%EF%BC%8C%E5%85%B3%E9%97%ADissue%EF%BC%8C%E6%88%91%E4%BC%9A%E5%90%91hao%E4%B8%BB%E9%A2%98%E4%BD%9C%E8%80%85%E6%8A%A5%E5%91%8A%E8%AF%A5%E9%97%AE%E9%A2%98)

经网友提醒，更换了几套主题进行测试，最终在使用官方earth主题时该issue的问题得到解决，可以确定是主题的问题，同时也得到比较确定的回复https://github.com/halo-dev/plugin-comment-widget/issues/90%EF%BC%8C%E5%85%B3%E9%97%ADissue%EF%BC%8C%E6%88%91%E4%BC%9A%E5%90%91hao%E4%B8%BB%E9%A2%98%E4%BD%9C%E8%80%85%E6%8A%A5%E5%91%8A%E8%AF%A5%E9%97%AE%E9%A2%98

**Comment by Orange-AFK** [comment]
> <img alt="image" width="605" src="https://private-user-images.githubusercontent.com/38999863/310420881-cbe51142-7a28-4daf-8e67-98f6ba24fd1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTQzOTAsIm5iZiI6MTcwOTcxNDA5MCwicGF0aCI6Ii8zODk5OTg2My8zMTA0MjA4ODEtY2JlNTExNDItN2EyOC00ZGFmLThlNjctOThmNmJhMjRmZDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA4MzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YmU0ZmMyNjQ0OTZhMjU0ZjFjMThlNjExNmY3MDk4ODczODMwYzlkOTQwZWFlNjA2YzQzNGJhM2JkNTMyOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3tDsw2Nz3P-8yURTWL9K-v7R2_NwId5Bhg3rfomfG_Q">
> 根据你的描述无法复现

经网友提醒，更换了几套主题进行测试，最终在使用官方earth主题时该issue的问题得到解决，可以确定是主题的问题，同时也得到比较确定的回复https://github.com/halo-dev/plugin-comment-widget/issues/90%EF%BC%8C%E5%85%B3%E9%97%ADissue%EF%BC%8C%E6%88%91%E4%BC%9A%E5%90%91hao%E4%B8%BB%E9%A2%98%E4%BD%9C%E8%80%85%E6%8A%A5%E5%91%8A%E8%AF%A5%E9%97%AE%E9%A2%98
