### ISSUE TITLE
在使用AI助手时候，没反应

### ISSUE THREAD

**Issue by txbxxx** [halo-dev/halo#5528]
### 系统信息

- 外部访问地址: http://blog.tanc.fun:9999/
- 启动时间: 2024-02-25 11:39
- 版本: 2.11.3
- 构建时间: 2023-12-27 12:13
- Git Commit: 8e9b07d
- Java: IBM Semeru Runtime Open Edition / 17.0.9+9
- 数据库: MariaDB Server / 5.5.5-10.4.32-MariaDB
- 操作系统: Linux / 3.10.0-1160.105.1.el7.x86_64
- 已激活主题: [Hao](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - AI 助手
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在我安装号AI编辑插件后，并且配置了openAI，使用默认编辑器来编辑使用ai会一直显示在写作中
![image](https://github.com/halo-dev/halo/assets/79389617/6aae436c-a4e1-4087-a7b3-3c7ef97e3801)
![image](https://github.com/halo-dev/halo/assets/79389617/33da785b-25b4-4316-86ad-6d14dc25af06)
![image](https://github.com/halo-dev/halo/assets/79389617/e2cb0a15-9f9b-49aa-beb0-a450bfc29323)

**Comment by htwins019** [comment]
我用的是文心一言 提示的是未授权

**Comment by JohnNiang** [comment]
Hi @txbxxx , thank you for reaching out here!

建议提供一下出错时的完整日志，以便排查原因。

/triage needs-information

**Comment by txbxxx** [comment]
> Hi @txbxxx , thank you for reaching out here!
> 
> 建议提供一下出错时的完整日志，以便排查原因。
> 
> /triage needs-information
您好，请问插件的日志在哪呢
2024-03-20T10:52:55.921+08:00  INFO 6 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Stop plugin 'ai-assistant@1.0.0-alpha.2'
插件停止！
2024-03-20T10:53:00.371+08:00  INFO 6 --- [nReconciler-t-1] run.halo.app.plugin.HaloPluginManager    : Start plugin 'ai-assistant@1.0.0-alpha.2'
2024-03-20T10:53:00.402+08:00  INFO 6 --- [nReconciler-t-1] run.halo.app.plugin.BasePlugin           : Initialized plugin ai-assistant
插件启动成功！
我暂时只能查看这个日志

**Comment by txbxxx** [comment]
> Hi @txbxxx , thank you for reaching out here!
> 
> 建议提供一下出错时的完整日志，以便排查原因。
> 
> /triage needs-information

org.springframework.web.reactive.function.client.WebClientRequestException: connection timed out: api.openai.com/157.240.12.50:443
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136) ~[spring-webflux-6.1.1.jar:6.1.1]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to POST https://api.openai.com/v1/chat/completions [DefaultWebClient]
Original Stack Trace:
		at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136) ~[spring-webflux-6.1.1.jar:6.1.1]
		at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:222) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:93) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onError(MonoFlatMapMany.java:204) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:228) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:278) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.maybeOnError(FluxConcatMapNoPrefetch.java:326) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:211) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.SinkManyEmitterProcessor.drain(SinkManyEmitterProcessor.java:476) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.SinkManyEmitterProcessor$EmitterInner.drainParent(SinkManyEmitterProcessor.java:620) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxPublish$PubSubInner.request(FluxPublish.java:874) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:336) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.Operators$DeferredSubscription.request(Operators.java:1743) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:195) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:205) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$ClientTransportSubscriber.onError(HttpClientConnect.java:311) ~[reactor-netty-http-1.1.13.jar:1.1.13]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:205) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onError(DefaultPooledConnectionProvider.java:162) ~[reactor-netty-core-1.1.13.jar:1.1.13]
		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:475) ~[reactor-netty-core-1.1.13.jar:1.1.13]
		at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:433) ~[reactor-netty-core-1.1.13.jar:1.1.13]
		at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:205) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator$PooledConnectionInitializer.onError(DefaultPooledConnectionProvider.java:560) ~[reactor-netty-core-1.1.13.jar:1.1.13]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4512) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.6.0.jar:3.6.0]
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:576) ~[reactor-netty-core-1.1.13.jar:1.1.13]
		at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:522) ~[reactor-netty-core-1.1.13.jar:1.1.13]
		at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:261) ~[reactor-netty-core-1.1.13.jar:1.1.13]
		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:614) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: api.openai.com/157.240.12.50:443
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
这是最新的报错日志貌似是连接超时，如果我想要使用GPT是否还需要手动配置个代理呢？

**Comment by LIlGG** [comment]
> 
> 这是最新的报错日志貌似是连接超时，如果我想要使用GPT是否还需要手动配置个代理呢？

使用 GPT 在国内机器上是需要配置代理的。 AI 助手设置当中本身也提供了全局代理设置。或者你也可以考虑转发 https://api.openai.com 这个地址。

如果确实因为网络无法连接，也可以尝试文心一言。

**Comment by txbxxx** [comment]
> https:

请教一下如何实现转发呢？代理地址又如何配置，有没有相关的博客和文章适合学习一下

**Comment by xiaodingfeng** [comment]
> > https:
> 
> 请教一下如何实现转发呢？代理地址又如何配置，有没有相关的博客和文章适合学习一下

可以使用CloudFlare Pages进行中转，可以得到类似这个地址，然后替换https://api.openai.com
https://chatgptproxyapi-8l9.pages.dev/api

**Comment by ruibaby** [comment]
不属于 Halo 本身的问题，这个问题也无法在此仓库得到解决，所以我将转移到 Discussion。
