### ISSUE TITLE
DOCKER搭建的，群晖硬盘发生故障，恢复后，容器就运行不了了，自动重启容器

### ISSUE THREAD

**Issue by pp6451303** [halo-dev/halo#5691]
### 系统信息

DOCKER搭建的，群晖硬盘发生故障，恢复后，容器就运行不了了，自动重启容器

### 使用的哪种方式运行？

Docker

### 发生了什么？

DOCKER搭建的，群晖硬盘发生故障，恢复后，容器就运行不了了，自动重启容器

### 相关日志输出

```shell
Version: 2.13.1
2024-04-12T00:48:39.222+08:00  INFO 7 --- [           main] run.halo.app.Application                 : Starting Application v2.13.1 using Java 21.0.2 with PID 7 (/application/BOOT-INF/classes started by root in /application)
2024-04-12T00:48:39.265+08:00  INFO 7 --- [           main] run.halo.app.Application                 : No active profile set, falling back to 1 default profile: "default"
2024-04-12T00:48:50.015+08:00  WARN 7 --- [           main] o.s.c.a.AnnotationBeanNameGenerator      : Support for convention-based stereotype names is deprecated and will be removed in a future version of the framework. Please annotate the 'value' attribute in @run.halo.app.theme.finders.Finder with @AliasFor(annotation=Component.class) to declare an explicit alias for @Component's 'value' attribute.
2024-04-12T00:49:14.367+08:00  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2024-04-12T00:49:14.388+08:00  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data R2DBC repositories in DEFAULT mode.
2024-04-12T00:49:18.083+08:00  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 3556 ms. Found 1 R2DBC repository interface.
2024-04-12T00:50:03.598+08:00  INFO 7 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Enabled plugins: []
2024-04-12T00:50:03.637+08:00  INFO 7 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Disabled plugins: [plugin-friends, cloudinary-envoy]
2024-04-12T00:50:03.667+08:00  INFO 7 --- [           main] org.pf4j.DefaultPluginManager            : PF4J version 3.10.0 in 'deployment' mode
2024-04-12T00:50:10.538+08:00  INFO 7 --- [           main] o.a.l.s.MemorySegmentIndexInputProvider  : Using MemorySegmentIndexInput with Java 21; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
2024-04-12T00:50:24.998+08:00  INFO 7 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 32 endpoint(s) beneath base path '/actuator'
2024-04-12T00:50:29.375+08:00  WARN 7 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/R2dbcInitializationConfiguration.class]: Failed to execute database script
2024-04-12T00:50:29.413+08:00  INFO 7 --- [           main] r.h.a.e.c.DefaultControllerManager       : Shutting down 0 controllers...
2024-04-12T00:50:29.420+08:00  INFO 7 --- [           main] r.h.a.e.c.DefaultControllerManager       : Shutdown 0 controllers.
2024-04-12T00:50:29.433+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Disposing controller garbage-collector-controller
2024-04-12T00:50:29.437+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Controller garbage-collector-controller is disposed
2024-04-12T00:50:29.997+08:00  INFO 7 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-04-12T00:50:30.277+08:00 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/R2dbcInitializationConfiguration.class]: Failed to execute database script
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.4.jar:6.1.4]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.3.jar:3.2.3]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:149) ~[spring-boot-3.2.3.jar:3.2.3]
	at run.halo.app.Application.main(Application.java:28) ~[classes/:2.13.1]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[application/:na]
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[application/:na]
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[application/:na]
Caused by: org.springframework.r2dbc.connection.init.UncategorizedScriptException: Failed to execute database script
	at org.springframework.r2dbc.connection.init.DatabasePopulator.lambda$populate$4(DatabasePopulator.java:65) ~[spring-r2dbc-6.1.4.jar:6.1.4]
	at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3836) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3926) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.MonoUsingWhen$ResourceSubscriber.onError(MonoUsingWhen.java:203) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4563) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:96) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:488) ~[reactor-pool-1.0.5.jar:1.0.5]
	at reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:436) ~[reactor-pool-1.0.5.jar:1.0.5]
	at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onError(MonoSubscribeOn.java:152) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:142) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.MonoSupplier$MonoSupplierSubscription.request(MonoSupplier.java:134) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.trySchedule(MonoSubscribeOn.java:189) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onSubscribe(MonoSubscribeOn.java:134) ~[reactor-core-3.6.3.jar:3.6.3]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.6.3.jar:3.6.3]
搜索
```

**Comment by pp6451303** [comment]
<html>
<body>
<div id="ext-comp-1683" syno-ext-id="ext-comp-1683" class="x-window syno-sds-docker-container-status sds-window-v5 x-resizable-pinned x-window-maximized x-window-split active-win" style="margin: 0px; padding: 0px; zoom: 1; box-shadow: rgba(0, 0, 0, 0.6) 0px 4px 16px 0px; border-radius: 3px; overflow: hidden; position: absolute; z-index: 9123; visibility: visible; left: 0px; top: 39px; width: 2560px;"><div class="x-window-bwrap" id="ext-gen4300" style="margin: 0px; padding: 0px; z-index: 1; position: relative; zoom: 1; left: 0px; top: 0px; overflow: hidden;"><div class="x-window-ml" style="margin: 0px; padding: 0px; background: none 0px 0px repeat-y transparent; zoom: 1;"><div class="x-window-mr" style="margin: 0px; padding: 0px; background: none right 0px repeat-y transparent; zoom: 1;"><div class="x-window-mc" id="ext-gen4303" style="margin: 0px; padding: 0px; border-top: 0px !important; border-right: 1px solid rgb(170, 175, 180); border-bottom: 0px !important; border-left: 1px solid rgb(170, 175, 180); border-image: initial !important; background: none rgb(255, 255, 255);"><div class="x-window-body" id="ext-gen4301" style="margin: 0px; padding: 16px 16px 0px; overflow: hidden; background-color: rgb(255, 255, 255); border: none; width: 2528px; height: 1199px;"><div id="ext-comp-1682" syno-ext-id="ext-comp-1682" class="x-tab-panel syno-ux-tab-panel" style="margin: 0px; padding: 0px; overflow: hidden; width: 2528px;"><div class="x-tab-panel-bwrap" id="ext-gen4315" style="margin: 0px; padding: 0px; overflow: hidden; border-color: rgb(122, 170, 204);"><div class="x-tab-panel-body x-tab-panel-body-top" id="ext-gen4316" style="margin: 0px; padding: 4px 0px 0px; overflow: hidden; border: none; background-color: transparent; width: 2528px; height: 1165px;"><div id="ext-comp-1670" syno-ext-id="ext-comp-1670" class="x-panel docker-container-log-panel syno-ux-panel x-panel-noborder" style="margin: 0px; padding: 8px 0px 0px; border-style: solid; border-width: 0px; width: 2528px;"><div class="x-panel-bwrap" id="ext-gen4521" style="margin: 0px; padding: 0px; overflow: hidden; zoom: 1; left: 0px; top: 0px;"><div class="x-panel-body x-panel-body-noheader x-panel-body-noborder x-border-layout-ct" id="ext-gen4523" style="margin: 0px; padding: 0px; border: 0px solid; overflow: hidden; position: relative; zoom: 1; background: none transparent; width: 2528px; height: 1120px;"><div id="ext-comp-1669" syno-ext-id="ext-comp-1669" class="x-panel docker-container-log-logpanel syno-ux-panel x-panel-noborder x-border-panel" style="margin: 0px; padding: 0px 16px; border-style: solid; border-width: 0px; position: absolute; left: 209px; top: 0px; width: 2287px;"><div class="x-panel-bwrap" id="ext-gen4539" style="margin: 0px; padding: 0px; overflow: hidden; zoom: 1; left: 0px; top: 0px;"><div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen4540" style="margin: 0px; padding: 0px; border: 0px solid; overflow: hidden; position: relative; zoom: 1; background: none transparent; width: 2287px; height: 1120px;"><div id="ext-comp-1668" syno-ext-id="ext-comp-1668" class=" x-panel syno-ux-gridpanel x-panel-noborder x-grid-panel hide-org-hd-menu" style="margin: 0px; padding: 8px 0px 0px; border-style: solid; border-width: 0px; width: 2287px;"><div class="x-panel-bwrap" id="ext-gen4594" style="margin: 0px; padding: 0px 0px 12px; overflow: hidden; zoom: 1; left: 0px; top: 0px; color: rgb(65, 75, 85); font-size: 13px; user-select: none;"><div class="x-panel-body x-panel-body-noheader x-panel-body-noborder" id="ext-gen4595" style="margin: 0px; padding: 0px; border: 0px; overflow: hidden !important; position: relative; zoom: 1; background: none transparent; color: rgb(65, 75, 85); font-size: 13px; width: 2287px; height: 1070px;"><div class="x-grid3" hidefocus="true" id="ext-gen4598" style="margin: 0px; padding: 0px; position: relative; overflow: hidden; color: rgb(65, 75, 85); font-size: 13px; background-color: transparent; border-top: 1px solid rgba(198, 212, 224, 0.7); width: 2287px; height: 1069px;"><div class="x-grid3-viewport" id="ext-gen4599" style="margin: 0px; padding: 0px; overflow: hidden; color: rgb(65, 75, 85); font-size: 13px;"><div class="x-grid3-scroller flexcrollactive" id="ext-gen4601" tabindex="-1" style="margin: 0px; padding: 0px; overflow: hidden; zoom: 1; position: relative; outline: none; color: rgb(65, 75, 85); font-size: 13px; width: 2287px; height: 1040px; border-width: 0px; text-align: left;"><div id="ext-gen4601_mcontentwrapper" class="mcontentwrapper" style="margin: 0px; padding: 0px; color: rgb(65, 75, 85); font-size: 13px; width: 2287px; height: 1040px; top: 0px; left: 0px; border-bottom: 0px solid black; text-align: start; position: relative; overflow: hidden; z-index: 2;"><div id="ext-gen4601_contentwrapper" class="contentwrapper" style="margin: 0px; padding: 0px; color: rgb(65, 75, 85); font-size: 13px; position: relative; top: -18656px; width: 2287px; display: block; left: 0px;"><div class="x-grid3-body" id="ext-gen4603" style="margin: 0px; padding: 0px; zoom: 1; color: rgb(65, 75, 85); font-size: 13px; width: 2287px;"><div class="x-grid3-row x-grid3-row-over" role="row" style="margin: 0px; padding: 0px; cursor: default; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(220, 230, 240) rgb(220, 230, 240) rgba(198, 212, 224, 0.4); border-image: initial; width: 2287px; background: none left top repeat-x rgba(5, 127, 235, 0.04); color: rgb(65, 75, 85); font-size: 13px; height: 24px;">
__  __      __ | stdout
-- | --


</td><td class="x-toolbar-right" align="right" style="margin: 0px; padding: 0px; vertical-align: middle; white-space: nowrap;"><table cellspacing="0" class="x-toolbar-right-ct"><tbody><tr><td style="margin: 0px; padding: 0px; vertical-align: middle; white-space: nowrap; text-align: center;"><table cellspacing="0"><tbody><tr class="x-toolbar-right-row"><td class="x-toolbar-cell" id="ext-gen5446" style="margin: 0px; padding: 0px; vertical-align: middle; white-space: nowrap; text-align: center;"><span id="ext-comp-1975" syno-ext-id="" cellspacing="0" class="x-btn syno-sds-webfm-tbar-viewmode-btn-no-margin syno-ux-button syno-ux-button-split syno-ux-button-default syno-ux-button-dropdown x-btn-icon" aria-level="1" style="cursor: pointer; white-space: nowrap; height: 26px; line-height: 26px; border-radius: 3px; display: inline-block; text-align: center; border: 1px solid rgba(198, 212, 224, 0); background-color: rgba(198, 212, 224, 0.4); margin: 0px; padding-right: 0px; width: 45px;"><em class="x-btn-split x-unselectable" unselectable="on" style="font-style: normal; font-weight: normal; display: block; position: relative; cursor: pointer; padding-right: 14px; background-image: url(&quot;images/1x/bt_dp_arrow.png?v=962626479046c582bcbb8b90db41783d&quot;); background-repeat: no-repeat; background-position: right 1px top 1px; height: 26px;"><button type="button" id="ext-gen5447" aria-label="undefined" class=" x-btn-text syno-sds-webfm-tbar-viewmode-btn webfm-viewmode-btn-thumb-medium" tabindex="-1" style="font-family: Verdana, Arial, &quot;Microsoft YaHei&quot;, sans-serif; font-size: 13px; line-height: 1.15; margin: 1px 0px; overflow: visible; text-transform: none; appearance: button; border-radius: 0px; cursor: pointer; white-space: nowrap; padding: 0px 13px 0px 14px; background-image: url(&quot;images/1x/sprite-s7cdc4c4742.png&quot;); background-position-x: 50%; background-position-y: -572px !important; position: relative; background-origin: content-box; width: auto; height: 24px; border-width: 0px 1px 0px 0px; border-style: none solid none none; border-top-color: initial; border-right-color: rgb(200, 210, 220); border-bottom-color: initial; border-left-color: initial; border-image: initial; background-color: transparent; outline: none 0px; background-repeat: no-repeat; color: rgb(65, 75, 85); vertical-align: top; orphans: 2; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </button><br class="Apple-interchange-newline">
</body>
</html>

**Comment by vatebur** [comment]
我也是硬盘故障，重构容器失败，删除容器网络` halo_network`也不行。
`Caused by: io.netty.channel.ConnectTimeoutException: connection timed out after 30000 ms:`
halodb都是正常的但是halo就是启动不了。
怀疑是群晖的容器网络有问题
解决方法：把项目所以的文件拷贝到其他Linux系统上 ，用`docker compose up -d `直接启动就成了
