### ISSUE TITLE
app-store-integration not found

### ISSUE THREAD

**Issue by Herbert0501** [halo-dev/halo#5766]
### 系统信息

- 外部访问地址: https://blog.kangyaocoding.top
- 启动时间: 2024-04-21 12:07
- 版本: 2.14.0
- 构建时间: 2024-04-01 11:15
- Git Commit: ae274db
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.0.36
- 操作系统: Linux / 5.15.0-94-generic
- 已激活主题: [Sakura](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [SEO 工具集](https://github.com/f2ccloud/plugin-seo-tools)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [live2d 看板娘](https://github.com/LIlGG/plugin-live2d)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在启动Halo的时候在日志中看见了，这个问题。不过不影响使用。
是插件启动时出现了错误吗？

### 相关日志输出

```shell
1Panel-halo-Vc3P  | org.pf4j.DependencyResolver$DependenciesNotFoundException: Dependencies '[app-store-integration]' not found
1Panel-halo-Vc3P  | 	at org.pf4j.AbstractPluginManager.resolveDependencies(AbstractPluginManager.java:1068) ~[pf4j-3.11.0.jar:3.11.0]
1Panel-halo-Vc3P  | 	at org.pf4j.AbstractPluginManager.resolvePlugins(AbstractPluginManager.java:820) ~[pf4j-3.11.0.jar:3.11.0]
1Panel-halo-Vc3P  | 	at org.pf4j.AbstractPluginManager.loadPlugin(AbstractPluginManager.java:209) ~[pf4j-3.11.0.jar:3.11.0]
1Panel-halo-Vc3P  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.loadOrReload(PluginReconciler.java:301) ~[classes/:2.14.0]
1Panel-halo-Vc3P  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$reconcile$0(PluginReconciler.java:113) ~[classes/:2.14.0]
1Panel-halo-Vc3P  | 	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
1Panel-halo-Vc3P  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:96) ~[classes/:2.14.0]
1Panel-halo-Vc3P  | 	at run.halo.app.core.extension.reconciler.PluginReconciler.reconcile(PluginReconciler.java:65) ~[classes/:2.14.0]
1Panel-halo-Vc3P  | 	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.14.0.jar:na]
1Panel-halo-Vc3P  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
1Panel-halo-Vc3P  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
1Panel-halo-Vc3P  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
1Panel-halo-Vc3P  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
1Panel-halo-Vc3P  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by JohnNiang** [comment]
可能是某个插件依赖了[应用市场插件](https://www.halo.run/store/apps/app-VYJbF)，但是你的 Halo 实例中并没有安装它。

建议提前安装好这个插件，不然某些插件可能不会正常工作。

/kind support

**Comment by JohnNiang** [comment]
另外，还有一种情况就是：依赖“应用市场插件”的插件比它更先启动，会抛出以上异常并尝试重新启动，直到“应用市场插件“启动成功。

后期可以考虑忽略这个依赖异常，直接重试即可。

/remove-kind support
/kind improvement
/area plugin
/area core
/assign
