### ISSUE TITLE
文章发布失败，请重试

### ISSUE THREAD

**Issue by Jackiexiao** [halo-dev/halo#5834]
### 系统信息

- 外部访问地址: http://localhost:8080
- 启动时间: 2024-04-27 15:55
- 版本: 2.14.1
- 构建时间: 2024-04-23 14:57
- Git Commit: ea3b5a9
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 16.2
- 操作系统: Linux / 5.15.0-86-generic
- 已激活主题: [Theme Fluid](https://github.com/chengzhongxue/halo-theme-fluid)
- 已启动插件:
  - [Willow Markdown 编辑器](https://github.com/guqing/willow-mde)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)

### 使用的哪种方式运行？

Docker

### 发生了什么？

<img width="828" alt="9dbdeae65e2fe955ae7453a599b25a6" src="https://github.com/halo-dev/halo/assets/18050469/1287888c-8d8b-446b-8b28-11bee55b7729">

### 相关日志输出

```shell
PUT https://jackiexiao.com/apis/api.console.halo.run/v1alpha1/singlepages/373a5f79-f44f-441a-9df1-85a4f553ece8/content 403 (Forbidden)
(anonymous) @ vendor-8da49f84.js:11
xhr @ vendor-8da49f84.js:11
Zg @ vendor-8da49f84.js:13
_request @ vendor-8da49f84.js:14
request @ vendor-8da49f84.js:13
(anonymous) @ vendor-8da49f84.js:9
(anonymous) @ index-ed0d244a.js:35
(anonymous) @ index-ed0d244a.js:35
Promise.then (async)
updateSinglePageContent @ index-ed0d244a.js:35
b @ index-ed0d244a.js:39
await in b (async)
y @ index-ed0d244a.js:39
jt @ vue.global.a9e86e7d.js:6
Ht @ vue.global.a9e86e7d.js:6
un @ vue.global.a9e86e7d.js:6
l @ halo-components.iife.a9e86e7d.js:1
jt @ vue.global.a9e86e7d.js:6
Ht @ vue.global.a9e86e7d.js:6
n @ vue.global.a9e86e7d.js:8
index-ed0d244a.js:39 Failed to publish single page Ve {message: 'Request failed with status code 403', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_REQUEST"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}adapter: (2) ['xhr', 'http']baseURL: ""data: "{\"raw\":\"<p style=\\\"\\\"></p><p style=\\\"\\\">/p>\",\"content\":\"<p style=\\\"\\\"></p><p style=\\\"\\\"></p>\",\"rawType\":\"HTML\",\"snapshotName\":\"2b71e76f-2014-4efe-9c20-68eeeb27ec8d\"}"env: {FormData: ƒ, Blob: ƒ}headers: ls {Accept: 'application/json, text/plain, */*', Content-Type: 'application/json', X-Requested-With: 'XMLHttpRequest', X-XSRF-TOKEN: '106cc77c-25f0-478a-8874-8ee989933fa1'}maxBodyLength: -1maxContentLength: -1method: "put"timeout: 0transformRequest: [ƒ]transformResponse: [ƒ]transitional: {silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}url: "/apis/api.console.halo.run/v1alpha1/singlepages/373a5f79-f44f-441a-9df1-85a4f553ece8/content"validateStatus: ƒ (e)withCredentials: truexsrfCookieName: "XSRF-TOKEN"xsrfHeaderName: "X-XSRF-TOKEN"[[Prototype]]: Objectmessage: "Request failed with status code 403"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}onabort: ƒ ()length: 0name: ""prototype: {}arguments: (...)caller: (...)[[FunctionLocation]]: vendor-8da49f84.js:11[[Prototype]]: ƒ ()[[Scopes]]: Scopes[4]onerror: ƒ ()onload: nullonloadend: ƒ y()onloadstart: nullonprogress: nullonreadystatechange: nullontimeout: ƒ ()readyState: 4response: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<metresponseText: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<metresponseType: ""responseURL: "https://jackiexiao.com/apis/api.console.halo.run/v1alpha1/singlepages/373a5f79-f44f-441a-9df1-85a4f553ece8/content"responseXML: nullstatus: 403statusText: ""timeout: 0upload: XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}withCredentials: true[[Prototype]]: XMLHttpRequestresponse: config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}data: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<metheaders: ls {content-encoding: 'gzip', content-type: 'text/html; charset=UTF-8', date: 'Mon, 29 Apr 2024 17:04:50 GMT', server: 'openresty', vary: 'Accept-Encoding'}request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}status: 403statusText: ""[[Prototype]]: Objectstack: "AxiosError: Request failed with status code 403\n    at $1 (https://jackiexiao.com/console/assets/vendor-8da49f84.js:11:1046)\n    at XMLHttpRequest.y (https://jackiexiao.com/console/assets/vendor-8da49f84.js:11:4238)\n    at xr.request (https://jackiexiao.com/console/assets/vendor-8da49f84.js:13:3118)\n    at async b (https://jackiexiao.com/console/assets/index-ed0d244a.js:39:48525)"[[Prototype]]: Error
```

**Comment by ruibaby** [comment]
先检查是否是防火墙导致的。
