### ISSUE TITLE
windows环境下dockercompose安装，报错

### ISSUE THREAD

**Issue by TrisAXJ** [halo-dev/halo#5853]
### System information

mariodb 11.3
Windows docker
使用mysql的模板
host网络 连接外部数据库
```yaml
version: "3"

services:
  halo:
    image: halohub/halo:2.15
    restart: on-failure:3
    network_mode: "host"
    volumes:
      - ./halo2:/root/.halo2
    command:
      # 修改为自己已有的 MySQL 配置
      - --spring.r2dbc.url=r2dbc:pool:mysql://localhost:3306/halo
      - --spring.r2dbc.username=root
      - --spring.r2dbc.password=****
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://***:8091/
      # 端口号 默认8090
      - --server.port=8091
```

### What is the project operation method?

Docker Compose

### What happened?

无法启动
看了其他的iss 试了localhost、127.0.0.1都无法连接，中间有个拒绝连接不知怎么处理，端口3306打开的
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: **finishConnect(..) failed: Connection refused: localhost/127.0.0.1:3306**
2024-05-03 15:55:23 Caused by: java.net.ConnectException: finishConnect(..) **failed: Connection refused**

### Relevant log output

```shell
24-05-03 15:55:06     __  __      __
2024-05-03 15:55:06    / / / /___ _/ /___
2024-05-03 15:55:06   / /_/ / __ `/ / __ \
2024-05-03 15:55:06  / __  / /_/ / / /_/ /
2024-05-03 15:55:06 /_/ /_/\__,_/_/\____/
2024-05-03 15:55:06 
2024-05-03 15:55:06 Version: 2.15.0
2024-05-03 15:55:07 2024-05-03T15:55:07.268+08:00  INFO 7 --- [           main] run.halo.app.Application                 : Starting Application v2.15.0 using Java 21.0.2 with PID 7 (/application/BOOT-INF/classes started by root in /application)
2024-05-03 15:55:07 2024-05-03T15:55:07.281+08:00  INFO 7 --- [           main] run.halo.app.Application                 : No active profile set, falling back to 1 default profile: "default"
2024-05-03 15:55:07 2024-05-03T15:55:07.480+08:00  WARN 7 --- [           main] o.s.c.a.AnnotationBeanNameGenerator      : Support for convention-based stereotype names is deprecated and will be removed in a future version of the framework. Please annotate the 'value' attribute in @run.halo.app.theme.finders.Finder with @AliasFor(annotation=Component.class) to declare an explicit alias for @Component's 'value' attribute.
2024-05-03 15:55:08 2024-05-03T15:55:08.413+08:00  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2024-05-03 15:55:08 2024-05-03T15:55:08.415+08:00  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data R2DBC repositories in DEFAULT mode.
2024-05-03 15:55:08 2024-05-03T15:55:08.537+08:00  INFO 7 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 113 ms. Found 1 R2DBC repository interface.
2024-05-03 15:55:20 2024-05-03T15:55:20.596+08:00  INFO 7 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Enabled plugins: []
2024-05-03 15:55:20 2024-05-03T15:55:20.597+08:00  INFO 7 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Disabled plugins: []
2024-05-03 15:55:20 2024-05-03T15:55:20.600+08:00  INFO 7 --- [           main] org.pf4j.DefaultPluginManager            : PF4J version 3.10.0 in 'deployment' mode
2024-05-03 15:55:20 2024-05-03T15:55:20.966+08:00  INFO 7 --- [           main] o.a.l.s.MemorySegmentIndexInputProvider  : Using MemorySegmentIndexInput with Java 21; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
2024-05-03 15:55:23 2024-05-03T15:55:23.203+08:00  INFO 7 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 34 endpoints beneath base path '/actuator'
2024-05-03 15:55:23 2024-05-03T15:55:23.833+08:00  WARN 7 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/R2dbcInitializationConfiguration.class]: Failed to execute database script
2024-05-03 15:55:23 2024-05-03T15:55:23.842+08:00  INFO 7 --- [           main] r.h.a.e.c.DefaultControllerManager       : Shutting down 0 controllers...
2024-05-03 15:55:23 2024-05-03T15:55:23.843+08:00  INFO 7 --- [           main] r.h.a.e.c.DefaultControllerManager       : Shutdown 0 controllers.
2024-05-03 15:55:23 2024-05-03T15:55:23.845+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Disposing controller garbage-collector-controller
2024-05-03 15:55:23 2024-05-03T15:55:23.845+08:00  INFO 7 --- [           main] r.h.a.e.controller.DefaultController     : Controller garbage-collector-controller is disposed
2024-05-03 15:55:23 2024-05-03T15:55:23.918+08:00  INFO 7 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
2024-05-03 15:55:23 
2024-05-03 15:55:23 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-05-03 15:55:23 2024-05-03T15:55:23.947+08:00 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
2024-05-03 15:55:23 
2024-05-03 15:55:23 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'r2dbcScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/R2dbcInitializationConfiguration.class]: Failed to execute database script
2024-05-03 15:55:23     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23     at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23     at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:149) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23     at run.halo.app.Application.main(Application.java:28) ~[classes/:2.15.0]
2024-05-03 15:55:23     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
2024-05-03 15:55:23     at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2024-05-03 15:55:23     at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[application/:na]
2024-05-03 15:55:23     at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[application/:na]
2024-05-03 15:55:23     at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[application/:na]
2024-05-03 15:55:23 Caused by: org.springframework.r2dbc.connection.init.UncategorizedScriptException: Failed to execute database script
2024-05-03 15:55:23     at org.springframework.r2dbc.connection.init.DatabasePopulator.lambda$populate$4(DatabasePopulator.java:65) ~[spring-r2dbc-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3840) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3930) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.MonoUsingWhen$ResourceSubscriber.onError(MonoUsingWhen.java:203) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxRetry$RetrySubscriber.onError(FluxRetry.java:96) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.pool.AbstractPool$Borrower.fail(AbstractPool.java:488) ~[reactor-pool-1.0.5.jar:1.0.5]
2024-05-03 15:55:23     at reactor.pool.SimpleDequePool.lambda$drainLoop$9(SimpleDequePool.java:436) ~[reactor-pool-1.0.5.jar:1.0.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onError(FluxDoOnEach.java:186) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onError(MonoSubscribeOn.java:152) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:205) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.netty.resources.NewConnectionProvider$DisposableConnect.onError(NewConnectionProvider.java:156) ~[reactor-netty-core-1.1.18.jar:1.1.18]
2024-05-03 15:55:23     at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.netty.transport.TransportConnector$MonoChannelPromise.tryFailure(TransportConnector.java:576) ~[reactor-netty-core-1.1.18.jar:1.1.18]
2024-05-03 15:55:23     at reactor.netty.transport.TransportConnector$MonoChannelPromise.setFailure(TransportConnector.java:522) ~[reactor-netty-core-1.1.18.jar:1.1.18]
2024-05-03 15:55:23     at reactor.netty.transport.TransportConnector.lambda$doConnect$7(TransportConnector.java:261) ~[reactor-netty-core-1.1.18.jar:1.1.18]
2024-05-03 15:55:23     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:679) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:698) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:491) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2024-05-03 15:55:23     Suppressed: java.lang.Exception: #block terminated with an error
2024-05-03 15:55:23             at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23             at reactor.core.publisher.Mono.block(Mono.java:1779) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23             at org.springframework.boot.r2dbc.init.R2dbcScriptDatabaseInitializer.runScripts(R2dbcScriptDatabaseInitializer.java:68) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.runScripts(AbstractScriptDatabaseInitializer.java:146) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyScripts(AbstractScriptDatabaseInitializer.java:108) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applySchemaScripts(AbstractScriptDatabaseInitializer.java:98) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:76) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.afterPropertiesSet(AbstractScriptDatabaseInitializer.java:66) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.6.jar:6.1.6]
2024-05-03 15:55:23             at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:149) ~[spring-boot-3.3.0-RC1.jar:3.3.0-RC1]
2024-05-03 15:55:23             at run.halo.app.Application.main(Application.java:28) ~[classes/:2.15.0]
2024-05-03 15:55:23             at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
2024-05-03 15:55:23             at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
2024-05-03 15:55:23             at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[application/:na]
2024-05-03 15:55:23             at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[application/:na]
2024-05-03 15:55:23             at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[application/:na]
2024-05-03 15:55:23 Caused by: org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection
2024-05-03 15:55:23     at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:100) ~[spring-r2dbc-6.1.6.jar:6.1.6]
2024-05-03 15:55:23     at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3854) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.6.5.jar:3.6.5]
2024-05-03 15:55:23     ... 38 common frames omitted
2024-05-03 15:55:23 Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:3306
2024-05-03 15:55:23 Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
2024-05-03 15:55:23     at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166) ~[netty-transport-native-unix-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131) ~[netty-transport-native-unix-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[netty-transport-native-unix-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:715) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:692) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:491) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[netty-transport-classes-epoll-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.109.Final.jar:4.1.109.Final]
2024-05-03 15:55:23     at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by TrisAXJ** [comment]
mariodb root用户可以访问%，127.0.0.1，localhost，认证方式是native

**Comment by TrisAXJ** [comment]
改用mysql 使用sha2也同样报错

**Comment by TrisAXJ** [comment]
大概知道了，应该是window下docker无法使用host模式，这个坑，晕

**Comment by TrisAXJ** [comment]
经过摸索，能够部署

使用Windows 环境 docker desktop，若要使用外部数据库，需要使用mysql中sha2认证插件（mysql是默认，目前mariadb11.3不支持），**手动创建数据库halo**，如果库里没有也会报错，默认容器网络，**不能使用host（windocker不支持）**，映射端口出来，yaml中数据库地址去ipconfig里面看wsl的ip地址填入。可以成功部署

下面是我改动的compose文件，可以作为参考

`
version: "3"

services:
  halo:
    image: halohub/halo:2.15
    restart: on-failure:3
    #network_mode: "host"
    ports:
     - 8090:8090
    volumes:
      - ./halo2:/root/.halo2
    command:
      # 修改为自己已有的 MySQL 配置
      - --spring.r2dbc.url=r2dbc:pool:mysql://填本机网络中查看到的wsl的ip地址:3306/halo
      - --spring.r2dbc.username=root
      - --spring.r2dbc.password=****
      - --spring.sql.init.platform=mysql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://localhost:8090/
      # 端口号 默认8090
      #- --server.port=8090
`

**Comment by ly740612781** [comment]
@lvoxv 谢谢大哥，帮了大忙了。本地一直报你这个错误，翻了半天帖子终于找到解决办法了！！！ 赞赞赞
