### ISSUE TITLE
更新2.16.0版本，注册页输入框都不显示，控制台报错

### ISSUE THREAD

**Issue by XF-Store** [halo-dev/halo#6034]
### 系统信息

vue.global.b44a5c75.js:7 TypeError: Cannot read properties of undefined (reading 'name')
    at setup (index-YiepBVGM.js:41:129284)
    at jt (vue.global.b44a5c75.js:7:16029)
    at vue.global.b44a5c75.js:9:21100
    at vue.global.b44a5c75.js:9:21256
    at M (vue.global.b44a5c75.js:9:21279)
    at F (vue.global.b44a5c75.js:9:19641)
    at v (vue.global.b44a5c75.js:9:16781)
    at A (vue.global.b44a5c75.js:9:18041)
    at k (vue.global.b44a5c75.js:9:17390)
    at C (vue.global.b44a5c75.js:9:17216)

### 使用的哪种方式运行？

Docker

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/67722408/186d0846-3dfb-49da-bf4f-52f076a6c318)
注册页面无内容，控制台报错

**Comment by XF-Store** [comment]
我已经回滚到2.15.2了，新版本还需要测试呀

**Comment by JohnNiang** [comment]
Hi @XF-Store ，以下有两个建议：
1. 浏览器使用无痕模式访问测试是否可显示内容
2. 如果在使用 CDN，建议清理一下缓存后重试

从截图中看到 js 的 hash 和 Halo 2.16.0 的不太一致，我的是 `vue.global.4a4d0212.js`。

**Comment by XF-Store** [comment]
已解决，确实是浏览器缓存问题，感谢解答

**Comment by liuhuongtao** [comment]
清理浏览器缓存和cdn缓存都没有解决问题，用ip+端口访问也没有主页输入框

**Comment by JohnNiang** [comment]
Hi @liuhuongtao ，如果你正在是用面板工具，建议检查一下是否配置了反向代理缓存。

**Comment by godcreator02** [comment]
我也是咋搞都没有注册框
