### ISSUE TITLE
Halov2.16.3 默认编辑器输入次级标题就会导致界面无响应

### ISSUE THREAD

**Issue by Kizai** [halo-dev/halo#6095]
### 系统信息

- 外部访问地址: http://localhost:528/
- 启动时间: 2024-06-15 13:17
- 版本: 2.16.3
- 构建时间: 2024-06-14 12:48
- Git Commit: 6e1f0f3
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 4.4.180+
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [编辑器超链接卡片 1.0.2](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [站点推送插件 1.5.1](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [站点迁移 1.5.0](https://github.com/halo-sigs/plugin-migrate)
  - [StackEdit 1.1.1](https://github.com/halo-sigs/plugin-stackedit)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [瞬间 1.6.2](https://github.com/halo-sigs/plugin-moments)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [highlight.js 代码高亮 1.2.1](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱 1.2.0](https://github.com/halo-sigs/plugin-lightgallery)
  - [Vditor 编辑器 1.7.0](https://github.com/justice2001/halo-plugin-vditor)
  - [Media Optimizer 1.1.0](https://github.com/guqing/plugin-cloudinary)
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.2.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

![image](https://github.com/halo-dev/halo/assets/41446543/4e70c756-467f-47a3-bd89-ca568a76d52f)
![image](https://github.com/halo-dev/halo/assets/41446543/e84808bb-13c2-4310-b3d4-0cc6de6e3fbd)

### 相关日志输出

```shell
at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.6.6.jar:3.6.6]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[reactor-core-3.6.6.jar:3.6.6]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[reactor-core-3.6.6.jar:3.6.6]
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:294) ~[reactor-netty-core-1.1.19.jar:1.1.19]
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:403) ~[reactor-netty-core-1.1.19.jar:1.1.19]
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:426) ~[reactor-netty-core-1.1.19.jar:1.1.19]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.19.jar:1.1.19]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[netty-transport-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[netty-transport-classes-epoll-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[netty-transport-classes-epoll-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[netty-transport-classes-epoll-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.110.Final.jar:4.1.110.Final]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### 附加信息

[halo-log-2024-06-18 16_48.log](https://github.com/user-attachments/files/15883110/halo-log-2024-06-18.16_48.log)

**Comment by LIlGG** [comment]
我本地及线上均没有复现此问题，可能需要提供一下复现步骤，例如文章内容及数量。

另外日志中表示 Media Optimizer 这个插件的 cloud_name 值不存在，可以停用此插件之后再进行尝试。

/area editor
/triage not-reproducible

**Comment by Kizai** [comment]
好的，我先试下，感谢🙏

**Comment by Kizai** [comment]
我把插件停掉了，再重新新建文章进行测试，请看GIF，可以看到我在点击次级标题的时候整个网页就卡住不动了，然后就无响应最后奔溃。
![recording](https://github.com/halo-dev/halo/assets/41446543/ffbf7021-cdae-4b75-867f-4f3ad181c1b0)

同时我还发现，我之前使用默认编辑器编辑的文章全部都打不开了，一打开也是卡死，但使用第三方编辑器的又可以正常打开，我现在写文章也只能用第三方去写，十分难受😣。
![recording](https://github.com/halo-dev/halo/assets/41446543/6da06365-70a8-44e3-bbf4-396ed654e7c7)

**Comment by ruibaby** [comment]
建议使用浏览器隐私模式或者换一个浏览器试试，某些浏览器插件也会影响网页的表现。

**Comment by Kizai** [comment]
使用隐私模式后打开，确实都正常了，看来是我浏览器插件的问题，万分感谢啦。
