### ISSUE TITLE
docker 启动失败

### ISSUE THREAD

**Issue by graveskeeper** [halo-dev/halo#6099]
### System information

1.4.17

### What is the project operation method?

Docker

### What happened?

halo容器执行了 docker restart  

### Relevant log output

```shell
2024-06-18 19:26:09.576  INFO 7 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2024-06-18 19:26:09.577  INFO 7 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3633 ms
2024-06-18 19:26:09.959  INFO 7 --- [           main] run.halo.app.config.HaloConfiguration    : Halo cache store load impl : [class run.halo.app.cache.LevelCacheStore]
2024-06-18 19:26:10.427  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2024-06-18 19:26:11.583 ERROR 7 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

org.h2.jdbc.JdbcSQLException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.message.DbException.get(DbException.java:168) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:196) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.engine.Database.getPageStore(Database.java:2538) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.engine.Database.open(Database.java:709) ~[h2-1.4.197.jar:1.4.197]
```

**Comment by JohnNiang** [comment]
Hi @graveskeeper, thank you for reaching out here!

需要注意的是，Halo 1.x 我们已经停止维护，建议利用备份迁移至 Halo 2.x。

另外，提交 Issue 之前建议先在 Issue 中搜索，例如：<https://github.com/halo-dev/halo/issues?q=is%3Aissue+sort%3Aupdated-desc+%22File+corrupted+while+reading+record%22+is%3Aclosed>。

/triage duplicate
/close
