### ISSUE TITLE
RiVerifiedBadgeLine  not found   

### ISSUE THREAD

**Issue by etongle** [halo-dev/halo#6102]
### 系统信息

- 外部访问地址: 
- 启动时间: 2024-06-19 23:22
- 版本: 2.17.0-SNAPSHOT
- 构建时间: 2024-06-19 23:22
- Git Commit: b445b50
- Java: OpenJDK Runtime Environment / 17.0.11+9-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Mac OS X / 13.5.2
- 已激活主题: [Earth 1.7.1](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [Sitemap 1.1.1](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.4.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.2.2](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.1.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.1.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Source Code

### 发生了什么？

/ui/console-src/modules/system/users/tabs/Detail.vue
/ui/uc-src/modules/profile/tabs/TwoFactor.vue
根据文档clone 源码，发现以上两处源码中有 引入 RiVerifiedBadgeLine（import RiVerifiedBadgeLine from "~icons/ri/verified-badge-line";）
源码运行的时候提示 ： Icon ri/verified-badge-line not found 
http://localhost:8090/console 无法进入。 请修复！

### 相关日志输出

```shell
ERROR  11:32:01 PM [vite] Internal server error: Icon ri/verified-badge-line not found                                                                                                                           23:32:01
      at generateComponent (file:///Users/null/workspace_cms/halo_null/ui/node_modules/.pnpm/unplugin-icons@0.14.15_@vue+compiler-sfc@3.4.29_vue-template-compiler@2.7.16/node_modules/unplugin-icons/dist/chunk-YZHHVA2M.mjs:304:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async LoadPluginContext.load (file:///Users/null/workspace_cms/halo_null/ui/node_modules/.pnpm/unplugin-icons@0.14.15_@vue+compiler-sfc@3.4.29_vue-template-compiler@2.7.16/node_modules/unplugin-icons/dist/chunk-YZHHVA2M.mjs:359:20)
      at async file:///Users/null/workspace_cms/halo_null/ui/node_modules/.pnpm/vite-plugin-inspect@0.8.4_rollup@4.18.0_vite@5.3.1_@types+node@18.19.36_less@4.2.0_sass@1.77.6_terser@5.31.1_/node_modules/vite-plugin-inspect/dist/index.mjs:407:17
      at async PluginContainer.load (file:///Users/null/workspace_cms/halo_null/ui/node_modules/.pnpm/vite@5.3.1_@types+node@18.19.36_less@4.2.0_sass@1.77.6_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49511:22)
      at async loadAndTransform (file:///Users/null/workspace_cms/halo_null/ui/node_modules/.pnpm/vite@5.3.1_@types+node@18.19.36_less@4.2.0_sass@1.77.6_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:52306:22)
      at async viteTransformMiddleware (file:///Users/null/workspace_cms/halo_null/ui/node_modules/.pnpm/vite@5.3.1_@types+node@18.19.36_less@4.2.0_sass@1.77.6_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62102:24) (x2)
```

### 附加信息

![WechatIMG3422](https://github.com/halo-dev/halo/assets/1782337/0b7a532c-ae7b-4e8a-82c8-fcd147678ee9)

**Comment by ruibaby** [comment]
相关问题：https://bbs.halo.run/d/5668-%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E8%AE%BF%E9%97%AEconsole%E5%87%BA%E7%8E%B0vite%E9%94%99%E8%AF%AF

/triage duplicate
