### ISSUE TITLE
升级到2.17后大量报错

### ISSUE THREAD

**Issue by Omoinemie** [halo-dev/halo#6273]
### 系统信息

java -jar halo.jar

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

下面是相关错误日志

### 相关日志输出

```shell
2024-07-05T13:59:22.409+08:00 ERROR 1244 --- [oundedElastic-1] o.t.spring6.SpringWebFluxTemplateEngine  : [THYMELEAF][boundedElastic-1] Exception processing template "index": Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "modules/layouts/layout" - line 13, col 1)

2024-07-05T13:59:22.435+08:00 ERROR 1244 --- [oundedElastic-1] a.w.r.e.AbstractErrorWebExceptionHandler : [baf2633c-1]  500 Server Error for HTTP GET "/"

org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "modules/layouts/layout" - line 13, col 1)
        at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:141) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
    
2024-07-05T13:59:22.492+08:00 ERROR 1244 --- [oundedElastic-1] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-1] Exception processing template "error/500": Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "modules/layouts/layout" - line 13, col 1)

org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "modules/layouts/layout" - line 13, col 1)
        at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:141) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]

2024-07-05T13:59:22.495+08:00 ERROR 1244 --- [oundedElastic-1] o.t.spring6.SpringWebFluxTemplateEngine  : [THYMELEAF][boundedElastic-1] Exception processing template "error/500": Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "modules/layouts/layout" - line 13, col 1)

org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "modules/layouts/layout" - line 13, col 1)
        at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:141) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
        at org.thymeleaf.util.ProcessorConfigurationUtils$ElementModelProcessorWrapper.process(ProcessorConfigurationUtils.java:649) ~[thymeleaf-3.1.2.RELEASE.jar!/:3.1.2.RELEASE]
```

**Comment by ruibaby** [comment]
建议提供完整的日志文件。

/triage needs-information

**Comment by zhajianjun** [comment]
[halo (1).log](https://github.com/user-attachments/files/16107436/halo.1.log)

**Comment by zhajianjun** [comment]
> 建议提供完整的日志文件。
> 
> /triage needs-information

[halo (1).log](https://github.com/user-attachments/files/16107436/halo.1.log)
只要访问主站地址，就会报这个错误，相关错误请看附件

**Comment by ruibaby** [comment]
从日志看，应该是一个叫 Pangu 的插件不兼容，因为 Halo 2.17 移除了过时的 API。

```release-note
	at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:108) ~[reactor-core-3.6.7.jar:3.6.7]
	at reactor.core.publisher.Mono.blockOptional(Mono.java:1831) ~[reactor-core-3.6.7.jar:3.6.7]
	at run.halo.app.plugin.DefaultSettingFetcher.fetch(DefaultSettingFetcher.java:27) ~[classes/:2.17.0]
	at run.halo.starter.PanGuHeadProcessor.process(PanGuHeadProcessor.java:31) ~[na:na]
	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.lambda$doProcess$0(GlobalHeadInjectionProcessor.java:74) ~[classes/:2.17.0]
```

**Comment by zhajianjun** [comment]
别人也有可能使用其它插件，因为使用过时的api导致这样的问题了

**Comment by zhajianjun** [comment]
> 从日志看，应该是一个叫 Pangu 的插件不兼容，因为 Halo 2.17 移除了过时的 API。
> 
> ```
> 	at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:108) ~[reactor-core-3.6.7.jar:3.6.7]
> 	at reactor.core.publisher.Mono.blockOptional(Mono.java:1831) ~[reactor-core-3.6.7.jar:3.6.7]
> 	at run.halo.app.plugin.DefaultSettingFetcher.fetch(DefaultSettingFetcher.java:27) ~[classes/:2.17.0]
> 	at run.halo.starter.PanGuHeadProcessor.process(PanGuHeadProcessor.java:31) ~[na:na]
> 	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.lambda$doProcess$0(GlobalHeadInjectionProcessor.java:74) ~[classes/:2.17.0]
> ```

别人也有可能使用其它插件，因为使用过时的api导致这样的问题了

**Comment by ruibaby** [comment]
> > 从日志看，应该是一个叫 Pangu 的插件不兼容，因为 Halo 2.17 移除了过时的 API。
> > ```
> > 	at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:108) ~[reactor-core-3.6.7.jar:3.6.7]
> > 	at reactor.core.publisher.Mono.blockOptional(Mono.java:1831) ~[reactor-core-3.6.7.jar:3.6.7]
> > 	at run.halo.app.plugin.DefaultSettingFetcher.fetch(DefaultSettingFetcher.java:27) ~[classes/:2.17.0]
> > 	at run.halo.starter.PanGuHeadProcessor.process(PanGuHeadProcessor.java:31) ~[na:na]
> > 	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.lambda$doProcess$0(GlobalHeadInjectionProcessor.java:74) ~[classes/:2.17.0]
> > ```
> 
> 别人也有可能使用其它插件，因为使用过时的api导致这样的问题了

这已经是非常旧的 API 了，也已经在很久之前标记了过时，移除之后我们也在发布日志做出了提示。这个问题目前只能让插件去修改。

**Comment by Omoinemie** [comment]
> > > 从日志看，应该是一个叫 Pangu 的插件不兼容，因为 Halo 2.17 移除了过时的 API。
> > > ```
> > > 	at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:108) ~[reactor-core-3.6.7.jar:3.6.7]
> > > 	at reactor.core.publisher.Mono.blockOptional(Mono.java:1831) ~[reactor-core-3.6.7.jar:3.6.7]
> > > 	at run.halo.app.plugin.DefaultSettingFetcher.fetch(DefaultSettingFetcher.java:27) ~[classes/:2.17.0]
> > > 	at run.halo.starter.PanGuHeadProcessor.process(PanGuHeadProcessor.java:31) ~[na:na]
> > > 	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.lambda$doProcess$0(GlobalHeadInjectionProcessor.java:74) ~[classes/:2.17.0]
> > > ```
> > 
> > 
> > 别人也有可能使用其它插件，因为使用过时的api导致这样的问题了
> 
> 这已经是非常旧的 API 了，也已经在很久之前标记了过时，移除之后我们也在发布日志做出了提示。这个问题目前只能让插件去修改。

有没有什么安全模式，就是禁用所有插件后启动，可以更新或者禁用插件，现在连后台都进不去，没法管理插件

**Comment by ruibaby** [comment]
> 有没有什么安全模式，就是禁用所有插件后启动，可以更新或者禁用插件，现在连后台都进不去，没法管理插件

https://github.com/halo-dev/halo/issues/6273#issuecomment-2210265048

**Comment by kecikeci** [comment]
> > > > 从日志看，应该是一个叫 Pangu 的插件不兼容，因为 Halo 2.17 移除了过时的 API。
> > > > ```
> > > > 	at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:108) ~[reactor-core-3.6.7.jar:3.6.7]
> > > > 	at reactor.core.publisher.Mono.blockOptional(Mono.java:1831) ~[reactor-core-3.6.7.jar:3.6.7]
> > > > 	at run.halo.app.plugin.DefaultSettingFetcher.fetch(DefaultSettingFetcher.java:27) ~[classes/:2.17.0]
> > > > 	at run.halo.starter.PanGuHeadProcessor.process(PanGuHeadProcessor.java:31) ~[na:na]
> > > > 	at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.lambda$doProcess$0(GlobalHeadInjectionProcessor.java:74) ~[classes/:2.17.0]
> > > > ```
> > > 
> > > 
> > > 别人也有可能使用其它插件，因为使用过时的api导致这样的问题了
> > 
> > 
> > 这已经是非常旧的 API 了，也已经在很久之前标记了过时，移除之后我们也在发布日志做出了提示。这个问题目前只能让插件去修改。
> 
> 有没有什么安全模式，就是禁用所有插件后启动，可以更新或者禁用插件，现在连后台都进不去，没法管理插件

直接去文件夹里删了对应的插件，重启就能进了，之前也遇到过

**Comment by zhangbaiquan** [comment]
我也是访问主站报这个异常，但是没有找到Pangu这个插件

**Comment by UPToZ-Core** [comment]
[halo.log](https://github.com/user-attachments/files/16138471/halo.log)
我这个错误是什么引起的，在使用网站测速的时候，会报出大量的这种错误。

**Comment by ruibaby** [comment]
> [halo.log](https://github.com/user-attachments/files/16138471/halo.log) 我这个错误是什么引起的，在使用网站测速的时候，会报出大量的这种错误。

https://github.com/halo-dev/halo/issues/4468
