### ISSUE TITLE
恢复重启失败

### ISSUE THREAD

**Issue by yangshifei** [halo-dev/halo#6443]
### 系统信息

- 外部访问地址: https://www.yangsf.top
- 启动时间: 2024-08-05 16:21
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 15.4 (Debian 15.4-2.pgdg120+1)
- 操作系统: Linux / 3.10.0-1160.el7.x86_64
- 已激活主题: [Butterfly 2.0.5](https://github.com/dhjddcn/halo-theme-butterfly.git)
- 已启动插件:
  - [Vditor 编辑器 1.7.1](https://github.com/justice2001/halo-plugin-vditor)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

恢复重启报错

### 相关日志输出

```shell
halo-1    | 2024-08-06T17:00:52.587+08:00 ERROR 6 --- [    restartMain] run.halo.app.actuator.RestartEndpoint    : Failed to restart.
halo-1    |
halo-1    | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'luceneSearchEngine' defined in class path resource [run/halo/app/config/HaloConfiguration.class]: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=5dwap95plonp9cu0a9m8erzzs, got=5c7joop4zy1eflcwflxtprpq4 (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
halo-1    |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.3.1.jar:3.3.1]
halo-1    |     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.1.jar:3.3.1]
halo-1    |     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.1.jar:3.3.1]
halo-1    |     at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.1.jar:3.3.1]
halo-1    |     at run.halo.app.actuator.RestartEndpoint.doRestart(RestartEndpoint.java:48) ~[classes/:2.18.0]
halo-1    |     at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo-1    | Caused by: java.lang.RuntimeException: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=5dwap95plonp9cu0a9m8erzzs, got=5c7joop4zy1eflcwflxtprpq4 (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
halo-1    |     at run.halo.app.search.lucene.LuceneSearchEngine.afterPropertiesSet(LuceneSearchEngine.java:249) ~[classes/:2.18.0]
halo-1    |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1835) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[spring-beans-6.1.10.jar:6.1.10]
halo-1    |     ... 15 common frames omitted
halo-1    | Caused by: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=5dwap95plonp9cu0a9m8erzzs, got=5c7joop4zy1eflcwflxtprpq4 (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
halo-1    |     at org.apache.lucene.codecs.CodecUtil.checkIndexHeaderID(CodecUtil.java:371) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |     at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:255) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |     at org.apache.lucene.codecs.lucene99.Lucene99SegmentInfoFormat.read(Lucene99SegmentInfoFormat.java:98) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |     at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:411) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |     at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:368) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |     at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:304) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |     at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:293) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |     at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1088) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |     at run.halo.app.search.lucene.LuceneSearchEngine.afterPropertiesSet(LuceneSearchEngine.java:245) ~[classes/:2.18.0]
halo-1    |     ... 17 common frames omitted
halo-1    |     Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (ae510). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
halo-1    |             at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |             at org.apache.lucene.codecs.lucene99.Lucene99SegmentInfoFormat.read(Lucene99SegmentInfoFormat.java:104) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |             ... 23 common frames omitted
halo-1    |     Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (42757b45). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/segments_1")))
halo-1    |             at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |             at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:375) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
halo-1    |             ... 21 common frames omitted
halo-1    |
```

**Comment by JohnNiang** [comment]
建议删除 `~/.halo2/indices` 后重启即可。

**Comment by JohnNiang** [comment]
/close

If the issue persists, feel free to reopen it.

**Comment by JohnNiang** [comment]
/reopen

为解决该问题，我们可以尝试优化以下几点：

1. 备份时忽略索引目录 `indices/**`
2. 恢复时同样忽略索引目录 `indices/**`
