### ISSUE TITLE
Alist 附件存储策略文章上传失败

### ISSUE THREAD

**Issue by huajiba** [halo-dev/halo#6455]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-08-09 16:47
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: PostgreSQL / 15.7
- 操作系统: Linux / 5.15.0-107-generic
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [AList 存储库 1.0.1](https://github.com/halo-sigs/plugin-alist)
  - [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [朋友圈 1.3.3](https://github.com/chengzhongxue/plugin-friends)
  - [图床插件 1.1.0](https://github.com/liuyiwuqing/halo-plugin-picture-bed)
  - [Vditor 编辑器 1.7.1](https://github.com/justice2001/halo-plugin-vditor)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.1](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

使用alist插件添加存储策略后，选择附件存储策略后，编辑文章时用编辑器粘贴图片上传失败。

### 复现步骤

1.添加alist存储策略
![image](https://github.com/user-attachments/assets/5301c97c-e4c4-4130-b1b6-7301eb7f0a78)
2.设置文章附件存储策略
![image](https://github.com/user-attachments/assets/570ba09e-cb67-448e-ad8c-a714a92adbd0)
3.编辑文章复制图片进去报错
![image](https://github.com/user-attachments/assets/d3ec28f6-35b9-421f-9571-94db78597d63)

### 相关日志输出

```shell
halo-1    | 2024-08-09T17:46:10.194+08:00  INFO 7 --- [or-http-epoll-4] r.h.a.endpoint.AListAttachmentHandler    : [AList Info] :  Upload file file successfully
halo-1    | 2024-08-09T17:46:10.198+08:00 ERROR 7 --- [or-http-epoll-4] a.w.r.e.AbstractErrorWebExceptionHandler : [142b7208-1846]  500 Server Error for HTTP POST "/apis/uc.api.content.halo.run/v1alpha1/attachments?waitForPermalink=true"
halo-1    |
halo-1    | java.lang.ClassCastException: org.springframework.http.codec.multipart.DefaultParts$DefaultFilePart incompatible with run.halo.app.core.extension.attachment.endpoint.SimpleFilePart
halo-1    |     at run.halo.alist.endpoint.AListAttachmentHandler.lambda$upload$5(AListAttachmentHandler.java:125) ~[na:na]
halo-1    |     Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
halo-1    | Error has been observed at the following site(s):
halo-1    |     *__checkpoint ⇢ Handler run.halo.app.endpoint.uc.content.UcPostAttachmentEndpoint$$Lambda/0x000000008ee13840@eb7dc3df [DispatcherHandler]
halo-1    |     *__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ run.halo.app.security.device.DeviceSessionFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ TotpAuthenticationFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ run.halo.comment.widget.captcha.CommentCaptchaFilter [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ run.halo.app.webfilter.AdditionalWebFilterChainProxy [DefaultWebFilterChain]
halo-1    |     *__checkpoint ⇢ HTTP POST "/apis/uc.api.content.halo.run/v1alpha1/attachments?waitForPermalink=true" [ExceptionHandlingWebHandler]
halo-1    | Original Stack Trace:
halo-1    |             at run.halo.alist.endpoint.AListAttachmentHandler.lambda$upload$5(AListAttachmentHandler.java:125) ~[na:na]
halo-1    |             at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.6.7.jar:3.6.7]
halo-1    |             at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415) ~[reactor-netty-core-1.1.20.jar:1.1.20]
halo-1    |             at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:446) ~[reactor-netty-core-1.1.20.jar:1.1.20]
halo-1    |             at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:500) ~[reactor-netty-core-1.1.20.jar:1.1.20]
halo-1    |             at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:793) ~[reactor-netty-http-1.1.20.jar:1.1.20]
halo-1    |             at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.20.jar:1.1.20]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[netty-handler-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1473) ~[netty-handler-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1336) ~[netty-handler-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1385) ~[netty-handler-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530) ~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469) ~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[netty-transport-classes-epoll-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[netty-transport-classes-epoll-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[netty-transport-classes-epoll-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.111.Final.jar:4.1.111.Final]
halo-1    |             at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo-1    |
```

**Comment by JohnNiang** [comment]
Hi @huajiba , thank you for reaching out here!

该问题应该属于 [Alist 插件](https://github.com/halo-sigs/plugin-alist)，我将关闭当前 Issue，并在 https://github.com/halo-sigs/plugin-alist/issues/8 中回复。

/close
/triage duplicate
