### ISSUE TITLE
当插件实现 TemplateHeadProcessor 中出现异常时，页面无法显示

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#6479]
### 系统信息

- 外部访问地址: http://localhost:8090
- 启动时间: 2024-08-19 10:31
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 6.9.8-orbstack-00170-g7b4100b7ced4
- 已激活主题: [Sakura 2.4.0](https://github.com/LIlGG/halo-theme-sakura.git)
- 已启动插件:
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.2.0](https://www.halo.run/store/apps/app-VYJbF)
  - [MaxKB 小助手 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-aWHcE)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

当插件中实现了 `TemplateHeadProcessor` 这个扩展点，并且在这个扩展点中抛出任意的运行时异常后，会导致主题端页面无法展示并出现各种错误。

期望当插件中抛出运行时异常时，不会导致主题端页面无法展示。或者说在部分情况下，该异常对于主题端是静默的。

/kind bug
/area core

### 相关日志输出

```shell
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/error/error.html]")
        at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:666) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf
.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.7.jar:3.6.7]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(
Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.attoparser.ParseException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "error/error" - line 3, col 1)
        at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.MarkupParser.parse(MarkupParser.java:257) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        ... 15 common frames omitted
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "error/error" - line 3, col 1)
        at org.thymeleaf.processor.element.AbstractElementModelPro
cessor.process(AbstractElementModelProcessor.java:141) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.util.ProcessorConfigurationUtils$ElementModelProcessorWrapper.process(ProcessorConfigurationUtils.java:649) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1510) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELE
ASE]
        at org.thymeleaf.engine.TemplateHandlerAdapterMarkupHandler.handleCloseElementEnd(TemplateHandlerAdapterMarkupHandler.java:388) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterPreProcessorHandler.handleCloseElementEnd(InlinedOutputExpressionMarkupHandler.java:322) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.standard.inline.OutputExpressionInlinePreProcessorHandler.handleCloseElementEnd(OutputExpressionInlinePreProcessorHandler.java:220) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler.handleCloseElementEnd(InlinedOutputExpressionMarkupHandler.java:164) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.attoparser.HtmlElement.handleCloseElementEnd(HtmlElement.java:169) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.HtmlMarkupHandler.handleCloseElementEnd(HtmlMarkupHandler.java:412) ~[attoparser-2.0.7.RE
LEASE.jar:2.0.7.RELEASE]
        at org.attoparser.MarkupEventProcessorHandler.handleCloseElementEnd(MarkupEventProcessorHandler.java:473) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.ParsingElementMarkupUtil.parseCloseElement(ParsingElementMarkupUtil.java:201) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:725) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        ... 17 common frames omitted
Caused by: org.springframework.web.server.ServerWebInputException: 400 BAD_REQUEST "MaxKB 基础配置不正确。"
        at run.halo.maxkb.MaxKBConfigGetterImpl.lambda$getAvailableWebClient$15(MaxKBConfigGetterImpl.java:200) ~[na:na]
        at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
        at run.halo.maxkb.MaxKBConfigGetterImpl.getAvailableWebClient(MaxKBConfigGetterImpl.java:200) ~[na:na]
        at run.halo.maxkb.MaxKBClientImpl.getApp
licationAccessToken(MaxKBClientImpl.java:78) ~[na:na]
        at run.halo.maxkb.MaxKBEmbedHeadProcessor.getEmbedScript(MaxKBEmbedHeadProcessor.java:49) ~[na:na]
        at run.halo.maxkb.MaxKBEmbedHeadProcessor.process(MaxKBEmbedHeadProcessor.java:34) ~[na:na]
        at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.lambda$doProcess$0(GlobalHeadInjectionProcessor.java:74) ~[classes/:2.18.0]
        at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:183) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:453) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:724) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:256) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseab
leSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:209) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:79) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.Mono.block(Mono.java:1778) ~[reactor-core-3.6.7.jar:3.6.7]
        at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.doProcess(GlobalHeadInjectionProcessor.java:76) ~[classes/:2.18.0]
        at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:98) ~[th
ymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        ... 34 common frames omitted
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104) ~[reactor-core-3.6.7.jar:3.6.7]
                at reactor.core.publisher.Mono.block(Mono.java:1779) ~[reactor-core-3.6.7.jar:3.6.7]
                ... 36 common frames omitted
2024-08-19T10:49:13.790+08:00 ERROR 7 --- [undedElastic-10] o.t.spring6.SpringWebFluxTemplateEngine  : [THYMELEAF][boundedElastic-10] Exception processing template "error/error": An error happened during template parsing (template: "class path resource [templates/error/error.html]")

org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/error/error.html]")
        at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:666) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf
.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.7.jar:3.6.7]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(
Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.attoparser.ParseException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "error/error" - line 3, col 1)
        at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.MarkupParser.parse(MarkupParser.java:257) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        ... 15 common frames omitted
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'run.halo.app.theme.dialect.GlobalHeadInjectionProcessor' (template: "error/error" - line 3, col 1)
        at org.thymeleaf.processor.element.AbstractElementModelPro
cessor.process(AbstractElementModelProcessor.java:141) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.util.ProcessorConfigurationUtils$ElementModelProcessorWrapper.process(ProcessorConfigurationUtils.java:649) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1510) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELE
ASE]
        at org.thymeleaf.engine.TemplateHandlerAdapterMarkupHandler.handleCloseElementEnd(TemplateHandlerAdapterMarkupHandler.java:388) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterPreProcessorHandler.handleCloseElementEnd(InlinedOutputExpressionMarkupHandler.java:322) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.standard.inline.OutputExpressionInlinePreProcessorHandler.handleCloseElementEnd(OutputExpressionInlinePreProcessorHandler.java:220) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler.handleCloseElementEnd(InlinedOutputExpressionMarkupHandler.java:164) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        at org.attoparser.HtmlElement.handleCloseElementEnd(HtmlElement.java:169) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.HtmlMarkupHandler.handleCloseElementEnd(HtmlMarkupHandler.java:412) ~[attoparser-2.0.7.RE
LEASE.jar:2.0.7.RELEASE]
        at org.attoparser.MarkupEventProcessorHandler.handleCloseElementEnd(MarkupEventProcessorHandler.java:473) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.ParsingElementMarkupUtil.parseCloseElement(ParsingElementMarkupUtil.java:201) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:725) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301) ~[attoparser-2.0.7.RELEASE.jar:2.0.7.RELEASE]
        ... 17 common frames omitted
Caused by: org.springframework.web.server.ServerWebInputException: 400 BAD_REQUEST "MaxKB 基础配置不正确。"
        at run.halo.maxkb.MaxKBConfigGetterImpl.lambda$getAvailableWebClient$15(MaxKBConfigGetterImpl.java:200) ~[na:na]
        at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
        at run.halo.maxkb.MaxKBConfigGetterImpl.getAvailableWebClient(MaxKBConfigGetterImpl.java:200) ~[na:na]
        at run.halo.maxkb.MaxKBClientImpl.getApp
licationAccessToken(MaxKBClientImpl.java:78) ~[na:na]
        at run.halo.maxkb.MaxKBEmbedHeadProcessor.getEmbedScript(MaxKBEmbedHeadProcessor.java:49) ~[na:na]
        at run.halo.maxkb.MaxKBEmbedHeadProcessor.process(MaxKBEmbedHeadProcessor.java:34) ~[na:na]
        at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.lambda$doProcess$0(GlobalHeadInjectionProcessor.java:74) ~[classes/:2.18.0]
        at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onNext(FluxConcatMapNoPrefetch.java:183) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:453) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:724) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:256) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseab
leSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:209) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:79) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.Mono.
subscribe(Mono.java:4568) ~[reactor-core-3.6.7.jar:3.6.7]
        at reactor.core.publisher.Mono.block(Mono.java:1778) ~[reactor-core-3.6.7.jar:3.6.7]
        at run.halo.app.theme.dialect.GlobalHeadInjectionProcessor.doProcess(GlobalHeadInjectionProcessor.java:76) ~[classes/:2.18.0]
        at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:98) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        ... 34 common frames omitted
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104) ~[reactor-core-3.6.7.jar:3.6.7]
                at reactor.core.publisher.Mono.block(Mono.java:1779) ~[reactor-core-3.6.7.jar:3.6.7]
                ... 36 common frames omitted
```

**Comment by guqing** [comment]
如果异常时不需要阻断其他扩展的执行那么应该是扩展点的实现者自己通过 .onErrorResume 处理

**Comment by LIlGG** [comment]
> 如果异常时不需要阻断其他扩展的执行那么应该是扩展点的实现者自己通过 .onErrorResume 处理，一旦在全局统一忽略了异常那么如果扩展想要终止后续执行将无法实现

出现这个问题的原因是，理论上如果插件抛出异常，主题页面应该显示 error.html。但在实际运行中，error.html 也同样具有这个异常，进而导致请求整个页面时，显示的不是 error.html 页面而是一个响应 400 或 500 的页面。

另外我在实现了此扩展的位置使用 `onErrorResume`，即便 `onErrorResume` 执行了，这个页面仍旧会抛出异常，进而导致整个页面报错，我的初衷是目标插件是有可能抛出异常但不影响整个页面渲染的。

**Comment by guqing** [comment]
> > 如果异常时不需要阻断其他扩展的执行那么应该是扩展点的实现者自己通过 .onErrorResume 处理，一旦在全局统一忽略了异常那么如果扩展想要终止后续执行将无法实现
> 
> 出现这个问题的原因是，理论上如果插件抛出异常，主题页面应该显示 error.html。但在实际运行中，error.html 也同样具有这个异常，进而导致请求整个页面时，显示的不是 error.html 页面而是一个响应 400 或 500 的页面。
> 
> 另外我在实现了此扩展的位置使用 `onErrorResume`，即便 `onErrorResume` 执行了，这个页面仍旧会抛出异常，进而导致整个页面报错，我的初衷是目标插件是有可能抛出异常但不影响整个页面渲染的。

建议在试一下 onErrorResume 返回 Mono.emtpy

**Comment by guqing** [comment]
> > > 如果异常时不需要阻断其他扩展的执行那么应该是扩展点的实现者自己通过 .onErrorResume 处理，一旦在全局统一忽略了异常那么如果扩展想要终止后续执行将无法实现
> > 
> > 
> > 出现这个问题的原因是，理论上如果插件抛出异常，主题页面应该显示 error.html。但在实际运行中，error.html 也同样具有这个异常，进而导致请求整个页面时，显示的不是 error.html 页面而是一个响应 400 或 500 的页面。
> > 另外我在实现了此扩展的位置使用 `onErrorResume`，即便 `onErrorResume` 执行了，这个页面仍旧会抛出异常，进而导致整个页面报错，我的初衷是目标插件是有可能抛出异常但不影响整个页面渲染的。
> 
> 建议在试一下 onErrorResume 返回 Mono.emtpy

经排查看到你的代码是在方法中调用 webClient.get() 抛出的异常并没有被 Mono 或者 Flux 接管因此 onErrorResume 无法捕捉到，只能通过 try-catch，可以通过 Mono.fromSupplier 之类的包裹，因此我将关闭此 issue

**Comment by JohnNiang** [comment]
我猜测 @LIlGG 想要实现的效果是，插件报错能够让用户第一时间在页面上知晓并立即采取行动，而不是需要通过查看日志的方式才能知晓到底发生了什么以及如何补救。

**Comment by LIlGG** [comment]
> 我猜测 @LIlGG 想要实现的效果是，插件报错能够让用户第一时间在页面上知晓并立即采取行动，而不是需要通过查看日志的方式才能知晓到底发生了什么以及如何补救。

实际上如我上面所说 

> 出现这个问题的原因是，理论上如果插件抛出异常，主题页面应该显示 error.html。但在实际运行中，error.html 也同样具有这个异常，进而导致请求整个页面时，显示的不是 error.html 页面而是一个响应 400 或 500 的页面。

可能是此 issue 未表达清楚。期望在插件出现未知错误之后，不要影响到 error.html。即代码注入不要注入至 error.html 中。我会新启用一个页面以解决这个问题。
