### ISSUE TITLE
Halo 2.8 备份恢复时重启失败，代码报错

### ISSUE THREAD

**Issue by 569258yin** [halo-dev/halo#6558]
### 系统信息

- 外部访问地址: https://blog.xy0716.life
- 启动时间: 2024-08-27 19:33
- 版本: 2.18.0
- 构建时间: 2024-08-01 10:17
- Git Commit: 58fe872
- Java: IBM Semeru Runtime Open Edition / 21.0.3+9-LTS
- 数据库: MySQL Community Server (GPL) / 5.7.28
- 操作系统: Linux / 3.10.0-1160.11.1.el7.x86_64
- 已激活主题: [Hao 1.5.2](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [highlight.js 代码高亮 1.2.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [豆瓣 1.2.1](https://github.com/chengzhongxue/plugin-douban)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [通知我 1.1.0](https://github.com/monyuan/notify-me)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [对象存储（Amazon S3 协议） 1.11.0](https://github.com/halo-dev/plugin-s3)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.4.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

> 对现有博客进行备份，迁移到另一个服务器进行同等部署，docker-compose.yaml文件一致，创建了新的数据库，点击恢复，重启后服务启动失败,控制台报错

### 复现步骤

1. 在另一个数据库使用2.8镜像部署halo
2. 在原有博客点击备份
3. 在新博客点击恢复

### 相关日志输出

```shell
2024-08-31T11:46:59.269+08:00  INFO 6 --- [    restartMain] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-08-31T11:46:59.315+08:00 ERROR 6 --- [    restartMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'luceneSearchEngine' defined in class path resource [run/halo/app/config/HaloConfiguration.class]: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=2gu84g5liekqowx4d983gmu1v, got=4abbhqthv0nox322ktrn5a65q (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.10.jar:6.1.10]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.10.jar:6.1.10]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.1.jar:3.3.1]
	at run.halo.app.actuator.RestartEndpoint.doRestart(RestartEndpoint.java:48) ~[classes/:2.18.0]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.RuntimeException: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=2gu84g5liekqowx4d983gmu1v, got=4abbhqthv0nox322ktrn5a65q (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
	at run.halo.app.search.lucene.LuceneSearchEngine.afterPropertiesSet(LuceneSearchEngine.java:249) ~[classes/:2.18.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1835) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[spring-beans-6.1.10.jar:6.1.10]
	... 15 common frames omitted
Caused by: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=2gu84g5liekqowx4d983gmu1v, got=4abbhqthv0nox322ktrn5a65q (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
	at org.apache.lucene.codecs.CodecUtil.checkIndexHeaderID(CodecUtil.java:371) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:255) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.codecs.lucene99.Lucene99SegmentInfoFormat.read(Lucene99SegmentInfoFormat.java:98) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:411) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:368) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:304) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:293) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1088) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at run.halo.app.search.lucene.LuceneSearchEngine.afterPropertiesSet(LuceneSearchEngine.java:245) ~[classes/:2.18.0]
	... 17 common frames omitted
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (ec1c7421). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
		at org.apache.lucene.codecs.lucene99.Lucene99SegmentInfoFormat.read(Lucene99SegmentInfoFormat.java:104) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
		... 23 common frames omitted
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (8113b5ee). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/segments_2")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
		at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:375) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
		... 21 common frames omitted

2024-08-31T11:46:59.324+08:00 ERROR 6 --- [    restartMain] run.halo.app.actuator.RestartEndpoint    : Failed to restart.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'luceneSearchEngine' defined in class path resource [run/halo/app/config/HaloConfiguration.class]: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=2gu84g5liekqowx4d983gmu1v, got=4abbhqthv0nox322ktrn5a65q (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.10.jar:6.1.10]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.10.jar:6.1.10]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.1.jar:3.3.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.1.jar:3.3.1]
	at run.halo.app.actuator.RestartEndpoint.doRestart(RestartEndpoint.java:48) ~[classes/:2.18.0]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.RuntimeException: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=2gu84g5liekqowx4d983gmu1v, got=4abbhqthv0nox322ktrn5a65q (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
	at run.halo.app.search.lucene.LuceneSearchEngine.afterPropertiesSet(LuceneSearchEngine.java:249) ~[classes/:2.18.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1835) ~[spring-beans-6.1.10.jar:6.1.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[spring-beans-6.1.10.jar:6.1.10]
	... 15 common frames omitted
Caused by: org.apache.lucene.index.CorruptIndexException: file mismatch, expected id=2gu84g5liekqowx4d983gmu1v, got=4abbhqthv0nox322ktrn5a65q (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
	at org.apache.lucene.codecs.CodecUtil.checkIndexHeaderID(CodecUtil.java:371) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:255) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.codecs.lucene99.Lucene99SegmentInfoFormat.read(Lucene99SegmentInfoFormat.java:98) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:411) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:368) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:304) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:293) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1088) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
	at run.halo.app.search.lucene.LuceneSearchEngine.afterPropertiesSet(LuceneSearchEngine.java:245) ~[classes/:2.18.0]
	... 17 common frames omitted
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (ec1c7421). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/_1.si")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
		at org.apache.lucene.codecs.lucene99.Lucene99SegmentInfoFormat.read(Lucene99SegmentInfoFormat.java:104) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
		... 23 common frames omitted
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (8113b5ee). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(MemorySegmentIndexInput(path="/root/.halo2/indices/halo/segments_2")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
		at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:375) ~[lucene-core-9.11.1.jar:9.11.1 0c087dfdd10e0f6f3f6faecc6af4415e671a9e69 - 2024-06-23 12:31:02]
		... 21 common frames omitted
```

**Comment by ruibaby** [comment]
/triage duplicate

See https://github.com/halo-dev/halo/issues/6443#issuecomment-2270825319

**Comment by JohnNiang** [comment]
/close

See https://github.com/halo-dev/halo/issues/6443#issuecomment-2327915658 for more.
