### ISSUE TITLE
手动压缩主题包后可能无法正常解压

### ISSUE THREAD

**Issue by xiaowei-vip** [halo-dev/halo#6620]
### 系统信息

- 外部访问地址: http://localhost:8090/
- 启动时间: 2024-09-07 08:29
- 版本: 2.19.2
- 构建时间: 2024-09-06 22:17
- Git Commit: 7f68de3
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: H2 / 2.2.224
- 操作系统: Linux / 5.15.153.1-microsoft-standard-WSL2
- 已激活主题: [1 1.0.0](https://52he.cc)
- 已启动插件:
  - [链接管理 1.4.0](https://github.com/halo-sigs/plugin-links)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [瞬间 1.7.0](https://github.com/halo-sigs/plugin-moments)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.5.0](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.3.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

使用docker在本地部署主题，使用Visual Studio Code开发，开发后压缩了这几个文件。与之前别人打包给我的压缩一样，上传时候报错400，具体放到下边日志，已经确认了yaml格式化后没有问题，貌似是压缩的问题？在议题中找到相似案例还是没有得以解决，如果要是压缩的问题的话该怎么解决？第一次做halo的开发。
![图片](https://github.com/user-attachments/assets/73f6a1f5-0224-4e1c-aa4b-6268251f2dd8)

### 相关日志输出

```shell
2024-09-07 12:49:04 2024-09-07T12:49:04.354+08:00 ERROR 7 --- [undedElastic-32] r.h.app.core.extension.theme.ThemeUtils  : Failed to unzip theme
2024-09-07 12:49:04 
2024-09-07 12:49:04 java.lang.IllegalArgumentException: malformed input off : 45, length : 1
2024-09-07 12:49:04     at java.base/java.lang.String.throwMalformed(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.lang.String.decodeUTF8_UTF16(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.lang.String.newStringUTF8NoRepl(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.lang.Access.newStringUTF8NoRepl(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.toString(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.util.zip.ZipCoder.toString(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.util.zip.ZipInputStream.readLOC(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.util.zip.ZipInputStream.getNextEntry(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at run.halo.app.infra.utils.FileUtils.unzip(FileUtils.java:100) ~[classes/:na]
2024-09-07 12:49:04     at run.halo.app.infra.utils.FileUtils.lambda$unzip$0(FileUtils.java:57) ~[classes/:na]
2024-09-07 12:49:04     at reactor.core.publisher.MonoUsingWhen.deriveMonoFromResource(MonoUsingWhen.java:114) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.MonoUsingWhen.access$000(MonoUsingWhen.java:46) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.MonoUsingWhen$ResourceSubscriber.onNext(MonoUsingWhen.java:181) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:176) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at run.halo.app.infra.utils.DataBufferUtils.lambda$toInputStream$1(DataBufferUtils.java:37) ~[classes/:na]
2024-09-07 12:49:04     at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.Mono.subscribe(Mono.java:4576) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.MonoUsingWhen.subscribe(MonoUsingWhen.java:97) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.Mono.subscribe(Mono.java:4576) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.Mono.subscribe(Mono.java:4576) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.9.jar:3.6.9]
2024-09-07 12:49:04     at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
2024-09-07 12:49:04     at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2024-09-07 12:49:04 Caused by: java.nio.charset.MalformedInputException: Input length = 1
2024-09-07 12:49:04     ... 30 common frames omitted
2024-09-07 12:49:04
```

**Comment by JohnNiang** [comment]
Hi @xiaowei-vip, thank you for reaching out here!

确实发现手动打的 ZIP 包会存在问题。目前建议使用命令的方式打包。

近期我将排查一下发生错误的原因。如果你能够提供一下压缩之后的主题包，我这边就更容易复现，问题会更快得到解决。

/kind bug
/area core
/assign

**Comment by xiaowei-vip** [comment]
> 你好@xiaowei-vip，感谢您与我们联系！
> 
> 我发现手动打的ZIP包上传后确实会存在问题。目前建议使用命令的方式压缩。
> 
> 最近我将列出一下发生错误的原因。如果您能够提供一下压缩之后的主题包，我的注意力就更容易恢复，问题会更快得到解决。
> 
> /kind bug /area core /assign

hello，这个问题已经解决了，解决方式如下：卸载当前的压缩软件，使用bandzip，
![1726014151550](https://github.com/user-attachments/assets/128417ba-1056-4fcf-b478-3fec9ee526db)
在设置项中打开：在 Zip 文件中使用 Unicode 文件名(UTF-8)，得以解决！

**Comment by JohnNiang** [comment]
Hi @xiaowei-vip , 感谢更进一步的反馈。

从[源码](https://github.com/halo-dev/halo/blob/39545a1e4c1fdce312fb47b82969eea3b5c6493c/application/src/main/java/run/halo/app/infra/utils/FileUtils.java#L56)发现，解压时默认使用的 `UTF-8` 字符集解析文件名。

> Creates a new ZIP input stream.
The UTF-8 charset is used to decode the entry names.

/close
/retitle 手动压缩主题包后可能无法正常解压
/remove-kind bug
/remove-area core
/kind support

**Comment by xiaowei-vip** [comment]
@JohnNiang 
感谢帮助，确实排查到最后发现是压缩的问题，当然，也在本机尝试使用命令行的方式压缩，以失败告终，可能方法不对，但是现在得以解决！再次感谢！
