### ISSUE TITLE
附件库删除图片资源时，一直显示删除中，无法删除资源

### ISSUE THREAD

**Issue by Joneeys** [halo-dev/halo#6683]
### 系统信息

- 外部访问地址: https://blog.iooioio.com
- 启动时间: 2024-09-20 17:20
- 版本: 2.19.3
- 构建时间: 2024-09-10 17:46
- Git Commit: b6ec7b9
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 6.1.0-10-amd64
- 已激活主题: [Hao 1.4.8](https://githubfast.com/liuzhihang/halo-theme-hao)
- 已启动插件:
  - [链上好文 1.0.1](https://github.com/guqing/plugin-share-post-via-link)
  - [AList 存储库 1.1.0](https://github.com/halo-sigs/plugin-alist)
  - [无色界 1.0.0](https://github.com/guqing/halo-plugin-colorless)
  - [页面静态缓存 1.2.0](https://github.com/halo-sigs/plugin-page-cache)
  - [Data Studio（数据工厂） 1.0.0-alpha.2](https://github.com/halo-sigs/plugin-data-studio)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [静态网页服务 1.0.0-alpha.5](https://www.halo.run/store/apps/app-gFkMn)
  - [爱发电插件 1.6.3](https://github.com/carolcoral/plugin-afdian)
  - [Webhook 1.0.0](https://www.wxy97.com/)
  - [豆瓣 1.2.1](https://github.com/chengzhongxue/plugin-douban)
  - [朋友圈 1.3.5](https://github.com/chengzhongxue/plugin-friends-new)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [文本绘图 1.3.0](https://github.com/halo-sigs/plugin-text-diagram)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [我的装备管理 1.2.0](https://github.com/halo-sigs/plugin-equipments)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [Docsme 1.0.0-alpha.8](https://www.halo.run/store/apps/app-yffxw)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [Metrics Graph 1.0.0](https://github.com/guqing/plugin-metrics-graph)
  - [AI 助手 1.0.0](https://www.halo.run/store/apps/app-riNgb)
  - [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
  - [Unsplash 1.2.1](https://github.com/halo-sigs/plugin-unsplash)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.4.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在删除附件库中的图片资源时，突然就出现无法删除图片，删除后一直显示“删除中...”，我重启服务器、删浏览器缓存，刷新，重建容器都无法解决。
![WX20240920-205708@2x](https://github.com/user-attachments/assets/8593fccb-97b1-464e-abb3-d041350911d5)

Uploading 116837_1726825716.mp4…

### 相关日志输出

```java
2024-09-20T21:20:00.925+08:00 ERROR 7 --- [run.halo.app.core.attachment.reconciler.AttachmentReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.attachment.reconciler.AttachmentReconciler-worker-1 aborted with an error, re-enqueuing...

reactor.core.Exceptions$ReactiveException: java.nio.file.FileSystemException: /root/.halo2/attachments/thumbnails/2024/w1600/leddianweiqi.png: Operation not permitted
	at reactor.core.Exceptions$ReactiveException.fillInStackTrace(Exceptions.java:736) ~[reactor-core-3.6.9.jar:3.6.9]
	at java.base/java.lang.Throwable.<init>(Unknown Source) ~[na:na]
	at java.base/java.lang.Throwable.<init>(Unknown Source) ~[na:na]
	at java.base/java.lang.Exception.<init>(Unknown Source) ~[na:na]
	at java.base/java.lang.RuntimeException.<init>(Unknown Source) ~[na:na]
	at reactor.core.Exceptions$ReactiveException.<init>(Exceptions.java:726) ~[reactor-core-3.6.9.jar:3.6.9]
	at reactor.core.Exceptions.propagate(Exceptions.java:410) ~[reactor-core-3.6.9.jar:3.6.9]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:144) ~[reactor-core-3.6.9.jar:3.6.9]
	at reactor.core.publisher.Mono.block(Mono.java:1807) ~[reactor-core-3.6.9.jar:3.6.9]
	at run.halo.app.core.attachment.reconciler.AttachmentReconciler.lambda$cleanUpResources$7(AttachmentReconciler.java:123) ~[classes/:2.19.3]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
	at run.halo.app.core.attachment.reconciler.AttachmentReconciler.cleanUpResources(AttachmentReconciler.java:123) ~[classes/:2.19.3]
	at run.halo.app.core.attachment.reconciler.AttachmentReconciler.lambda$reconcile$2(AttachmentReconciler.java:48) ~[classes/:2.19.3]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
	at run.halo.app.core.attachment.reconciler.AttachmentReconciler.reconcile(AttachmentReconciler.java:45) ~[classes/:2.19.3]
	at run.halo.app.core.attachment.reconciler.AttachmentReconciler.reconcile(AttachmentReconciler.java:32) ~[classes/:2.19.3]
	at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.19.3.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:146) ~[reactor-core-3.6.9.jar:3.6.9]
		... 14 common frames omitted
Caused by: java.nio.file.FileSystemException: /root/.halo2/attachments/thumbnails/2024/w1600/leddianweiqi.png: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source) ~[na:na]
	at java.base/java.nio.file.Files.deleteIfExists(Unknown Source) ~[na:na]
	at run.halo.app.core.attachment.impl.LocalThumbnailServiceImpl.lambda$deleteFile$14(LocalThumbnailServiceImpl.java:256) ~[classes/:2.19.3]
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73) ~[reactor-core-3.6.9.jar:3.6.9]
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32) ~[reactor-core-3.6.9.jar:3.6.9]
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228) ~[reactor-core-3.6.9.jar:3.6.9]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.6.9.jar:3.6.9]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.6.9.jar:3.6.9]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	... 3 common frames omitted
```

**Comment by guqing** [comment]
是否有对容器开启类似防篡改之类的功能呢，这个错误是删除文件时没有权限删除导致的

可以通过 
`docker exec -it <container_id> bash` 进入 halo 的容器内部，然后 `ll /root/.halo2/attachments/thumbnails/2024/w1600/leddianweiqi.png` 看一下该文件的权限，并且需要确保挂在的 volumes 具有 rw 的权限

/triage needs-information

**Comment by ruibaby** [comment]
没有后续动态，我将关闭此 issue。

/close
