### ISSUE TITLE
专业版前端404错误，后端正常

### ISSUE THREAD

**Issue by aspnmy** [halo-dev/halo#6732]
### 系统信息

- 外部访问地址: https://blog.t2be.cn/
- 启动时间: 2024-09-30 04:16
- 版本: 2.19.0
- 构建时间: 2024-09-02 11:10
- Git Commit: 6c9a7dd
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: PostgreSQL / 16.4 (Debian 16.4-1.pgdg120+1)
- 操作系统: Linux / 5.10.120
- 已激活主题: [Apex 企业官网主题 1.2.2](https://www.halo.run/store/apps/app-OTFHl)
- 已启动插件:
  - [应用市场 1.5.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

前端404，后端模板预览也是404，后端其他页面正常，

### 复现步骤

打开首页就能看到，登陆后端 打开主题预览就可以，镜像拉取 docker pull halohub/halo-pro:2.19.0

### 相关日志输出

```shell
at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:61) ~[reactor-core-3.6.9.jar:3.6.9]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4576) ~[reactor-core-3.6.9.jar:3.6.9]
		at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.6.9.jar:3.6.9]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.6.9.jar:3.6.9]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.6.9.jar:3.6.9]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		... 1 common frames omitted
```

### 附加信息

![企业微信截图_17276415873340](https://github.com/user-attachments/assets/6395c4e9-5d96-4091-846c-554a44db1632)
![企业微信截图_17276416567141](https://github.com/user-attachments/assets/dcbc0c0c-6411-4bdb-8f3b-e40fece268f4)

**Comment by aspnmy** [comment]
附上Docker Compose配置


services:
  halo:
    image: halohub/halo-pro:2.19.0
    restart: always
    volumes:
      - ./halo2:/root/.halo2
    network_mode: host
    command:
      
      - --spring.r2dbc.url=r2dbc:pool:postgresql://10.168.3.165:55432/halo2
      - --spring.r2dbc.username=
      - --spring.r2dbc.password=
      - --spring.sql.init.platform=postgresql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=https://blog.t2be.cn/            

      # 端口号 默认8090
      #- --server.port=8090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.168.3.165:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

**Comment by ruibaby** [comment]
相同问题：https://github.com/halo-dev/halo/issues/6619#issuecomment-2335343716

你去创建一个新的菜单并设置为主菜单即可。目前初始化的时候是会创建一个默认菜单的，尚不清楚为什么会没有菜单，我们无法复现这个问题。

/triage duplicate

**Comment by aspnmy** [comment]
3Q
