### ISSUE TITLE
邮件发送失败

### ISSUE THREAD

**Issue by Mcayear** [halo-dev/halo#6841]
### 系统信息

版本: [2.19.3](https://www.lxware.cn/docs/helpcenter/halo-pro/changlog)
构建时间: 2024-09-10 17:46
Git Commit: b6ec7b9
Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
数据库: PostgreSQL / 17.0
操作系统: Linux 5.15.0-30-generic / amd64
系统时区: Asia/Shanghai
系统语言: en_US

### 使用的哪种方式运行？

Docker

### 发生了什么？

在测试邮箱时弹出：
Failed to send email, please check your email configuration.

### 复现步骤

1. 建立一个 SMTPServer
2. 配置“邮件通知器”
![image patch1](https://github.com/user-attachments/assets/cd569f9e-d65a-4aa6-8770-c2685edb0531)
![image patch2](https://github.com/user-attachments/assets/88981720-c727-4161-8d37-12818dee98a6)

3. 尝试“测试邮箱”

### 相关日志输出

```shell
2K1Panel-halo-C5gd  | 2024-10-12T15:34:31.444+08:00 ERROR 7 --- [tor-tcp-epoll-4] r.h.a.n.e.EmailConfigValidationEndpoint  : Failed to send email, please check your email configuration.
2K1Panel-halo-C5gd  | 
2K1Panel-halo-C5gd  | org.springframework.mail.MailAuthenticationException: Authentication failed
2K1Panel-halo-C5gd  | 	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:402) ~[spring-context-support-6.1.12.jar:6.1.12]
2K1Panel-halo-C5gd  | 	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:350) ~[spring-context-support-6.1.12.jar:6.1.12]
2K1Panel-halo-C5gd  | 	at org.springframework.mail.javamail.JavaMailSender.send(JavaMailSender.java:158) ~[spring-context-support-6.1.12.jar:6.1.12]
2K1Panel-halo-C5gd  | 	at org.springframework.mail.javamail.JavaMailSender.send(JavaMailSender.java:132) ~[spring-context-support-6.1.12.jar:6.1.12]
2K1Panel-halo-C5gd  | 	at run.halo.app.notification.endpoint.EmailConfigValidationEndpoint.lambda$verifyEmailSenderConfig$1(EmailConfigValidationEndpoint.java:79) ~[classes/:2.19.3]
2K1Panel-halo-C5gd  | 	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.6.9.jar:3.6.9]
....too long
2K1Panel-halo-C5gd  | Caused by: jakarta.mail.AuthenticationFailedException: 538 Error: Must issue a STARTTLS command first
2K1Panel-halo-C5gd  | 
2K1Panel-halo-C5gd  | 	at org.eclipse.angus.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:954) ~[jakarta.mail-2.0.3.jar:na]
2K1Panel-halo-C5gd  | 	at org.eclipse.angus.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:865) ~[jakarta.mail-2.0.3.jar:na]
2K1Panel-halo-C5gd  | 	at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:769) ~[jakarta.mail-2.0.3.jar:na]
2K1Panel-halo-C5gd  | 	at jakarta.mail.Service.connect(Service.java:345) ~[jakarta.mail-2.0.3.jar:na]
2K1Panel-halo-C5gd  | 	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:480) ~[spring-context-support-6.1.12.jar:6.1.12]
2K1Panel-halo-C5gd  | 	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:399) ~[spring-context-support-6.1.12.jar:6.1.12]
2K1Panel-halo-C5gd  | 	... 122 common frames omitted
2K1Panel-halo-C5gd  |
```

### 附加信息

可能需要邮件通知器忽略 STARTTLS 发送，或者 tls rejectUnauthorized。

附 nodejs SMTPServer 代码
```js
const { SMTPServer } = require('smtp-server');
const axios = require('axios');
const simpleParser = require('mailparser').simpleParser;

// 创建一个本地SMTP服务器
const server = new SMTPServer({
  secure: false,             // 不使用加密
  authOptional: true,         // 允许没有认证
  onData(stream, session, callback) {
    let emailData = '';

    // 收集邮件数据
    stream.on('data', (chunk) => {
      emailData += chunk.toString();
    });

    // 完成邮件接收时调用
    stream.on('end', () => {
      console.log('邮件已接收，开始解析并转发到 Resend API');
      // 使用 mailparser 解析邮件
      simpleParser(emailData).then(parsed => {
        // 提取发件人、收件人、主题
        const from = parsed.from.text;
        const to = parsed.to.text;
        const subject = parsed.subject;
        const html = parsed.html || parsed.text;

        console.log(`从: ${from}, 到: ${to}, 主题: ${subject}`);

        resendEmail(from, to, subject, html).then(() => {
          callback(null); // 成功时
        }).catch((error) => {
          console.error('转发邮件失败:', error);
          callback(error); // 失败时
        });
      }).catch(err => {
        console.error('解析邮件失败:', err);
        callback(err);
      });
    });
  }
});

// 启动SMTP服务器
server.listen(5556, '0.0.0.0', () => {
  console.log('SMTP 服务器正在本地运行，监听端口 5556');
});

// 使用Resend API转发邮件
async function resendEmail(from, to, subject, html) {
  try {
    const response = await axios.post('https://api.resend.com/emails', {
      from: from,        // 来自SMTP接收的发件人
      to: to,            // 来自SMTP接收的收件人
      subject: subject,  // 来自SMTP接收的主题
      html: html,        // 邮件内容（HTML或text）
    }, {
      headers: {
        Authorization: `Bearer re_xxxxxxxxxxxxxxxxxxxxxxxx`, // 使用你的Resend API Key
        'Content-Type': 'application/json'
      }
    });

    console.log('邮件已成功通过 Resend API 发送:', response.data);
  } catch (error) {
    console.error('发送到 Resend API 失败:', error.response ? error.response.data : error.message);
    throw error;
  }
}
```

**Comment by Mcayear** [comment]
给本地服务器用上证书，然后halo邮件通知器使用 SSL

nodejs 代码参考：
https://gist.github.com/Mcayear/3cf031c02937cb4463f72c386298ef97

目录：
```tree
./ssl/privkey.pem
./ssl/fullchain.pem
./index.js
```
