### ISSUE TITLE
访问/about页面时发生500错误

### ISSUE THREAD

**Issue by 1078249029** [halo-dev/halo#6943]
### System information

- 外部访问地址: https://wumingzi.top/
- 启动时间: 
- 版本: 2.20.7
- 构建时间: 2024-10-23 20:59
- Git Commit: 17e9f2b
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.0.31
- 操作系统: Linux / 5.4.0-198-generic
- 已激活主题: [Next for Halo 2+ 1.0.0-beta.3](https://github.com/bit15k/halo-theme-next)
- 已启动插件:
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [应用市场 1.7.0](https://www.halo.run/store/apps/app-VYJbF)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.5.0](https://github.com/halo-dev/plugin-comment-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)

### What is the project operation method?

Docker

### What happened?

当我新建页面/about并尝试访问时会产生500错误，我按照论坛和之前issue的提示将其他插件停用后也会稳定触发bug。
下面是/about页面的配置
![Image](https://github.com/user-attachments/assets/2d32ab73-32f0-43dc-a9c4-ecb271145f66)

### Relevant log output

```java
2024-10-25T10:10:19.344+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_partials/head/head] Deprecated unwrapped fragment expression "_config/halo-config" found in template _partials/head/head, line 26, col 11. Please use the complete syntax of fragment expressions instead ("~{_config/halo-config}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:19.601+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_partials/head/head] Deprecated unwrapped fragment expression "_config/next-config.html" found in template _partials/head/head, line 37, col 11. Please use the complete syntax of fragment expressions instead ("~{_config/next-config.html}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:19.759+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_layout] Deprecated unwrapped fragment expression "_partials/head/head-unique" found in template _layout, line 11, col 19. Please use the complete syntax of fragment expressions instead ("~{_partials/head/head-unique}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:19.982+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_layout] Deprecated unwrapped fragment expression "_partials/header/index" found in template _layout, line 39, col 31. Please use the complete syntax of fragment expressions instead ("~{_partials/header/index}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:20.095+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_partials/header/index] Deprecated unwrapped fragment expression "_partials/header/menu" found in template _partials/header/index, line 5, col 11. Please use the complete syntax of fragment expressions instead ("~{_partials/header/menu}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:20.097+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_partials/header/menu] Deprecated unwrapped fragment expression "_partials/header/menu-item" found in template _partials/header/menu, line 7, col 27. Please use the complete syntax of fragment expressions instead ("~{_partials/header/menu-item}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:20.470+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_partials/header/index] Deprecated unwrapped fragment expression "_partials/search/index" found in template _partials/header/index, line 7, col 11. Please use the complete syntax of fragment expressions instead ("~{_partials/search/index}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:20.473+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_macro/sidebar] Deprecated unwrapped fragment expression "_partials/sidebar/site-overview.html" found in template _macro/sidebar, line 25, col 31. Please use the complete syntax of fragment expressions instead ("~{_partials/sidebar/site-overview.html}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:23.939+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][index] Deprecated unwrapped fragment expression "_partials/pagination::render(posts = ${posts},type = 'posts')" found in template index, line 9, col 19. Please use the complete syntax of fragment expressions instead ("~{_partials/pagination::render(posts = ${posts},type = 'posts')}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:24.045+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_layout] Deprecated unwrapped fragment expression "_partials/footer" found in template _layout, line 64, col 27. Please use the complete syntax of fragment expressions instead ("~{_partials/footer}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:24.047+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_layout] Deprecated unwrapped fragment expression "_partials/widgets" found in template _layout, line 75, col 19. Please use the complete syntax of fragment expressions instead ("~{_partials/widgets}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:10:24.049+08:00  WARN 7 --- [boundedElastic-47] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-47][_layout] Deprecated unwrapped fragment expression "_scripts/index" found in template _layout, line 76, col 19. Please use the complete syntax of fragment expressions instead ("~{_scripts/index}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:11:01.515+08:00 ERROR 7 --- [boundedElastic-47] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-47] Exception processing throttled template "page": Cannot resolve fragment. Signature "html (head,title,content,sidebar,class,is_home,is_archive,have_comment)" declares parameter "title", which is not specified at the fragment selection. (template: "page" - line 13, col 7)

org.thymeleaf.exceptions.TemplateProcessingException: Cannot resolve fragment. Signature "html (head,title,content,sidebar,class,is_home,is_archive,have_comment)" declares parameter "title", which is not specified at the fragment selection. (template: "page" - line 13, col 7)
	at org.thymeleaf.standard.expression.FragmentSignatureUtils.processParameters(FragmentSignatureUtils.java:219) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.doProcess(AbstractStandardFragmentInsertionTagProcessor.java:182) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:155) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ThrottledTemplateProcessor.process(ThrottledTemplateProcessor.java:235) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.ThrottledTemplateProcessor.process(ThrottledTemplateProcessor.java:200) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine$StreamThrottledTemplateProcessor.process(SpringWebFluxTemplateEngine.java:720) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createChunkedStream$2(SpringWebFluxTemplateEngine.java:269) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:271) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:213) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:85) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2024-10-25T10:11:02.872+08:00 ERROR 7 --- [parallel-1] a.w.r.e.AbstractErrorWebExceptionHandler : [bcc54b83-561]  500 Server Error for HTTP GET "/about"

org.thymeleaf.exceptions.TemplateProcessingException: Cannot resolve fragment. Signature "html (head,title,content,sidebar,class,is_home,is_archive,have_comment)" declares parameter "title", which is not specified at the fragment selection. (template: "page" - line 13, col 7)
	at org.thymeleaf.standard.expression.FragmentSignatureUtils.processParameters(FragmentSignatureUtils.java:219) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler run.halo.app.theme.router.SinglePageRoute$$Lambda/0x000000000c3418c8@9b743acb [DispatcherHandler]
	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.infra.webfilter.LocaleChangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.device.DeviceSessionFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ MapOAuth2AuthenticationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢  [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.comment.widget.captcha.CommentCaptchaFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.infra.webfilter.AdditionalWebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerWebExchangeContextFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/about" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.thymeleaf.standard.expression.FragmentSignatureUtils.processParameters(FragmentSignatureUtils.java:219) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.doProcess(AbstractStandardFragmentInsertionTagProcessor.java:182) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:155) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.ThrottledTemplateProcessor.process(ThrottledTemplateProcessor.java:235) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.engine.ThrottledTemplateProcessor.process(ThrottledTemplateProcessor.java:200) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.spring6.SpringWebFluxTemplateEngine$StreamThrottledTemplateProcessor.process(SpringWebFluxTemplateEngine.java:720) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createChunkedStream$2(SpringWebFluxTemplateEngine.java:269) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
		at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:271) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:213) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:85) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.7.0-M6.jar:3.7.0-M6]
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2024-10-25T10:13:54.881+08:00  WARN 7 --- [boundedElastic-49] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-49][_layout] Deprecated unwrapped fragment expression "_partials/head/head" found in template _layout, line 9, col 19. Please use the complete syntax of fragment expressions instead ("~{_partials/head/head}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:13:54.904+08:00  WARN 7 --- [boundedElastic-49] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-49][_partials/head/head] Deprecated unwrapped fragment expression "_config/halo-config" found in template _partials/head/head, line 26, col 11. Please use the complete syntax of fragment expressions instead ("~{_config/halo-config}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
2024-10-25T10:13:54.925+08:00  WARN 7 --- [boundedElastic-49] actStandardFragmentInsertionTagProcessor : [THYMELEAF][boundedElastic-49][_partials/head/head] Deprecated unwrapped fragment expression "_config/next-config.html" found in template _partials/head/head, line 37, col 11. Please use the complete syntax of fragment expressions instead ("~{_config/next-config.html}"). The old, unwrapped syntax for fragment expressions will be removed in future versions of Thymeleaf.
```

**Comment by JohnNiang** [comment]
关键日志如下所示：

```java
2024-10-25T10:11:01.515+08:00 ERROR 7 --- [boundedElastic-47] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-47] Exception processing throttled template "page": Cannot resolve fragment. Signature "html (head,title,content,sidebar,class,is_home,is_archive,have_comment)" declares parameter "title", which is not specified at the fragment selection. (template: "page" - line 13, col 7)
```

从日志中看，是主题的 page 模板存在问题，建议向对应的[主题](https://github.com/bit15k/halo-theme-next/blob/b84b6736a8a4dab4264ff6eda15f57995d1151cb/templates/page.html#L13)提交 Issue。

/triage unresolved
/close
