### ISSUE TITLE
配置阿里云OSS上传文件NullPointerException

### ISSUE THREAD

**Issue by MrChen00** [halo-dev/halo#700]
在附件设置中调整了附件上传位置为阿里云OSS服务，以下为配置信息
![image](https://user-images.githubusercontent.com/51355342/77226657-ffe98200-6bb4-11ea-9fd3-627f2271974b.png)
由于服务同样是部署在阿里云服务器，所以域名填写的是经典网络访问（内网）的Bucket域名
以下为OSS配置：
![image](https://user-images.githubusercontent.com/51355342/77226701-4f2fb280-6bb5-11ea-88be-5513fb8a794c.png)
以下为RAM用户配置：
![image](https://user-images.githubusercontent.com/51355342/77226729-75ede900-6bb5-11ea-863b-dccde985275c.png)
![image](https://user-images.githubusercontent.com/51355342/77226737-8bfba980-6bb5-11ea-97fe-4b4ad16b8344.png)
以下为具体错误信息：
![image](https://user-images.githubusercontent.com/51355342/77226745-a33a9700-6bb5-11ea-8f4a-3f95ef927882.png)

**Comment by MrChen00** [comment]
对了，域名配置外网地址也是会报错

**Comment by ruibaby** [comment]
这个日志不够详细，看不出问题。去 ~/.halo/logs/spring.log 看一下。

**Comment by MrChen00** [comment]
![image](https://user-images.githubusercontent.com/51355342/77228959-d7b64f00-6bc5-11ea-8421-e965f01ed8f5.png)
![image](https://user-images.githubusercontent.com/51355342/77228971-e866c500-6bc5-11ea-9d01-3e15af30f053.png)
这是一次错误的全部信息

**Comment by MrChen00** [comment]
是否是我域名或者OSS配置错误导致报错呢？

以下为错误信息文本：
java.lang.NullPointerException: null
        at com.aliyun.oss.OSSClient.isIpOrLocalhost(OSSClient.java:249) ~[aliyun-sdk-oss-3.4.2.jar!/:na]
        at com.aliyun.oss.OSSClient.setEndpoint(OSSClient.java:228) ~[aliyun-sdk-oss-3.4.2.jar!/:na]
        at com.aliyun.oss.OSSClient.<init>(OSSClient.java:206) ~[aliyun-sdk-oss-3.4.2.jar!/:na]
        at com.aliyun.oss.OSSClientBuilder.build(OSSClientBuilder.java:33) ~[aliyun-sdk-oss-3.4.2.jar!/:na]
        at run.halo.app.handler.file.AliOssFileHandler.upload(AliOssFileHandler.java:57) ~[classes!/:1.2.0]
        at run.halo.app.handler.file.FileHandlers.upload(FileHandlers.java:54) ~[classes!/:1.2.0]
        at run.halo.app.service.impl.AttachmentServiceImpl.upload(AttachmentServiceImpl.java:106) ~[classes!/:1.2.0]
        at run.halo.app.service.impl.AttachmentServiceImpl$$FastClassBySpringCGLIB$$2d9c80b9.invoke(<generated>) ~[classes!/:1.2.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at run.halo.app.service.impl.AttachmentServiceImpl$$EnhancerBySpringCGLIB$$27c7e0e4.upload(<generated>) ~[classes!/:1.2.0]
        at run.halo.app.controller.admin.api.AttachmentController.uploadAttachment(AttachmentController.java:76) ~[classes!/:1.2.0]
        at run.halo.app.controller.admin.api.AttachmentController$$FastClassBySpringCGLIB$$8f3ff968.invoke(<generated>) ~[classes!/:1.2.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at run.halo.app.core.ControllerLogAop.controller(ControllerLogAop.java:48) ~[classes!/:1.2.0]
        at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at run.halo.app.controller.admin.api.AttachmentController$$EnhancerBySpringCGLIB$$3b734270.uploadAttachment(<generated>) ~[classes!/:1.2.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_11]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_11]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:523) [jakarta.servlet-api-4.0.3.jar!/:4.0.3]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) [jakarta.servlet-api-4.0.3.jar!/:4.0.3]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at run.halo.app.security.filter.AdminAuthenticationFilter.doAuthenticate(AdminAuthenticationFilter.java:89) [classes!/:1.2.0]
        at run.halo.app.security.filter.AbstractAuthenticationFilter.doFilterInternal(AbstractAuthenticationFilter.java:167) [classes!/:1.2.0]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at run.halo.app.filter.CorsFilter.doFilter(CorsFilter.java:41) [classes!/:1.2.0]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108) [spring-boot-actuator-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]

**Comment by ruibaby** [comment]
这看起来是 ali oss sdk 的错误。要不你再本地跑一个 1.3.0-beta.3 试试？这个版本升级了 ali oss sdk 的版本。

目前还没出现过你这种错误，不太好判断。

**Comment by MrChen00** [comment]
![image](https://user-images.githubusercontent.com/51355342/77230364-ac842d80-6bce-11ea-8f5f-5ea3974d5397.png)
![image](https://user-images.githubusercontent.com/51355342/77230373-b73ec280-6bce-11ea-8caf-df3ba124627e.png)
刚下载的最新代码，数据库也是用的新建的，还是一样的问题，这是在向OSS上传文件时报的错

**Comment by MrChen00** [comment]
该问题已找到
![image](https://user-images.githubusercontent.com/51355342/77243842-abdcad00-6c49-11ea-940c-9111d2d39470.png)
问题出在endPoint地域节点上，之前以为就是单纯的填服务器所在节点，所以之前填的为华南1。后来debug发现程序中有去拼接Bucket和EndPoint，才发现问题，该位置应该填的是访问域名的访问域名的EndPoint，修改后文件上传成功。而且发现小问题，就是访问图片时，是直接返回的路径，如果说bucket权限设置为私有，那么页面上就不能显示图片，因为权限不足。是否可以由后台先通过配置的AccessKey先将图片拉取下来再转成base64或者其他格式呢？这样就能保证一些私密文件的安全性

**Comment by ruibaby** [comment]
bucket 肯定要设置为公有读才能正常在页面显示的。那么如果要把图片拉取到本地，上传到 oss 的意义是什么？望指点，对不太常用阿里的 oss。

**Comment by MrChen00** [comment]
不，不是拉取到本地，而是就是由后台程序在线将保存在oss中的图片转成base64字符串，然后将该字符串返回给前端，前端再将这个base64的字符串解析成图片，这样就不会把你的文件资源路径直接暴露给用户，因为前端拿到的只是一个base64格式的字符串而已，而且这样就如果图片本来就是保存在本地服务器，而不是oss这些服务器，就还能再减少一些http请求，因为后台是可以直接读取文件资源的。而且虽然说不能减少对于oss服务器的请求次数，但是也是把oss的资源路径给隐藏掉了，oss也不需要再设置公共读，是直接由后台程序通过AccessKey读取资源在线转成base64，可以不需要保存到本地。这样就能提高安全性，也更符合oss的要求，全局私有，只能通过特定的方式来读写文件

**Comment by ruibaby** [comment]
不过转成 base64 有点大啊，而且在文章中用 base64 似乎也不是一个明智的选择。

**Comment by MrChen00** [comment]
如果说博文中的图片也是跟附件一样的话，那这种方式的确不合适

**Comment by ruibaby** [comment]
后续再优化一下 oss 的一些配置问题吧，但是通过 AccessKey 获取图片我觉得还是算了。

**Comment by MrChen00** [comment]
关于endPoint地域节点这个配置我觉得可能是个坑，因为从文本信息上给人的一个主观感受应该是就是单纯的填写oss服务器所在的地域，但是需要的是域名后缀。而且就算是需要域名后缀，但是当已经填写了绑定的域名后，也就没必要再去自己主动拼接Bucket和EndPoint了，而且自己主动拼接，只要这两个一个配置错误，就会导致oss访问失败

**Comment by ruibaby** [comment]
> 关于endPoint地域节点这个配置我觉得可能是个坑，因为从文本信息上给人的一个主观感受应该是就是单纯的填写oss服务器所在的地域，但是需要的是域名后缀。而且就算是需要域名后缀，但是当已经填写了绑定的域名后，也就没必要再去自己主动拼接Bucket和EndPoint了，而且自己主动拼接，只要这两个一个配置错误，就会导致oss访问失败

![Snipaste_2020-03-23_21-01-38](https://user-images.githubusercontent.com/21301288/77319296-8d5ddb00-6d49-11ea-9728-8a96289792f7.png)

**Comment by MrChen00** [comment]
不，我上面的截图是一直都有填写绑定域名的，但还是使用的
![image](https://user-images.githubusercontent.com/51355342/77319872-86839800-6d4a-11ea-8a16-90bd6b409e24.png)
![image](https://user-images.githubusercontent.com/51355342/77319896-94391d80-6d4a-11ea-8725-aa6aa1584d4d.png)
请注意我此时的配置，绑定域名是有填写的，因为EndPoint必须填写，所以我填了一个错误的EndPoint，但是绑定域名是正确的，但是此时图片是上传失败的。而且我有debug过程序，我发现程序中是直接去拼接的Bucket和EndPoint，直接无视了绑定域名

**Comment by ruibaby** [comment]
```

        // Init OSS client
        OSS ossClient = new OSSClientBuilder().build(endPoint, accessKey, accessSecret);

        StringBuilder basePath = new StringBuilder(protocol);

        if (StringUtils.isNotEmpty(domain)) {
            basePath.append(domain)
                .append(URL_SEPARATOR);
        } else {
            basePath.append(bucketName)
                .append(".")
                .append(endPoint)
                .append(URL_SEPARATOR);
        }
```

逻辑上并没有任何错误啊，本来 endPoint 在创建 ossClient 的时候都是必须要有的，所以你填写一个错误的本来就不行。

至于绑定域名，那是为了让你填写你在阿里云那边绑定的自定义域名，用于拼接附件访问地址的。如果没有填写，那么则是 oss 自动配置的 buctket+endPoint。

**Comment by MrChen00** [comment]
好吧，那就是我理解错误

**Comment by ruibaby** [comment]
> 好吧，那就是我理解错误

这个确实，如果在没有文档的情况下很容易蒙，后面有时间都会把文档补上的。
