### ISSUE TITLE
2.20.0版本更新2.20.9版本后首页打不开，能手动修改地址进入console后台。，默认主题，已关闭额外插件，且已经通过手动重装主题修复

### ISSUE THREAD

**Issue by 20191864231** [halo-dev/halo#7048]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: http://lnjweb.top:80/
- 启动时间: 2024-11-18 14:01
- 版本: 2.20.9
- 构建时间: 2024-11-12 06:43
- Git Commit: 06f3c28
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.3
- 操作系统: Linux / 5.15.0-106-generic
- 已激活主题: [Earth 1.11.1](https://github.com/halo-dev/theme-earth)
- 已启动插件:
  - [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)

### 使用的哪种方式运行？

Docker Compose

### 发生了什么？

2.20.0版本更新2.20.9版本后首页打不开，显示 404 NOT_FOUND "Template index was not found."，但能手动修改地址进入console后台。最后解决方法，在后台卸载默认主题后从官网的应用商店下载默认主题，上传到自己的halo中。整了好久终于能用新版了。不想再回去复现一遍了。管理可以把这个问题关闭，希望给其他人一点思路。

### 复现步骤

![Image](https://github.com/user-attachments/assets/eda12fd9-ba4a-490a-8fb2-38049f915ae1)
先安装2.20版本，，后修改版本号为2.20.9，执行docker-compose up -d 问题即可复现。
安装的插件如下
![Image](https://github.com/user-attachments/assets/1c57afe7-6041-416a-9ca0-25e69a6ba36b)

### 相关日志输出

```shell
2024-11-18T14:10:38.127+08:00 ERROR 7 --- [oundedElastic-3] org.thymeleaf.TemplateEngine             : [THYMELEAF][boundedElastic-3] Exception preparing throttled template "index": 404 NOT_FOUND "Template index was not found."

run.halo.app.infra.exception.NotFoundException: 404 NOT_FOUND "Template index was not found."
	at run.halo.app.theme.CompositeTemplateResolver.lambda$resolveTemplate$1(CompositeTemplateResolver.java:59) ~[classes/:2.20.9]
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
	at run.halo.app.theme.CompositeTemplateResolver.resolveTemplate(CompositeTemplateResolver.java:59) ~[classes/:2.20.9]
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:845) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.engine.TemplateManager.parseAndProcessThrottled(TemplateManager.java:757) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.TemplateEngine.processThrottled(TemplateEngine.java:1189) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.TemplateEngine.processThrottled(TemplateEngine.java:1163) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createChunkedStream$1(SpringWebFluxTemplateEngine.java:245) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:80) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by ruibaby** [comment]
没有复现，Halo 不会在升级后更改任何主题模板，NotFoundException 代表找不到模板文件，建议检查你的挂载目录是否正确。

**Comment by 20191864231** [comment]
> 没有复现，Halo 不会在升级后更改任何主题模板，NotFoundException 代表找不到模板文件，建议检查你的挂载目录是否正确。

好的，可能是我个人的问题，但我把版本号改成2.20就可以，改成2.20.9就不行了。总之我现在没问题了，就提供点问题样本。

**Comment by ruibaby** [comment]
> 建议检查你的挂载目录是否正确

建议检查你的挂载配置，不然你下次升级时重建容器仍然会有问题，这和改版本没有关系。

**Comment by 20191864231** [comment]
> > 建议检查你的挂载目录是否正确
> 
> 建议检查你的挂载配置，不然你下次升级时重建容器仍然会有问题，这和改版本没有关系。

了解谢谢提醒，但我目前水平有限，看不出来问题，服务器用的腾讯云，也没修改过挂载的配置，这是1panel的容器挂载信息
![Image](https://github.com/user-attachments/assets/a96e0739-25eb-454b-9e04-a5b2373eecc7)
之所以没有在1panel安装halo是因为我想用最新版，商店里更新慢。
