### ISSUE TITLE
menuFinder.getPrimary() 无法正常使用 (Exception evaluating SpringEL expression: "menuFinder.getPrimary()")

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/halo#7059]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: https://howiehz.top
- 启动时间: 2024-11-21 23:45
- 版本: 2.20.9
- 构建时间: 2024-11-12 06:47
- Git Commit: ed5afb2
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MariaDB / 10.11.9-MariaDB-ubu2204
- 操作系统: Linux / 6.1.0-26-amd64
- 已激活主题: [彼岸-皓改 1.12.0](https://github.com/howiehz/halo-theme-higan-hz.git)
- 已启动插件:
  - [Vditor 编辑器 1.8.0](https://github.com/justice2001/halo-plugin-vditor)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [Metrics Graph 1.1.0](https://github.com/guqing/plugin-metrics-graph)
  - [Meilisearch 2.0.1](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [图库管理 1.4.0](https://github.com/halo-sigs/plugin-photos)
  - [瞬间 1.8.0](https://github.com/halo-sigs/plugin-moments)
  - [通知我 1.1.0](https://github.com/monyuan/notify-me)
  - [OAuth2 认证 1.4.2](https://github.com/halo-sigs/plugin-oauth2)
  - [文章导入导出 1.2.4](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [Willow Markdown 编辑器 1.0.0](https://github.com/guqing/willow-mde)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [RSS 1.3.0](https://github.com/halo-dev/plugin-feed)
  - [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.8.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

本地测试环境不会报错，部署到 docker 后会报错。
实际菜单也会渲染，但是会卡一下反应比较慢。
```html
<!-- template: "fragments/common" - line 19 -->
<th:block th:fragment="base-menu" th:with="menu = ${menuFinder.getPrimary()}"> 
  <th:block th:with="menuItems = ${menu.menuItems}">
    <th:block th:unless="${theme.config?.global?.is_i18n_menu_show}">
      <!-- 普通 menu -->
      <li th:each="menuItem : ${menuItems}" class="matched-menu">
        <a
          th:href="@{${menuItem.status?.href}}"
          th:target="${menuItem.spec.target?.value}"
          th:aria-label="#{fragment.menu.menuItem.aria-label(${menuItem.status?.displayName})}"
          th:text="${menuItem.status?.displayName}"
          >目录项填充位置</a
        >
      </li>
    </th:block>

    <!-- ...  -->
  </th:block>
 </th:block>
```

原来的写法是 `<th:block th:each="menuItem : ${menuFinder.getPrimary().menuItems}">` 但是频繁报错，于是查找[文档](https://docs.halo.run/developer-guide/theme/finder-apis/menu/#%E7%A4%BA%E4%BE%8B-1)，模仿文档的方式写。可是依旧报错。

### 复现步骤

- 以下日志为报错部分

### 相关日志输出

```shell
halo  | org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "menuFinder.getPrimary()" (template: "fragments/common" - line 19, col 35)
halo  | 	at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at run.halo.app.theme.ReactiveSpelVariableExpressionEvaluator.evaluate(ReactiveSpelVariableExpressionEvaluator.java:36) ~[classes/:2.20.9]
halo  | 	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.standard.processor.StandardWithTagProcessor.doProcess(StandardWithTagProcessor.java:93) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.Model.process(Model.java:300) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.OpenElementTagModelProcessable.process(OpenElementTagModelProcessable.java:110) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.queueProcessable(ProcessorTemplateHandler.java:2106) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1559) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.Model.process(Model.java:300) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.OpenElementTagModelProcessable.process(OpenElementTagModelProcessable.java:110) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.queueProcessable(ProcessorTemplateHandler.java:2106) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1559) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.Model.process(Model.java:300) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.StandaloneElementTagModelProcessable.process(StandaloneElementTagModelProcessable.java:114) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ProcessorTemplateHandler.handlePending(ProcessorTemplateHandler.java:2054) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ThrottledTemplateProcessor.process(ThrottledTemplateProcessor.java:230) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.engine.ThrottledTemplateProcessor.process(ThrottledTemplateProcessor.java:200) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine$StreamThrottledTemplateProcessor.process(SpringWebFluxTemplateEngine.java:720) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createChunkedStream$2(SpringWebFluxTemplateEngine.java:269) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:271) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:213) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:85) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo  | Caused by: reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
halo  | 	at reactor.core.Exceptions$ReactiveException.fillInStackTrace(Exceptions.java:736) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at java.base/java.lang.Throwable.<init>(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.Throwable.<init>(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.Exception.<init>(Unknown Source) ~[na:na]
halo  | 	at java.base/java.lang.RuntimeException.<init>(Unknown Source) ~[na:na]
halo  | 	at reactor.core.Exceptions$ReactiveException.<init>(Exceptions.java:726) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.Exceptions.propagate(Exceptions.java:410) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:158) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at reactor.core.publisher.Mono.blockOptional(Mono.java:1861) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	at run.halo.app.infra.utils.ReactiveUtils.blockReactiveValue(ReactiveUtils.java:45) ~[classes/:na]
halo  | 	at run.halo.app.infra.utils.ReactiveUtils.blockReactiveValue(ReactiveUtils.java:28) ~[classes/:na]
halo  | 	at run.halo.app.theme.dialect.EvaluationContextEnhancer$ReactiveMethodExecutor.lambda$execute$1(EvaluationContextEnhancer.java:206) ~[classes/:2.20.9]
halo  | 	at java.base/java.util.Optional.map(Unknown Source) ~[na:na]
halo  | 	at run.halo.app.theme.dialect.EvaluationContextEnhancer$ReactiveMethodExecutor.execute(EvaluationContextEnhancer.java:206) ~[classes/:2.20.9]
halo  | 	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:152) ~[spring-expression-6.2.0-RC3.jar:6.2.0-RC3]
halo  | 	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:398) ~[spring-expression-6.2.0-RC3.jar:6.2.0-RC3]
halo  | 	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:97) ~[spring-expression-6.2.0-RC3.jar:6.2.0-RC3]
halo  | 	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:116) ~[spring-expression-6.2.0-RC3.jar:6.2.0-RC3]
halo  | 	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:338) ~[spring-expression-6.2.0-RC3.jar:6.2.0-RC3]
halo  | 	at org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:265) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:3.1.2.RELEASE]
halo  | 	... 45 common frames omitted
halo  | 	Suppressed: java.lang.Exception: #blockOptional(timeout) has been interrupted
halo  | 		at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:160) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 		... 57 common frames omitted
halo  | Caused by: java.lang.InterruptedException: null
halo  | 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(Unknown Source) ~[na:na]
halo  | 	at java.base/java.util.concurrent.CountDownLatch.await(Unknown Source) ~[na:na]
halo  | 	at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:150) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
halo  | 	... 57 common frames omitted
halo  |
```

**Comment by ruibaby** [comment]
> 实际菜单也会渲染，但是会卡一下反应比较慢。

能够渲染就证明 API 并没有问题，卡的话就不清楚是什么原因了。

这个日志看起来和 https://github.com/halo-dev/halo/issues/4468 一致。

**Comment by HowieHz** [comment]
> > 实际菜单也会渲染，但是会卡一下反应比较慢。
> 
> 能够渲染就证明 API 并没有问题，卡的话就不清楚是什么原因了。
> 
> 这个日志看起来和 [#4468](https://github.com/halo-dev/halo/issues/4468) 一致。

卡顿确定是 #7071，驱动换 mysql 就不会卡了

**Comment by JohnNiang** [comment]
Hi @HowieHz , 当前 Issue 中所提到的日志问题已经在 #7284 修复。我将关闭当前 Issue，如果有任何问题请随时重新打开。

/close
