### ISSUE TITLE
开发环境在线安装和zip安装主题失败

### ISSUE THREAD

**Issue by feitian124** [halo-dev/halo#713]
## 我的环境

```
版本：
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
启动时间：2020-03-25 22:51
```

---

## 错误日志

```
java.lang.NullPointerException: null
	at java.util.StringTokenizer.<init>(StringTokenizer.java:199) ~[na:1.8.0_242]
	at java.util.StringTokenizer.<init>(StringTokenizer.java:221) ~[na:1.8.0_242]
	at run.halo.app.utils.VersionUtil.getCanonicalVersion(VersionUtil.java:19) ~[main/:na]
	at run.halo.app.utils.VersionUtil.compare(VersionUtil.java:50) ~[main/:na]
	at run.halo.app.utils.VersionUtil.compareVersion(VersionUtil.java:79) ~[main/:na]
	at run.halo.app.service.impl.ThemeServiceImpl.add(ThemeServiceImpl.java:483) ~[main/:na]
	at run.halo.app.service.impl.ThemeServiceImpl.upload(ThemeServiceImpl.java:449) ~[main/:na]
	at run.halo.app.controller.admin.api.ThemeController.uploadTheme(ThemeController.java:163) ~[main/:na]
	at run.halo.app.controller.admin.api.ThemeController$$FastClassBySpringCGLIB$$e8e9d45c.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at run.halo.app.core.ControllerLogAop.controller(ControllerLogAop.java:48) ~[main/:na]
	at sun.reflect.GeneratedMethodAccessor219.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
```

在线安装和zip安装主题均失败， 似乎
```
        if (StringUtils.isNotEmpty(tmpThemeProperty.getRequire()) && !VersionUtil.compareVersion(HaloConst.HALO_VERSION, tmpThemeProperty.getRequire())) {
            throw new ThemeNotSupportException("当前主题仅支持 Halo " + tmpThemeProperty.getRequire() + " 以上的版本");
        }
```
中 HaloConst.HALO_VERSION 为空？

**Comment by feitian124** [comment]
版本那里也显示空

**Comment by JohnNiang** [comment]
请问你是使用的 jar 包的来源是？

**Comment by ruibaby** [comment]
@feitian124 开发环境获取不了版本

**Comment by feitian124** [comment]
@ruibaby 那开发环境咋整呢

**Comment by feitian124** [comment]
@JohnNiang 我是开发环境

**Comment by JohnNiang** [comment]
至于那个空指针错误， @ruibaby 可以排查一下。

**Comment by JohnNiang** [comment]
> @JohnNiang 我是开发环境

开发环境是无法获取到 halo 的版本的。

**Comment by JohnNiang** [comment]
你使用的主题的 setting.yml 和 theme.yml 可以提供一下么？

**Comment by ruibaby** [comment]
空指针的报错就是因为 HaloConst.VERSION 没有值。所以判断主题版本时候回抛空指针。

解决方案：

手动下载或 clone 主题到 `工作目录/templates/themes`。

**Comment by feitian124** [comment]
clone 之后 git submodule update，默认的主题，没动

**Comment by JohnNiang** [comment]
> 空指针的报错就是因为 HaloConst.VERSION 没有值。所以判断主题版本时候会抛空指针。
> 
> 解决方案：
> 
> 手动下载或 clone 主题到 `工作目录/templates/themes`。
---
那也建议判断一下 VERSION 是否为空哦，不为空，直接抛异常或者忽略哦。

**Comment by ruibaby** [comment]
> clone 之后 git submodule update，默认的主题，没动。
> 也没创建 halo-dev, 是这个的原因吗

那为什么是 `在线安装和zip安装主题失败`

**Comment by feitian124** [comment]
@ruibaby 我没说清楚
项目使用默认主题运行，然后尝试安装另外的主题时出错，具体是：
https://github.com/imkundev/halo-theme-fantastic

**Comment by ruibaby** [comment]
> https://github.com/imkundev/halo-theme-fantastic

上面给出解决方案了。如果你没有生成 halo-dev，那么说明你没有使用 dev 的 profile 启动，默认的工作路径为 `~/.halo`

手动下载或 clone 主题到 工作目录/templates/themes。

**Comment by ruibaby** [comment]
版本校验只发生在安装主题。

**Comment by feitian124** [comment]
好的，我试试，谢谢。
问一下开发环境取不到版本是故意如此，还是实现的限制？
springboot 应该可以取到 pom 中的定义的版本

**Comment by ruibaby** [comment]
> 好的，我试试，谢谢。
> 问一下开发环境取不到版本是故意如此，还是实现的限制？
> springboot 应该可以取到 pom 中的定义的版本

应该可以做到，后面研究一下。

**Comment by feitian124** [comment]
感谢，辛苦，我也看看

**Comment by JohnNiang** [comment]
目前我们是获取的 META-INF 内的 Version，开发模式下是不会执行 build.gradle 中的 bootJar task。

**Comment by feitian124** [comment]
https://github.com/spring-projects/spring-boot/issues/1540
