### ISSUE TITLE
特定条件下无法输出部分字符

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-dev/halo#7157]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

- 外部访问地址: https://qingf.me
- 启动时间: 2024-12-18 11:44
- 版本: 2.20.12
- 构建时间: 2024-12-17 15:44
- Git Commit: 4442859
- Java: IBM Semeru Runtime Open Edition / 21.0.5+11-LTS
- 数据库: MySQL Community Server - GPL / 8.4.3
- 操作系统: Linux / 6.1.0-25-amd64
- 已激活主题: [Hao 1.6.1](https://github.com/chengzhongxue/halo-theme-hao)
- 已启动插件:
  - [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱 1.2.1](https://github.com/halo-sigs/plugin-lightgallery)
  - [Trailing Slash 1.0.0](https://github.com/halo-sigs/plugin-trailing-slash)
  - [Markdown / HTML 内容块 1.2.0](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [OAuth2 认证 1.5.0](https://github.com/halo-sigs/plugin-oauth2)
  - [编辑器超链接卡片 1.3.0](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [链接管理 1.5.0](https://github.com/halo-sigs/plugin-links)
  - [瞬间 1.9.0](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.9.0](https://www.halo.run/store/apps/app-VYJbF)

### 使用的哪种方式运行？

Docker

### 发生了什么？

在一行末尾无法输入字符`————`。

https://github.com/user-attachments/assets/e375d70b-9609-43e1-b189-ba20554cc9f3

### 复现步骤

可能无法稳定复现,但大部分时候都可以。
具体如何复现请看上方视频。

### 相关日志输出

```shell

```

**Comment by QingFeng-awa** [comment]
刚刚试了一下,`……`也会触发同样bug

**Comment by ruibaby** [comment]
我这边未复现此问题，建议先尝试使用干净的浏览器复现，排除插件的干扰，毕竟存在编辑器被浏览器插件干扰的 issue 案例。

/triage not-reproducible

**Comment by guqing** [comment]
我尝试和你使用同样的环境 demo.halo.run 并没有复现，浏览器为 Chrome

https://github.com/user-attachments/assets/91670a49-dcd2-4da4-8206-cf2df7a3f5d1

**Comment by guqing** [comment]
我在 Windows 系统下使用 Edge 和 Chrome 都可以复现此问题，看来是系统字符集导致的差异
<img width="556" alt="Image" src="https://github.com/user-attachments/assets/67037d57-d052-466a-aa78-df18802c09b4" />

/ping @LIlGG

**Comment by ruibaby** [comment]
建议测试一下 2.22.0-alpha 版本，我尝试在 Windows 下没有再复现此问题。

**Comment by JohnNiang** [comment]
在 Windows 上的 Edge 仍然能够复现以上问题。复现步骤如下所示：

1. 新建一篇文章
2. 切换为中文输入法
3. 直接输入字符 `——`
4. 字符一闪而过，接着消失，出现以下错误：
    ```js
    editor.593a15e5.js:3  Uncaught RangeError: Position 3 out of range
        at e.resolve (editor.593a15e5.js:3:62414)
        at e.resolveCached (editor.593a15e5.js:3:62786)
        at e.resolve (editor.593a15e5.js:3:65298)
        at e.valid (editor.593a15e5.js:166:3650)
        at B.createSelectionBetween (editor.593a15e5.js:166:5462)
        at editor.593a15e5.js:9:21955
        at Of.someProp (editor.593a15e5.js:12:46212)
        at mu (editor.593a15e5.js:9:21918)
        at bf (editor.593a15e5.js:12:40068)
        at S (editor.593a15e5.js:12:39006)
    resolve @ editor.593a15e5.js:3
    resolveCached @ editor.593a15e5.js:3
    resolve @ editor.593a15e5.js:3
    valid @ editor.593a15e5.js:166
    createSelectionBetween @ editor.593a15e5.js:166
    (anonymous) @ editor.593a15e5.js:9
    someProp @ editor.593a15e5.js:12
    mu @ editor.593a15e5.js:9
    bf @ editor.593a15e5.js:12
    S @ editor.593a15e5.js:12
    n @ editor.593a15e5.js:12
    yf @ editor.593a15e5.js:12
    (anonymous) @ editor.593a15e5.js:12
    flush @ editor.593a15e5.js:12
    observer @ editor.593a15e5.js:12
    ```
