### ISSUE TITLE
500 Internal Server Error  Configuration with name 'authentication' does not exist

### ISSUE THREAD

**Issue by BeardedManZhao** [halo-dev/halo#7175]
### 前置条件

- [x] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [x] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [x] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [x] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

无法进入到终端界面
jdk 17
halo-2.20.12

### 使用的哪种方式运行？

Fat Jar

### 发生了什么？

我成功启动了 halo，在Web 中访问到了初始化页面，初始化成功之后，跳转到登录，我登录会出现 500 问题。
![Image](https://github.com/user-attachments/assets/b58e72c8-505d-4921-b128-fc949c3c0671)

### 复现步骤

1. Windows 中 使用 jar 部署好 halo
2. 初始化
3. 使用初始化时候填写的用户名和密码登录
4. 发生了 500 错误

### 相关日志输出

```shell
2024-12-27T12:18:58.792+08:00 ERROR 30100 --- [ctor-http-nio-3] a.w.r.e.AbstractErrorWebExceptionHandler : [4f84dc82-8]  500 Server Error for HTTP POST "/login"

io.github.resilience4j.core.ConfigurationNotFoundException: Configuration with name 'authentication' does not exist
        at io.github.resilience4j.ratelimiter.internal.InMemoryRateLimiterRegistry.lambda$rateLimiter$2(InMemoryRateLimiterRegistry.java:198) ~[resilience4j-ratelimiter-2.2.0.jar!/:2.2.0]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint 鈬? [DefaultWebFilterChain]
        *__checkpoint 鈬?SecurityWebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint 鈬?ReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint 鈬?CsrfWebFilter [DefaultWebFilterChain]
        *__checkpoint 鈬?CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint 鈬?HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        *__checkpoint 鈬?SecurityWebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint 鈬?ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint 鈬?org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint 鈬?run.halo.comment.widget.captcha.CommentCaptchaFilter [DefaultWebFilterChain]
        *__checkpoint 鈬?run.halo.app.infra.webfilter.AdditionalWebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint 鈬?org.springframework.web.filter.reactive.ServerWebExchangeContextFilter [DefaultWebFilterChain]
        *__checkpoint 鈬?HTTP POST "/login" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at io.github.resilience4j.ratelimiter.internal.InMemoryRateLimiterRegistry.lambda$rateLimiter$2(InMemoryRateLimiterRegistry.java:198) ~[resilience4j-ratelimiter-2.2.0.jar!/:2.2.0]
                at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
                at io.github.resilience4j.ratelimiter.internal.InMemoryRateLimiterRegistry.lambda$rateLimiter$3(InMemoryRateLimiterRegistry.java:198) ~[resilience4j-ratelimiter-2.2.0.jar!/:2.2.0]
                at io.github.resilience4j.core.registry.AbstractRegistry.lambda$computeIfAbsent$0(AbstractRegistry.java:101) ~[resilience4j-core-2.2.0.jar!/:2.2.0]
                at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
                at io.github.resilience4j.core.registry.InMemoryRegistryStore.computeIfAbsent(InMemoryRegistryStore.java:41) ~[resilience4j-core-2.2.0.jar!/:2.2.0]
                at io.github.resilience4j.core.registry.AbstractRegistry.computeIfAbsent(AbstractRegistry.java:100) ~[resilience4j-core-2.2.0.jar!/:2.2.0]
                at io.github.resilience4j.ratelimiter.internal.InMemoryRateLimiterRegistry.rateLimiter(InMemoryRateLimiterRegistry.java:197) ~[resilience4j-ratelimiter-2.2.0.jar!/:2.2.0]
                at io.github.resilience4j.ratelimiter.internal.InMemoryRateLimiterRegistry.rateLimiter(InMemoryRateLimiterRegistry.java:189) ~[resilience4j-ratelimiter-2.2.0.jar!/:2.2.0]
                at run.halo.app.security.authentication.login.LoginAuthenticationConverter.createIpBasedRateLimiter(LoginAuthenticationConverter.java:64) ~[!/:2.20.12]
                at run.halo.app.security.authentication.login.LoginAuthenticationConverter.convert(LoginAuthenticationConverter.java:56) ~[!/:2.20.12]
                at org.springframework.security.web.server.authentication.AuthenticationWebFilter.lambda$filter$2(AuthenticationWebFilter.java:113) ~[spring-security-web-6.4.1.jar!/:6.4.1]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmitScalar(FluxFlatMap.java:492) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:424) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:335) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:373) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:371) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:724) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onComplete(FluxFlattenIterable.java:273) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2098) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:371) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:724) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onComplete(FluxFlattenIterable.java:273) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2098) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:118) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:209) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:79) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4576) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4576) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:189) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:250) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:324) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.innerResult(MonoFilterWhen.java:213) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFilterWhen$FilterWhenInner.onNext(MonoFilterWhen.java:333) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFilterWhen$FilterWhenInner.onNext(MonoFilterWhen.java:291) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1865) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[reactor-core-3.7.0.jar!/:3.7.0]
                at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413) ~[reactor-netty-core-1.2.0.jar!/:1.2.0]
                at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:455) ~[reactor-netty-core-1.2.0.jar!/:1.2.0]
                at reactor.netty.http.server.HttpServerOperations.handleLastHttpContent(HttpServerOperations.java:864) ~[reactor-netty-http-1.2.0.jar!/:1.2.0]
                at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:786) ~[reactor-netty-http-1.2.0.jar!/:1.2.0]
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:115) ~[reactor-netty-core-1.2.0.jar!/:1.2.0]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:316) ~[reactor-netty-http-1.2.0.jar!/:1.2.0]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.115.Final.jar!/:4.1.115.Final]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.115.Final.jar!/:4.1.115.Final]
                at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

 ~[na:na]
```

**Comment by guqing** [comment]
没有复现此问题，建议给出你使用 jar 包启动的命令及复现步骤

/triage needs-information

**Comment by stackcn** [comment]
我也是一样情况，java21 启动命令和文档给的一样。使用数据库是mysql
