### ISSUE TITLE
进入不了后台

### ISSUE THREAD

**Issue by xiechuanyu** [halo-dev/halo#768]
## 我的环境

登录不了后台，无法复制环境
1.2.0-release 版本

---

## 错误日志
```
2020-04-17 17:38:51.526  WARN 24816 --- [XNIO-1 task-6] .s.h.DefaultAuthenticationFailureHandler : Handle unsuccessful authentication, ip: [183.17.124.195]
2020-04-17 17:38:51.529 ERROR 24816 --- [XNIO-1 task-6] .s.h.DefaultAuthenticationFailureHandler : Authentication failure

run.halo.app.exception.AuthenticationException: 未登录，请登陆后访问
	at run.halo.app.security.filter.AdminAuthenticationFilter.doAuthenticate(AdminAuthenticationFilter.java:67) [classes!/:1.2.0]
	at run.halo.app.security.filter.AbstractAuthenticationFilter.doFilterInternal(AbstractAuthenticationFilter.java:167) [classes!/:1.2.0]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at run.halo.app.filter.CorsFilter.doFilter(CorsFilter.java:41) [classes!/:1.2.0]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108) [spring-boot-actuator-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
```

---

## 当前行为
点击登录：提示**`未登录，请登陆后访问`**
![image](https://user-images.githubusercontent.com/12131262/79555537-570a4600-80d2-11ea-852f-7057ac767e83.png)

-->

**Comment by ruibaby** [comment]
是不是更新了 admin?

**Comment by xiechuanyu** [comment]
回复好快。。
我没有单独部署 admin，使用的 admin 是在 halo.jar 里面的。所以应该是没有更新 admin 吧？
补充一下：我是重启了 halo 才出现这种情况。

**Comment by ruibaby** [comment]
看了你的后台，确实是 1.3.2 的，与服务端不兼容。要么去 ~/.halo/templates 删掉 admin，要么直接更新 Halo 到最新版。

**Comment by xiechuanyu** [comment]
我知道了，谢谢哈。
因为之前用了 1.3.2 版本的 Halo，然后又用回了 1.2.0 版本。
我不知道会修改 ~/.halo/templates/admin 里面的内容。
删掉 admin 之后再重启可以了。
再次感谢，这个是我的问题，不是 bug

**Comment by ruibaby** [comment]
> 我知道了，谢谢哈。
> 因为之前用了 1.3.2 版本的 Halo，然后又用回了 1.2.0 版本。
> 我不知道会修改 ~/.halo/templates/admin 里面的内容。
> 删掉 admin 之后再重启可以了。
> 再次感谢，这个是我的问题，不是 bug

十分不建议降级，不知你降级的原因是?

**Comment by xiechuanyu** [comment]
> > 我知道了，谢谢哈。
> > 因为之前用了 1.3.2 版本的 Halo，然后又用回了 1.2.0 版本。
> > 我不知道会修改 ~/.halo/templates/admin 里面的内容。
> > 删掉 admin 之后再重启可以了。
> > 再次感谢，这个是我的问题，不是 bug
> 
> 十分不建议降级，不知你降级的原因是?

好多主题在 1.3.2  都报错。。所以降级了。我猜是主题没有适配 Halo 1.3.2？

**Comment by ruibaby** [comment]
> > > 我知道了，谢谢哈。
> > > 因为之前用了 1.3.2 版本的 Halo，然后又用回了 1.2.0 版本。
> > > 我不知道会修改 ~/.halo/templates/admin 里面的内容。
> > > 删掉 admin 之后再重启可以了。
> > > 再次感谢，这个是我的问题，不是 bug
> > 
> > 
> > 十分不建议降级，不知你降级的原因是?
> 
> 好多主题在 1.3.2 都报错。。所以降级了。我猜是主题没有适配 Halo 1.3.2？

可是我在发布说明已经反复强调了呀，更新 Halo 之后需要更新主题。而且目前 halo.run/p/themes 下的主题都已经更新。

**Comment by xiechuanyu** [comment]
> > > > 我知道了，谢谢哈。
> > > > 因为之前用了 1.3.2 版本的 Halo，然后又用回了 1.2.0 版本。
> > > > 我不知道会修改 ~/.halo/templates/admin 里面的内容。
> > > > 删掉 admin 之后再重启可以了。
> > > > 再次感谢，这个是我的问题，不是 bug
> > > 
> > > 
> > > 十分不建议降级，不知你降级的原因是?
> > 
> > 
> > 好多主题在 1.3.2 都报错。。所以降级了。我猜是主题没有适配 Halo 1.3.2？
> 
> 可是我在发布说明已经反复强调了呀，更新 Halo 之后需要更新主题。而且目前 halo.run/p/themes 下的主题都已经更新。

好，我没看。。
