### ISSUE TITLE
halo1.0升级到halo1.3.2报错

### ISSUE THREAD

**Issue by pythonqi** [halo-dev/halo#782]
```
Caused by: org.h2.jdbc.JdbcSQLException: NULL not allowed for column "SOURCE_CONTENT"; SQL statement:
alter table journals add column source_content clob not null [23502-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.196.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.196.jar!/:na]
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:345) ~[h2-1.4.196.jar!/:na]
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:797) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.dml.Insert.addRow(Insert.java:195) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.dml.Select.queryFlat(Select.java:523) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:625) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:114) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.dml.Query.query(Query.java:371) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.dml.Insert.insertRows(Insert.java:167) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.dml.Insert.update(Insert.java:114) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:192) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.ddl.AlterTableAlterColumn.execute(AlterTableAlterColumn.java:501) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:401) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:267) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:184) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.CommandContainer.update(CommandContainer.java:101) ~[h2-1.4.196.jar!/:na]
	at org.h2.command.Command.executeUpdate(Command.java:260) ~[h2-1.4.196.jar!/:na]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:192) ~[h2-1.4.196.jar!/:na]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164) ~[h2-1.4.196.jar!/:na]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.2.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.2.jar!/:na]
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final]
	... 108 common frames omitted
```
请问这个改怎么改啊

**Comment by ruibaby** [comment]
1. 用 1.0 启动，去数据库清空 `flyway_history` 表。
2. 下载 halo 1.2.0，运行，没问题进入下一步。
3. 下载 halo 1.3.2，运行。

**Comment by pythonqi** [comment]
你好，我在h2-console这个页面没有发现`flyway_history`这个表

![1587552348365](https://user-images.githubusercontent.com/38207031/79973133-97e6ce00-84c9-11ea-9f82-5f79b8d4c783.jpg)

**Comment by ruibaby** [comment]
@pythonqi 注意看你上面的连接地址 jdbc:h2:~/test

**Comment by pythonqi** [comment]
好的，谢谢

**Comment by pythonqi** [comment]
非常感谢！终于弄好了。记录一下修改过程。
## 问题是这样产生的
1.更新了一下icarus主题
2.发现不支持halo1.0，主页报500错误
3.因为我是docker-compose部署的，docker-compose pull拉取新镜像，docker-compose up -d 重启后，访问域名报50x错误
4.docker ps 查看发现halo这个容器的启动时间一直没有超过一分钟(一直重启)，怀疑halo容器报错
5.tail -f ~/.halo/log/spring.log 查看日志，发现一开头的错误，因为没用过h2所以过来求助

## 问题的解决过程
1.感谢ruibaby的给出了解决方案
2.因为之前说到了是docker-compose部署的，是最新的halo镜像(halo version == 1.3.2)
3.想找halo之前版本的docker镜像，没有找到
4.直接通过wget下载halo.1.0.0.jar到远程机器上，通过`java -jar halo.1.0.0.jar`运行后发现，运行时日志给的访问url并非127.0.0.1，直接是博客域名（估计数据库文件中有记录）
5.通过浏览器访问，报50x错误，无法解决
6.从日志的报错信息和ruibaby给出的解决方案看，关键在于`~/.halo/db/`中的`halo.mv.db`和`halo.trace.db`两个文件，只要将这两个文件改对，是不是就ok了呢？
7.利用scp指令将远程linux上的`~/.halo/db/`中的文件拷到本地机器中的`~/.halo/db`中
8.下载halo.1.0.0.jar到本地机器，`java -jar halo.1.0.0.jar`打开，没有问题，访问127.0.0.1:8091/h2-console（此时在日志中显示的竟然还是我的博客域名，肯定和数据库文件有关了），
9.需要注意，8091是我本地机器的`~/.halo/application.yaml`中的端口，然后我把h2相关配置的两个false改成了true，这样才可以访问h2-console页面，在h2-console页面中的url选择要使用application.yaml中的url（默认应该是这样jdbc:h2:file:~/.halo/db/halo），不然就出现了我提的第二个愚蠢的问题
10.然后我清除了这个`flyway_scheam_history`表，` truncate table table_name;`用了这个sql语句
11.我很开心地把两个数据库文件传回到远程机器上，发现还是报错，回过头一开，ruibaby的第二步我没做！
12.再次下载halo.1.2.0.jar到本机上，运行`java -jar halo.1.2.0.jar`，浏览器访问本机127.0.***没问题
13.最后再下载halo.1.3.2.jar到本机上，运行`java -jar halo.1.3.2.jar`，浏览器访问本机127.0***也没问题
14.应该稳了吧？我再把两个数据库文件再次传回到远程机器上
15.真的稳了！！！重新docker-compose restart一下，正常恢复~嘿嘿
