### ISSUE TITLE
请问SMTP服务是否支持STARTTLS？

### ISSUE THREAD

**Issue by sunging** [halo-dev/halo#892]
使用office365的邮箱 (仅支持STARTTLS) 配置SMTP服务时，邮件无法发送，log中有如下错误输出：

```java
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.office365.com, port: 587;
  nested exception is:
        javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2211)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
        at javax.mail.Service.connect(Service.java:342)
        at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
        ... 8 more
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
        at sun.security.ssl.InputRecord.read(InputRecord.java:527)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
        ... 12 more
```

**Comment by JohnNiang** [comment]
目前似乎不支持 TLS。

**Comment by sunging** [comment]
这样子，那只能换个邮箱了，希望能加入一下STARTTLS的支持~
