### ISSUE TITLE
最新版本上传文件出现BUG

### ISSUE THREAD

**Issue by wajncn** [halo-dev/halo#928]
重启也不行. 

```java
2020-06-21 21:30:00.217 ERROR 21601 --- [  XNIO-1 task-3] io.undertow.request                      : UT005023: Exception handling request to /api/admin/attachments/upload

java.lang.RuntimeException: java.nio.file.NoSuchFileException: /data/upload_tmp/undertow.6738298393645750953.8090/\/data/upload_tmp/undertow3307954452084769537upload
        at io.undertow.server.handlers.form.MultiPartParserDefinition$MultiPartUploadHandler.beginPart(MultiPartParserDefinition.java:261) ~[undertow-core-2.0.29.Final.jar!/:2.0.29.Final]
        at io.undertow.util.MultipartParser$ParseState.headerName(MultipartParser.java:208) ~[undertow-core-2.0.29.Final.jar!/:2.0.29.Final]
        at io.undertow.util.MultipartParser$ParseState.parse(MultipartParser.java:123) ~[undertow-core-2.0.29.Final.jar!/:2.0.29.Final]
        at io.undertow.server.handlers.form.MultiPartParserDefinition$MultiPartUploadHandler.parseBlocking(MultiPartParserDefinition.java:232) ~[undertow-core-2.0.29.Final.jar!/:2.0.29.Final]
        at io.undertow.servlet.spec.HttpServletRequestImpl.parseFormData(HttpServletRequestImpl.java:835) ~[undertow-servlet-2.0.29.Final.jar!/:2.0.29.Final]
```

**Comment by ruibaby** [comment]
什么版本？

**Comment by wajncn** [comment]
halo-1.3.2.jar


[image: image.png]

前面这个 /data/update_tmp 是我自定义的.  (我原本以为自定义就好了.  结果还是不行. )

nohup java -Xmx512m -Xms156m -Djava.io.tmpdir=/data/upload_tmp -jar
${APP_NAME} --spring.config.location=/root/.halo/application.yaml

最终原因 应该是 \ 目录导致的.




Ryan Wang <notifications@github.com> 于2020年6月21日周日 下午9:34写道：

**Comment by wajncn** [comment]
我在服务上面
创建了  /data/upload_tmp/undertow.6738298393645750953.8090/\/data/upload_tmp
目录就可以上传图片了.

王进 <wajncn@gmail.com> 于2020年6月21日周日 下午11:06写道：

**Comment by wajncn** [comment]
图片补充:
![image](https://user-images.githubusercontent.com/37337912/85228179-7e53fb00-b414-11ea-864e-e83939aed3f0.png)

**Comment by JohnNiang** [comment]
大致明白了。我去排查一下。

**Comment by JohnNiang** [comment]
这个看起来像是 Undertow 的 bug。

**Comment by JohnNiang** [comment]
可以看看 /root/.halo/application.yaml 配置么？（**去除敏感配置**）

**Comment by kfyidrig** [comment]
我发现，上传文件居然是先上传到服务器，再上传到七牛云，我哭了，1mbps的小水管，传个文件真不容易

**Comment by JohnNiang** [comment]
> 我发现，上传文件居然是先上传到服务器，再上传到七牛云，我哭了，1mbps的小水管，传个文件真不容易

这确实是一个比较不合理的方案。后面会考虑直接用 JS SDK 替代第三方 OSS。

**Comment by kfyidrig** [comment]
> > 我发现，上传文件居然是先上传到服务器，再上传到七牛云，我哭了，1mbps的小水管，传个文件真不容易
> 
> 这确实是一个比较不合理的方案。后面会考虑直接用 JS SDK 替代第三方 OSS。

谢谢咯，美滋滋

**Comment by wajncn** [comment]
这个问题原因是 linux系统的临时文件会定时清理的. (前提是你很久没用过系统)   .   解决方法就是自定义上传文件目录
