### ISSUE TITLE
当文件不存在时，删除附件会报错

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/halo#950]
## 我的环境
版本：1.3.2
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
启动时间：2020-07-07 21:12

---

## 错误日志
```
Caused by: java.nio.file.NoSuchFileException: /root/.halo/upload/2020/07/docker-463320b8a3be4a5d87329966537c3aed.jpg
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_252]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_252]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_252]
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244) ~[na:1.8.0_252]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103) ~[na:1.8.0_252]
	at java.nio.file.Files.delete(Files.java:1126) ~[na:1.8.0_252]
	at run.halo.app.handler.file.LocalFileHandler.delete(LocalFileHandler.java:190) ~[classes!/:na]
	... 100 common frames omitted
```

---

## 期望行为
我的服务器由于某些原因重置了。在这之前我备份了halo（数据备份）。
当我重新安装halo并且导入备份之后，发现我的图片数据还存在，但图片为空。
我想删除这些空的图片并重新上传新的图片

## 当前行为
删除图片就会出现 [错误日志](#错误日志) 这样的错误信息。导致我无法删除旧的图片。 这可能是由于读取文件目录为空导致的BUG。

**Comment by ruibaby** [comment]
目前没有其他办法，去数据库删除吧。另外，你可能需要的是全站备份，数据导出不会备份 upload 文件夹。
