### ISSUE TITLE
# 首次安装出现迁移异常(报错信息为：SQL语法错误)

### ISSUE THREAD

**Issue by corgile** [halo-dev/halo#972]
## 初次启动日志如下：

未修改任何sql文件

```shell

2020-07-15 13:44:01.275  INFO 13120 --- [  restartedMain] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 2 - migrate 1.2.0-beta.1 to 1.2.0-beta.2
2020-07-15 13:44:01.289 ERROR 13120 --- [  restartedMain] o.f.core.internal.command.DbMigrate      : Migration of schema "PUBLIC" to version 2 - migrate 1.2.0-beta.1 to 1.2.0-beta.2 failed! Please restore backups and roll back database and code!
2020-07-15 13:44:01.299  INFO 13120 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-15 13:44:01.310 ERROR 13120 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql failed
-------------------------------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "                         
ALTER TABLE JOURNALS MODIFY[*] CONTENT TEXT NOT NULL"; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
-- Migrate journals Table
alter table journals modify content text not null [42001-200]
Location   : migration/V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql (E:\WorkSpace\Java\Blog\target\classes\migration\V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql)
Line       : 3
Statement  : -- Migrate journals Table
alter table journals modify content text not null

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:369) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:282) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:37) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:199) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:159) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:530) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159) ~[flyway-core-6.4.1.jar:na]
	at xhl.blog.listener.StartedListener.migrate(StartedListener.java:99) ~[classes/:na]
	at xhl.blog.listener.StartedListener.onApplicationEvent(StartedListener.java:66) ~[classes/:na]
	at xhl.blog.listener.StartedListener.onApplicationEvent(StartedListener.java:40) ~[classes/:na]
	at xhl.blog.listener.StartedListener$$EnhancerBySpringCGLIB$$e2bb5eba.onApplicationEvent(<generated>) ~[classes/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:102) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:71) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at xhl.blog.Application.main(Application.java:27) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.3.0.RELEASE.jar:2.3.0.RELEASE]
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql failed
-------------------------------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "                         
ALTER TABLE JOURNALS MODIFY[*] CONTENT TEXT NOT NULL"; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
-- Migrate journals Table
alter table journals modify content text not null [42001-200]
Location   : migration/V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql (E:\WorkSpace\Java\Blog\target\classes\migration\V2__migrate_1.2.0-beta.1_to_1.2.0-beta.2.sql)
Line       : 3
Statement  : -- Migrate journals Table
alter table journals modify content text not null

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:274) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:220) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:127) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:88) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.access$000(SqlMigrationExecutor.java:33) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:77) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:74) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:74) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:366) ~[flyway-core-6.4.1.jar:na]
	... 39 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "                         
ALTER TABLE JOURNALS MODIFY[*] CONTENT TEXT NOT NULL"; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
-- Migrate journals Table
alter table journals modify content text not null [42001-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getSyntaxError(DbException.java:243) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.getSyntaxError(Parser.java:1053) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parseAlterTable(Parser.java:7705) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parseAlter(Parser.java:6983) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parsePrepared(Parser.java:887) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parse(Parser.java:843) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parse(Parser.java:819) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.prepareCommand(Parser.java:738) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.engine.Session.prepareLocal(Session.java:657) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.engine.Session.prepareCommand(Session.java:595) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201) ~[h2-1.4.200.jar:1.4.200]
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:244) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111) ~[flyway-core-6.4.1.jar:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:208) ~[flyway-core-6.4.1.jar:na]
	... 47 common frames omitted

2020-07-15 13:44:01.503  WARN 13120 --- [  restartedMain] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'tomcatMetricsBinder': java.lang.NullPointerException
2020-07-15 13:44:01.515  INFO 13120 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-07-15 13:44:01.518  INFO 13120 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-07-15 13:44:01.548  INFO 13120 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

Process finished with exit code 1

```

**Comment by ruibaby** [comment]
你确定是首次运行？

**Comment by corgile** [comment]
> 你确定是首次运行？

准确的说应该是 解决了环境配置问题之后的 首次运行
每次运行失败都删除了~/,halo (应该算是首次吧😥)

**Comment by ruibaby** [comment]
数据库用的啥

**Comment by corgile** [comment]
> 数据库用的啥

默认的H2,

**Comment by ruibaby** [comment]
从日志上看，你应该对项目结构做了很多修改，包括部分依赖。所以无法得知导致此异常的问题。

**Comment by corgile** [comment]
依赖是根据gradle文件改的，版本都没有变化，只是将gradle通过 gradle install 改成了maven 项目，对代码有少许修改（仅写法上）

**Comment by ruibaby** [comment]
大概分析了下，首次启动执行 `alter table journals modify content text not null` 异常，那么基本只有一种可能，你把 Journal 实体的 content 字段删了。

**Comment by corgile** [comment]
还在呢 （实体相关的都没改）
![image](https://user-images.githubusercontent.com/48396880/87510211-b95ced80-c6a5-11ea-87e9-bad3b6f61316.png)

```java

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.GenericGenerator;
import xhl.blog.model.enums.JournalType;

import javax.persistence.*;

/**
 * Journal entity
 *
 * @author johnniang
 * @author ryanwang
 * @date 2019-03-22
 */
@Data
@Entity
@Table(name = "journals")
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class Journal extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "custom-id")
    @GenericGenerator(name = "custom-id", strategy = "xhl.blog.model.entity.support.CustomIdGenerator")
    private Integer id;

    @Column(name = "source_content", nullable = false)
    @Lob
    private String sourceContent;

    @Column(name = "content", nullable = false)
    @Lob
    private String content;

    @Column(name = "likes")
    @ColumnDefault("0")
    private Long likes;

    @Column(name = "type")
    @ColumnDefault("1")
    private JournalType type;

    @Override
    public void prePersist() {
        super.prePersist();

        if (likes == null || likes < 0) {
            likes = 0L;
        }

        if (type == null) {
            type = JournalType.PUBLIC;
        }
    }
}


```

**Comment by corgile** [comment]
> 大概分析了下，首次启动执行 `alter table journals modify content text not null` 异常，那么基本只有一种可能，你把 Journal 实体的 content 字段删了，导致表里面没有 content 这个字段。

我直接把migration删了，可以运行 请问这样的话后期会出现什么问题？

**Comment by ruibaby** [comment]
不太清楚你这样做的意图，我只能保证官方发布的版本没有问题。

**Comment by corgile** [comment]
> 不太清楚你这样做的意图，我只能保证官方发布的版本没有问题。

嗯嗯，那请问 这个migration目录的作用是什么呢

**Comment by ruibaby** [comment]
> > 不太清楚你这样做的意图，我只能保证官方发布的版本没有问题。
> 
> 嗯嗯，那请问 这个migration目录的作用是什么呢

各个版本的表结构修改。

**Comment by corgile** [comment]
行，这个问题就先放一放吧

另外问下 这写sql脚本是如何生成的？
