### ISSUE TITLE
更改个人说明怎么还需要验证密码字段?

### ISSUE THREAD

**Issue by listener-He** [halo-dev/halo#980]
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'password' cannot be null
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 160 common frames omitted

**Comment by ruibaby** [comment]
触发的条件是？

更新个人资料的接口参数是没有 password 字段的，所以不会设置为 null。

**Comment by listener-He** [comment]
这个是我点击头像中的个人资料后，切换的更改密码tab，然后在切换回来。填写个人介绍时提交出现的问题

**Comment by JohnNiang** [comment]
> 这个是我点击头像中的个人资料后，切换的更改密码tab，然后在切换回来。填写个人介绍时提交出现的问题

刚刚测试了一下，没有复现以上错误。
